### ISSUE TITLE
[question] Variable in job name - documentation error

### ISSUE THREAD

**Issue by msirovy** [hashicorp/nomad#10031]
At this page is example website/content/docs/job-specification/hcl2/locals.mdx

### Nomad version
Nomad v1.0.3 (08741d9f2003ec26e44c72a2c0e27cdf0eadb6ee)

### Operating system and Environment details
Debian 10.5 x86_64

### Reproduction steps

run this job in nomad

```
locals {
  job_name = "example"
}

job "${local.job_name}_test" {
  datacenters = ["dc1"]
  group "example" {
    task "nginx" {
      driver = "docker"

      config {
        image = "nginx"
      }
    }
  }
}
```

nomad job run example.nomad

### Job file (if appropriate)
```
locals {
  job_name = "example"
}

job "${local.job_name}_test" {
  datacenters = ["dc1"]
  group "example" {
    task "nginx" {
      driver = "docker"

      config {
        image = "nginx"
      }
    }
  }
}
```
### Nomad Client logs (if appropriate)

Error getting job struct: Error parsing job file from example.nomad:
example.nomad:6,6-8: Invalid string literal; Template sequences are not allowed in this string. To include a literal "$", double it (as "$$") to escape it.

> To: nomad-oss-debug@hashicorp.com
>
> Subject: GH-1234: Errors garbage collecting allocs

Emails sent to that address are readable by all HashiCorp employees but are *not* publicly visible.

**Comment by tgross** [comment]
Hi @msirovy! It's a little buried in technicalities in the docs, but you can't interpolate a label directly.

From the [using input variable values](https://www.nomadproject.io/docs/job-specification/hcl2/variables#using-input-variable-values) docs:
> Within the job that declared a variable, its value can be accessed from within expressions as var.<NAME>, where <NAME> matches the label given in the declaration block

[A block label isn't an expression](https://www.nomadproject.io/docs/job-specification/hcl2#arguments-blocks-and-expressions), so you can't use access variables there. I'm going to mark this as a documentation item to fix because you're not the first person to get caught by it (me included!)

It's a little ugly, but you can work around this with a [`dynamic`](https://www.nomadproject.io/docs/job-specification/hcl2/expressions#dynamic-blocks) block, which turns the label into an expression.


```hcl
locals {
  job_names = ["example"]
}

dynamic "job" {
  for_each = local.job_names
  labels = [job.value]
  content {
    datacenters = ["dc1"]
    group "example" {
      task "nginx" {
        driver = "docker"

        config {
          image = "nginx"
        }
      }
    }
  }
}

```

**Comment by traceypooh** [comment]
hmm, this workaround doesnt seem to work for me?

**Comment by tgross** [comment]
Well shoot, that's embarrassing 😊 . It looks like it works for blocks within the job, but not on the top-level job. So this jobspec validates but not the one above:

```hcl
locals {
  group_names = ["example"]
}

job "example" {
  datacenters = ["dc1"]
  dynamic "group" {
    for_each = local.group_names
    labels   = [group.value]
    content {
      task "nginx" {
        driver = "docker"
        config {
          image = "nginx"
        }
      }
    }
  }
}
```

**Comment by traceypooh** [comment]
yes, seems so!  but it _is very nice_ that it works for `group` and `task`

i wonder (looking around the bugs a bit) if there's some kind of "cheap option"
for just this top-level `job` -- where if no label name is given, a `name` new alternative could be used?

eg:
```
job {
  name = "${var.something}-${var.else}"
  ...
```
and that might not take as much work/triage w.r.t. HCL2?

**Comment by tgross** [comment]
Unfortunately as it turns out, [`name`](https://www.nomadproject.io/docs/job-specification/job#name) is already a field on job but can't be used as the ID. It's kind of a legacy design decision that we have a long-open issue https://github.com/hashicorp/nomad/issues/2248 to rework, but there'd be some backwards compatibility issues involved in letting name override ID at this point. Ex. the state store is all indexed by ID so you'd have to build an index-by-name which would balloon the server memory requirements.

I don't _think_ there's anything particularly inherent to the design of either Nomad or HCL2 that prevents us from interpolating labels. Our implementation in Nomad was largely lifted directly from Packer, so I'd want to check with them to see if there was something they'd run into (or maybe they just don't use block labels very much).

As a workaround in the meantime, I think folks were using [Levant](https://github.com/hashicorp/levant) for this sort of thing before HCL2.

**Comment by tgross** [comment]
Docs update in #10041, which will ship with the website update for Nomad 1.0.4.

**Comment by traceypooh** [comment]
ok, thanks.

yes, and to avoid `levant` (which i just migrated from to HCL2) _just_ for that single swap-out
i'm working around with:
`sed -i "s/NOMAD_VAR_SLUG/$NOMAD_VAR_SLUG/" project.nomad`
(where `project.nomad` has this line: `job "NOMAD_VAR_SLUG" { ..` )

right before the `nomad plan/validate/run ..` lines 

(refs: https://gitlab.com/internetarchive/nomad/-/blob/master/.gitlab-ci.yml

**Comment by rajaseelan** [comment]
> 
> 
> ok, thanks.
> 
> yes, and to avoid `levant` (which i just migrated from to HCL2) _just_ for that single swap-out
> i'm working around with:
> `sed -i "s/NOMAD_VAR_SLUG/$NOMAD_VAR_SLUG/" project.nomad`
> (where `project.nomad` has this line: `job "NOMAD_VAR_SLUG" { ..` )
> 
> right before the `nomad plan/validate/run ..` lines
> 
> (refs: https://gitlab.com/internetarchive/nomad/-/blob/master/.gitlab-ci.yml
> https://gitlab.com/internetarchive/nomad/-/blob/master/project.nomad )

Sometimes a simple solution is all you need. I got tunnel visioned by the same problem until you pointed this out. Cheers.

**Comment by msirovy** [comment]
Yop, 

this is what I do right now, but integrated templating will be preferable and cleaner solution from my point of view. 

Thx for all reactions.

**Comment by nugend** [comment]
@tgross The fix still leaves the locals documentation error

https://www.nomadproject.io/docs/job-specification/hcl2/locals
