### ISSUE TITLE
[feature request] Supports template for scaling policy

### ISSUE THREAD

**Issue by fredwangwang** [hashicorp/nomad#10182]
### Proposal

supports template (Nomad's runtime environment variables + Node attributes and metadata) for `scaling -> policy -> check -> query`. For example:

```hcl
query  = "scalar(open_connections_example_cache{ datacenter = "${NOMAD_DC}", job_id = "${NOMAD_JOB_ID}", ip = "${attr.unique.network.ip-address}" })"
```

ref:
https://www.nomadproject.io/docs/job-specification/template
https://www.nomadproject.io/docs/autoscaling/policy#example-in-a-job

### Use-cases
When using a single metric sink for multiple Nomad clusters, it is impossible to have a hardcoded metric query, as the metric getting back is just not usable for the specific deployment that needs autoscaling. Allowing templating environment specific variables into the query makes reusing a single job file for different clusters possible.

**Comment by tgross** [comment]
Hi @fredwangwang! I suspect this is the sort of thing that actually has to be done in the autoscaler and not in Nomad itself, because we pass the scaling policy as an opaque blob to the autoscaler. Going to tag in my colleague @lgfa29 to confirm that though.

**Comment by lgfa29** [comment]
Hi @fredwangwang, thanks for the idea!

There are a few things that it would be good to clarify before we are able to better scope and evaluate this feature request. The main one would be what kind of variables are you looking to interpolate. In a broad sense, I would say there are 3 types:

1. **Static submit-time variables** are known at job submission time, and so they can be interpolated using a templating mechanism, such as HCL2 or Levant. For example:

```hcl
variable "dc" {
  type = string
}

job "webapp" {
  datacenters = ["${var.dc}"]

  group "demo" {
    ...
    scaling {
      ...
      policy {
        ...
        check "avg_instance_sessions" {
          source = "prometheus"
          query  = "avg(haproxy_server_current_sessions{backend=\"http_back\",datacenter=\"${var.dc}\"})"

          strategy "target-value" {
            target = 5
          }
        }
      }
    }
...
```

```shell-session
$ nomad run -var dc=dc1 example.nomad
```

2. **Static run-time variables** are only known when the allocation is scheduled and starts running, so they are related to the specifics of the environment (client IP, alloc ID etc.). What's not very clear to me here is the use case in which these variables would be used. When autoscaling workloads, we usually expect that any scaling decision would be based on an overall view of the target (for example, an average over all allocations), instead of specific instances (like an alloc ID, or host IP). 

    Could you provide more details of the scenario where you would need this? 

3. **Dynamic variables** can change at any point in time, even after the job is submitted and allocations are running. These are quite tricky to handle since the policy would be modified out-of-band. If you have a scenario that needs this type of values, using Consul template and `template` block in the Autoscaler would be the best option.

**Comment by fredwangwang** [comment]
Hi @lgfa29 thanks for the response! 

You are right that the variable used in the query fall into category 1, which I thought would need to be retrieved using [nomad runtime envs](https://www.nomadproject.io/docs/runtime/environment#runtime-environment). The one we used specifically right now is the datacenter name, basically what you showed in the example :) 

So I don't think template for scaling policy is needed anymore, closing this issue now.
