### ISSUE TITLE
ReadAt in HTTP API doesn't respect offset parameter

### ISSUE THREAD

**Issue by waziers** [hashicorp/nomad#1019]
### Nomad version
Nomad v0.3.1

### Operating system and Environment details
Ubuntu 14.04 

### Issue
The ReadAt function in the FS HTTP API doesn't respect the offset parameter

### Reproduction steps

- Run any job that produces output to stdout
- From the nomad client get which client node the job ran on and the alloc id
- Build a URL that looks like `curl -v "http://CLIENT_HOSTNAME:4646/v1/client/fs/readat/ALLOC_ID?path=alloc%2Flogs%2Fcaravan_job.stdout.0&offset=100&limit=392"`  

You will notice that changing the limit will work, but the offset doesn't do anything.

**Comment by diptanu** [comment]
@waziers Thanks for reporting this. This has been fixed in master. This will go out with the upcoming 0.3.2 release.

Also, if you are using this API for building a `cat` like feature, please use the `/v1/client/cat` API which would also make it's way with 0.3.2. If you are building anything else with `readat`, please let us know since we would like to see if we are missing any higher level APIs that might be useful!

**Comment by waziers** [comment]
That's great that it will make it 0.3.2.

I'm using `readat` to read the job's stdout in realtime and show it in an interface without having to re-fetch the entire file each polling interval with `cat`. It doesn't seem like `cat` supports an offset. 

I read somewhere that you will eventually have a streaming interface to `fs` that would be useful for this.
