### ISSUE TITLE
Allow specific binaries with raw_exec

### ISSUE THREAD

**Issue by passcod** [hashicorp/nomad#10231]
### Proposal

Instead of allowing the general use of `raw_exec`, add the ability to restrict `raw_exec` to a strict set of binaries (full paths would have to be provided in the nomad agent config, and artifact use as command disallowed maybe?).

### Use-cases

This is a little vague because it's internal tooling but we have a service that needs to run un-sandboxed on the host but we'll always want to run just that service, and we don't want to allow _everything_ to run as root via `raw_exec`.

### Attempted Solutions

We've played with suid attributes (like the `ping` utility) but ultimately went with the user denylist feature to ban all but one user for `raw_exec` and configured the sudoers file on the host to let that user call sudo on exactly only the binary we want. That's a bit horrid though.

**Comment by tgross** [comment]
Hi @passcod!

This is the sort of thing where we typically recommend people use the [Sentinel policy](https://www.nomadproject.io/docs/enterprise#sentinel-policies) support in Nomad Enterprise. We're not likely to implement this in Nomad OSS for that reason.

That being said, another option for you here is a custom task driver. Lots of folk have built their own and the maintenance burden of that isn't too terrible -- we really try to avoid breaking that API because of the ripple effects it has on the community. You can start from https://github.com/hashicorp/nomad-skeleton-driver-plugin, copy over the `raw_exec` code from https://github.com/hashicorp/nomad/tree/main/drivers/rawexec, and you're in good shape from there to write arbitrary business logic you want around restricting the binaries.

**Comment by passcod** [comment]
Ah. I understand :)

Also it occurs to me we could then hardcode the binary path in the task driver, that would be even nicer.

Thanks!
