### ISSUE TITLE
nomad fs ls is failing with strange error

### ISSUE THREAD

**Issue by mgenov** [hashicorp/nomad#1024]
### Nomad version
Nomad v0.3.1

### Operating system and Environment details
Linux

### Issue
```
$ echo $NOMAD_ADDR 
http://192.168.0.4:4646
$ nomad fs ls 0298d360 alloc/logs
Error listing alloc dir: Get http://127.0.0.1:5656/v1/client/fs/ls/0298d360-836b-1e3b-72ca-a9c989f6fe44?path=alloc%2Flogs: dial tcp 127.0.0.1:5656: getsockopt: connection refused

```

It's strange that nomad is trying to find it on port 5656, but it's configured to use: 4646

client.hcl
```
region = "xxxx"
datacenter = "xxxx"
log_level = "DEBUG"
data_dir = "/var/lib/nomad/"
client {
   	  enabled = true
    	  options = {
        "driver.raw_exec.enable" = "1"
  }
   	  servers = ["192.168.0.4:4647", "192.168.0.5:4647", "192.168.0.6:4647"]
}
ports {
    http = 5656
}
```

**Comment by diptanu** [comment]
@mgenov Two things here, In the `ports` section you have used `5656` which basically means that Nomad client's `http` service is listening on port `5656`. Also since you haven't set any `addresses` or `advertise` block the client is listening on `127.0.0.1`. So `nomad fs` is requesting `127.0.0.1:5656` on the node where you are running the command.

Are you running the clients on the same  node as servers?

**Comment by mgenov** [comment]
No, the client node that contains this information is only a client node, but there is one client in the cluster that runs on the same node as servers.

**Comment by diptanu** [comment]
@mgenov I see. So I am hoping the issue has been fixed?

Please set the appropriate `addresses` or `advertise` blocks so that the Nomad CLI can communicate with the Nomad client.

If you are using the `bind` configuration and setting that to `0.0.0.0` to make Nomad network processes listen on all interfaces, then you have to use the `advertise` block. You can use the `http` key in advertise block too, which is missing in our documentation.

**Comment by mgenov** [comment]
I'll give it a try. Thanks.
