### ISSUE TITLE
When Nomad is restarted, the successful Job will also perform the Recover task

### ISSUE THREAD

**Issue by jiaxuabc123** [hashicorp/nomad#10449]
### Nomad version
nomad 1.0.4

### Issue
When Nomad is restarted, the successful Job will also perform the Recover task
### Reproduction steps
steps:
1、Execute a job in the custom driver and the result is successful
2、restart nomad
3、 RecoverTask(handle *drivers.TaskHandle)  method is called ，The successful Job is resumed for repeated execution
#### Expected Result
A successful job should not be resumed when NOMAD is restarted

**Comment by tgross** [comment]
Hi @jiaxuabc123!

The [`RecoverTask`](https://github.com/hashicorp/nomad/blob/v1.0.4/plugins/drivers/client.go#L128-L135) operation is what happens when the Nomad client tries to sync its local state store with the state of the running tasks for the task drivers. So for example, with a Docker task, the client will have the Docker ID and ask `dockerd` for a handle to a container with that ID.

Normally when the Nomad client stops, tasks will keep on running. After some time, the Nomad server will declare these tasks as "lost" and reschedule them. At that point, if the Nomad client comes back online, the server will tell it to stop the tasks. So you shouldn't be seeing tasks stopped or restarted during a restart. Can you explain a bit more about what you're seeing? Logs from the client or the output of `nomad alloc status` would be helpful.

**Comment by jiaxuabc123** [comment]
I added a log to the recoverTask () method: d.loger.info ("rawexec recoverTask ","ID", handle.config.id).  
nomad  server and client are on the same machine.
**The job contents**：
job "testjob8" {
  datacenters = ["dc1"]
  type = "batch"
  constraint {
    attribute = "${attr.kernel.name}"
    value     = "linux"
  }
  group "job5_example" {
    count = 2
    task "ls" {
      driver = "raw_exec"
      config {
        command = "ls"
        args = ["/root"]
      }  } }}

**job status**
ID        Type   Priority  Status  Submit Date
testjob8  batch  50        dead    2021-04-28T16:23:55+08:00

**After nomad restart,  recoverTask () is automatically called **
Here is the log:
2021-04-28T16:24:57.934+0800 [INFO]  client.driver_mgr.raw_exec: rawexec RecoverTask: driver=raw_exec ID=28fc3488-ff33-cedb-e112-a0072be73719/ls/93489c3d
    2021-04-28T16:25:05.305+0800 [ERROR] client.driver_mgr.raw_exec: failed to reattach to executor: driver=raw_exec error="error creating rpc client for executor plugin: Reattachment process not found" task_id=28fc3488-ff33-cedb-e112-a0072be73719/ls/93489c3d
    2021-04-28T16:25:05.308+0800 [INFO]  client.driver_mgr.raw_exec: rawexec RecoverTask: driver=raw_exec ID=ead11ae3-887e-5f55-4ea4-001e8d927f7c/ls/bf9880cd
    2021-04-28T16:25:07.793+0800 [ERROR] client.driver_mgr.raw_exec: failed to reattach to executor: driver=raw_exec error="error creating rpc client for executor plugin: Reattachment process not found" task_id=ead11ae3-887e-5f55-4ea4-001e8d927f7c/ls/bf9880cd

**Comment by tgross** [comment]
Hi @jiaxuabc123! 

Running the server and the client on the same host is not really a supported topology, because the server can't keep track of what's going on for the client during the restart. So I'd expect to see a few weird behaviors. But in this case, the behavior you're seeing is completely harmless.

The `RecoverTask` step you're seeing is about recovering the client's handle to the task, not about restarting the task. So if the client restarts before the allocation has been garbage collected on the client, when the client restarts it will still have a handle it wants to restore in the state store, but there won't be a running task (because it's completed!) and you'll see that error message. But the task won't be restarting.

For example, using this job:

```hcl
job "example" {
  datacenters = ["dc1"]
  type        = "batch"

  group "group" {
    count = 2
    task "task" {
      driver = "raw_exec"
      config {
        command = "/bin/sh"
        args    = ["-c", "touch /srv/gh10449-${NOMAD_ALLOC_ID}-$(date +%H%M%S)"]
      }
    }
  }
}
```

If I run the job, I'll see two files written to disk, one for each allocation:

```
$ nomad job run ./example.nomad
==> Monitoring evaluation "9971f7d6"
    Evaluation triggered by job "example"
==> Monitoring evaluation "9971f7d6"
    Allocation "682b0afd" created: node "245acf96", group "group"
    Allocation "6d288974" created: node "245acf96", group "group"
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "9971f7d6" finished with status "complete"

$ ls /srv | grep gh*
gh10449-682b0afd-f820-d78f-9661-11684a49fde9-204330
gh10449-6d288974-88c9-f024-0d0b-b6b490672e8d-204330
```

If I then restart the client, I see the error messages around reattachment just as you did:

> 2021-04-28T20:44:06.593Z [ERROR] client.driver_mgr.raw_exec: failed to reattach to executor: driver=raw_exec error="error creating rpc client for executor plugin: Reattachment process not found" task_id=682b0afd-f820-d78f-9661-11684a49fde9/task/e1ce302d
> 2021-04-28T20:44:06.593Z [ERROR] client.driver_mgr.raw_exec: failed to reattach to executor: driver=raw_exec error="error creating rpc client for executor plugin: Reattachment process not found" task_id=6d288974-88c9-f024-0d0b-b6b490672e8d/task/e768a197

But the tasks don't restart, and so there are still only two files created:

```
$ ls /srv | grep gh*
gh10449-682b0afd-f820-d78f-9661-11684a49fde9-204330
gh10449-6d288974-88c9-f024-0d0b-b6b490672e8d-204330
```

**Comment by jiaxuabc123** [comment]
OK, I think I get it. Thanks a lot.
