### ISSUE TITLE
connect: improve envoy bootstrap coordination 

### ISSUE THREAD

**Issue by shoenig** [hashicorp/nomad#10451]
Currently the envoy bootstrap process needs Consul to accomplish 2 things before invoking `consul envoy -bootstrap ...`

1) For sidecar proxies, the parent service needs to finish being registered into Consul catalog

2) When ACLs are enabled, the minted Service Identity tokens need to be propagated through Consul 

The [implementation](https://github.com/hashicorp/nomad/blob/v1.0.4/client/allocrunner/taskrunner/envoy_bootstrap_hook.go#L204) right now is to simply retry 3 times on 2 second intervals. Until the final failure, errors invoking Consul are ignored. This implies the above 2 pre-requsites must be met within 6 seconds of the `envoy_bootstrap_hook` running, which is [not always the case](https://github.com/hashicorp/nomad/issues/9307#issuecomment-763384985). 

Ideally we would have blocking queries to work with, but neither the agent service registration or acl token creation APIs support blocking queries.

https://www.consul.io/api-docs/agent/service#register-service
https://www.consul.io/api-docs/acl/tokens#create-a-token

I spent a little time looking into setting a watch on the Catalog waiting for the service to be registered, but AFAICT Consul will trip the watch on _any_ service changes, not just the service we care about. In the end, using a watch was a lot more chatty over the wire than just polling every few seconds. For the time being, the best option here might be to just increase the amount of time the boostrap hook allows before giving up, maybe even making it a Nomad client config parameter. Experimenting locally it's hard to gauge how long to wait is "reasonable", so how about an increase from 6 to 60 seconds?

Ideas welcome.

**Comment by TimMensch** [comment]
Looking at this error shortly after its two year anniversary of being posted with zero actual responses from the developers is _not_ giving me warm-and-fuzzy feelings about the reliability of Consul/Nomad service meshes.

I'm still seeing frequent timeouts on high-end VMs with near zero load. 

This really strikes me as fundamentally a Consul bug (or design flaw). Why isn't a registered task effectively immediately available, especially on a server with effectively zero load? Raising the timeout is a band-aid to mask the fact that it can take 60+ seconds to register a task on an otherwise idle Consul cluster, and it clearly isn't enough.

<img width="870" alt="firefox_2023-05-04_09-57-29" src="https://user-images.githubusercontent.com/530873/236277109-1126759b-b7e7-4f2c-b59c-8937bc01eaf0.png">

The image above shows one of the intermittent failures I've seen. I've also seen tasks that Nomad says are 100% healthy take minutes to show up on Consul. Unless there's some Consul setting that I can change that will make Consul behave with reasonable latency, my only choice will be to abandon Nomad/Consul Service Mesh.

**Comment by colinbruner** [comment]
Switching recently to using Nomad workload identity (new in 1.7.x) to generate tokens from Consul, I've observed this is still relevant.

If possible it would be great to see this connectivity between Nomad <-> Consul further prioritized and strengthen with better solutions to problems like these.

**Comment by tgross** [comment]
Just a heads up that we've got a proposed fix being worked on. See https://github.com/hashicorp/nomad/issues/9307#issuecomment-2104799417 for explanation.

**Comment by colinbruner** [comment]
Thanks Tim, glad this is on the radar!

**Comment by tgross** [comment]
I've just merged https://github.com/hashicorp/nomad/pull/23381 which hopefully should close out this issue. That's planned for release in Nomad 1.8.2 (with backports to Nomad Enterprise 1.7.x and 1.6.x). Once you've deployed that, if you're still running into issues with Envoy bootstrap, please report a new issue after having gone through the troubleshooting guides in [Nomad's Service Mesh troubleshooting](https://developer.hashicorp.com/nomad/docs/integrations/consul/service-mesh#troubleshooting) and [Resolving Common Errors in Envoy Proxy](https://support.hashicorp.com/hc/en-us/articles/5295078989075-Resolving-Common-Errors-in-Envoy-Proxy-A-Troubleshooting-Guide). That'll help us separate out additional problems above-and-beyond the ones we've identified here.
