### ISSUE TITLE
Homepage still uses old wording

### ISSUE THREAD

**Issue by guettli** [hashicorp/nomad#10495]
On https://www.nomadproject.io/docs/nomad-vs-kubernetes

There is still

> Kubernetes aims to provide all the features needed to run Docker-based applications

This was fixed from "Docker" to "Linux" here: https://github.com/hashicorp/nomad/blame/main/website/content/docs/nomad-vs-kubernetes/index.mdx

But the change is not live yet.

**Comment by tgross** [comment]
Hi @guettli! We don't automatically ship documentation that lands on `main` to the `stable-website` branch that makes it live, because that would cause the docs to get updated for unreleased features. There's a "versioned docs" project in the works, but I'm not sure when that's going to land.

In any case, you can expect a docs update later today!
