### ISSUE TITLE
Roll raft replication metrics for heartbeat, appendEntries_rpc, and appendEntries_logs into a single set of metrics.

### ISSUE THREAD

**Issue by joshdurbin** [hashicorp/nomad#10533]
Roll nomad_raft_replication metrics for heartbeat, appendEntries_rpc, and appendEntries_logs into a single set of metrics separate by labels.

Nomad currently reports the following metrics;

1. `nomad_raft_replication_appendEntries_logs`
1. `nomad_raft_replication_appendEntries_rpc`
1. `nomad_raft_replication_heartbeat`

for each RPC server IP and port. That is, if you have 3 nomad servers 192.168.1.1-192.168.1.3 with an RPC binding on 4647, you'll have the following metrics for `nomad_raft_replication_heartbeat`:

```
nomad_raft_replication_heartbeat_192_168_1_1:4647
nomad_raft_replication_heartbeat_192_168_1_1:4647_count
nomad_raft_replication_heartbeat_192_168_1_1:4647_sum
nomad_raft_replication_heartbeat_192_168_1_2:4647
nomad_raft_replication_heartbeat_192_168_1_2:4647_count
nomad_raft_replication_heartbeat_192_168_1_2:4647_sum
nomad_raft_replication_heartbeat_192_168_1_3:4647
nomad_raft_replication_heartbeat_192_168_1_3:4647_count
nomad_raft_replication_heartbeat_192_168_1_3:4647_sum
```

The same pattern applies to `nomad_raft_replication_appendEntries_logs` and `nomad_raft_replication_appendEntries_rpc`.

### Proposal

Consul, on the other hand, reports this data under 3 metrics with additional labels; 

1. `consul_raft_replication_appendEntries_logs`
1. `consul_raft_replication_appendEntries_rpc`
1. `consul_raft_replication_heartbeat`

### Use-cases

This must makes generating dashboards reporting on internal raft metrics easier to develop between those two infrastructure tools. Particularly because I'm using functions like `label_values` in Grafana to dynamically grab the list of servers. I could rewrite these metrics to achieve the same thing, but thought I'd suggest this change or least get more information on why this is different.

### Attempted Solutions

--

**Comment by tgross** [comment]
Hi @joshdurbin! As it turns out, those metrics are being emitted by the shared raft library we use across HashiCorp products. And on Consul, they're on a more recent version which includes an [`appendEntries`](https://github.com/hashicorp/raft/blob/v1.3.1/replication.go#L583-L591) function with the labels. But in Nomad we still have a slightly older version of the library (1.1.3).

So the good news is we'll have this fixed as soon as we do our next raft library update. Because that takes a bit of testing it might be a little while. I'll mark this issue as accepted and we'll let you know when to expect that change to land.

**Comment by joshdurbin** [comment]
Woot! Thanks for the update.
