### ISSUE TITLE
Systems using cgroups v2 by default are incompatible

### ISSUE THREAD

**Issue by thetooth** [hashicorp/nomad#10551]
Using the latest nomad release and arch linux, tasks fail to stop or restart due to cleanup when trying to remove the cgroup using the (missing) v1 API

```
2021-05-10T16:31:45.187+0930 [ERROR] client.driver_mgr.raw_exec: error receiving stream from Stats executor RPC, closing stream: alloc_id=e20b6569-02d9-8c23-8fb2-a3405dcf3974 driver=raw_exec task_name=graphics-overlay error="rpc error: code = Unavailable desc = transport is closing"
client.driver_mgr.raw_exec: destroying executor failed: driver=raw_exec err="rpc error: code = Unknown desc = 1 error occurred:
* Can't destroy: cgroup configuration empty
```

As a workaround `systemd.unified_cgroup_hierarchy=0` can be set as a kernel parameter to bring back v1.

However I think it's a good time to look towards supporting v2 if distros are going to start using this by default.

**Comment by drewbailey** [comment]
Hey @thetooth thanks for reporting. I think this is related to https://github.com/hashicorp/nomad/issues/10251.  Currently in raw_exec, we attempt to use freezer cgroup to track pids and use cgroupv1 interface for it. Since this issue is covered in the one linked I'm going to close this out in favor of that one.
.

**Comment by tgross** [comment]
Whoops, never closed this out!
