### ISSUE TITLE
Allow ACL Token to be provided by a Reverse Proxy

### ISSUE THREAD

**Issue by legege** [hashicorp/nomad#10561]
### Proposal
It would be useful to allow a Reverse Proxy to set the Nomad ACL Token via the header `X-Nomad-Token`.

### Use-cases

Allowing a Reverse Proxy to inject this ACL Token can help to implement some login flow with 3rd party SSO. Consul does support that today.

The idea is also [mentioned in this comment](https://github.com/hashicorp/nomad/issues/6054#issuecomment-673897105) (issue #6054).

### Attempted Solutions

- With current version (1.0 or 1.1 beta), when you configure the Reverse Proxy to inject this header, most of the UI features work: jobs listing, servers/clients listing, etc. But some features are not working properly (e.g. the "Run job" button is greyed out).
- With the new One-Time Token feature introduced in 1.1, it would probably be easy to implement such feature, as there is already a UI flow to get a token and start using it in the UI. We simply need the UI to be aware that a token is provided.

### References

- [Configure NGINX Reverse Proxy for Nomad's Web UI](https://learn.hashicorp.com/tutorials/nomad/reverse-proxy-ui)

**Comment by tgross** [comment]
Thanks for opening this issue @legege! I've assigned this to @backspace so that once we review that PR we can determine whether that really closes out the issue described here.

**Comment by legege** [comment]
@tgross Anything I can do to help the discussion here for PR #10563?

**Comment by tgross** [comment]
Sorry @legege, we're in the middle of onboarding some folks onto the UI side of the team and that's creating a bit of delay there. I've changed the reviewer and pulled in one of our product security folks for review as well.

**Comment by tfeyereisen-exactsciences** [comment]
We use enterprise versions of Nomad, Vault, Consul and Terraform. Currently Nomad is the only product that doesnt support SSO. Our current Nomad authentication method is based on AWS credentials and reading from the Nomad secrets engine in Vault to obtain a short lived token. We have 100s of developers that we'd like to onboard to Nomad across some 15+ Nomad namespaces. In the end, we gain very little adoption from engineering teams because it's simply too inconvenient to navigate the authenticate workflow. We want our developers in Nomad, but we have to make it easy. This also goes for our operations teams. They should be comfortable getting into Nomad to potentially do first pass troubleshooting, restarting failed jobs, etc. It's hard to fathom integrating a product into an enterprise these days without SSO. We view Nomad as an enterprise product and need SSO to successfully integrate.

**Comment by josegonzalez** [comment]
Looks like https://github.com/hashicorp/nomad/pull/10563 potentially fixes this issue (though native integration with Okta would be great).

**Comment by lgfa29** [comment]
You are right @josegonzalez, this particular issue was fixed in #10563, so I am going to close this as fixed 🙂 

@tfeyereisen-exactsciences SSO support is part of a larger discussion, so I created #10999 for us to track it. Feel free to 👍 and add any additional comments you may have.

**Comment by josegonzalez** [comment]
@legege do you happen to have an nginx conf or some similar thing that implements the auth reverse proxy flow for reference?
