### ISSUE TITLE
Improve Connect scheduling 

### ISSUE THREAD

**Issue by shoenig** [hashicorp/nomad#10700]
Currently Nomad only checks for the presense of Consul at a minimum version number before scheduling Connect enabled tasks.

In reality, Connect must be explicitly enabled on each Consul agent, and the gRPC port must be set to active the grpc listener for the agent. This is been a source of pain and confusion for users who are missing these config values in Consul, which in turn appears like Nomad problems when their Connect sidecars fail to make contact with Consul. 

Using the `consul.connect` and `consul.grpc` node attributes introduced in #10699, add additional constraints for Connect tasks so they are only provisioned on nodes where Connect is actually enabled.

**Comment by kds-rune** [comment]
I know this is closed, but the [consul documentation ](https://www.consul.io/docs/connect/configuration#agent-configuration)states the following:

"The first step to use Connect is to enable Connect for your Consul cluster. By default, Connect is disabled. Enabling Connect requires changing the configuration **of only your Consul servers (not client agents)**. To enable Connect, add the following to a new or existing server configuration file."

I now had to reconfigure all clients with this setting in the consul client-configuration, otherwise they got filtered by nomad to connect.enabled-constraint. I couldn't find any reference in the consul-documentation stating this should be set on client nodes, so I am still a bit confused ;)

**Comment by tgross** [comment]
Hi @kds-rune! Let's open a new issue to discuss documentation concerns, or post on [Discuss](https://discuss.hashicorp.com/c/nomad/28). Thanks!

**Comment by runeron** [comment]
https://discuss.hashicorp.com/c/nomad/28
