### ISSUE TITLE
Configure cleanup behavior

### ISSUE THREAD

**Issue by sheerun** [hashicorp/nomad#1079]
The documentation says following about garbage collection behavior:

> Both these directories are persisted until the allocation is removed, which occurs hours after all the tasks in the task group enter terminal states. This gives time to view the data produced by tasks.

But I'd like to be able to configure this period, or actually to prevent gc at all until I explicitly remove allocation. I suggest to introdue per-task option to configure this period and to implement DELETE method for allocations.

**Comment by sheerun** [comment]
Optionally nomad could implement "Stopped" state similarly to Docker Cloud.

Stopped = not running, all logs and containers still there. Terminated = ready for cleanup.

**Comment by diptanu** [comment]
@sheerun So there are some issues around this.

a. Allowing configuration of per task GC of a Task - This would allow end-users to control internal behavior of Nomad and it will be hard to reason for operators or auditing systems to get any forensic data deterministically out of an allocation which ran on a client node.

b. Leaving allocation directories around until a user has intervened and asked Nomad to explicitly GC the allocation means that we will not be freeing up disk resources when a job finishes. This works fine if the size of clusters are small but breaks down the cluster size is 10s of 1000s of machines since at that scale very little manual intervention is desired. If operators or users want to see information from allocation directories beyond what Nomad client is going to have, pushing the contents to a centralized blob storage or logging service works well.

**Comment by sheerun** [comment]
> Also, imagine a user is running 1000s of jobs which run for a small amount of time and a user is setting the GC duration to be really long - this would adversely affect other users using the same Nomad cluster.

But this is what you do by setting gc period to ~4 hours. 1 000 000 can leave a lot of directories behind. Allowint for manually deleting allocations prevents such scenario as one can write simple script to fetch logs/artifacts from terminated allocations and automatically delete it.

> the cluster size is 10s of 1000s of machines since at that scale very little manual intervention is desired

By manual I meant automatic, by script

> a. Allowing configuration of GC of a Task - This would allow end-users to control internal behavior of Nomad and it will be hard to reason for operators or auditing systems to get any forensic data deterministically out of an allocation which ran on a client node.

True, but sometime 4 hours is too short. At last people sleep for 8 hours.

**Comment by dadgar** [comment]
You could run a sidecar task to ship your logs or required data off disk. The environment is ephemeral.

**Comment by sheerun** [comment]
Is it a recommended method? Could you provide an example of task that waits for other one to finish and then ships logs?

**Comment by dadgar** [comment]
@sheerun That is how we do it in our production use of Nomad. See here for an example https://github.com/hashicorp/nomad/issues/873#issuecomment-191424521

**Comment by diptanu** [comment]
@sheerun Yeah you are right that by having a fixed GC period we are leaving a lot of allocation directories behind, this needs to be fixed in Nomad client. Nomad clients should GC allocation directories when there is pressure on disk space, and keep old allocation directories based on a based effort guarantee. 

In my experience, I have seen that things scale when only when ephemeral storage is treated strictly as ephemeral and operators and users are not guaranteed that the data is going to live on a node when it's no longer used by the process which created it.

If a user needs persistent storage, the volume has to be treated differently and the service should provide some guarantee around how long it will be persisted and the number of such persisted volumes that the system can ever have in a certain number of compute nodes. Hopefully, we will be able to address all this in the future.

**Comment by leetrout** [comment]
This is slightly off topic but I wanted to toss this out since it's related and I didn't know if a separate issue is warranted. Something that would be awesome, because I'm going the sidecar route, would be an endpoint or an update to the fs stat endpoint that included a hash of the file or some other marker to know if the file has changed.

I'm basically making a vacuum process to pull the logs out and generating the hashes based on the info in the stat response (e.g. `base64(sha256(DateModified + Size))`) so I don't waste bytes over the wire. 

If this seems like a good pattern and something someone else might do it could be helpful to have that come back in the stat response...

**Comment by dadgar** [comment]
@leetrout We will probably keep the Stat call inline with the syscall. But sounds like you have a good solution.

**Comment by c4milo** [comment]
@dadgar, @diptanu: How would this work for periodic jobs running often? wouldn't the disk fill up pretty quickly?

**Comment by dadgar** [comment]
@c4milo Nomad 0.5 will have the client manage its own disk, so if there is disk pressure, the client will remove old allocations.

For now all I can really suggest is calling: `curl -XPUT http://127.0.0.1:4646/v1/system/gc` periodically to force garbage collection.

On a different note I am going to close this issue because we will not be doing custom GC intervals for jobs.
