### ISSUE TITLE
Inherit Docker Task networking configuration from Group Networking Block 

### ISSUE THREAD

**Issue by clly** [hashicorp/nomad#10851]
### Proposal
When configuring a nomad job the user can specify a networking configuration inside different job groups. Each task can also have a separate configuration and when that task is a docker image, that configuration can include newtorking specifications. If a user specifies a networking mode in the group configuration they must also specify the same networking mode in the docker task driver. This can create confusion until/unless the user ends up doing more investigation into the docker task driver configuration (which defaults to `bridge`). It'd reduce confusion to make the behavior inherited between from the group networking block into the task networking block.

This could be complicated by the fact that the group networking block defaults to `host` but the task networking block defaults to `bridge` in docker

### Use-cases
Reduce required duplication and confusion in networking configuration

### Attempted Solutions
Duplicate configuration and add extra documentation/gotcha's for group vs task networking configuration.

**Comment by tgross** [comment]
Hi @clly! This is definitely a documentation gap and I know @lgfa29 is working on some improvements there.

But the behavior is itself is intentional and had to be done that way for backwards compatibility when we added group networking.

> If a user specifies a networking mode in the group configuration they must also specify the same networking mode in the docker task driver. 

This isn't always the case. For example, if you've set the networking mode to `bridge` in the group configuration you do _not_ want to also set the networking mode on a Docker task or it will end up being in a different network namespace from that bridge network (and any other tasks in the same alloc!). If `network.mode = "bridge"` and the Docker task networking is unset, the Docker task's network will be set to `container:<id of pause container>`. (See https://www.nomadproject.io/docs/drivers/docker#network_mode)

**Comment by clly** [comment]
That makes sense and I appreciate the context. It sounds like the the documentation fix would probable prevent other folks from running into this issue. 

I can also attempt my own documentation fix for what I've run into here if y'all think it'd be useful.

**Comment by ruhrscholz** [comment]
The change in documentation would definitely help, as I've run into the problem this week and this GitHub issue seems to be the only place explaining why the networking only works one-way when specifying bridge-networking for the group only. Are there any updates on this?
