### ISSUE TITLE
acl bootstrap -json

### ISSUE THREAD

**Issue by tomlankhorst** [hashicorp/nomad#10880]
### Proposal
Add `-json` formatting to `acl bootstrap` 

Analogous to `consul acl bootstrap -format=json`.

### Use-cases
Easy automatic deployment of ACL in new Nomad clusters

`BOOTSTRAP_TOKEN=$(nomad acl bootstrap -json | jq -r '.SecretID')`

### Attempted Solutions
Parse the human-readable output, but this is not stable or elegant. 

`BOOTSTRAP_TOKEN=$(nomad acl bootstrap | awk '/Secret/ {print $4}')`

**Comment by mikenomitch** [comment]
Hey @tomlankhorst, this definitely seems like a good idea, especially since it is in Consul as well.

Unfortunately, it isn't super high priority for the team, so I worry that the issue might sit here un-done for a while.

Would you be open to opening a PR for this?

It seems like an ideal community PR since there is pretty clear success criteria, no coupling with the rest of the codebase, and the Consul code could be used for inspiration.

**Comment by jrasell** [comment]
This has now been resolved by https://github.com/hashicorp/nomad/pull/11411 and will be available within the Nomad 1.2.0 release.

**Comment by tomlankhorst** [comment]
Thanks a lot!
