### ISSUE TITLE
Cannot update a dispatched job

### ISSUE THREAD

**Issue by sirkrypt0** [hashicorp/nomad#10941]
### Nomad version

`Nomad v1.1.2 (60638a086ef9630e2a9ba1e237e8426192a44244)`

### Operating system and Environment details

Ubuntu 20.04

### Issue

Jobs created via `dispatch` cannot be updated.

### Reproduction steps

1. Start a Nomad dev aget
    ```
    $ nomad agent -dev
    ```
1. Run the reproduction parameterized batch job
    ```
    $ nomad run batch.nomad
    ```
1. Dispatch an instance of the parameterized job
    ```
    $ nomad job dispatch batch
    ```
1. Open the Nomad UI and navigate into the batch job
1. Navigate into the dispatched job
1. Edit the jobs definition, e.g., change available resources
1. Plan and submit the job

#### Expected Result

The job is updated correctly.

#### Actual Result

The following error is shown:

```
cannot update non-parameterized job to being parameterized
```

### Job file (if appropriate)

```hcl
job "batch" {
  datacenters = ["dc1"]
  type        = "batch"

  parameterized {}

  group "batch" {
    task "sleep" {
      driver = "docker"

      config {
        image   = "alpine:latest"
        command = "sleep"
        args = ["infinity"]
      }

      resources {
        cpu    = 40
        memory = 40
      }
    }
  }
}
```

**Comment by tgross** [comment]
Hi @sirkrypt0! That's the expected behavior, but not well documented and definitely a poor error message. Once a job has been dispatched, the dispatch payload has been set and it's no longer "parameterized". But trying to update it uses the parameterized job definition of its parent job, and that can't be done.

Generally speaking what you'll want to do is to update the parent job and then re-dispatch it.

**Comment by sirkrypt0** [comment]
Alright, thanks for the clarification :)

Then this issue can be closed, unless you want to keep it open for a better documentation/error message.

**Comment by waquidvp** [comment]
@tgross [nomad-pipeline](https://github.com/HyperBadger/nomad-pipeline) is a small tool I am working on. It allows you do create "pipeline" jobs in Nomad. It does this by using lifecycle hooks that updates the task groups `count`. It was inspired by this blog post: https://www.cgbaker.net/2020/12/hacking-nomad-job-dependencies/.

Since it relies on having to update the job to work, the behavior described in this bug means that it doesn't work with parameterized (dispatched) job. I know you have a valid reason for closing this bug however I though I show a possible use-case for needing the ability to update a dispatched job.

Also it's worth mentioning that I have been using the "fix" in https://github.com/hashicorp/nomad/pull/10942. It has been working so far without any issues.

Am I just asking for trouble with updating dispatched jobs? or maybe even normal jobs?

**Comment by tgross** [comment]
> Am I just asking for trouble with updating dispatched jobs?

Probably. 😀 Any sort of logic around the `reschedule` block, node drains, or node failure are places where stuff could be totally broken. It's not workflow we've tested at all. 

But for dispatch jobs the "scale to 1" workflow described by Chris' blog post is also unnecessary. Instead of scaling the next job from from 0 to 1, just dispatch the next job.

**Comment by waquidvp** [comment]
> Instead of scaling the next job from from 0 to 1, just dispatch the next job.

This would work, however you will loose the nice behaviour of using the meta tags to control the order. But I will definitely think about how I could handle this...

> It's not workflow we've tested at all.

Does this apply to in place updates to normal jobs aswell?

**Comment by tgross** [comment]
> Does this apply to in place updates to normal jobs aswell?

Updating non-dispatch jobs should work as one would expect and that's a well-tested path.

**Comment by waquidvp** [comment]
Thanks for the confirmation.
