### ISSUE TITLE
[ui] Exec UI selects wrong allocation

### ISSUE THREAD

**Issue by Mongey** [hashicorp/nomad#10962]
### Nomad version
1.1.2

### Operating system and Environment details

`Linux ip-<redacted> 4.9.0-16-amd64 #1 SMP Debian 4.9.272-1 (2021-06-21) x86_64 GNU/Linux`

### Issue
The exec UI is misleading about how it'll choose an allocation -- it only uses task names to filter allocations, and not group names.

### Reproduction steps
Start a job with different group names, but task names the same. 
Navigate to the UI. Select a job under the console group.

(some bad redacting done)
<img width="1085" alt="Screenshot 2021-07-28 at 17 25 52" src="https://user-images.githubusercontent.com/625787/127361578-21bcf6ec-7490-46bc-a2f5-8279f78b8807.png">

#### Expected Result
The allocation you exec into belongs to the expected  group. (in the example that would be the console group)

#### Actual Result
The allocation belongs to a random group.

**Comment by jrasell** [comment]
Hi @Mongey and thanks for raising this issue. I have assigned it to someone who has a much better understanding of the UI than myself, so they can look into this when they have availability.

**Comment by jwoglom** [comment]
I think a fix for this issue should be prioritized. For what it's worth, I would be okay with this bug if it selected the wrong task but at least highlighted the task inside the correct task group in which it arbitrarily decided to use. But in #14362 I raised the fact that it highlights the group name for the task you selected on the left hand side, **despite selecting the identically named task in the other group**. I think this presents serious risk for accidentally breaking something by connecting to the wrong task using the exec feature inside the UI, because unless you cross reference the task allocation ID manually before running a potentially destructive command, all indications appear that you are connected to a different task which gives the user a false sense of security.
