### ISSUE TITLE
Add user specified labels to Nomad Allocation Metrics 

### ISSUE THREAD

**Issue by kfenech1** [hashicorp/nomad#11011]
### Proposal
As a developer I would like to be able to add labels to the Nomad Telemetry Metrics.  I would like to add labels in the Job definition which are propagated to the allocations metrics generated by Nomad. This would allow a user to filter better when creating dashboards etc. Currently metrics are not being propagated to the Nomad Metrics telemetry when labels are added to to Task -> Config stanza. Having said that, when cAdvisor is installed as a container on Nomad-client, it manages to pick up those labels and adds them to the metrics generated by cAdvisor. Having the same for Nomad metrics would be very helpful.

### Use-cases
Having this functionality will allow users to perform better filtering when analysing metrics and create dashboards. 

### Attempted Solutions
Install cAdvisor and use metrics generated by cAdvisor instead of Nomad Metrics. This however introduces overhead and more network traffic since a new endpoint for each client (that essentials provides similar metrics to Nomad Metrics) will need to be scraped by your monitoring system.

**Comment by jrasell** [comment]
Hi @kfenech1 and thanks for raising this issue. It is certainly something we would be interested in supporting in the future.

**Comment by chrismikehogan** [comment]
Just wanted to add another use we have that would benefit: We run multiple jobs with different SLA tiers on the same nomad cluster (think bronze, silver, gold), each with different SLAs. 

If gold-tier jobs start queueing due to resource exhaustion in middle of night, we'd like to get alerted. If bronze-tier jobs are queueing however (they have lower priority) we don't want to get woken up. 

Having ability to add custom labels would allow us to do this!

**Comment by tgross** [comment]
Closed by https://github.com/hashicorp/nomad/pull/23964
