### ISSUE TITLE
"Dispatch Job" button does not work

### ISSUE THREAD

**Issue by evandam** [hashicorp/nomad#11031]
### Nomad version
`Nomad v1.1.3 (8c0c8140997329136971e66e4c2337dfcf932692)`

### Operating system and Environment details
Ubuntu 18.04

### Issue
Clicking the "Dispatch Job" button in the UI of a parameterized job results in a blank white page.

### Reproduction steps
Run following HCL and click "Dispatch Job" in UI

#### Expected Result
Matches screenshots in https://github.com/hashicorp/nomad/pull/10675

#### Actual Result
![Screen Shot 2021-08-10 at 3 47 53 PM](https://user-images.githubusercontent.com/3985383/128944940-c74f8f5f-36c7-4ba2-8050-c818e432c5f2.png)

### Job file (if appropriate)
```hcl
job "rake-task" {
  datacenters = ["kitchen"]
  type = "batch"

  parameterized {
    payload       = "forbidden"
    meta_required = ["RAKE_TASK_NAME"]
  }

  group "app" {
    task "rake-task" {
      driver = "docker"

      config {
        image      = "alpine"
        entrypoint = ["echo"]
        args       = ["${NOMAD_META_RAKE_TASK_NAME}"]
      }

      resources {
        cpu    = 20
        memory = 500
      }
    }
  }
}

```

**Comment by lgfa29** [comment]
Thank you for the report @evandam. 

This is unfortunately a known issue that was fixed in https://github.com/hashicorp/nomad/pull/10934, but hasn't shipped yet, so apologies for that. 

As a workaround for now you can set an empty list for `meta_optional` inside your `parameterized` block. So something like this:

```hcl
parameterized {
  payload       = "forbidden"
  meta_required = ["RAKE_TASK_NAME"]
  meta_optional = []
}
```

You may need to close the Nomad UI tab to reload its internal state. 

Give a try and let me know how it goes 🙂

**Comment by evandam** [comment]
Hey @lgfa29, no dice with `meta_optional = []` but adding a dummy value like `meta_optional = ["foo"]` did the trick. Not sure if the link you fixed covers it 🤞 

Thanks!

**Comment by lgfa29** [comment]
> Hey @lgfa29, no dice with `meta_optional = []` but adding a dummy value like `meta_optional = ["foo"]` did the trick.

Ah Interesting. I tested with only `meta_optional = []` and it worked. I was probably the one with some remaining internal state 😅 

>  Not sure if the link you fixed covers it 🤞

Yup. I just tested the job file you provided against our `main` UI code and it works without any modification
![image](https://user-images.githubusercontent.com/775380/129079108-884274fa-2b06-4b7e-ba55-44f70b9c7791.png)

So I'm going to close this since we have a fix already, but feel free to reach out again if you have any other problem.
