### ISSUE TITLE
Files from artifact do not persist in alloc directory

### ISSUE THREAD

**Issue by jmwilkinson** [hashicorp/nomad#11146]
### Nomad version
```
# nomad version
Nomad v1.1.4 (acd3d7889328ad1df2895eb714e2cbe3dd9c6d82)
```

### Operating system and Environment details

```
# uname -a
Linux host 4.18.0-240.el8.x86_64 #1 SMP Fri Sep 25 19:48:47 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

### Issue

When populating the `alloc` directory using the `artifact` stanza, it appears the files do not persist to subsequent tasks.

### Reproduction steps

1. Run the following job as described in the job file below.
2. Check the contents of the `test-pre` task `alloc/data` directory.
3. Check the contents of the `test-start` task `alloc/data` directory.

#### Expected Result

The directory `alloc/data/getting-started` should exist in both the `test-pre` and `test-run` directories.

#### Actual Result

The directory `alloc/data/getting-started` exists in `test-pre`, but not in `test-run`.

```
# ls -l test-pre/alloc/data/
total 0
drwxr-xr-x. 6 root root 220 Sep  7 18:55 getting-started
[root@host 129100e8-fe2b-f93a-684d-2bb396a58715]# ls -l test-run/alloc/data/
total 0
```

### Job file (if appropriate)

```
job "test" {
    name = "test"
    type = "system"

    datacenters = ["dc1"]

    group "test" {

        network {
            port "http" {
                static = 5000
            }
        }

        task "test-pre" {

            artifact {
                source      = "git::https://github.com/heroku/node-js-getting-started.git"
                destination = "alloc/data/getting-started"
            }
            driver = "raw_exec"

            config {
                command = "/bin/sh"
                args    = ["-c", "cd alloc/data/getting-started && npm install"]
            }

            lifecycle {
                hook = "prestart"
                sidecar = false
            }
        }

        task "test-run" {
            driver = "exec"

            config {
                command = "/bin/node"
                args    = ["alloc/data/getting-started/index.js"]
            }
        }
    }
}
```

**Comment by isabeldepapel** [comment]
Hi @jmwilkinson! Thanks for the super clear breakdown of the issue. It turns out the files from artifact do get persisted in the alloc directory, it's just not being called the right way in your jobspec (and our docs could definitely be clearer here; if you have suggestions on ways to avoid this confusion, please let us know! We're always looking for ways to make them better).

The file paths in the individual task stanzas are relative to that particular task's working directory. This means when you specify the test-pre artifact destination as `alloc/data/getting-started`, you're actually copying the getting started dir to `test-pre/alloc/data/getting-started` instead of the alloc dir that's shared between tasks. (Same thing when you pass `alloc/data/getting-started/index.js` as an arg to `/bin/node` in test-run; test-run is looking for `index.js` in `test-run/alloc/data/getting-started` instead of the shared alloc dir.) If we run the `alloc fs` command after running the jobspec you provided, we can confirm this is the case:

```sh
$ nomad alloc fs 021
Mode        Size     Modified Time         Name
drwxrwxrwx  4.0 KiB  2021-09-08T19:56:26Z  alloc/
drwxrwxrwx  4.0 KiB  2021-09-08T19:56:27Z  test-pre/

$ nomad alloc fs 021 /test-pre/alloc/data/
Mode        Size     Modified Time         Name
drwxr-xr-x  4.0 KiB  2021-09-08T19:56:30Z  getting-started/
```
To write to (and read from) the alloc dir that's shared between tasks, you can use the env var `NOMAD_ALLOC_DIR`. This means tweaking your jobspec so it looks something like this:

<details><summary>jobspec</summary>

```hcl   
job "test" {
    name = "test"  
    type = "system"  

    datacenters = ["dc1"] 

    group "test" { 

        network { 
            port "http" { 
                static = 5000
            } 
        } 

        task "test-pre" {
            artifact {
                source      = "git::https://github.com/heroku/node-js-getting-started.git"
                destination = "${NOMAD_ALLOC_DIR}/data/getting-started"
            }
            driver = "raw_exec"

            config {
                command = "/bin/sh"
                args    = ["-c", "cd ${NOMAD_ALLOC_DIR}/data/getting-started && npm install"]
            }

            lifecycle {
                hook    = "prestart"
                sidecar = false
            }
        }

        task "test-run" {
            driver = "exec"

            config {
                command = "/bin/node"
                args    = ["${NOMAD_ALLOC_DIR}/data/getting-started/index.js"]
            }
        }
    }
}

```

</details>

And if we run `alloc fs` this time, we can see that getting-started is in the shared alloc directory instead of the individual task directory:
```sh
$ nomad alloc fs fac
Mode        Size     Modified Time         Name
drwxrwxrwx  4.0 KiB  2021-09-08T21:00:35Z  alloc/
drwxrwxrwx  4.0 KiB  2021-09-08T21:00:30Z  test-pre/
drwxrwxrwx  4.0 KiB  2021-09-08T21:00:35Z  test-run/

$ nomad alloc fs fac alloc/data/
Mode        Size     Modified Time         Name
drwxr-xr-x  4.0 KiB  2021-09-08T21:00:34Z  getting-started/
```

(As a side note: I still couldn't get that jobspec to work because it couldn't find node installed anywhere, so I swapped out the exec driver with a docker driver using a node image. The test-run task ended up looking like this):
```hcl

task "test-run" {
      driver = "docker"

      config {
        image   = "node:14.17.6"
        command = "node"
        args    = ["${NOMAD_ALLOC_DIR}/data/getting-started/index.js"]
      }
    }
```

You can read more about our filesystem internals [here](https://www.nomadproject.io/docs/internals/filesystem).

Hope that clears things up, but if you're still running into issues, let us know.

**Comment by jmwilkinson** [comment]
Thanks for the reply and clarification!

Due to the way my testing was constructed, I think I added to my confusion because the artifact download was successfully creating the alloc directory in the task directory, which made me think the alloc directory was simply being populated by nomad and somehow sync'ed across tasks (the fact it wasn't symlinked should have given me a hint, though...).

I did change to using the env var and got it to work, but I don't really understand _why_ it worked given your explanation.

Namely, in the prestart task I have this:

```
            artifact {
                source      = "git::https://github.com/heroku/node-js-getting-started.git"
                destination = "local/getting-started"
            }
           
           config {
                command = "/bin/sh"
                args    = ["-c", "mv local/getting-started $NOMAD_ALLOC_DIR/data/getting-started && cd $NOMAD_ALLOC_DIR/data/getting-started && /bin/npm install"]
            }
```

And then in the main task:

```
            config {
                command = "/bin/node"
                args    = ["alloc/data/getting-started/index.js"]
            }
```

And this works! The path `alloc/data` within the main task contains the `getting-started` directory.

So I am very confused by this.

**Comment by isabeldepapel** [comment]
> And this works! The path alloc/data within the main task contains the getting-started directory.

So sorry about this! You're totally right and my explanation was only about half there. The other very important half is that the filesystem setup is also going to depend on the task driver and the [task driver's filesystem isolation capability](https://www.nomadproject.io/docs/internals/filesystem#task-drivers-and-filesystem-isolation-modes). Because the main task is using exec (instead of raw_exec), which uses `chroot` isolation, it's going to have access to the `NOMAD_ALLOC_DIR` within the task working directory (nomad provides the `NOMAD_ALLOC_DIR`, `NOMAD_TASK_DIR`, and `NOMAD_SECRETS_DIR` to tasks with [`chroot` isolation](https://www.nomadproject.io/docs/internals/filesystem#chroot-isolation)).

You can confirm this by running `alloc fs`:
```sh
$ nomad alloc fs 24f
Mode        Size     Modified Time         Name
drwxrwxrwx  4.0 KiB  2021-09-09T15:47:38Z  alloc/
drwxrwxrwx  4.0 KiB  2021-09-09T15:47:31Z  test-pre/
drwxrwxrwx  4.0 KiB  2021-09-09T15:47:38Z  test-run/

$ nomad alloc fs 24f test-run/
Mode         Size     Modified Time         Name
drwxrwxrwx   4.0 KiB  2021-09-09T15:47:38Z  alloc/  # This is the NOMAD_ALLOC_DIR
drwxr-xr-x   4.0 KiB  2021-09-09T15:47:36Z  bin/
drwxr-xr-x   4.0 KiB  2021-09-09T15:47:38Z  dev/
drwxr-xr-x   4.0 KiB  2021-09-09T15:47:36Z  etc/
-rw-r--r--   345 B    2021-09-09T15:47:38Z  executor.out
drwxr-xr-x   4.0 KiB  2021-09-09T15:47:36Z  lib/
drwxr-xr-x   4.0 KiB  2021-09-09T15:47:36Z  lib32/
drwxr-xr-x   4.0 KiB  2021-09-09T15:47:36Z  lib64/
drwxrwxrwx   4.0 KiB  2021-09-09T15:47:36Z  local/
drwxr-xr-x   4.0 KiB  2021-09-09T15:47:38Z  proc/
drwxr-xr-x   4.0 KiB  2021-09-09T15:47:36Z  run/
drwxr-xr-x   12 KiB   2021-09-09T15:47:36Z  sbin/
drwxrwxrwx   60 B     2021-09-09T15:47:36Z  secrets/
drwxr-xr-x   4.0 KiB  2021-09-09T15:47:38Z  sys/
dtrwxrwxrwx  4.0 KiB  2021-09-09T15:47:36Z  tmp/
drwxr-xr-x   4.0 KiB  2021-09-09T15:47:36Z  usr/
```
If you were to change the main task driver to raw_exec, which doesn't have chroot isolation, then you'll get an error:
 
```hcl
task "test-run" {
      driver = "raw_exec"

      config {
        command = "/bin/node"
        args    = ["alloc/data/getting-started/index.js"]
      }
    }

```
The error:
```sh
$ nomad alloc logs -task test-run -stderr 77f
internal/modules/cjs/loader.js:892
  throw err;
  ^
# raw_exec is looking for an alloc dir within the task working directory
Error: Cannot find module '/tmp/NomadClient937137739/77ffb9e8-ad60-7981-a811-e60b8a81b5b2/test-run/alloc/data/getting-started/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```
Does that make more sense?

**Comment by jmwilkinson** [comment]
Ah that makes so much more sense. Clearly I didn't read far enough in the docs :)

Just as a thought, would a pull request to bring the `none isolation` drivers' directory structure in line with the others via symlinks be considered? Or would that be considered unnecessary, given the existence of the env? In which case, perhaps we could update the docs section for alloc to reference below regarding the different driver behaviors, for impatient people like me who only read the sections they feel necessary.

**Comment by isabeldepapel** [comment]
I think having the symlinks would be considered unnecessary at this time. We're always open to updating our docs, though!

> perhaps we could update the docs section for alloc to reference below regarding the different driver behaviors

Would you mind clarifying exactly which section(s) this is since I'm not exactly sure where you think it would be most helpful to have this information? And if you find it easier to just make the updates yourself in a PR, you're more than welcome to :)

**Comment by jmwilkinson** [comment]
So, I read this section:

> alloc/: This directory is shared across all tasks in an allocation and can be used to store data that needs to be used by multiple tasks, such as a log shipper. This is the directory that's provided to the task as the NOMAD_ALLOC_DIR. Note that this alloc/ directory is not the same as the "allocation working directory", which is the top-level directory. **All tasks in a task group can read and write to the alloc/ directory.** Within the alloc/ directory are three standard directories:

And, without reading further, though I should just be able to use the directory name, not the environment variable.

So perhaps we can change it to:

> alloc/: This directory is shared across all tasks in an allocation and can be used to store data that needs to be used by multiple tasks, such as a log shipper. This is the directory that's provided to the task as the NOMAD_ALLOC_DIR. Note that this alloc/ directory is not the same as the "allocation working directory", which is the top-level directory. Tasks with driver isolation of `none` may reference this directory use the `NOMAD_ALLOC_DIR` (see [here](https://www.nomadproject.io/docs/internals/filesystem#none-isolation)). Other task drivers will have this directory provided within their working directory, and may access it via the `alloc/` path (see [here](https://www.nomadproject.io/docs/internals/filesystem#image-isolation) and [here](https://www.nomadproject.io/docs/internals/filesystem#chroot-isolation)). Within the alloc/ directory are three standard directories:

Thoughts?

**Comment by isabeldepapel** [comment]
I totally agree--I think that's a great place to reference the filesystem docs. What you suggested looks really good. I might tweak it a bit so it's something like (the bolded parts are the changes):
>alloc/: This directory is shared across all tasks in an allocation and can be used to store data that needs to be used by multiple tasks, such as a log shipper. This is the directory that's provided to the task as the NOMAD_ALLOC_DIR. Note that this alloc/ directory is not the same as the "allocation working directory", which is the top-level directory. **All tasks in a task group can read and write to the alloc directory, but the path may differ depending on the task driver's [filesystem isolation mode](https://www.nomadproject.io/docs/internals/filesystem#task-drivers-and-filesystem-isolation-modes).**  Tasks with driver isolation of none may reference this directory using the `NOMAD_ALLOC_DIR` environment variable (see here) **or a relative path that traverses up into the allocation working directory (`../alloc/`)**. Other task drivers will have this directory provided within their working directory, and may access it via the alloc/ path (see here and here). Within the alloc/ directory are three standard directories:

And then maybe have the links reference parts of the text itself instead of just 'see here' (e.g. "driver isolation of `none`" can be the link you provide).

If you'd like to submit the changes as a PR (docs [here](https://github.com/hashicorp/nomad/blob/main/website/content/docs/internals/filesystem.mdx)), please do--these improvements are very much your idea and I'd love to see you get the credit you deserve. But if you'd rather someone on the team that's totally fine--just let us know and we'll get it taken care of when we get the chance

**Comment by jmwilkinson** [comment]
Those changes look good! I'll open a PR. Thank you for the link to the docs, and your assistance!
