### ISSUE TITLE
Please add ARM builds to the ubuntu repositories

### ISSUE THREAD

**Issue by tedivm** [hashicorp/nomad#11305]
Right now it's impossible to install ARM binaries via the Hashicorp apt repositories.

> Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'https://apt.releases.hashicorp.com focal InRelease' doesn't support architecture 'arm64'

### Proposal

Since you're already building for ARM it makes sense to also allow those resources to be installed from APT.

### Use-cases

I want to use Nomad to run a cluster on AWS, and I'd like to use Gravitron machines because they are significantly cheaper.

### Attempted Solutions

For now I can manually install on my instances and ignore the repository.

**Comment by lgfa29** [comment]
Hi @tedivm 👋 

I will check with the release team if there are any plans for ARM packaging and will get back to you once I have an answer.

**Comment by tgross** [comment]
@tedivm just a heads up that we have a PR open in the repo where the packages are built and are waiting on a merge (and then a release!) to make that live.

**Comment by tedivm** [comment]
Fantastic news! It'll definitely make deploying hashi projects easier.

**Comment by tgross** [comment]
Wanted to leave an update on this. Our release engineering team is gearing up to do a bunch of rework on how we build and release Nomad, so that's why the PR that's open on the old version of it has been sitting unloved for a while. We'll make sure that ARM is part of the discussion with the rel-eng folks though.

@lgfa29 I'm going make you the owner of this one as I know you were planning on coordinating that work, if that's ok?

**Comment by lgfa29** [comment]
> @lgfa29 I'm going make you the owner of this one as I know you were planning on coordinating that work, if that's ok?

Sounds good, thanks!

**Comment by centur** [comment]
Hi, is there any progress\update on this ? We are trying to run a dev cluster with nomad\consul\vault in lima-vm on MacOS (because macos has no support of bridge network in Docker which is required for consul mesh - we need to run dev env in linux vm) and we use arm64 image of Ubuntu Jelly.  Would be really great to see some progress in official supported way to install HCP tools in arm64 environments

**Comment by tgross** [comment]
@centur there are ARM builds available via the repository and we just never got around to closing this issue. We do have https://github.com/hashicorp/nomad/issues/13226 open but that appears to be a transient issue with the build infrastructure. I'm going to close this out and suggest you keep an eye on that issue.
