### ISSUE TITLE
`tls-skip-verify` may not work on nomad monitor

### ISSUE THREAD

**Issue by DerekStrickland** [hashicorp/nomad#11460]
### Nomad version

1.x.x

### Operating system and Environment details

Unknown

### Issue

The `nomad monitor` command may not be respecting the `-tls-skip-verify` flag

### Reproduction steps

- Set up a cluster with TLS enabled
- Make sure `NOMAD_CLIENT_CERT`, `NOMAD_CLIENT_KEY`, and `NOMAD_CACERT` don't match
- Run `nomad monitor -log-level=debug -tls-skip-verify`

#### Expected Result

Logs stream to console

#### Actual Result

TLS configuration error is returned

**Comment by davemay99** [comment]
@DerekStrickland `nomad operator debug` also captures monitor logs, and I have not heard reports of Nomad TLS related issues.  Might be worth comparing before digging too deep.

**Comment by DerekStrickland** [comment]
@lgfa29  Is this the error you see?

```shell
==> Error starting monitor: Get "https://3.226.47.12:4646/v1/agent/monitor?log_json=false&log_level=debu&node_id=&server_id=": remote error: tls: bad certificate
==> For additional help try 'nomad monitor -help'
```

**Comment by lgfa29** [comment]
There wasn't any particular error, the command just didn't return anything and it would just hang. Using `curl` with the proper certificates did work.

But looking at the message you posted, that seems like what I would expect to see 🤔 

Were you able to use `-tls-skip-verify` to bypass this error? If so, the problem was likely something else.
