### ISSUE TITLE
Incorrect nomad_client_allocs_memory_usage values for docker containers

### ISSUE THREAD

**Issue by rparelius** [hashicorp/nomad#11501]
### Nomad version
Nomad v1.1.6 (b83d623fb5ff475d5e40df21e9e7a61834071078)

### Operating system and Environment details
Cores: 20
Memory: 120GB
Virtualization: vmware
Operating System: CentOS Linux 7 (Core)
CPE OS Name: cpe:/o:centos:centos:7
Kernel: Linux 3.10.0-1160.42.2.el7.x86_64
Architecture: x86-64
### Issue
nomad_client_allocs_memory_usage is not correct for docker container.

We are running several allocations with 64GB of memory allocated.  

The output of `docker stats` shows only 62% utilization, and this value remains relatively constant:
```
CONTAINER ID   NAME                                             CPU %     MEM USAGE / LIMIT   MEM %     NET I/O          BLOCK I/O        PIDS
9339fdb84da0   timescale-ec4dba10-9cbc-a805-e214-2200e736b560   33.24%    40.25GiB / 64GiB    62.90%    122GB / 1.28GB   367GB / 2.78TB   21
```

However, the nomad prometheus metrics for this allocation show it at 99-100% utilization:
```
nomad_client_allocs_memory_usage{alloc_id="ec4dba10-9cbc-a805-e214-2200e736b560"}/nomad_client_allocs_memory_allocated*100
```
![image](https://user-images.githubusercontent.com/42849348/141653629-d22fa57a-9e46-4854-ad34-343592b189fa.png)

### Reproduction steps
Simply running the job, regardless of the node it runs on or how many different times it runs. 

#### Expected Result
That Nomad would accurately report (docker) allocation metrics as reported by docker

#### Actual Result
Nomad telemetry metrics show that memory usage for the allocation continues to grow until it reaches the maximum allocated amount of memory

### Job file
```
job "timescale-data" {
    datacenters = ["hydra-data"]
    type = "service"
    dynamic "group" {
        for_each = [1,2,3]
        labels = ["timescale-data-${group.value}"]
        content {
            constraint {
                distinct_hosts = true
            }

            volume "timescale" {
                type = "host"
                source = "timescale-${group.value}"
            }
                
            network {
                port "postgres" {
                    static = 5432
                }
            }

            task "timescale" {
                driver = "docker"
                volume_mount {
                    volume      = "timescale"
                    destination = "/var/lib/postgresql/data"
                    read_only   = false
                }
                config {
                    image = "timescaledev/promscale-extension:latest-ts2-pg13"
                    ports = ["postgres"]
                    args = [
                        "-ccheckpoint_timeout=30min",
                        "-cmin_wal_size=4GB",
                        "-cmax_wal_size=64GB",
                        "-cmax_prepared_transactions=150",
                        "-cwal_level=replica"
                    ]
                }
                service {
                    name = "timescale-data-${group.value}"
                    port = "postgres"
                }
                resources {
                    cores = 20
                    memory = 65536
                }
                env {
                    POSTGRES_HOST_AUTH_METHOD="trust"
                    TS_TUNE_MEMORY="64GB"
                    TIMESCALEDB_TELEMETRY="off"
                }
            }
        }
    }
}
```

**Comment by Liraim** [comment]
Hi, seems like I encountered same issue, and found cause of it: it is the way how `docker stats` works vs how Docker container API works. Here link to docker documentation about it https://docs.docker.com/engine/api/v1.41/#operation/ContainerStats.

In short: in `docker stats` they make additional conversation for Used memory (subtract `cached` memory).

Now you can write same formula in Prometheus as `nomad` provides all necessary fields.

Eg,`(nomad_client_allocs_memory_usage - nomad_client_allocs_memory_cache) / nomad_client_allocs_memory_allocated * 100`

**Comment by tgross** [comment]
Hi @rparelius! Sorry for the delayed response but @Liraim has the right of it. If you take a look at the [Allocation Metrics reference docs](https://www.nomadproject.io/docs/operations/metrics-reference#allocation-metrics) you'll see a few different fine-grained memory metrics:

| Metric                                        | Description                                                    |
|-----------------------------------------------|----------------------------------------------------------------|
| `nomad.client.allocs.memory.allocated`        | Amount of memory allocated by the task                         |
| `nomad.client.allocs.memory.cache`            | Amount of memory cached by the task                            |
| `nomad.client.allocs.memory.kernel_max_usage` | Maximum amount of memory ever used by the kernel for this task |
| `nomad.client.allocs.memory.kernel_usage`     | Amount of memory used by the kernel for this task              |
| `nomad.client.allocs.memory.max_usage`        | Maximum amount of memory ever used by the task                 |
| `nomad.client.allocs.memory.rss`              | Amount of RSS memory consumed by the task                      |
| `nomad.client.allocs.memory.swap`             | Amount of memory swapped by the task                           |
| `nomad.client.allocs.memory.usage`            | Total amount of memory used by the task                        |

These metrics aren't necessarily 1:1 with what Docker is doing because they're used across task drivers (and even operating systems!).

In your case your workload is Postgres/Timescale and that's going to be reading pages from disk and that'll increase the page cache usage, just as the developers of Postgres intended. I'm not particularly a Postgres guru, so I can't really tell you _exactly_ which metrics you should be monitoring, but honestly for a database most of the fields are fairly important.

I'm going to close this issue as resolved. Again, sorry for the delayed response.
