### ISSUE TITLE
Exec driver unable to find binary from volume_mount

### ISSUE THREAD

**Issue by tserkov** [hashicorp/nomad#11690]
### Nomad version
Nomad v1.2.3 (a79efc8422082c4790046c3f5ad92c542592a54f)

### Operating system and Environment details
Fedora 33 (inside Vagrant 2.2.19 with box `generic/fedora33`)

### Issue
Job fails to start when using binary within a `volume_mount`-ed binary as the command to the `exec` driver. If I change the command to `stat` the binary, allocation log output shows the successful stat output.

I'm not which debug output to enable/capture, so just tell me which diagnostics are missing and I'll provide them. 😄 

### Reproduction steps
1. Start Nomad with the configuration below (host path `/path/on/host` contains one binary named `bar`)
2. Run `nomad job run example.nomad`
3. Expect failed deployment with error below
4. Change task's command to `stat /foo/bar`, allocation logs show successful stat output describing binary (job fails since stat exits, but that's expected)

#### Expected Result
Job runs successfully using binary at `/foo/bar`.

#### Actual Result
`failed to launch command with executor: rpc error: code = Unknown desc = file /foo/bar not found under path /opt/nomad/data/alloc/3496c272-7485-1a1a-cc2d-909a44c75254/server`

### Job file (if appropriate)
nomad.hcl
```hcl
data_dir = "/opt/nomad/data"
bind_addr = "0.0.0.0"

server {
  enabled = true
  bootstrap_expect = 1
}

client {
  enabled = true
  servers = ["127.0.0.1"]

  host_volume "my-volume" {
    path = "/foo/on/host"
    read_only = true
  }
}
```

example.nomad
```nomad
job "example" {
  datacenters = ["dc1"]
  type = "service"

  group "example" {
    count = 1

    // (omitted network stanza)

    // (omitted service stanza)

    volume "my-volume" {
      type = "host"
      source = "my-volume"
      read_only = true
    }

    task "server" {
      driver = "exec"

      volume_mount {
        volume = "my-volume"
        destination = "/foo"
      }

      config {
        command = "/foo/bar"
      }
    }
  }
}
```

### Nomad Client logs (if appropriate)
When using `stat /foo/bar` instead of `/foo/bar` as exec command:
```
  File: /foo/bar
  Size: 13407477  	Blocks: 26192      IO Block: 4096   regular file
Device: 29h/41d	Inode: 99          Links: 1
Access: (0755/-rwxr-xr-x)  Uid: ( 1000/ vagrant)   Gid: ( 1000/ vagrant)
Access: 2021-12-15 20:33:54.498364018 +0000
Modify: 2021-12-15 18:40:04.327865070 +0000
Change: 2021-12-15 18:40:04.327865070 +0000
 Birth: -
```

**Comment by tgross** [comment]
Hi @tserkov you're running into a consequence of the order in which the filesystem for a task is built. If you take a look at the [filesystem docs](https://www.nomadproject.io/docs/internals/filesystem#templates-artifacts-and-dispatch-payloads) you'll see that the task gets started with the volume mount in a single step at the end. That happens in the task driver by calling out to [`libcontainer`](https://github.com/hashicorp/nomad/blob/v1.2.3/drivers/shared/executor/executor_linux.go#L100-L119). So you can't use binaries from a volume mount for the task driver.

As a workaround, you _might_ be able to get away with using `/bin/sh` as the command and have it exec into your binary, because it won't be started until after the volume is mounted. Something like:

```hcl
commands = "/bin/sh"
args = ["-c", "exec /foo/var"]
```

**Comment by tserkov** [comment]
Hey @tgross, the trick with `/bin/sh -c exec /foo/var` does work, so that's definitely a viable workaround.

This made me curious though, so I did some digging! The error comes from [`lookupTaskBin`](https://github.com/hashicorp/nomad/blob/bc2a51d43a20f4e2ba6cdc33d4eed947177417c5/drivers/shared/executor/executor_linux.go#L840-L864). Like you mentioned, `libcontainer` is the one that officially mounts the volume; however, `lookupTaskBin` resolves binaries only within NOMAD_TASK_DIR or specific paths (and rightly so), hence why `/bin/sh` works.

I believe this could be solved if `lookupTaskBin` were to also resolve paths within to-be-mounted-by-libcontainer paths. This might not be trivial, given the [immediately-following code](https://github.com/hashicorp/nomad/blob/bc2a51d43a20f4e2ba6cdc33d4eed947177417c5/drivers/shared/executor/executor_linux.go#L132-L149) that ensures the binary is executable and chrooted.

**Comment by tgross** [comment]
You're right about the `lookupTaskBin`, which is used to give us a path for checking the task sandbox. But it turns out that even if we completely bypassed that check, `libcontainer` would balk at it. I ran a patched Nomad with the following diff:

<details><summary>diff</summary>

```diff
diff --git a/drivers/shared/executor/executor_linux.go b/drivers/shared/executor/executor_linux.go
index c2788e9b9..821736372 100644
--- a/drivers/shared/executor/executor_linux.go
+++ b/drivers/shared/executor/executor_linux.go
@@ -122,33 +122,7 @@ func (l *LibcontainerExecutor) Launch(command *ExecCommand) (*ProcessState, erro
        }
        l.container = container

-       // Look up the binary path and make it executable
-       absPath, err := lookupTaskBin(command)
-
-       if err != nil {
-               return nil, err
-       }
-
-       if err := makeExecutable(absPath); err != nil {
-               return nil, err
-       }
-
-       path := absPath
-
-       // Ensure that the path is contained in the chroot, and find it relative to the container
-       rel, err := filepath.Rel(command.TaskDir, path)
-       if err != nil {
-               return nil, fmt.Errorf("failed to determine relative path base=%q target=%q: %v", command.TaskDir, path, err)
-       }
-
-       // Turn relative-to-chroot path into absolute path to avoid
-       // libcontainer trying to resolve the binary using $PATH.
-       // Do *not* use filepath.Join as it will translate ".."s returned by
-       // filepath.Rel. Prepending "/" will cause the path to be rooted in the
-       // chroot which is the desired behavior.
-       path = "/" + rel
-
-       combined := append([]string{path}, command.Args...)
+       combined := append([]string{command.Cmd}, command.Args...)
        stdout, err := command.Stdout()
        if err != nil {
                return nil, err
```

</details>

And then ran the following job on a host with the executable file `artifacts/sleeper.sh` in my host volume:

<details><summary>jobspec</summary>

```hcl
job "example" {
  datacenters = ["dc1"]

  group "sleep" {

    volume "shared" {
      type      = "host"
      source    = "shared_data"
      read_only = true
    }

    task "sleep" {

      driver = "exec"

      config {
        command = "/foo/artifacts/sleeper.sh"
      }

      volume_mount {
        volume      = "shared"
        destination = "/foo"
      }

    }
  }
}

```

</details>

That results in Nomad building the task directory for the `exec` task but then getting the following error from libcontainer, because libcontainer requires the executable be present before mounting as well:

> container_linux.go:367: starting container process caused: exec: "/foo/artifacts/sleeper.sh": stat /foo/artifacts/sleeper.sh: no such file or directory


I'm going to close this issue. Even if we could fix this in Nomad we'd just hit it again from libcontainer. But thanks for opening this issue and thanks for digging in a bit further!
