### ISSUE TITLE
[UI] ACL gives Not Authorized

### ISSUE THREAD

**Issue by cberescu** [hashicorp/nomad#11763]
### Nomad version
Nomad v1.2.3 (a79efc8422082c4790046c3f5ad92c542592a54f)

### Operating system and Environment details
Ubuntu 20.04

### Issue
So, when using a token with the following policy in the UI: 
```
namespace "default" {
  policy = "read"
  capabilities = ["read-logs"]
}
```

I receive the `Not Authorized` screen .

### Reproduction steps
Use a token with the policy described. 

From what i can see in dev tools one of the ajax request returns 4xx after witch the  `Not Authorized` screen is shown. 

#### Expected Result

View the logs screen 

#### Actual Result

Seeng the `Not Authorized` screen

**Comment by tgross** [comment]
@cberescu if you look at the browser developer tools you'll see requests for 

* `/v1/node/$node_id`
* `/v1/agent/members`
* `/v1/agent/self`

Because the UI is a much richer experience than the CLI, almost every page in the UI is going to need the following ACLs:

```hcl
node {
  policy = "read"
}

agent {
  policy = "read"
}
```

Try that change and let us know if that solves the problem.

**Comment by cberescu** [comment]
Hi,

yes, it is working now as expected. It seems i didn't think to look at what the requests were. 

Thank you for your help!!
