### ISSUE TITLE
CSI volume per_alloc availability zone placement

### ISSUE THREAD

**Issue by ygersie** [hashicorp/nomad#11778]
### Nomad version
v1.2.3

### Issue
According to the recommendation here https://github.com/hashicorp/nomad/issues/10793#issuecomment-864998759 and in the [docs](https://www.nomadproject.io/docs/job-specification/csi_plugin#recommendations-for-deploying-csi-plugins) the proper way to deal with scheduling volumes that are required to be mounted in the same AZ is to run a plugin controller per AZ. When using the [per_alloc](https://www.nomadproject.io/docs/job-specification/volume#per_alloc) volume option, this doesn't work as expected. I assume this has to do with the fact that an alloc id isn't known at time of scheduling, so Nomad tries to randomly assign an alloc to a node that can't satisfy the volume requirement, this however conflicts with the purpose of the `per_alloc` directive. It also makes me wonder if the alloc index is even supposed to be a runtime variable as it is, as far as I can tell, determined during scheduling time?

With the following volumes and job:
```sh
$ nomad volume status myvolume[0]
ID                   = myvolume[0]
Name                 = myvolume
External ID          = vol-xxxxxxxxxxxxxx
Plugin ID            = aws-ebs-us-west-2a
Provider             = ebs.csi.aws.com
Version              = v1.4.0
Schedulable          = true
Controllers Healthy  = 1
Controllers Expected = 1
Nodes Healthy        = 1
Nodes Expected       = 1
Access Mode          = <none>
Attachment Mode      = <none>
Mount Options        = <none>
Namespace            = default

Allocations
No allocations placed

$ nomad volume status myvolume[1]
ID                   = myvolume[1]
Name                 = myvolume
External ID          = vol-xxxxxxxxxxxxxx
Plugin ID            = aws-ebs-us-west-2b
Provider             = ebs.csi.aws.com
Version              = v1.4.0
Schedulable          = true
Controllers Healthy  = 1
Controllers Expected = 1
Nodes Healthy        = 1
Nodes Expected       = 1
Access Mode          = <none>
Attachment Mode      = <none>
Mount Options        = <none>
Namespace            = default

Allocations
No allocations placed
```
```hcl
job "example" {
  type = "service"

  region      = "us-west-2"
  datacenters = ["us-west-2a", "us-west-2b", "us-west-2c"]

  group "example" {
    count = 2

    volume "ebs" {
      type      = "csi"
      source    = "myvolume"
      read_only = false
      per_alloc = true

      attachment_mode = "file-system"
      access_mode     = "single-node-writer"

      mount_options {
        fs_type = "ext4"
      }
    }

    task "example" {
      driver = "docker"
      config {
        image = "alpine"
        args  = ["tail", "-f", "/dev/null"]
      }

      volume_mount {
        volume      = "ebs"
        destination = "/data"
        read_only   = false
      }

      resources {
        cpu    = 100
        memory = 64
      }
    }
  }
}
```
The result is that placement intermittently fails:
```
$ nomad plan example.hcl
+ Job: "example"
+ Task Group: "example" (2 create)
  + Task: "example" (forces create)

Scheduler dry-run:
- WARNING: Failed to place all allocations.
  Task Group "example" (failed to place 1 allocation):
    * Class "default": 1 nodes excluded by filter
    * Constraint "CSI plugin aws-ebs-us-west-2b is missing from client <clientNodeID>": 1 nodes excluded by filter

Job Modify Index: 0
To submit the job with version verification run:

nomad job run -check-index 0 example.hcl

When running the job with the check-index flag, the job will only be run if the
job modify index given matches the server-side version. If the index has
changed, another user has modified the job and the plan's results are
potentially invalid.
```

**Comment by tgross** [comment]
Hi @ygersie! Yeah unfortunately you'll probably want to namespace the volume names by AZ as well, if you're using the `per_alloc` field. Note this should all be fixed more nicely once we've implemented topology (coming soon!)

**Comment by ygersie** [comment]
Hi @tgross thanks for the quick response! Forgive my ignorance, could you elaborate a bit on what you mean with namespacing the volumes per AZ?

**Comment by tgross** [comment]
The jobspec you have crosses AZs, so the allocations are being placed based on binpacking across those AZs. So if you use `per_alloc = true` then the volume names created during scheduling will point to volumes that might not exist in those AZs, as you've seen.

So as a very hacky workaround, you can name the volumes `myvolume-2a[0]`, `myvolume-2a[1]`, etc. and then target jobs to each AZ independently. I recognize this isn't ideal, which is why we want topology so that we don't have this requirement anymore.

**Comment by ygersie** [comment]
@tgross thanks, yeah it's not pretty. In case someone runs into the same issue I came up with the following for now:
```hcl
variable "datacenters" {
  type    = list(string)
  default = ["us-west-2a", "us-west-2b", "us-west-2c"]
}

variable "instance_count" {
  type    = number
  default = 3
}

locals {
  nr_of_dcs   = length(var.datacenters)
  alloc_to_az = { for i, dc in var.datacenters : i => dc }
}

job "example" {
  type = "service"

  region      = "us-west-2"
  datacenters = var.datacenters

  dynamic "group" {
    for_each = range(var.instance_count)
    iterator = alloc
    labels   = ["example-${alloc.key}"]

    content {
      volume "ebs" {
        type = "csi"
        # creates volume source ids like:
        # us-west-2a-myvolume[0]
        # us-west-2b-myvolume[1]
        source    = "${local.alloc_to_az[alloc.key % local.nr_of_dcs]}-myvolume[${alloc.key}]"
        read_only = false

        attachment_mode = "file-system"
        access_mode     = "single-node-writer"

        mount_options {
          fs_type = "ext4"
        }
      }

      task "example" {
        driver = "docker"
        config {
          image = "alpine"
          args  = ["tail", "-f", "/dev/null"]
        }

        volume_mount {
          volume      = "ebs"
          destination = "/data"
          read_only   = false
        }

        resources {
          cpu    = 100
          memory = 64
        }
      }
    }
  }
}
```
At least this makes it easier to schedule a different number of instances in a single job.

**Comment by tgross** [comment]
Just a heads up that I'm actively working on #7669 which will resolve this issue.

**Comment by tgross** [comment]
Resolved by #12129, which will ship in Nomad 1.3.0

**Comment by ygersie** [comment]
Awesome stuff @tgross !

**Comment by tgross** [comment]
Hi @ygersie! That message bubbles up from the per-node feasibility check (ref [feasible.go#L305-L309](https://github.com/hashicorp/nomad/blob/v1.3.0/scheduler/feasible.go#L305-L309)), which looks like this:

```go
plugin, ok := n.CSINodePlugins[vol.PluginID]
if !ok {
	return false, fmt.Sprintf(FilterConstraintCSIPluginTemplate, vol.PluginID, n.ID)
}
```

The reason you're seeing different behaviors on different runs is most likely because the scheduler shuffles the list of nodes. For each allocation the list is feasibility checked (filtered) and scored until we either have at least 1 (and a maximum of 2) viable node scores or we run out of nodes.

So suppose we have (nodeA, nodeB, nodeC, nodeD) one for each DC. Our example[0] has a volume[0] in zone A, and example[1] has a volume[1] in zone B. One possible iteration through the scheduler might look like this:

* example[0]:
  * nodeD is feasible? no
  * nodeB is feasible? no
  * nodeA is feasible? yes, score it.
  * nodeC is feasible? no
  * no more nodes
  * take node with max score (out of first 2 scored, but we scored only 1)
  * planned for nodeA
* example[1]:
  * nodeD is feasible? no
  * allocB: nodeB is feasible? yes, score it.
  * allocB: nodeA is feasible? no
  * allocB: nodeC is feasible? no
  * no more nodes
  * take node with max score (out of first 2 scored, but we scored only 1)
  * planned for nodeB

The failure you're getting suggests that one of the zones doesn't have a plugin (much less a healthy one). So when you say:

> I'm still using the plugin_id with the AZ in there as this is how we currently have our plugins deployed. I wouldn't expect this to be related to the issue I'm seeing here.

I think this may be unexpectedly be a factor still. If it were topology-related I'd expect to see "did not meet topology requirement" (ref [`feasible.go#L317-L323`](https://github.com/hashicorp/nomad/blob/v1.3.0/scheduler/feasible.go#L317-L323)).

I'll re-open this issue while we debug this. Some questions on your test environment that might help narrow down the behavior:

* Can you verify that the volumes were created in the correct AWS AZ as their topology says?
* Do you have more than one node in each DC with the running plugins?
* Do any nodes in the DC _not_ have a plugin?
* Which DC is 17224e99-393e-16d2-aa0a-329ff47ca63b in? It would be interesting to see whether that was a DC with a different plugin or a DC without a plugin at all.

**Comment by ygersie** [comment]
It seems this issue even occurs *with* the manual AZ mapping of source volumes, this worked at least before the 1.3.0 upgrade. I have a job that is failing to be scheduled with the same constraint issue. The job has 3 taskgroups each with a volume claim looking like:
```json
                "Volumes": {
                    "data": {
                        "AccessMode": "single-node-writer",
                        "AttachmentMode": "file-system",
                        "MountOptions": {
                            "FSType": "ext4",
                            "MountFlags": null
                        },
                        "Name": "data",
                        "PerAlloc": false,
                        "ReadOnly": false,
                        "Source": "us-west-2c-redis[2]",
                        "Type": "csi"
                    }
                }
```
the volume status:
```sh
$ nomad volume status us-west-2c-redis[2]
ID                   = us-west-2c-redis[2]
Name                 = redis[2]
External ID          = vol-asdfasdfasdfasdf
Plugin ID            = aws-ebs-us-west-2c
Provider             = ebs.csi.aws.com
Version              = v1.4.0
Schedulable          = true
Controllers Healthy  = 2
Controllers Expected = 2
Nodes Healthy        = 3
Nodes Expected       = 3
Access Mode          = single-node-writer
Attachment Mode      = file-system
Mount Options        = fs_type: ext4
Namespace            = mynamespace

Allocations
No allocations placed
```
And the job status:
```sh
Placement Failure
Task Group "redis-0":
  * Class "default": 1 nodes excluded by filter
  * Constraint "CSI plugin aws-ebs-us-west-2a is missing from client f13406f2-1cb1-008b-ebf5-74c27f418a46": 1 nodes excluded by filter

Task Group "redis-1":
  * Class "default": 1 nodes excluded by filter
  * Constraint "CSI plugin aws-ebs-us-west-2b is missing from client f562d820-a589-6c02-807a-d653ebfb7b14": 1 nodes excluded by filter

Task Group "redis-2":
  * Class "default": 1 nodes excluded by filter
  * Constraint "CSI plugin aws-ebs-us-west-2c is missing from client 17224e99-393e-16d2-aa0a-329ff47ca63b": 1 nodes excluded by filter
```
The node ids are indeed in completely different datacenters, so they are rightfully missing the plugin.

**Comment by tgross** [comment]
Ok, I haven't had a chance to come back to write that test. But:

> I'm not sure why the plugins report "No allocations placed",

Just FYI on this the `nomad plugin status` command has to hit the Allocations API in order to get the list of allocations. But because plugins don't have a namespace but the plugin _jobs_ do, the Allocations API will respond with an empty list if the plugins aren't in the default namespace if you don't provide a namespace to `nomad plugin status`.

**Comment by ygersie** [comment]
I'm now also seeing this every now and then:
```sh
Placement Failure
Task Group "example":
  * Class "default": 1 nodes excluded by filter
  * Constraint "did not meet topology requirement": 1 nodes excluded by filter
```
There really seems to be a problem with selecting feasible nodes.

**Comment by tgross** [comment]
I've just opened a PR in https://github.com/hashicorp/nomad/pull/13274 which should ship in Nomad 1.3.2 with backports to Nomad 1.2.x and Nomad 1.1.x.
