### ISSUE TITLE
CSI: per_alloc volumes have wrong link in alloc task table

### ISSUE THREAD

**Issue by tgross** [hashicorp/nomad#11965]
In https://github.com/hashicorp/nomad/pull/11896 we moved the link target for CSI volumes on the allocation detail page to use the `source` field as the target for the URL. But for volumes with `per_alloc = true`, this doesn't work because the source does not include the allocation index:

```
$ curl -s "http://localhost:4646/v1/allocation/$alloc_id" |  jq '.Job.TaskGroups[0].Volumes'
{
  "csi_data": {
    "Name": "csi_data",
    "Type": "csi",
    "Source": "webdata",
    "ReadOnly": false,
    "AccessMode": "single-node-writer",
    "AttachmentMode": "file-system",
    "MountOptions": null,
    "PerAlloc": true
  }
}
```

For example, this link should be to `webdata[0]` because it's the 0th alloc:

<img width="1261" alt="Screen Shot 2022-01-31 at 2 21 00 PM" src="https://user-images.githubusercontent.com/1409219/151860490-fe77aadc-7e25-4bad-a657-cdb264b7f9e0.png">

Because this data is written to the job and not to the individual allocations in the state store, we'd have to modify the state on the fly to make it the "correct" value in the API, but that would make the job definition in this API vary depending on which allocation we look at. So we should have this bit of logic in the UI add the allocation index, just as we do in the client when we consume this value.

Note that we haven't yet shipped this bug in a release, so it'd be nice for us to get to as part of the 1.3.0 work. I can probably take this one on while doing other CSI cleanup.

**Comment by philrenaud** [comment]
Did some digging with @ChaiWithJai

- The volumeMount object within a taskgroup lacks the volume.name property that would give us something like volume0[0] vs volume0[1];
- the volume object has that name property, but does not come back with `job.taskgroups[].tasks[].volumeMounts`, nor with `job.taskgroups[].volumes`

there are two ways we could solve this:
- Make an explicit ember store.findAll('volumes')... and query by the task's volume ID 
- Modify the API response for job.taskgroups[] and job.taskgroups[].tasks[] to return volume.name

Because of how many places we'd have to make that store request in the former option, I'm going to advocate for the latter. I'll have a look at the response schema shortly.

**Comment by tgross** [comment]
> Modify the API response for job.taskgroups[] and job.taskgroups[].tasks[] to return volume.name

The problem here is that the API doesn't know the volume name, as the volume request is part of a task group and not an allocation. Including the name would imply that the output of `nomad job status` changes depending on which allocation you're looking at, but it doesn't look at allocations at all.
