### ISSUE TITLE
The UI incorrenctly includes dead tasks' memory in the `Task Group`'s view, under the `Reserved Memory` column

### ISSUE THREAD

**Issue by jfragoulis** [hashicorp/nomad#11978]
### Nomad version

1.1.3

### Operating system and Environment details

Debian Bullseye
Nomad installed through debian package.

### Issue

The UI incorrenctly includes dead tasks' memory in the `Task Group`'s view, under the `Reserved Memory` column.

### Reproduction steps

A service job with a prestart task and a normal task should display something like the following:

![image](https://user-images.githubusercontent.com/1748736/152157072-ef5006bc-74fe-4f0e-8515-d666ba585c35.png)

Diving into the `redis` allocation as an example:

![image](https://user-images.githubusercontent.com/1748736/152157296-1c597083-bc5c-4a96-bc6e-cb3555855bdc.png)

The prestart task has a default memory (300MB) while the redis task has 20MB.

![image](https://user-images.githubusercontent.com/1748736/152157688-57d84526-dfd5-4c56-a9f4-1db7bf9c3fc9.png)

(images are from our live production cluster)

#### Expected Result

I would expect that the `Reserved Memory` column to display the actual memory reserved at the time and not the memory as defined in the job spec.

#### Actual Result

The UI does not take account which tasks are dead when displaying the allocation's reserved memory.

**Comment by lgfa29** [comment]
Hi @jfragoulis 👋 

This is actually the right value for `Reserved Memory`. It doesn't represent what is being currently used, but how much memory it is required in a client in order to schedule an allocation for that task group.

Even though the `prestart` and `main` tasks may not be running at the same time, Nomad still uses the sum when computing allocation placements to guarantee the alloc would still fit even in the case the `prestart` needs to run again: the entire memory block is reserved for the allocation.

Does that make sense? 😄

**Comment by jfragoulis** [comment]
First of all, thank you for the quick reply.

So, it is not actually wrong, the memory is **indeed** reserved, even for dead tasks, in case the allocation needs to restart which would mean that the `prestart` task will run again and the scheduler needs to account for that.

Ok I guess I get it now.

**Comment by lgfa29** [comment]
Yup, so that will show the "size" of the allocation as seen by the **scheduler**. The `Topology` view may help you visualize this idea:

<img width="1391" alt="image" src="https://user-images.githubusercontent.com/775380/152433768-6d988fac-c4e8-4dd0-8bbe-05185a8d47c6.png">

Here's the job I used:

```hcl
job "example" {
  datacenters = ["dc1"]


  group "cache" {
    task "prestart" {
      driver = "raw_exec"

      lifecycle {
        hook    = "prestart"
        sidecar = false
      }

      config {
        command = "/bin/bash"
        args    = ["-c", "echo hi"]
      }

      resources {
        memory = 1000
      }
    }

    task "redis" {
      driver = "docker"

      config {
        image = "redis:3.2"
      }

      resources {
        memory = 30
      }
    }
  }
}
```

I'm going to close this issue for now, but feel free to let us know if you still have any question.
