### ISSUE TITLE
Sidecar Restart interval different than main task 

### ISSUE THREAD

**Issue by jhitt25** [hashicorp/nomad#12250]
### Nomad version
Nomad v1.2.6 (a6c6b475db5073e33885377b4a5c733e1161020c)

### Issue
When a connect-enabled job fails a healthcheck i would expect the automatically created sidecar to restart at the same time as the task itself.  We just had a small server issue and tasks on the server all started failing their healthchecks and restarting.  While watching, we noticed multiple apps not starting up properly.  Upon inspection, it was because the task itself hit it's restart delay and attempted to restart, but the sidecar was still waiting out a separate restart delay.  As a result, the application wasn't able to talk to upstreams and failed to start, triggering a constant cycle of delay/restart/delay/restart.  I've attached screenshots of 2 separate jobs, one with only a connect sidecar and another with a filebeat secondary task in the same group to ship logs for an older application.

![Capture](https://user-images.githubusercontent.com/11196566/157502498-b174aaec-92ef-4874-8ab1-192b6d43e8d3.png)
![Capture2](https://user-images.githubusercontent.com/11196566/157503108-c5408253-2f84-4f27-a715-92c6023661f5.PNG)

### Reproduction steps
I don't know how to reproduce this, and it may be more of a misunderstanding about how Nomad operates.  I'm open to suggestions as to reproducability.

#### Expected Result
I would expect a sidecar service and all tasks in a group to restart at the same time.

#### Actual Result
The sidecar and separate tasks in the same group were restarting at drastically different intervals.

### Job file (if appropriate)
As above, I'm not sure if a job file is appropriate here or not since im not sure how to forcibly reproduce this situation.

**Comment by tgross** [comment]
Hi @jhitt25!

> I would expect a sidecar service and all tasks in a group to restart at the same time.

The case where you have 2 tasks in the same group (the main task, filebeat, plus the Connect sidecar) really shows where this is a bit tricky. If we restart the Connect sidecar task when any task in the allocation restarts, we could easily get into the same situation where the sidecar is delayed.

For example:
* the main task exits
* we delay up to the main task's `restart.delay` before restarting the main task
* at that point we also restart the Connect sidecar
* and then by bad luck the filebeat task exits

At this point we'd be potentially violating the `restart.delay` if we immediately restarted the Connect sidecar again.

I suspect that we probably want to rework how the Connect sidecars restart so that they don't have their own `restart` controls apart from the tasks that they connect. I think I'm going to ping my colleague @shoenig here as he has deeper understanding of the Connect sidecar setup than I do.

In the meantime, if you have a (redacted) jobspec you can share -- particularly with respect to the `connect` and `restart` blocks -- that might help us figure out if there's anything unique to your environment that's involved here.

**Comment by jhitt25** [comment]
Here's a simplified/redacted version of the job with filebeat involved.
[redacted_job.txt](https://github.com/hashicorp/nomad/files/8227312/redacted_job.txt)

**Comment by tgross** [comment]
Thanks @jhitt25, that was very helpful in tracking this down!

I had a conversation with some of my colleagues and where we arrived is that things are working as intended but the behavior isn't very clear and the docs need improving.

The [`restart`](https://www.nomadproject.io/docs/job-specification/restart) docs say:

> If specified at the group level, the configuration is inherited by all tasks in the group.

That is, a `restart` block at the `group` level doesn't set a restart policy on the group, but an individual restart policy on each task within the group. That includes the sidecar task! We can see that with the following jobspec:

<details><summary>jobspec</summary>

```hcl
job "myjob" {
  datacenters = ["dc1"]

  group "mygroup" {

    restart {
      attempts = 5
      delay    = "21s"
      interval = "15m"
      mode     = "delay"
    }

    network { mode = "bridge" }

    service {
      name = "myjob"
      port = 8080
      connect {
        sidecar_service {}
        sidecar_task {
          resources {
            cpu    = 20
            memory = 64
          }
        }
      }
    }

    task "mytask" {
      driver = "docker"

      config {
        image   = "busybox:1"
        command = "httpd"
        args    = ["-v", "-f", "-p", "8080", "-h", "/var/www"]
      }

      resources {
        memory = 512
        cpu    = 200
      }
    }

  }
}
```

</details>

If I run that and then inspect the resulting tasks, they have the same (non-default) restart policy:


```
$ nomad job inspect myjob | jq '.Job.TaskGroups[0].Tasks[0].RestartPolicy'
{
  "Attempts": 5,
  "Delay": 21000000000,
  "Interval": 900000000000,
  "Mode": "delay"
}
$ nomad job inspect myjob | jq '.Job.TaskGroups[0].Tasks[1].RestartPolicy'
{
  "Attempts": 5,
  "Delay": 21000000000,
  "Interval": 900000000000,
  "Mode": "delay"
}
```

So what's happening here is that the Connect sidecar is taking on the behavior of the parent task. Although you've got a short `delay` set, you can end up with very long restart delays because you're using `mode = "delay"` instead of `mode = "fail"`. And with very long restarts, it's easy to get everyone out of sync with the sidecar.

If you really want to use `mode = "delay"` for your main task, what I'd recommend is that you set that at the task level and then set a tighter restart with `mode = "fail"` on the two extra tasks. With the partial jobspec below you'll have the same `restart` for the main task, but for both Connect and filebeat you'll have a quick set of attempts to recover over the course of a minute or so before failing the whole allocation so it can be rescheduled:

```hcl
job "myjob" {

  group "main" {

    service {
      connect {
        sidecar_service {}
        sidecar_task {
          restart {
            attempts = 5
            delay    = "10s"
            interval = "5m"
            mode     = "fail"
          }
        }
      }
    }

    task "myjob" {
      restart {
        attempts = 3
        delay    = "15s"
        interval = "15m"
        mode     = "delay"
      }
    }

    task "filebeat" {
      restart {
        attempts = 5
        delay    = "10s"
        interval = "5m"
        mode     = "fail"
      }
    }

  }
}
```

I'm working up a docs PR to cover this scenario and also #12017 and will have that up later this afternoon.

**Comment by tgross** [comment]
Sorry, follow up on this @jhitt25. I spoke too soon and it turns out that `restart` isn't permitted on the `sidecar_task`. That results in a validation error like the following:

```
$ nomad job run ./jobs/sidecar-restart.nomad
Error getting job struct: Error parsing job file from ./jobs/sidecar-restart.nomad:
sidecar-restart.nomad:22,11-18: Unsupported block type; Blocks of type "restart" are not expected here.
```

That seems like a miss to me and I'll look into what we can do about it.

**Comment by jhitt25** [comment]
Perfect.  I think a bit of this was an oversight on my part.  After re-reading the restart documentation i also notice that i misunderstood 'mode=fail' to be a permanent stopping of the job.  I was using 'mode=delay' specifically to have failing jobs attempt to restart after a period of time, which appears to be what 'reschedule' is for.  In my simplistic view of the tool i completely ignored 'reschedule'.

The documentation clarification will definitely help, but so will me using the tool properly!
