### ISSUE TITLE
Getting not more then ~25 containers in Vagrant using Centos/7 box '[question]'

### ISSUE THREAD

**Issue by Karen09** [hashicorp/nomad#1230]
Hi 
last time i was busy with nomad and consul configuration and i have found some interesting vagrant nomad implementation , following this guys i get in Ubuntu 14.04 Vagrant box maximum 25 containers at each host . i did it with puppet nomad module in centos 7 and getting max 18 containers at each host . Maybe someone has experience  with this issue ?

Vagrant repo: https://github.com/dontrebootme/nomad-intro
Puppet Nomad: https://github.com/dudemcbacon/puppet-nomad

it would be greate if someone can share his expariance . Most probably I am thinking about some maxprocess limitation somewhere.

Regards 
Karen

**Comment by diptanu** [comment]
@Karen09 This is probably because Nomad can only fit 25 containers based on the resources requested by your job. You can see the available resources on a node by running the command `nomad node-status <node-id>` and once you run your job, the same command will also show you the allocations running on the node and amount of resources they are using.

Hope this helps. I am going to close this issue, we prefer to answer questions on the mailing list and use GitHub issues normally for bug.

**Comment by Karen09** [comment]
@diptanu Thank you for your answer ! exactly it was CPU limitation and all my test done with 1 Vcpu thats why its stops with 25 container , now With 2 Vcpus  i can reach 56 and more .
Ragards 
Karen
