### ISSUE TITLE
[question] why consul service registration will be done on client nodes?

### ISSUE THREAD

**Issue by rmmjohann** [hashicorp/nomad#1233]
When submitting an job the nomad server will be aware of the node and its ip/port where the submitted job is running. My first intention was that the server handles service registration, but that's only the case when submitting system jobs.
Why was that way chosen?
Is there any plan on configuring who registers services at consul?

At the moment I'm trying to run a job on a node where nomad client and consul client are installed. The consul client is only allowed to read service definitions, but not register them. If the nomad client config contains the consul ACL token for registering services, everyone can register services within the constraints defined at the role.

So it will be useful to either define a consul ACL at the nomad job (https://github.com/hashicorp/nomad/issues/590) or to define who is responsible for registering the jobs services

**Comment by diptanu** [comment]
We decided to do the registrations on the client so that we scale the registration/de-registrations of services across the cluster and it is the client who knows precisely when a task has started or it has failed so doing this on the client made more sense.

However, we acknowledge that currently it's possible for all jobs to register services with Consul which is not ideal. We are still thinking what's the best way to add ACLs to address this, and it should come in the next few releases. 

Closing this issue, but happy to answer any other questions. Also, we prefer using the mailing list for questions.
