### ISSUE TITLE
Node Memory Resource Randomly Went Down 1 MB

### ISSUE THREAD

**Issue by herter4171** [hashicorp/nomad#12397]
### Nomad version
Nomad v1.2.5 (06d912a20ba029c7f4d6b371cd07594cba3ae3cd)

### Operating system and Environment details
Amazon Linux 2

### Issue
When we boot up our head nodes, a job is launched to get node resource values for a given instance type.  For example, our `c5n.9xlarge` nodes used to have 94,532 MB RAM, then they suddenly started having 94,531 MB with no change in tooling.  This led to jobs not being placed ever.  I didn't adequately plan for an edge case of users exceeding node resources, so this ran up our cost.

### Reproduction steps
I don't know.  It just randomly changed while our tooling remained constant.

#### Expected Result
The node RAM would be the same as when we profiled it at head node boot.

#### Actual Result
The node RAM is 1 MB less than the original value.

**Comment by tgross** [comment]
@herter4171 I did a little more digging on this and it looks like the kernel is the most likely culprit to be taking over that extra bit of RAM (from `vmalloc` or kernel modules). If you're trying to run that tightly on RAM, you'll probably want to have some monitoring in place over the `/proc/meminfo` so that you can dial that in to a safe value. We generally recommend that folks set `client.reserved` though as I mentioned above.

**Comment by tgross** [comment]
I think this question has been answered as best we can without more information. Going to close it out. Please feel free to re-open if you have more info @herter4171!
