### ISSUE TITLE
Vault token renewals race with task shutdown

### ISSUE THREAD

**Issue by tgross** [hashicorp/nomad#12465]
@cullenmcdermott reported spurious Vault client errors when a batch job that required Vault had exited.

Searching through their logs, we find the following series of events. Note: these log messages are reconstructed from structured log outputs, so they may not match standard Nomad stdout logging you'd find in the journal:

> T40:58.352672Z  [client.alloc_runner.task_runner] not restarting task alloc_id=cb3d5b0f-3a08-23f0-a8bc-46590e2e5af4
> T40:58.631671Z [client.driver_mgr.docker] stopped container
> T40:58.650978Z [client.alloc_runner] killing task alloc_id=cb3d5b0f-3a08-23f0-a8bc-46590e2e5af4
> T40:58.651019Z [client.gc] marking allocation for GC alloc_id=cb3d5b0f-3a08-23f0-a8bc-46590e2e5af4
> T40:58.785934Z [client.vault] error during renewal of lease or token failed due to a non-fatal error; retrying

That last log line came with the following multi-line log:

```
failed to renew the vault token: Error making API request.

URL: PUT https://active.vault.service.consul:8200/v1/auth/token/renew-self
Code: 400. Errors:

* invalid lease ID
```

And then finally:

> T41:13.787658Z [client.vault] error renewing token

```
failed to renew the vault token: Error making API request.

URL: PUT https://active.vault.service.consul:8200/v1/auth/token/renew-self
Code: 403. Errors:

* permission denied
```

The final set of errors are coming from [`vaultclient.go#L360-L363`](https://github.com/hashicorp/nomad/blob/v1.2.6/client/vaultclient/vaultclient.go#L360-L363) which gets called from [`vault_hook.go#L229`](https://github.com/hashicorp/nomad/blob/v1.2.6/client/allocrunner/taskrunner/vault_hook.go#L229) in the task runner. At a quick glance it looks like the renew step does not include the task runner's context, so we don't have a way to interrupt that operation. The fix will probably need to be threading the task runner context into the vault client renewal somehow.

cc @lgfa29 and @mikenomitch as a heads up for this internally-reported issue that we should probably get onto the near-term backlog.

**Comment by tgross** [comment]
Cross-linking to https://github.com/hashicorp/nomad/issues/12261 because although it's not the same error message or symptoms, they smell potentially related.

**Comment by mikenomitch** [comment]
FYI, @cullenmcdermott has some more information on this in case any Nomad team members want talk thru this. @mikenomitch has a video repro/discussion handy as well.

**Comment by tgross** [comment]
@DerekStrickland I've reopened https://github.com/hashicorp/nomad/issues/12261 based on feedback from the user that the problem isn't fixed in their 1.3.5 build, but I see you've got #13279 open still. I'll point them that way but wanted to give you a heads up.

**Comment by DerekStrickland** [comment]
@tgross  Thanks for the heads up. Sorry for the delay.  The testing we're doing is not complete, but is actively ongoing.

**Comment by lgfa29** [comment]
Thinking through this a little more as I work on the Vault integration improvements, I think the race comes from the fact that we renew and clear the heap in concurrent processes.

Imagine this sequence of steps:

1. Token is in the Vault client heap waiting for renewal.
2. Token is retrieved from the heap for a future renewal. `vaultClient` blocks until the renewal time.
https://github.com/hashicorp/nomad/blob/f5b0da1d551daacc400126b330d2f6e0ca6befff/client/vaultclient/vaultclient.go#L472-L496
3. Alloc is killed.
4. `vaultHook.Stop` is executed, cancelling the `run` loop.
https://github.com/hashicorp/nomad/blob/f5b0da1d551daacc400126b330d2f6e0ca6befff/client/allocrunner/taskrunner/vault_hook.go#L175-L179
5. The `run` loop unblocks and calls `stopRenewal()`
https://github.com/hashicorp/nomad/blob/f5b0da1d551daacc400126b330d2f6e0ca6befff/client/allocrunner/taskrunner/vault_hook.go#L305-L308
6. `stopRenewal()` then calls the `vaultClient` to stop the renewal process.
https://github.com/hashicorp/nomad/blob/f5b0da1d551daacc400126b330d2f6e0ca6befff/client/allocrunner/taskrunner/vault_hook.go#L190-L195
7. Stopping the renewal loop consists of removing the token from the heap.
https://github.com/hashicorp/nomad/blob/f5b0da1d551daacc400126b330d2f6e0ca6befff/client/vaultclient/vaultclient.go#L510-L528
8. The blocked goroutine from step 2 unblocks and calls `vaultClient.renew()`, resulting in the first set of errors.
https://github.com/hashicorp/nomad/blob/f5b0da1d551daacc400126b330d2f6e0ca6befff/client/vaultclient/vaultclient.go#L361-L362
9. This is not considered a fatal error and, since step 7 removed the token from the heap, the token is added to the heap once again.
https://github.com/hashicorp/nomad/blob/f5b0da1d551daacc400126b330d2f6e0ca6befff/client/vaultclient/vaultclient.go#L430-L448
10. Being in the heap will cause renewal attempts until the last `permission denied` happens, which _is_ considered a fatal error.
https://github.com/hashicorp/nomad/blob/f5b0da1d551daacc400126b330d2f6e0ca6befff/client/vaultclient/vaultclient.go#L392-L397

So I think `vaultClient` will need some kind of renewal cancellation cache, being absent from the heap is not enough to detect that a renewal should _not_ happen. 

When the `vaultHook` cancels the renewal process it will be removed from the heap, but also tracked in the cache. `vaultClient.renew()` can then check the cache to decide if it should actually renew the token or not.
