### ISSUE TITLE
Nomad should have a method to detach joined clusters

### ISSUE THREAD

**Issue by robothor** [hashicorp/nomad#1270]
At the Nomad workshop during Hashiconf EU, all the participants joined their trial clusters together using `nomad server-join`.  There is no way, however, to unjoin these clusters short of destroying and recreating each one individually.

This probably won't be a common usage, but infrastructure patterns change and there may be business reasons why two clusters should be separated.

**Comment by mikesimons** [comment]
We had two consul clusters accidentally merge and various bits of config and latent data kept mashing them together on occasion (despite manual separation). retry_join did not get updated in one case, rejoin_after_leave tried to join all the nodes it *ever* knew about instead of just the ones that were active at time of last shutdown, a node was missed in raft cleanup separating clusters etc.

We fixed it for good by setting a different consul gossip encryption key per cluster. Perhaps if nomad adds support for gossip encryption it could be used to the same effect? Admittedly this may cause a blip in uptime as a new key is deployed to all servers but the gossip stuff is really quite effective (too effective?!) at healing so unless this is implemented as some kind of cluster-wide purge you might find these things joining themselves together again.

**Comment by dadgar** [comment]
Hey this won't be a feature we will be introducing.
