### ISSUE TITLE
UI: general keyboard navigation

### ISSUE THREAD

**Issue by philrenaud** [hashicorp/nomad#12762]
It would be nice to use keyboard commands to navigate the Nomad UI.

I'd like to move between nav/subnav sections with arrow key modifiers, or vim-like go-to keys.

## Launch Blockers
- [x] Shift-key vimium-style "hint" highlighting
- [x] #13046
- [x] #13777
- [x] Extend Custom Modifier to to allow hints on pre-loaded items (main menu)
- [x] #13890
- [x] Shortcuts modal: add dismiss button; trap focus
- [x] #13477
- [x] #13753
- [x] Fix shiftFriendlyBuffer to allow up/down arrow keys to work (currently auto-trigger shift commands)
- [x] Bugfix: "u" to go up a level in jobs has an extra stage

## Later:
- [ ] #13478
- [ ] #13495
- [ ] Handle table sorting for enumerable keyboard nav items
- [ ] Add `Shift + ->` etc. hint to subnav and nav

**Comment by mikenomitch** [comment]
Some random/incomplete feedback after playing with the vercel link:
* Do we want to show the key strokes in the middle of the screen? Maybe we could turn that on with some mode? (Maybe this was the plan all along?) - FWIW, I'm not a big fan.
* Esc causes "Hide Keyboard Shortcuts" to show regardless of whether or not its open
* If we do show: think showing arrow up/down, and tab, and maybe escape/meta or some others that one would normally get hit in standard keyboard use is probably not great. Maybe we hide these?

* What I really want is some easy way to select the Nth element from a index page (i.e. Jobs list). I keep hitting "j" to try to jump to the first element of the index (assuming j/k move me up and down the table). Gmail & Fastmail and some other webapps use j/k to do that, and then "o" to open the selected element. IMO that's probably more the expected behavior than switching tabs with j/k. (Maybe shift+j and shift+k and the shift+arrow commands could do the tab switching?)
* When I do use j/k to tab switch it usually only works once. If I re-click onto the page then re-hit the key, it'll work again. I am on firefox fwiw, so maybe it behaves differently on chrome.

**Comment by philrenaud** [comment]
> Do we want to show the key strokes in the middle of the screen? Maybe we could turn that on with some mode? (Maybe this was the plan all along?) - FWIW, I'm not a big fan.

Intent is to never show these; all the associated styles currently in #12831 are for demo purposes only.

> What I really want is some easy way to select the Nth element from a index page (i.e. Jobs list). I keep hitting "j" to try to jump to the first element of the index (assuming j/k move me up and down the table). Gmail & Fastmail and some other webapps use j/k to do that, and then "o" to open the selected element. IMO that's probably more the expected behavior than switching tabs with j/k. (Maybe shift+j and shift+k and the shift+arrow commands could do the tab switching?)

I like this as a concept a lot. I think what I might do is remove `j` and `k` from subnav/nav traversal, and reserve them for in-page stuff like you mention.

VimCal and a few other info-dense tools do this thing where you hold a key (would probably shift in our case) that annotates all items on your page with its corresponding shortcut. That would probably be the thing that gets us closest number-key-bound list-item opening. Future work I think!

**Comment by mikenomitch** [comment]
@philrenaud oh also another idea in the same vein as j/k/o, hitting "u" to traverse up a breadcrumb. Idea taken from Gmail.

**Comment by philrenaud** [comment]
Tackled in https://github.com/hashicorp/nomad/pull/14138 and https://github.com/hashicorp/nomad/pull/14165 — marking complete!
