### ISSUE TITLE
Secure Variables /new and /edit: make eye toggles only toggle on/off for their respective row

### ISSUE THREAD

**Issue by philrenaud** [hashicorp/nomad#13390]
![image](https://user-images.githubusercontent.com/713991/174083833-1d243725-0262-4ce1-8b33-dea8faa255a2.png)

Currently they toggle all rows; make them individually toggle-able.

**Comment by ChaiWithJai** [comment]
This one seems super straight forward. @philrenaud do you think these specifications cover the job?

- Given a user is in editing mode in the secure variables form and in default password mode when they click the eye-off icon button, the input field will show text instead of asterisks and the svg icon will display .
- Given a user is in editing mode in the secure variables form and not in default password mode when they click the eye-on toggle button, the input field will show asterisks instead of text.
- Given a user is in editing mode in the secure variables form, when they arrive on the page then all existing passwords will default to being obscured text.
- Given a user is in editing mode, when they click "Add More" the unsaved value that is currently being created will show text by default.
