### ISSUE TITLE
allow multiple service tags to be used together

### ISSUE THREAD

**Issue by maxadamo** [hashicorp/nomad#13604]
### Proposal

According to the following links:
https://docs.ldap.com/ldap-sdk/docs/javadoc/index.html?com/unboundid/ldap/sdk/DNSSRVRecordServerSet.html
https://ldap.com/dns-srv-records-for-ldap/

a DNS SRV record for LDAP should contain 2 tags at the same time `_ldap._tcp` (or `_ldaps._tcp`)

service tag in Nomad is a list and it tried to define: 
`["ldap", "tcp"]`

but I get an unexpected result. The name can be resolved either as: 
```
_host._tcp.example.com
_host._ldap.example.com
```
but it cannot be resolved as:
```
_host._ldap._tcp.example.com
```

Furthermore, the above documentation says that in order to get a list of DNS records for a domain, the tag should be prepended. For instance:
```
_ldap._tcp.example.com
```

### Use-cases

use proper LDAP SRV record (with escapes as follows):
```
ldap:///dc%3Dexample%2Cdc%3Dcom
```

### Attempted Solutions

could you make the multiple tags work together, and maybe even one at once? 
For instance, we can resolve these all:

```
_host._tcp.example.com
_host._ldap.example.com
_host._ldap._tcp.example.com
```

p.s.: maybe the prepending "_" is enough and we don't need to prepend the tags. I don't have it clear yet.

**Comment by tgross** [comment]
Hi @maxadamo! Nomad's service tags are passed directly to Consul via their API, so those DNS SRV records you're getting are whatever Consul is doing with the [`Tags` field](https://www.consul.io/api-docs/agent/service#tags). I'm going to move this issue over to the Consul repo so that folks on that team can address this request with more expertise.

(The [Nomad provider](https://www.nomadproject.io/docs/job-specification/service#provider) for `services` doesn't yet have any support for DNS yet, but we'll keep an eye on what Consul decided to do for sure.)

**Comment by tgross** [comment]
I apparently can't transfer issues over there for some reason, so I've opened https://github.com/hashicorp/consul/issues/13674 on your behalf. I'm going to close this issue out and I'll suggest you head over there. Thanks!
