### ISSUE TITLE
ceph csi volume not populating via nomad api but it work via hcl file.

### ISSUE THREAD

**Issue by thatsk** [hashicorp/nomad#13842]
### Nomad version
Nomad v1.3.2 (bf602974112964e9691729f3f0716ff2bcdb3b44)

### Operating system and Environment details
centos7

### Issue
Nomad volume not generating block image in ceph ui via nomad HTTP API

### Reproduction steps
create test volume.hcl
```
id = "test-data"
name = "test-data"
type = "csi"
plugin_id = "ceph-csi"
capability {
  access_mode     = "single-node-writer"
  attachment_mode = "file-system"
}
mount_options {
  fs_type = "ext4"
}
secrets {
  userID  = "admin"
  userKey = "AQCZdNFiGm82JBAAnVI1js9MOUtd/ovDOcXeyA=="
}
parameters {
  clusterID = "11c21580-0430-11ed-b181-0050568ee646"
  pool = "test"
  imageFeatures = "layering"
}
```

**nomad volume create volume.hcl**

It should work as expected.
but when I try to do it via API it failed to mount and not able to view in ceph ui
```
{
	"Volumes": [{
		"Context": {
			"imageFeatures": "layering",
			"pool": "test",
			"journalPool": "test",
			"clusterID": "11c21580-0430-11ed-b181-0050568ee646"
		},
		"ID": "test-data",
		"MountOptions": {
			"FSType": "ext4"
		},
		"Name": "test-data",
		"Namespace": "default",
		"Parameters": {
			"pool": "test",
			"clusterID": "11c21580-0430-11ed-b181-0050568ee646",
			"imageFeatures": "layering"
		},
		"Secrets": {
			"userID": "admin,
			"userKey": "AQCZdNFiGm82JBAAnVI1js9MOUtd/ovDOcXeyA=="
		},
		"PluginID": "ceph-csi",
		"Provider": "rbd.csi.ceph.com",
		"ProviderVersion": "v3.3.1",
		"RequestedCapabilities": [{
			"AttachmentMode": "file-system",
			"AccessMode": "single-node-writer"
		}]
	}]
}
```

```
**curl -v --request PUT --data @test-volume.json http://nomadmaster:4646/v1/volume/csi/test-data**

* About to connect() to nomadmaster port 4646 (#0)
*   Trying nomadmaster...
* Connected to nomadmaster. (nomadmaster.) port 4646 (#0)
> PUT /v1/volume/csi/test-data HTTP/1.1
> User-Agent: curl/7.29.0
> Host: nomadmaster.:4646
> Accept: */*
> Content-Length: 895
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 895 out of 895 bytes
< HTTP/1.1 200 OK
< Vary: Accept-Encoding
< X-Nomad-Index: 36810
< X-Nomad-Knownleader: true
< X-Nomad-Lastcontact: 0
< Date: Tue, 19 Jul 2022 14:03:19 GMT
< Content-Length: 0
< 
* Connection #0 to host 10.174.206.17 left intact
```

#### Expected Result
it should also generate in ceph 

#### Actual Result
just showing in nomad ui but not able to load 
### Job file (if appropriate)
https://learn.hashicorp.com/tutorials/nomad/stateful-workloads-csi-volumes?in=nomad/stateful-workloads

**Comment by Amier3** [comment]
Hey @thatsk 

Thanks for reporting this bug! We will get this shortly and hopefully figure out what's going on here.

Before that,I wanted to give a little bit of context into how our bug review process works. When an issue is labeled `type/bug` , it's  added to a project board that the " community engineer " works through that week. The community engineer is a rotating position on the nomad engineering team and is responsible for looking at the bug reports for that come through that week. 

Therefore, directly "@-ing" ( ex. @thatsk  ) individual engineers isn't the most efficient way to get this or any future bug reports reviewed. We'd prefer you not to do so in order to maintain a considerate and respectful environment ( as outlined in our [Community Code of Conduct](https://www.hashicorp.com/community-guidelines) ) 

Still, we understand that the issues you are experiencing can be frustrating and costly for your Nomad environment, and could possibly be holding up important deployments. If you frequently experience these time sensitive issues in your production environment, we recommend checking out [Nomad Enterprise](https://www.hashicorp.com/products/nomad/trial) and/or reaching out to our [sales team](https://www.hashicorp.com/contact-sales) to setup an official support contract.

**Comment by tgross** [comment]
Hi @thatsk! The API you're using is the [Register Volume API](https://www.nomadproject.io/api-docs/volumes#register-volume). The docs for the Register Volume API say:
> This endpoint registers an external volume with Nomad. The volume must exist in the external storage provider (see [Create Volume](https://www.nomadproject.io/api-docs/volumes#create-volume) below). It is an error to register an already registered volume.

You want the [Create Volume API](https://www.nomadproject.io/api-docs/volumes#create-volume), which would be at `http://nomadmaster:4646/v1/volume/csi/test-data/create` in your case. If you do have trouble with the Create Volume API then you'll want to look into the appropriate logs:

* Check the Nomad leader's server logs (at debug-level), to see if there's any information specific to this operation there.
* Check the plugin allocations' logs (both stderr and stdout, depending on the plugin), to see if there's any clues about whether the CSI RPC was treated as successful but failed at Ceph.
* Check the Ceph logs. I'm going to be honest and say I'm less able to help you out with that, because I'm not an expert on Ceph. But I can at least help eliminate any Nomad-side problems.

But I think you'll probably be in good shape if you use Create instead of Register here.

**Comment by thatsk** [comment]
thanks @tgross
