### ISSUE TITLE
[ui] Attempting to link to a variable from a namespaced job doesn't return any variables

### ISSUE THREAD

**Issue by philrenaud** [hashicorp/nomad#13864]
For example, if I have a job at `my-job@my-namespace`, and I create a variable at `jobs/my-job`, setting its namespace to `my-namespace`, a GET from the aforementioned job page does not find that variable.

**Comment by philrenaud** [comment]
@angrycub , can you confirm if `vars?prefix=some-prefix` queries work with namespaces? If so, does the namespace get tacked on as a query parameter or in some other way?

**Comment by tgross** [comment]
@philrenaud yeah that should work. The expected behaviors can be seen below:

```
$ nomad namespace apply dev
Successfully applied namespace "dev"!

$ echo '{"Namespace": "dev", "Items": {"foo": "bar"}}' | nomad operator api -X PUT "/v1/var/hello/world"

$ nomad operator api "/v1/vars?namespace=dev"
[{"CreateIndex":12,"CreateTime":1658331776707504000,"ModifyIndex":12,"ModifyTime":1658331776707504000,"Namespace":"dev","Path":"hello/world"}]%

$ nomad operator api "/v1/vars?prefix=hell&namespace=dev"
[{"CreateIndex":12,"CreateTime":1658331776707504000,"ModifyIndex":12,"ModifyTime":1658331776707504000,"Namespace":"dev","Path":"hello/world"}]%

$ nomad operator api "/v1/vars?prefix=hell"
[]%

$ nomad operator api "/v1/vars?prefix=x&namespace=dev"
[]%
```

**Comment by ChaiWithJai** [comment]
Chiming in here. I agree with @tgross that it should work. However, its worth noting that:

1. The Nomad API maybe defaulting the namespace to `default` instead of `*` here.
2. We need to factor in for namespaces in our waterfall request.

I just played around with the following `curl` requests:

My Set-up
1. Nomad Job created from `nomad job init` and edited to have a `namespace` set to `madness`.
2. Creating a variable `nomad/jobs/example` and set to have a `namespace` set to `madness`.

Currently, when we get to the Job Detail Overview Page for we dispatch a waterfall request to the following url:

```
http://localhost:4200/v1/vars?prefix=jobs%2Fexample
```

The issue here is 2-fold, the should check the prefix `nomad/jobs/$JOB_NAME` this is a UI issue. But, we also need to specify the namespace because the API is defaulting to search only the default namespace.

This is proved by simply adding:

```
http://localhost:4200/v1/vars?prefix=nomad%2Fjobs%2Fexample&namespace=*
```

This returns a result, simply searching only using the correct prefix does not.

I can throw up a patch on our end.
