### ISSUE TITLE
panic when creating new agent (via internal methods)

### ISSUE THREAD

**Issue by Joffref** [hashicorp/nomad#13908]
### Nomad version
I use package : `github.com/hashicorp/nomad v1.3.2`

### Operating system and Environment details
```
          .-/+oossssoo+/-.               
        `:+ssssssssssssssssss+:`           ---------------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 20.04.4 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: HP EliteBook 835 G8 Notebook P 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.13.0-39-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 1 hour, 48 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 3255 (dpkg), 9 (snap) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: zsh 5.8 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1920x1080 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: GNOME 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: Adwaita 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: Yaru [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Icons: Yaru [GTK2/3] 
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal: gnome-terminal 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      CPU: AMD Ryzen 7 PRO 5850U with Rade 
    .ossssssssssssssssssdMMMNysssso.       GPU: AMD ATI 04:00.0 Device 1638 
      -+sssssssssssssssssyyyssss+-         Memory: 5862MiB / 15307MiB 
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.                                       
                                                                   


```

### Issue
When trying to create a new Nomad Server using go provided SDK, it panics with a nil pointer errors that seems to came from a SDK function that's trying to access some part of the config that's not initialized.

### Reproduction steps
The code I use to produce this bug : 
```go
func NewOrchestrator() *nomad.Server{
	cfg := agent.DefaultConfig()
	cfg.Server.Enabled = true
	nomadServer, err := agent.NewAgent(cfg,
		hclog.NewInterceptLogger(&hclog.LoggerOptions{
			Name:   "nomad",
			Level:  hclog.LevelFromString("DEBUG"),
			Output: logger.Out,
		}),
		logger.Writer(),
		metrics.NewInmemSink(10e9, 10e9),
	)
	if err != nil {
		logger.Errorf("Error while creating nomad server : %v", err)
		return nil
	}
       return nomadServer
}
```

#### Expected Result
Creation of a new Nomad Server basically 

#### Actual Result
```bash

2022-07-23T14:31:20.488+0200 [DEBUG] nomad.plugin_loader.docker: using client connection initialized from environment: plugin_dir=""
2022-07-23T14:31:20.488+0200 [DEBUG] nomad.plugin_loader.docker: using client connection initialized from environment: plugin_dir=""
2022-07-23T14:31:20.488+0200 [INFO]  nomad: detected plugin: name=raw_exec type=driver plugin_version=0.1.0
2022-07-23T14:31:20.488+0200 [INFO]  nomad: detected plugin: name=exec type=driver plugin_version=0.1.0
2022-07-23T14:31:20.488+0200 [INFO]  nomad: detected plugin: name=qemu type=driver plugin_version=0.1.0
2022-07-23T14:31:20.488+0200 [INFO]  nomad: detected plugin: name=java type=driver plugin_version=0.1.0
2022-07-23T14:31:20.488+0200 [INFO]  nomad: detected plugin: name=docker type=driver plugin_version=0.1.0
2022-07-23T14:31:20.488+0200 [INFO]  nomad: detected plugin: name=mock_driver type=driver plugin_version=0.1.0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1bfb01a]

goroutine 1 [running]:
github.com/hashicorp/nomad/command/agent.convertServerConfig(0xc0003e2600)
        /home/majoffre/go/pkg/mod/github.com/hashicorp/nomad@v1.3.2/command/agent/agent.go:290 +0x71a
github.com/hashicorp/nomad/command/agent.(*Agent).serverConfig(0xc0001e8400)
        /home/majoffre/go/pkg/mod/github.com/hashicorp/nomad@v1.3.2/command/agent/agent.go:479 +0x25
github.com/hashicorp/nomad/command/agent.(*Agent).setupServer(0xc0001e8400)
        /home/majoffre/go/pkg/mod/github.com/hashicorp/nomad@v1.3.2/command/agent/agent.go:748 +0x49
github.com/hashicorp/nomad/command/agent.NewAgent(0xc0003e2600, {0x2b85ce8?, 0xc0008f8bd0}, {0x2b630a0?, 0xc000116330}, 0xc00075e0a0)
        /home/majoffre/go/pkg/mod/github.com/hashicorp/nomad@v1.3.2/command/agent/agent.go:145 +0x1fe
stash.ovh.net/~mathis.joffre/poc-orchestrator/orchestrator.NewOrchestrator({0x2b73a70?, 0xc0000600f0}, 0xc0003f1580, 0xc000658918, {0xc00083cde0, 0x1, 0x1})
        /home/majoffre/Documents/orchestrator_PoC/orchestrator/orchestator.go:34 +0x215
main.main()
        /home/majoffre/Documents/orchestrator_PoC/main.go:27 +0x2e8
exit status 2

```

**Comment by tgross** [comment]
Hi @Joffref, you've skipped calling `normalizeAddrs` as we do in the agent setup code at [`command.go#L224-L270`](https://github.com/hashicorp/nomad/blob/v1.3.2/command/agent/command.go#L224-L270). The default config can't include that because normalization has to happen after merging of config files.

But just for clarity, the `command/agent` package is not part of our public API. Only the [`api`](https://github.com/hashicorp/nomad/tree/main/api) package and the protobufs in [`plugins`](https://github.com/hashicorp/nomad/tree/main/plugins) are considered part of the stable API that you should be using for applications. So there's no SDK documentation for "proper" use of this code and it will definitely break backwards compatibility with your application with nearly every version of Nomad.

What is your goal here? Depending on what you're trying to do, you may get better results trying to use [`testutil/server.go`](https://github.com/hashicorp/nomad/blob/main/api/internal/testutil/server.go), because at least that's intended to test the externally-facing code. But not that's not considered stable either.

**Comment by Joffref** [comment]
Hi @tgross, I know that I've skipped to use normalizeAddrs, indeed it's not callable outside agent package.

My goal here is to use nomad as part of a home-made orchestrator in order to directly interact with scheduler and push job without the overhead of a HTTP request.

But If I follow what you're saying, creating a nomad server directly in Go is not possible, am I right ? Or there is any workaround except forking nomad ?

**Comment by tgross** [comment]
> My goal here is to use nomad as part of a home-made orchestrator in order to directly interact with scheduler and push job without the overhead of a HTTP request.

For what it's worth, the HTTP API isn't going to be a meaningful amount of overhead here relative to the scheduling work, which is CPU intensive. You _might_ be better off trying to use the yamux/msgpack RPC directly rather than trying to fiddle with getting all the server configuration correct.

> But If I follow what you're saying, creating a nomad server directly in Go is not possible, am I right ? Or there is any workaround except forking nomad ?

It's probably _possible_ just not at all supported. You might be able to get away with it if you directly modify the configuration fields to duplicate the minimum behavior of `normalizeAddrs`.

**Comment by Joffref** [comment]
I will look at yamux/msgpack.

For what is about nomarlizedAddrs, I will keep the solution I found for the moment, because nomad seems to work properly like this. 

Thanks for you reply ! Issue could be closed, thanks a lot :100:
