### ISSUE TITLE
learn guide install instructions produce weird terminal output

### ISSUE THREAD

**Issue by shoenig** [hashicorp/nomad#14047]
On a fresh VM, following the learn guide install instructions produces some binary output on the terminal. Hopefully the screen shot is self-explanatory.

![Screenshot from 2022-08-08 09-18-39](https://user-images.githubusercontent.com/394887/183440269-b80eb7a7-13de-4d3c-a301-99964ba61d5f.png)

```
ubuntu@ip-172-31-31-191:~$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Comment by angrycub** [comment]
Why not `dd` the apt source too.  If I remember right, the `sudo tee` calls were just to facilitate the file creation at the end of the pipeline into root-only targets

**Comment by marcindulak** [comment]
The issue is still present in most if not all hashicorp installation guides, e.g. https://developer.hashicorp.com/vault/downloads or https://developer.hashicorp.com/terraform/downloads

Instead of:
`wget --quiet -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg`
for example this would work
`wget --quiet -O- https://apt.releases.hashicorp.com/gpg | sudo sh -c 'gpg --dearmor > /usr/share/keyrings/hashicorp-archive-keyring.gpg'`

**Comment by marcindulak** [comment]
or use `... | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg` as suggested in https://github.com/hashicorp/dev-portal/pull/797#discussion_r1061027388
