### ISSUE TITLE
Windows templating failure with error "failed looking up user: managing file ownership is not supported on Windows"

### ISSUE THREAD

**Issue by ScatteredRay** [hashicorp/nomad#14085]
### Nomad version
1.3.3

### Operating system and Environment details
Agents running Windows Server 2022 10.0.20348 Build 20348 on AWS EC2

### Issue

Unable to render template with error 
```
Template failed: error rendering "(dynamic)" => "C:\\nomad\\data\\alloc\\239e8d2c-894a-b1a5-d59e-b7eb09819f2e\\testtask\\local\\test.txt": failed looking up user: managing file ownership is not supported on Windows
```

It seems that this happens on Windows if `user` is anything but "" as seen here https://github.com/hashicorp/consul-template/blob/583050a85eea46c3faa947b3247ff31a7ec90234/renderer/file_ownership_windows.go?q=lookupUser#L26

But I'm not explicitly setting user, so it's unclear where this value is coming from.

### Reproduction steps

Run a simple job with a single template of any value on a Windows agent.

#### Expected Result

The job runs successfully, and the template renders correctly.

### Job file (if appropriate)

```
job "testjob" {
  datacenters = ["dc1"]
  type = "batch"

  group "testgroup" {
    count = 1

    constraint {
      attribute = "${attr.kernel.name}"
      value = "windows"
    }

    task "testtask" {
      driver = "raw_exec"

      template {
        data = "Test"
        destination = "local/test.txt"
      }
    }
  }
}
```

With agent config of:
```

datacenter = "dc1"
data_dir = "C:\\nomad\\data"

client {
  enabled = true
  servers = ["${NomadUrl}:4647"]
}

plugin "raw_exec" {
  config {
    enabled = true
  }
}
```

**Comment by lgfa29** [comment]
Hi @ScatteredRay 👋 

I haven't been able to reproduce this yet, do you have a full jobspec as example? The one you provided is missing a task `config`  block 😄

**Comment by jjunanet** [comment]
Hello, I am seeing this as well "failed looking up user: managing file ownership is not supported on Windows".

To be clear, the activity that is failing is the creation of rendered* templates on disk.

A ref from searching the error message:
https://github.com/hashicorp/consul-template/blob/583050a85eea46c3faa947b3247ff31a7ec90234/renderer/file_ownership_windows.go?q=lookupUser#L26


Strangely this is only occuring on certain Windows Server instances among the windows clients in my cluster for this job, ranging from Windows Server 2019 Standard, Microsoft Windows Server 2012 R2 Standard, and Microsoft Windows Server 2019 Datacenter. The config and client versions are the same for all windows instances in the cluster and I can not figure out what the issue is.


Some details on the windows client and configuration:

`os.name Microsoft Windows Server 2019 Standard`

`os.kernel 10.0.17763 Build 17763`

`nomad --version`
`Nomad v1.2.6 (a6c6b475db5073e33885377b4a5c733e1161020c)`

nomad client config:
`ports { http = "9696" } plugin "raw_exec" { config { enabled = true } } log_file = "C:/nomad-client/nomad-client.log"`

nomad client runtime (via nssm.exe):
`C:/ProgramData/chocolatey/bin/nomad.exe agent -client -node="{{ env "node.unique.name" }}" -dc="{{ env "NOMAD_META_datacenter" }}" -data-dir="C:/nomad-client" -encrypt="{{ env "NOMAD_META_gossip_encryption_key" }}" -region="{{ env "NOMAD_META_nomad_region" }}" -bind="{{ env "attr.unique.network.ip-address" }}" -servers="{{ env "NOMAD_META_nomad_server" }}:4647" -config="C:/nomad.conf" -log-json`

**Comment by lgfa29** [comment]
Thanks for the extra information @jjunanet. 

> Strangely this is only occuring on certain Windows Server instances among the windows clients in my cluster for this job

This may explain why we haven't been able to reproduce this yet 🤔 

Did you change anything in your cluster recently? Like updated the Nomad version, or deployed clients with a new Windows version?

**Comment by ScatteredRay** [comment]
So, it actually launches fine with the job in the report without a config and expresses the error, Just copied-pasted it and tried again, but for reference, my original job had a config of 

`      config {
        command = "powershell.exe"
        args = [
          "-NoProfile",
          "-Command",
          "\"& local\\run.ps1\""
        ]
      }
`

where run.ps1 was the result of the failed template.

**Comment by ScatteredRay** [comment]
My cluster only has a single node at the moment, so I am not seeing the case where it works on some nodes yet, but am happy to run any experiments since this is just a test cluster at the moment.

**Comment by lgfa29** [comment]
> My cluster only has a single node at the moment, so I am not seeing the case where it works on some nodes yet, but am happy to run any experiments since this is just a test cluster at the moment.
> 
> And to be clear, in my case this is from the initial setup of the cluster, so I've never run a successful job yet on this cluster.

Oh nice, thanks for the offer 😄 

One thing that would be very useful is to try to narrow down in which version of Nomad this started happening (if any!). @jjunanet is running Nomad v1.2.6 so maybe walk backwards for a bit, like test 1.2.0, then 1.1.0 etc. until you find a version where this doesn't happen.

The other hypothesis is that it may be something with a specific Windows version, but that would take more work to isolate.

**Comment by lgfa29** [comment]
I think I was able to reproduce the problem, at least in one way. 

This happens when you have a job registered using a version prior to 1.3.3 and then upgrades the cluster version. https://github.com/hashicorp/nomad/pull/13998 handled the case of new job registrations, but existing jobs would use the zero value of `int` which is `0`. On Windows environments this will cause the error you are seeing because Nomad would try to set the template `uid`and `gid`, which is not supported.

Here are my reproduction steps:

1. Start a Nomad v1.3.2 agent (non-dev, it must retain state)
2. Register a job
3. Verify the job runs successfully
4. Stop Nomad agent
5. Start a Nomad v1.3.3 agent
6. Verity that the existing job fails with the event:
    ```
    Template failed: error rendering "(dynamic)" => "C:\\...": failed looking up user: managing file ownership is not supported on Windows
    ```

Agent config:

```hcl
data_dir = "C:\\..."

client {
  enabled = true
}

server {
  enabled          = true
  bootstrap_expect = 1
}

plugin "raw_exec" {
  config {
    enabled = true
  }
}
```

Job file:

```hcl
job "sleep" {
  datacenters = ["dc1"]

  group "sleep" {
    network {
      port "db" {
        to = 6379
      }
    }

    task "sleep" {
      driver = "raw_exec"

       config { 
        command = "powershell.exe" 
        args = ["local/sleep.ps1"] 
      }

      template {
        data = <<EOF
if (-not (Test-Path env:SLEEP_SECS)) { $env:SLEEP_SECS = 2 }

"$(get-date) -- Starting SleepyEcho. Sleep interval is $env:SLEEP_SECS sec."

while ($true) { 
  "$(get-date) -- Alive... going back to sleep for $env:SLEEP_SECS seconds."
  start-sleep $env:SLEEP_SECS
} 
EOF
        destination = "local/sleep.ps1"
      }
    }
  }
}
```

Does this sound like something you may have done?

**Comment by lutemartin** [comment]
I was able to get the error cleared by reverting to nomad 1.2.6 from 1.3.3 on one particular instance. Deleting the nomad config folder and clearing all client state has also been a fix on other instances.

**Comment by lgfa29** [comment]
Thanks for sharing the extra info @lutemartin.

I think another option is to explicitly set `gid` and `uid` to `-1`. But a fix for this is coming in Nomad 1.3.4, so, if possible, it may be better to wait for the new version 🙂

**Comment by lutemartin** [comment]
@lgfa29 very impressive turn around time, thank you as well. I will try the 1.3.6 release when it becomes available.

**Comment by lgfa29** [comment]
1.3.4 is available now and this problem should be fixed now, but let us know if that's not the case and we can reopen this issue 👍

**Comment by ScatteredRay** [comment]
Ok, oddly enough, I never upgraded any instance, everything in my cluster has been setup excursively on 1.3.3 from the start.

Having said that, I just updated to 1.3.4 and the problem appears to be resolved, thanks!

**Comment by lgfa29** [comment]
Oh interesting, but yeah I can see how that would be a problem as well. Glad to hear the fix worked for you 🙂
