### ISSUE TITLE
Forcing a periodic job with a name similar to other periodic jobs fails to find the job

### ISSUE THREAD

**Issue by jamesooo** [hashicorp/nomad#14116]
### Nomad version
Nomad v1.1.6 (b83d623fb5ff475d5e40df21e9e7a61834071078)

### Operating system and Environment details
`PRETTY_NAME="Debian GNU/Linux 10 (buster)"`

### Issue

When a periodic job's name is prepended to other jobs `nomad job periodic force` is unable to find the job
```
$ nomad job periodic force cluster-rebalance
Prefix matched multiple periodic jobs

ID                                    Type            Priority  Status   Submit Date
cluster-rebalance                     batch/periodic  50        running  2022-08-15T16:51:47Z
cluster-rebalance-testing-drain       batch/periodic  50        running  2022-08-15T17:38:25Z
cluster-rebalance-testing-validation  batch/periodic  50        running  2022-08-15T17:38:25Z
```

### Reproduction steps
1. create batch/periodic jobs named `x`, `x-testing`
2. attempt `nomad job periodic force x` will now fail with the message `Prefix matched multiple periodic jobs`

#### Expected Result
Execution of `x` should be forced

#### Actual Result
Command fails to force placement of job and exits with message `Prefix matched multiple periodic jobs`

**Comment by jrasell** [comment]
Hi @jamesooo and thanks for raising this issue which I can also reproduce locally using the steps you provided. The bug is because the CLI performs a [prefix search only](https://github.com/hashicorp/nomad/blob/c1abf47e16ec65309e986f80bd05cd437b2440c0/command/job_periodic_force.go#L116); whereas we should attempt a direct lookup first before falling back to a prefix lookup.
