### ISSUE TITLE
Job revert should respect the update stanza

### ISSUE THREAD

**Issue by johnnyplaydrums** [hashicorp/nomad#14200]
### Proposal

Hey Nomad team! When issuing the `nomad job revert` command, Nomad should respect the `update` stanza for that job. Currently, when the revert is issued, the existing allocations are spun down and new allocations spun up all at once, ignoring the `update` stanza. It would also be helpful if the [nomad job revert docs](https://www.nomadproject.io/docs/commands/job/revert) described how revert works. It's seems counter-intuitive that the `update` stanza is ignored during revert, and the docs don't describe how revert works.

### Use-cases

We use `nomad job revert` when we want to quickly revert a deploy that introduced a bug. In this case the deploy succeeded and finished, but there is some bug causing end user issues that we want to mitigate as quickly as possible. In these instances, we want to bypass our CI/CD process in order to fix the issue quickly, and then we follow up with a revert PR which removes the problematic code from version control. The current revert command causes a complete outage of the job as all the existing allocations are spun up. It would be ideal if the revert command followed the job's `update` stanza, especially the `max_parallel` parameter, so that there isn't a complete outage of the job during revert. 

### Attempted Solutions

I'm not aware of any Nomad native solution to this problem. If we catch the issue while the deploy is still in progress we could fail the deployment, which does seem to revert to the previous version without spinning down all running allocations, but that only works if we happen to catch the issue while the deploy is still in progress (for us, about a 5 minute window).

**Comment by tgross** [comment]
Hi @johnnyplaydrums!

From an internals perspective, the `nomad job revert` command updates the job to the previous jobspec with an incremented job version and re-registers it (ref [`job_endpoint.go#L622-L623`]( https://github.com/hashicorp/nomad/blob/v1.3.3/nomad/job_endpoint.go#L622-L623)), so from there it's treated the same as any other job update. So I would expect this to work as you're asking for already.

But I wasn't able to reproduce what you're seeing -- the `job revert` command does seem to be respecting the `update` block for me (with a current version of Nomad), so I'm not sure what's going on there. It might be helpful if you can provide the output `nomad job status` and `nomad deployment status` for the job and deployment in question.

My attempts at reproduction are below.

---

With the following update block:

```hcl
  update {
    max_parallel      = 1
    min_healthy_time  = "30s"
    auto_promote      = false
    canary            = 1
  }
```

<details><summary>(full jobspec)</summary>

```hcl
job "example" {
  datacenters = ["dc1"]

  update {
    max_parallel      = 1
    min_healthy_time  = "30s"
    auto_promote      = false
    canary            = 1
  }

  group "web" {

    count = 3

    network {
      mode = "bridge"
      port "www" {
        to = 8001
      }
    }

    service {
      port = "www"
    }

    task "http" {

      driver = "docker"

      config {
        image   = "busybox:1"
        command = "httpd"
        args    = ["-v", "-f", "-p", "8001", "-h", "/local"]
        ports   = ["www"]
      }

      template {
        data        = "<html>hello, world</html>"
        destination = "local/index.html"
      }

      resources {
        cpu    = 128
        memory = 128
      }

    }
  }
}


```

</details>


I ran the job, made a minor edit and resubmitted. Eventually I ended up with an allocations list like the following:

```
Allocations
ID        Node ID   Task Group  Version  Desired  Status    Created    Modified
6d6d319c  d2c16083  web         1        run      running   8s ago     2s ago
f7f3af3d  79f8b256  web         1        run      running   46s ago    9s ago
557c3e81  f63232c1  web         1        run      running   1m53s ago  1m22s ago
b4ca130b  79f8b256  web         0        stop     complete  5m47s ago  40s ago
e95f9fd6  f63232c1  web         0        stop     complete  5m47s ago  40s ago
fc2d2be4  d2c16083  web         0        stop     complete  5m47s ago  3s ago
```

Then I did a revert and you can see that it's definitely using the `update` block's workflow, because it's hanging waiting for manual canary promotion:

```
$ nomad job revert example 0
==> 2022-08-22T11:50:40-04:00: Monitoring evaluation "b0726e9d"
    2022-08-22T11:50:40-04:00: Evaluation triggered by job "example"
    2022-08-22T11:50:41-04:00: Evaluation within deployment: "797fbf1c"
    2022-08-22T11:50:41-04:00: Allocation "758776be" created: node "d2c16083", group "web"
    2022-08-22T11:50:41-04:00: Evaluation status changed: "pending" -> "complete"
==> 2022-08-22T11:50:41-04:00: Evaluation "b0726e9d" finished with status "complete"
==> 2022-08-22T11:50:41-04:00: Monitoring deployment "797fbf1c"
  ⠋ Deployment "797fbf1c" in progress...

    2022-08-22T11:50:44-04:00
    ID          = 797fbf1c
    Job ID      = example
    Job Version = 2
    Status      = running
    Description = Deployment is running but requires manual promotion

    Deployed
    Task Group  Promoted  Desired  Canaries  Placed  Healthy  Unhealthy  Progress Deadline
    web         false     3        1         1       0        0          2022-08-22T16:00:40Z
```

Just in case the behavior I'm seeing was related to canaries, I tried again with the following update block:

```hcl
  update {
    max_parallel      = 1
    min_healthy_time  = "30s"
  }
```

And the revert respected the `update` block as I'd expect.


(Aside: somewhat related is https://github.com/hashicorp/nomad/issues/10882, which is asking for the opposite behavior you're looking for using `nomad deployment fail`.)

**Comment by johnnyplaydrums** [comment]
Hi @tgross! Thank you for your quick response here and for providing an easily reproducible example. I tested this on our clusters and confirmed that Nomad is behaving as you describe, going through the normal deployment process when reverting a job. I think I was testing this with the wrong job spec (e.g. `max_parallel == count`) that made it look like the `update` stanza was being ignored. When I re-tested with the job in question, the `update` stanza was followed correctly.

Apologies for the false alarm, and thanks again for your help!
