### ISSUE TITLE
Be able to toggle count behavior

### ISSUE THREAD

**Issue by jshaw86** [hashicorp/nomad#1423]
We would like to have the ability to schedule a task group per DC rather than across DC.

Consider the below JobSpec, rather than scheduling event_handler_1 **across** region1 and region2 for a total of 3 instances nomad would schedule 3 event_handler_1's **per** region for a total of 6 instances.

```
{
"Job" : { 
             "Region": "region1",
             "ID": 1,
             "Name": 1,
             "Type": "service",
             "Priority": 50,
             "AllAtOnce": False,
             "Datacenters": ["dc1","dc2"],
             "TaskGroups": [
                   { "Name": "event_handler_1",
                     "Count": 3,
                     "Constraints": None,
                     "Tasks": [ { "Name": "event_handler",
                                         "Driver": "exec",
                                         "User": "",
                                         "Config": { "command": "/usr/bin/start.sh" },
                                         "Constraints": None,
                                         "Env": { "HOME": "/usr/lib/service1" },
                                         "Services": [ { "Id": "",
                                                                 "Name": "service1",
                                                                 "Tags": tags,
                                                                 "PortLabel": "http",
                                                                 "Checks": [] } ]
                                       } ]
             }]
           ....
         }
}
```

**Comment by DBuret** [comment]
Hi,

We are evaluating nomad. We want to spread the tasks of a given job over 2 datacenters in order to insure business continuity (our DCs are not so far away so that's the same 'region' if you look at network-latency)

this #1423 request could solve our need. 
#1387  may add a new constraint (spread-over-dc ?)
The thread at #1990 seems to also seek the same goal.

I'm with Hashicorp when they state that bin packing is the way to go, but the spreading per DC and/or regions would be usefull for many people.

managing on nomad job per DC could work, but  adds uneeded complexity

thanks.

**Comment by tgross** [comment]
Doing a bit of issue cleanup here... this use case is currently covered by the [`multiregion`](https://www.nomadproject.io/docs/job-specification/multiregion) feature of Nomad Enterprise.
