### ISSUE TITLE
Unique hostnames

### ISSUE THREAD

**Issue by suikast42** [hashicorp/nomad#14401]
The nomad [docu ](https://www.nomadproject.io/docs/configuration) says  for agent configura

> _[name](https://www.nomadproject.io/docs/configuration#name) (string: [hostname]) - Specifies the name of the local node. This value is used to identify individual agents. When specified on a server, the name must be unique within the region._

But if I set two workers wit same node name then consul denies one of the hosts and nomad not. 

> consul version
> Consul v1.12.3

> nomad version
> Nomad v1.3.3
>

**Comment by jrasell** [comment]
Hi @suikast42; this value is only required to be unique on Nomad agents running with [server mode enabled](https://www.nomadproject.io/docs/configuration/server#enabled). This differs from Consul due to the architectural differences between the two applications.

Could you confirm whether you are seeing this name issue when running the Nomad agent within server mode or not?

**Comment by jrasell** [comment]
Hi @suikast42, as we have not had a response I am going to close this issue. If you are still experiencing this problem, please feel free to reopen it with additional context as requested in my previous response.
