### ISSUE TITLE
Consul ACL Token Permissions Require Total Access to KV Store

### ISSUE THREAD

**Issue by stevenheinze57** [hashicorp/nomad#14402]
Through some testing I found that in consul token permissions require total access to the consul KV store, when submitting Nomad jobs. 

Before setting the right policy I was getting this: 

```
Error submitting job: Unexpected response code: 500 (rpc error: job-submitter consul token denied: insufficient Consul ACL permissions to use template)
```

And [here](https://github.com/hashicorp/nomad/blob/b7fea76f7fffdc3aca856e1910bb1ba1758da992/nomad/consul_policy.go#L299) it seems to be checking for an empty key_prefix read policy. 

I was actually able to hack my way around this by creating the below policy, since the function is looking for at least one key_prefix policy that matches, and the actual behavior of how consul applies these policies seems to be top down. 

```
key_prefix "" {
  policy = "read"
}
key_prefix "" {
  policy = "deny"
}
key_prefix "dev/path/" {
  policy = "read"
}
```

I imagine the reason for leaving this so open would be the complexity required to actually check all possible consul-template paths against the user submitted token.

**Comment by lgfa29** [comment]
Hi @stevenheinze57 👋 

I was able to reproduce this and I agree that this check may be too strict. The function you linked was added in [this commit](https://github.com/hashicorp/nomad/commit/a97254fa209c0d64b3fb0f71d95ce8d1e29a97c2#diff-b3fa2dbd6520f4c84fe21b55f48b958b5e9ef24191c15477720a23702fb07405R195), which mentions this:

> There is no new functionality provided by this changeset

So I suspect this was an accidental change in 1.1.0. I will check with the rest of team to make sure I'm not missing anything and I will get back to you once I have a better answer.

**Comment by lgfa29** [comment]
Quick update after discussing wit the team, this check is done to avoid a privilege escalation problem. Since the template is rendered by the Nomad client, it uses the client's Consul token to access Consul KV store, and this token usually has wide access to KV paths in order to run several different jobs.

At job registration Nomad doesn't know where the job's allocations will run yet, so it can make any checks against the client token either.

So anything short of an exact permission match could lead to privilege escalation problems, but we can't do that since `template` content can be arbitrary complex when accessing key paths (imagine, for example, that the path is determine by interpolating several other variables. A simple string match would not be able to evaluate this).

And so the safest option we have right now is to require a high degree of access (`read ""`) from job submitters. Anything lower than this is almost like  setting [`consul.allow_unauthenticated = true`](https://www.nomadproject.io/docs/configuration/consul#allow_unauthenticated).

This is not a great solution, so I will leave this open for us to reassess it in the future, but just to set the expectations here, I don't think we'll have a solution any time soon.

**Comment by tgross** [comment]
Just a heads up that following 1.6.0 we'll be kicking off early work on https://github.com/hashicorp/nomad/issues/15618, which will be the ultimate solution to this problem.

**Comment by tgross** [comment]
Starting in [Nomad 1.7.0-beta.1](https://github.com/hashicorp/nomad/releases/tag/v1.7.0-beta.1) we've deprecated the use of Consul tokens in the Nomad agent configuration for purposes of giving workload access to Consul KV. Nomad will use workload identities to sign into Consul for purposes of getting Consul tokens for those workloads, and those tokens can be downscoped in privilege by the Consul role.
