### ISSUE TITLE
NOMAD_ALLOC_COUNT environment variable

### ISSUE THREAD

**Issue by spiralw** [hashicorp/nomad#14476]
### Proposal
Add an environment variable `NOMAD_ALLOC_COUNT` that represents the `count` variable in a task group.

### Use-cases
If an app needs to do a specific number of tasks while knowing which sequential task it's doing, tasks can be split between replicas and the alloc index / alloc count can be used to calculate the tasks that each alloc ends up doing.

In my personal use-case, I run a Discord bot, and Discord requires websocket connections to them to have a (index, total count) attached. I run a fixed number of connections per worker, and use the alloc index / alloc count to calculate the values for each connection.

### Attempted Solutions
I currently give a custom environment variable to my app that duplicates the value of `count`, however I sometimes forget to update it, and some allocs end up not working correctly.

I would be willing to submit a PR if the feature request is accepted.

**Comment by tgross** [comment]
Hi @spiralw! This sounds like a good idea on the surface and it's similar to requests we've had before for a `NOMAD_JOB_VERSION` environment variable. But we're not going to be able to implement this. I'm going to give both an explanation of why and a workaround for you below.

This feature runs into two important invariants:
* Once a process has started, only that process can modify its environment (outside of doing something scary like ptrace).
* Nomad doesn't restart allocations that are unchanged.

Using this ordinary jobspec with count = 1.

<details><summary>jobspec</summary>

```hcl
job "example" {
  datacenters = ["dc1"]

  group "web" {

    count = 1

    task "http" {

      driver = "docker"

      config {
        image   = "busybox:1"
        command = "httpd"
        args    = ["-v", "-f", "-p", "8001", "-h", "/var/www"]
      }

      resources {
        cpu    = 128
        memory = 128
      }

    }
  }
}
```

</details>

I can run this and see that we get allocation `b7faa08d` running version 0 of the job:

```
$ nomad job status example
...
Allocations
ID        Node ID   Task Group  Version  Desired  Status   Created  Modified
b7faa08d  1a11398e  web         0        run      running  21s ago  10s ago
```

If we bump the count to 3, we can see that the original allocation `b7faa08d` has its version incremented but is otherwise left running:

```
Allocations
ID        Node ID   Task Group  Version  Desired  Status   Created  Modified
1faf8fce  1a11398e  web         1        run      running  8s ago   7s ago
478d8660  1a11398e  web         1        run      running  8s ago   7s ago
b7faa08d  1a11398e  web         1        run      running  52s ago  8s ago
```

And just to prove the task hasn't been touched:

```
$ nomad alloc status b7faa08d
...
Recent Events:
Time                       Type        Description
2022-09-07T08:38:04-04:00  Started     Task started by client
2022-09-07T08:38:02-04:00  Driver      Downloading image
2022-09-07T08:38:02-04:00  Task Setup  Building Task Directory
2022-09-07T08:38:02-04:00  Received    Task received by client
```

So because the task hasn't been restarted, we can't update its environment variables. If we _did_ update its environment variables, we'd have to restart it. Which wouldn't be backwards compatible and would be a nasty surprise to anyone who isn't using a hypothetical `NOMAD_ALLOC_COUNT` variable. Or we could leave the environment alone and then the environment variable would be stale.

Now for the workaround! You can use a [HCL2 variable](https://www.nomadproject.io/docs/job-specification/hcl2/variables) to set the count and then pass it in the task [`env`](https://www.nomadproject.io/docs/job-specification/env) block:


```hcl
variable "count" {
  type    = number
  default = 1
}

job "example" {
  datacenters = ["dc1"]

  group "web" {

    count = var.count

    task "http" {

      driver = "docker"

      config {
        image   = "busybox:1"
        command = "httpd"
        args    = ["-v", "-f", "-p", "8001", "-h", "/var/www"]
      }

      env {
        ALLOC_COUNT = var.count
      }

      resources {
        cpu    = 128
        memory = 128
      }

    }
  }
}

```

When I run this job I get an allocation `225a61af`:

```
$ nomad job status example
....
Allocations
ID        Node ID   Task Group  Version  Desired  Status    Created    Modified
225a61af  5c7f70cb  web         0        run      running   10s ago  6s ago
```

I can exec into this allocation and see the environment variable has been set:

```
$ nomad alloc exec 225a61af env | grep ALLOC_COUNT
ALLOC_COUNT=1
```

And if I re-run the job with a different value for the variable, I can see all the allocations get updated. This lets you opt-in to the behavior you're asking for in this feature request without breaking the deployments of other jobs that don't care about the count:

```
$ nomad job run -var count=3 ./example.nomad
$ nomad job status example
....
Allocations
ID        Node ID   Task Group  Version  Desired  Status    Created    Modified
ce60e135  5c7f70cb  web         1        run      running   11s ago    5s ago
e0250f06  5c7f70cb  web         1        run      running   23s ago    12s ago
ef85fd85  5c7f70cb  web         1        run      running   23s ago    12s ago
225a61af  5c7f70cb  web         0        stop     complete  1m10s ago  6s ago
```

**Comment by spiralw** [comment]
@tgross hey, thanks for the explanation and the workaround. however, i'm not seeing the same behaviour as you - when I change the `count` variable on a group, every allocation gets restarted:

```
+/- Job: "my_job"
+/- Task Group: "my_group" ( 2 create 26 in-place update )
+/- Count:	"26" => "28"
Task: "my_task"
```

(and if the readout from job plan doesn't mean what i think it means, i did try it and my allocations do get rolling restarted as if I changed a different part of config)

is that not intended?

**Comment by tgross** [comment]
The plan is showing "in-place update", which is just the version bump in this case. I'd need to see the rest of your job spec to figure out why it's rolling the whole thing; it generally shouldn't unless there's something that's getting interpolated at job submission time.
