### ISSUE TITLE
Logical operators in nomad job constraint configuration

### ISSUE THREAD

**Issue by FranksRobins** [hashicorp/nomad#14554]
### Proposal
Hi Hashicorp team,
I am trying to fine tune a constraint but Nomad seems to be missing the right operators to achieve my goal. Would it be possible to have a AND and OR operators in the constraint stanza?
There are situations where the current list cannot be a fit:
```
=
!=
>
>=
<
<=
distinct_hosts
distinct_property
regexp
set_contains
set_contains_any
version
semver
is_set
is_not_set
```
An `&&` and `||` operators would also be useful to add flexibility to the stanza to be used in the **operator** field.

### Use-cases
I want a task to run on only 2 specific servers

```
    constraint {
      attribute     = "${meta.machine-role}"
      operator      = "&&"
      value         = "admin-server, network-server"
    }
```

I want a task to run only on one of those specific machines
```
    constraint {
      attribute     = "${meta.machine-role}"
      operator      = "||"
      value         = "admin-server, network-server"
    }
```

### Attempted Solutions
Currently I am using the regex operator, which is flexible enough to do so but then I have to be careful on the naming of the other machine-role meta values that I am attributing to new nodes and it can become difficult to implement a valid regex on an infrastructure that is already deployed depending on those values. An AND or OR operator would be way easier and more specific with no possible matching mistake.

Currently, it returns this error `* Unknown constraint type "&&"`. Also tried something like

```
    constraint {
      attribute     = "${meta.machine-role}"
      operator      = "="
      value         = "admin-server, network-server"
    }
```
and

```
    constraint {
      attribute     = "${meta.machine-role}"
      value         = "admin-server, network-server"
    }
```
Both return a `failed to place 1 allocation` message.

Is that something that could be possible? Thanks

**Comment by DerekStrickland** [comment]
Hi @FranksRobins. Thanks for using Nomad and for raising this issue. 

To first answer the question, of is it possible, I suspect that yes Nomad could be modified to support these operators. However, the operators we have are very well vetted, so I'd like to explore using what exists first. 

To set the context, let me restate that constraints are used to determine if a node is _feasible_ for placing allocations for a job.

## Use Case - "I want a task to run on only 2 specific servers"

You expressed the logic this way:

```hcl
    constraint {
      attribute     = "${meta.machine-role}"
      operator      = "&&"
      value         = "admin-server, network-server"
    }
```

If what you want is for the machines with either of those roles to be considered _feasible_ have you tried the [`set_contains_any`](https://www.nomadproject.io/docs/job-specification/constraint#set_contains_any) operator? It seems like it is purpose built for exactly this use case. 

```hcl
constraint {
  attribute    = "${meta.machine-role}"
  operator  = "set_contains_any"
  value = "admin-server,network-server"
}
```

## Use Case - "I want a task to run only on one of those specific machines"

You expressed the logic this way

```hcl
    constraint {
      attribute     = "${meta.machine-role}"
      operator      = "||"
      value         = "admin-server, network-server"
    }
```

In both these cases, it seems like you are interested in controlling both _where_ the task runs and the the _number of allocation instances_ that are run. The number of allocation instances is determined by the `count` configuration. Constraints only handle the _feasability_ concern. It seems like you can achieve either use cases using the `set_contains_any` operator combined with the `count` configuration.  Can you give that a try and let me know how it works for you? I'll leave this open for now pending your results.

**Comment by FranksRobins** [comment]
Hi @DerekStrickland, thanks for your reply!
The `set_contains_any` does not accomplish the desired result. It will effectively figure out which nodes' meta.machine-role value match the constraint but the `_any` from the operator most likely will behave like an _OR_ condition based on a partial match. Meaning that it will stop evaluating after one of the value stated in the _value_ field returns true. As a result, only one node will be running the task.

By using `set_contains` and providing 2 values, it will most likely concatenate those values into 1 string to then search which node's meta will match that string. `set_contains_any` paired with a `type = system` cannot work with the `count` key and a `type = service` with a count of 2 will simply run the task on one of the matching node twice. The _distinc_host_ operator cannot be of use here as only one node is returned. The task actually needs to be deployed as a system job. 

It is important to note that this deployment's purpose is to test a workload, meaning that this would not be permanent and would be repeated as many time as needed. The task in question is to deploy 2x telegraf instances on those 2 machines as a stress test will be performed for benchmarking purposes. But it could also be to test a workload on those machines before deploying it to others.
Now, I could of course add another meta key/value and restart the services but this would not be the preferred practice. Especially not on a running infrastructure, even if its not a production environment and especially if I have to do that every time a new test is needed. This control should be defined at the nomad job spec level. 

This is why I really feel like the constraint stanza does need an _&&_ operator. To be honest, the _||_ operator is not that of a need here. It just feels natural to mention it in this context. Also, the `set_contains_any` is a partial match, _||_ would be an exact match. So I do see potential use cases.

What are your thoughts on this? Am I missing something?

Thank you again for taking the time to review this.

**Comment by DerekStrickland** [comment]
> Hi @DerekStrickland, thanks for your reply! 

No worries! 

> The `set_contains_any` does not accomplish the desired result. It will effectively figure out which nodes' meta.machine-role value match the constraint but the `_any` from the operator most likely will behave like an _OR_ condition based on a partial match. Meaning that it will stop evaluating after one of the value stated in the _value_ field returns true. As a result, only one node will be running the task.
> 

So this goes back to the point I was making about _feasibility_.  Here's a useful explanation from one of our [blog posts](https://www.hashicorp.com/blog/resilient-infrastructure-with-nomad-scheduling).

"Placing allocations is split into two distinct phases: feasibility checking and ranking. In the first phase the scheduler finds nodes that are feasible by filtering unhealthy nodes, those missing necessary drivers, and those failing the specified constraints for the job. This is where Nomad uses the node fingerprinting and driver information provided by Nomad clients.

The second phase is ranking, where the scheduler scores feasible nodes to find the best fit. Scoring is based on a combination of bin packing and anti-affinity (co-locating multiple instances of a task group is discouraged) which optimizes for density while reducing the likelihood of correlated failures. As of Nomad 0.9.0, scoring also takes into consideration user-specified affinities and anti-affinities"

Also, from your statement "most likely will behave like", is it safe to assume you haven't tested?  If so, I think some experimentation will really help.

> By using `set_contains` and providing 2 values, it will most likely concatenate those values into 1 string to then search which node's meta will match that string. 
>

Actually, it's a split rather than a concat.  We can confirm this from the [docs](https://www.nomadproject.io/docs/job-specification/constraint).

[set_contains](https://www.nomadproject.io/docs/job-specification/constraint#set_contains) - Specifies a contains constraint against the attribute. The attribute and the list being checked are split using commas. This will check that the given attribute contains all of the specified elements.
[set_contains_any](https://www.nomadproject.io/docs/job-specification/constraint#set_contains_any) - Specifies a contains constraint against the attribute. The attribute and the list being checked are split using commas. This will check that the given attribute contains any of the specified elements.

>`set_contains_any` paired with a `type = system` cannot work with the `count` key and a `type = service` with a count of 2 will simply run the task on one of the matching node twice. 
>

Yeah, a service job might end up getting bin-packed onto the same node.  The [spread stanza](https://www.hashicorp.com/blog/spreads-and-affinites-in-nomad) was introduced to solve this. This job file below works for me every time in the scenario you described.

```hcl
job "contains-any" {
  datacenters = ["dc1"]
  type        = "service"

  constraint {
    attribute = "${meta.machine-role}"
    operator  = "set_contains_any"
    value     = "admin-server,network-server"
  }

  spread {
    attribute = "${attr.unique.hostname}"
  }

  group "cache" {
    count = 2

    network {
      port "db" {
        to = 6379
      }
    }

    task "redis" {
      driver = "docker"

      config {
        image = "redis:6.0"

        ports = ["db"]
      }

      resources {
        cpu    = 256
        memory = 128
      }
    }
  }
}
```

>The _distinct_host_ operator cannot be of use here as only one node is returned. The task actually needs to be deployed as a system job.
> 

Actually, I think _distinct_hosts_ can be of used here! It's designed to help spread workloads around. Did you know that constraints can stack?  I used the following jobspec and achieved exactly the desired results. First I'm saying filter to nodes with the desired `meta.machine-role` and then I'm saying  no more than 1 alloc on any of those matches . As long as my count is equal to the number of clients I know I've tagged with that `meta`, I'll get the desired result. 

```hcl
job "contains-any" {
  datacenters = ["dc1"]
  type        = "service"

  constraint {
    attribute = "${meta.machine-role}"
    operator  = "set_contains_any"
    value     = "admin-server,network-server"
  }

  constraint {
    operator  = "distinct_property"
    attribute = "${meta.machine-role}"
    value     = "1"
  }

  group "cache" {
    count = 2

    network {
      port "db" {
        to = 6379
      }
    }

    task "redis" {
      driver = "docker"

      config {
        image = "redis:6.0"

        ports = ["db"]
      }

      resources {
        cpu    = 256
        memory = 128
      }
    }
  }
}
```

> It is important to note that this deployment's purpose is to test a workload, meaning that this would not be permanent and would be repeated as many time as needed. The task in question is to deploy 2x telegraf instances on those 2 machines as a stress test will be performed for benchmarking purposes. But it could also be to test a workload on those machines before deploying it to others. Now, I could of course add another meta key/value and restart the services but this would not be the preferred practice. Especially not on a running infrastructure, even if its not a production environment and especially if I have to do that every time a new test is needed. This control should be defined at the nomad job spec level.
> 

Ah, thanks for sharing this detail of your use case!  Have you looked into Nomad's `Deployments` features? I feel like [Canary Deployments](https://learn.hashicorp.com/tutorials/nomad/job-blue-green-and-canary-deployments) are specifically designed to help with the scenario.

> This is why I really feel like the constraint stanza does need an _&&_ operator. To be honest, the _||_ operator is not that of a need here. It just feels natural to mention it in this context. Also, the `set_contains_any` is a partial match, _||_ would be an exact match. So I do see potential use cases.
> 
> What are your thoughts on this? Am I missing something?
> 
> Thank you again for taking the time to review this.

You're welcome!  My main thought is that I think we can achieve your goals using the features we have, and in multiple ways. A lot of thought has gone into the constraints, and they are pretty flexible already. Since we have multiple ways to achieve the desired goal, I think I'll close this issue. Feel free to re-open if you disagree.
