### ISSUE TITLE
Nomad exec websocket: close 1000 (normal)

### ISSUE THREAD

**Issue by surajthakur** [hashicorp/nomad#14595]
### Nomad version
Output from `nomad version`
```
Nomad v1.3.5
```
### Operating system and Environment details
- Debian 10

### Issue
Hi Community,
We are facing a small issue, thought someone would have come across already, so asking here first before raising a git issue.

I get kicked out of nomad exec after 10 mins and get this error

```
failed to exec into task: websocket closed before receiving exit code: websocket: close 1000 (normal)
```

To try with latest version, I have updated my local client version to latest

```
nomad -v
Nomad v1.3.5
```
But our the agent running on nomad cluster is still version `1.0.4`. We haven’t updated our cluster yet. Could that be an issue?

I am using these params when doing exec
```
nomad alloc exec -e none $ALLOCATION_ID /bin/bash
```
Any ideas what could be going wrong here ?

Thanks

**Comment by DerekStrickland** [comment]
Hi @surajthakur.  Thanks for reporting this issue.  From what you've shared with me this seems like an idle timeout.
This message `websocket: close 1000 (normal)` indicates to me that no traffic has been sent for a while, so the connection gets shut down.  Does this seem like what your are experiencing, or is this happening when you are actively interacting with the alloc?

**Comment by surajthakur** [comment]
Hi @DerekStrickland  
It's in both the cases, but the issue causing is someone already working gets kicked out and get this message. 
To link this to a recent change. We moved our infra from OVH cloud provider to AWS provider, but the architecture remains the same, we use HAproxy as our load balancer, same version of it running after the migration. 
If we can get some idea why `websocket: close 1000 (normal)` error occur, would be easy to troubleshoot.

**Comment by DerekStrickland** [comment]
Hi @surajthakur 

I ran an "idle" exec session this morning without a disconnect for over an hour and a half. Strictly speaking, it's not idle, since it turns out we are heart-beating.  Given the information you provided about the switch to AWS, I'd start to look there. I'm not sure which product you're connecting through, butI've heard of customers having to tune their session timeouts. A quick way to test and rule out Nomad would be to SSH into your infra and run an `alloc exec` session from inside and see if it times out.

For what it's worth, I did do a code exploration and here's what I can tell you:

- [This line](https://github.com/hashicorp/nomad/blob/0c3f64f7a3257156bf298222ac973e52418a38f4/api/allocations_exec.go#L215) is where the error bubbles up from the gorilla/websocket library that we use.
- That library is returning a `close 1000` which is defined as a ["normal closure"](https://www.rfc-editor.org/rfc/rfc6455#section-11.7)
- This indicates that whatever is happening is being detected/handled by that library and not Nomad. I realize that isn't super helpful so I kept digging.
- Nomad is calling [`websocket.Conn.ReadJSON`](https://github.com/gorilla/websocket/blob/af47554f343b4675b30172ac301638d350db34a5/json.go#L49) which calls [`websocket.Conn.NextReader`](https://github.com/gorilla/websocket/blob/af47554f343b4675b30172ac301638d350db34a5/conn.go#L998) which calls [`websocket.conn.advanceFrame`](https://github.com/gorilla/websocket/blob/af47554f343b4675b30172ac301638d350db34a5/conn.go#L794).
- `websocket.conn.advanceFrame` has numerous places that it could error, but based on what you are seeing, and that the value 1000 is a valid close code, I suspect [this is the handler](https://github.com/gorilla/websocket/blob/af47554f343b4675b30172ac301638d350db34a5/conn.go#L961) that is being triggered.
- If you really want to dig into what's going on beyond that, I think you'd have to modify that code to either log or enrich the error message somehow, but to be honest I don't think it's a code issue. Especially since this happened after an infrastructure provider swap. 

I'm going to go ahead and close this issue since it doesn't look like it's a bug.  If you feel that is incorrect, let us know. You can always re-open. Also, I'd suggest posting your on our [Discuss Forum](https://discuss.hashicorp.com/c/nomad/28) which is a great place to get input from other operators on issues related to specific infrastructure providers.
