### ISSUE TITLE
Dynamic node metadata

### ISSUE THREAD

**Issue by EtienneBruines** [hashicorp/nomad#14617]
### Proposal

Adding a `HTTP PUT` for `/v1/node/:node_id/meta` to update the metadata stanza of that node. 

Potential issues: what if the node reloads? Which metadata should be used? One solution would be to always use the "latest", e.g. upon reloading the file-config, using that which is defined. Ideally, the dynamic metadata would persist a reload/restart. 

### Use-cases

The end-goal would be to set dynamic properties for specific nodes, to micro-manage the job allocation process a bit. For example dynamically figuring out which nodes are acting as load-balancers / ingress, and then marking those nodes as such using the API without restarting nomad. (Mostly because restarting is VERY destructive, restarting/rescheduling all jobs that are present.)

That way, this metadata can be used by new jobs for scheduling (e.g. `affinity`). 

### Attempted Solutions

Manually tagging all nodes that might potentially end up being a load-balancer (and then restarting the nodes), but I'd rather not restart my nodes every time I change that metadata. 

An alternative solution (e.g. a different feature request, since this isn't possible as far as I know) to my use-case would be to reference other jobs in the `affinity` stanza. To tell it to "please allocate me next to this job", or "please do not allocate me next to that job". (Within the same namespace, I'd assume.) As a `constraint` that'd potentially cause issues, since then you could create mutually-dependent jobs - but for `affinity` that should be fine. 

Another alternative solution (that doesn't quite work yet) would be to support the metadata as part of `systemctl reload nomad`.

**Comment by lgfa29** [comment]
Thanks for the idea @EtienneBruines.

We've heard a few similar requests in the past. I placed the item for further scoping and roadmapping. We will let you know if have any further updates.

Thanks again!

**Comment by ostkrok** [comment]
We would also very much like to see this implemented for two reasons:

The first reason is essentially the same as EtienneBruines, i.e. being able to set meta programmatically in order to achieve better scheduling.

The other one is that we run Nomad clients on different hardware, which sometimes require different docker images/binaries for our jobs. We'd still like to use a single job file, and just set the docker image based on the client meta. There isn't really any problem for us to do this today (we think), other than that it feels a bit unnecessary to restart all of our Nomad clients when we want to update the version of a binary or docker image.

**Comment by cqueinnec** [comment]
I also had the need to update node metadata programmatically, and thought about a hack: have a Go [device plugin](https://www.nomadproject.io/docs/devices) which would fingerprint metadata stored locally. Metadata would appear as node attributes, which can also be used to set `constraints` on jobs. Updating node metadata would then be as easy as running a Nomad job to update local store.

**Comment by mikenomitch** [comment]
We have picked this feature up and plan to ship it as part of 1.5.

(Also FYI, I've updated the title to be a little bit broader)

**Comment by parkan** [comment]
how can I actually use this from my jobs? the commit message states that:

> Dynamic Node Metadata allows Nomad users, **and their jobs**, to update Node metadata through an API.

however I can only see the HTTP API and cli examples, not using it from a job spec

I need to do the same thing that the OP in this thread: schedule jobs on the same client as another job (in my case a an app and a backing DB need to be on the same machine as otherwise network latency kills our performance, but they can't be in a task group as that has unworkable semantics for peer task death)

it would of course be better to just have an direct way to do this with a task-task affinity, but the method listed here (tag client with a `meta` when it has the database job scheduled) seems like an ok compromise
