### ISSUE TITLE
Services with a task defined fails if there are tcp/http checks

### ISSUE THREAD

**Issue by dani** [hashicorp/nomad#14822]
For one of my job (to run a traefik instance), I need both native connect support (for traefik to reach the proxied services) and an Envoy sidecar (to expose two external services, LDAP and outbound web proxy which are required for traefik, and are reachable through a mesh terminating gateway). I used to do this by defining 2 services, one with connect = "native" and the other with a sidecar.

For this to work in Nomad 1.3, I had to define task = "traefik" in the connect native service, so Nomad could identify which task is using the native connect.

Attached is a sample / simplified job which used to run in Nomad 1.3, but now fails in Nomad 1.4.
[traefik-test.nomad.txt](https://github.com/hashicorp/nomad/files/9725549/traefik-test.nomad.txt)

The error with Nomad 1.4 is
```
Error submitting job: Unexpected response code: 500 (rpc error: 1 error occurred:
	* Task group traefik-test validation failed: 1 error occurred:
	* Task group service validation failed: 1 error occurred:
	* Check service: "traefik" check invalid: only script and gRPC checks should have tasks)
```

If I remove the task = "traefik" stanza from the traefik service, the job fails with
```
Error submitting job: Unexpected response code: 500 (rpc error: error in job mutator connect: task for Consul Connect Native service traefik-test->traefik is ambiguous and must be set)
```
This was already the case in Nomad 1.3, and was the reason I've added task = "traefik".

Now in Nomad 1.4 I have to either

- Run without any test
- Run with script tests, which would be really suboptimal

**Comment by gmichalec-pandora** [comment]
I'll also add that the documentation for task does not indicate it cannot be used for non-grpc/script checks: 
>[task](https://developer.hashicorp.com/nomad/docs/job-specification/service#task-1) (string: "") - Specifies the name of the Nomad task associated with this service definition. Only available on group services. Must be set if this service definition represents a Consul Connect-native service and there is more than one task in the task group.

This also is not mentioned in the upgrade guide. We have lots of service definitions that specify a task. Is there a reason why having a task specified in a regular health check is an error vs a warning?

**Comment by maxramqvist** [comment]
I see the same issue with checks for "http"-services on the task-level on Nomad 1.4.1. Worked fine on 1.3.5.
```
Task group cats validation failed: 1 error occurred:
	* Task group service validation failed: 1 error occurred:
	* Check service: "cats" check invalid: only script and gRPC checks should have tasks
``` 
The check is under the Services level and im running Connect, not native.

**Comment by dani** [comment]
Indeed, the problem is not strictly with native connect. Just more visible because when using native connect and you have several tasks in a group, you must set task = "XXX" at the service level.

**Comment by maxramqvist** [comment]
For anyone hitting this issue and using JSON in their Nomad jobs.

Try just removing `TaskName` from the `Services` part of your job definition.

**Comment by tgross** [comment]
Hi @dani! I was able to reproduce this pretty easily with the example job you provided, so thanks for providing that.

```
$ nomad plan example.nomad
Error during plan: Unexpected response code: 500 (1 error occurred:
        * Task group traefik-test validation failed: 1 error occurred:
        * Task group service validation failed: 1 error occurred:
        * Check service: "traefik" check invalid: only script and gRPC checks should have tasks)
```

The reason we make that check that only script/gRPC checks have `task` set is because it's meaningless to have `task` set for a HTTP check -- the check gets sent to a _port_, not to a _task_. I'm not super familiar with why the Connect Native requires a task.

We added checks to Nomad native service discovery in Nomad 1.4.0, so I did a `git bisect` session to see if I could find where the problem was introduced. After each step I built Nomad, ran it in `-dev` mode, and then ran `nomad plan example.nomad` to see if the error above was hit again.


<details><summary>git bisect session</summary>

```
$ git bisect start
status: waiting for both good and bad commits
$ git bisect bad
status: waiting for good commit(s), bad commit known
$ git bisect good v1.3.6
Bisecting: a merge base must be tested
[4d404b3958aceea5b3cf746f632f4dcf01e276c2] Merge pull request #12740 from hashicorp/cleanup-makefile-help
$ git bisect good
Bisecting: 427 revisions left to test after this (roughly 9 steps)
[1a6880e05e3b0077f8d426b6643d104435991311] chore(deps): bump github.com/hashicorp/consul/api from 1.13.0 to 1.13.1
$ git bisect good
Bisecting: 213 revisions left to test after this (roughly 8 steps)
[3a4345ef328bbef941ad4e6617a87576e2cbdb82] docs: clarify CSI plugin compatibility (#14434)
$ git bisect bad
Bisecting: 106 revisions left to test after this (roughly 7 steps)
[934bafb9229b4aca7edcafcf995f62005c8510d6] template: use pointer values for gid and uid (#14203)
$ git bisect bad
Bisecting: 53 revisions left to test after this (roughly 6 steps)
[f6c5700b08e279ec5737ce349528b4c144702029] Merge pull request #14104 from hashicorp/f-consistent-makefile-arrows
$ git bisect bad
Bisecting: 26 revisions left to test after this (roughly 5 steps)
[0eb21949245b0e38b7a2ea22c9f64fee9120e68d] Update index.mdx
$ git bisect bad
Bisecting: 13 revisions left to test after this (roughly 4 steps)
[6b4de8cc6637e74eaacee4b4527d4534dae68c03] ui:  handle error messages for when filtering doesn't return matches (#14048)
$ git bisect bad
Bisecting: 6 revisions left to test after this (roughly 3 steps)
[279631eeb56ef7d722095fbcc6997db1d75711d4] Sweep of docs for repeated words; minor edits (#14032)
$ git bisect good
Bisecting: 2 revisions left to test after this (roughly 2 steps)
[312ee450c4ec87f07060f641689590a55f47f025] Merge pull request #14033 from hashicorp/f-plumb-task-names
$ git bisect bad
Bisecting: 1 revision left to test after this (roughly 1 step)
[ea3f4cd1f109bc9ece8963f10316543ba3b1cb59] Merge pull request #14026 from hashicorp/docs-tweak-readme
$ git bisect good
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[d6cb8927887623513cf2b0d0d3448b6687af388d] core: automatically plumb task name into task-level services and checks
```

</details>


That narrowed it down to https://github.com/hashicorp/nomad/commit/d6cb8927887623513cf2b0d0d3448b6687af388d which seems innocuous but definitely touches the validation code path. It also ensures that a service has an associated task name if it's not associated with the group.

The original PR https://github.com/hashicorp/nomad/pull/14033 includes this note:

> The jobspec validation needs to loosen up a bit - such that we accept setting the task name but only if it actually matches the task in which that service/check exists in.

But there may be additional validation changes we need to do here. I've pushed up a PR https://github.com/hashicorp/nomad/pull/14849 that in my testing here fixes the immediate problem. I'm going to get my colleagues @shoenig @jrasell to take a look at that change and see if I'm wildly off base, but just a fair warning a bunch of folks are traveling this week and so the PR review might not be done right away. You're welcome to build Nomad from source (`make bootstrap; make dev`) and help test though!

**Comment by tgross** [comment]
Hi @dani! I was able to reproduce this pretty easily with the example job you provided, so thanks for providing that.

```
$ nomad plan example.nomad
Error during plan: Unexpected response code: 500 (1 error occurred:
        * Task group traefik-test validation failed: 1 error occurred:
        * Task group service validation failed: 1 error occurred:
        * Check service: "traefik" check invalid: only script and gRPC checks should have tasks)
```

The reason we make that check that only script/gRPC checks have `task` set is because it's meaningless to have `task` set for a HTTP check -- the check gets sent to a _port_, not to a _task_. I'm not super familiar with why the Connect Native requires a task.

We added checks to Nomad native service discovery in Nomad 1.4.0, so I did a `git bisect` session to see if I could find where the problem was introduced. After each step I built Nomad, ran it in `-dev` mode, and then ran `nomad plan example.nomad` to see if the error above was hit again.


<details><summary>git bisect session</summary>

```
$ git bisect start
status: waiting for both good and bad commits
$ git bisect bad
status: waiting for good commit(s), bad commit known
$ git bisect good v1.3.6
Bisecting: a merge base must be tested
[4d404b3958aceea5b3cf746f632f4dcf01e276c2] Merge pull request #12740 from hashicorp/cleanup-makefile-help
$ git bisect good
Bisecting: 427 revisions left to test after this (roughly 9 steps)
[1a6880e05e3b0077f8d426b6643d104435991311] chore(deps): bump github.com/hashicorp/consul/api from 1.13.0 to 1.13.1
$ git bisect good
Bisecting: 213 revisions left to test after this (roughly 8 steps)
[3a4345ef328bbef941ad4e6617a87576e2cbdb82] docs: clarify CSI plugin compatibility (#14434)
$ git bisect bad
Bisecting: 106 revisions left to test after this (roughly 7 steps)
[934bafb9229b4aca7edcafcf995f62005c8510d6] template: use pointer values for gid and uid (#14203)
$ git bisect bad
Bisecting: 53 revisions left to test after this (roughly 6 steps)
[f6c5700b08e279ec5737ce349528b4c144702029] Merge pull request #14104 from hashicorp/f-consistent-makefile-arrows
$ git bisect bad
Bisecting: 26 revisions left to test after this (roughly 5 steps)
[0eb21949245b0e38b7a2ea22c9f64fee9120e68d] Update index.mdx
$ git bisect bad
Bisecting: 13 revisions left to test after this (roughly 4 steps)
[6b4de8cc6637e74eaacee4b4527d4534dae68c03] ui:  handle error messages for when filtering doesn't return matches (#14048)
$ git bisect bad
Bisecting: 6 revisions left to test after this (roughly 3 steps)
[279631eeb56ef7d722095fbcc6997db1d75711d4] Sweep of docs for repeated words; minor edits (#14032)
$ git bisect good
Bisecting: 2 revisions left to test after this (roughly 2 steps)
[312ee450c4ec87f07060f641689590a55f47f025] Merge pull request #14033 from hashicorp/f-plumb-task-names
$ git bisect bad
Bisecting: 1 revision left to test after this (roughly 1 step)
[ea3f4cd1f109bc9ece8963f10316543ba3b1cb59] Merge pull request #14026 from hashicorp/docs-tweak-readme
$ git bisect good
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[d6cb8927887623513cf2b0d0d3448b6687af388d] core: automatically plumb task name into task-level services and checks
```

</details>


That narrowed it down to https://github.com/hashicorp/nomad/commit/d6cb8927887623513cf2b0d0d3448b6687af388d which seems innocuous but definitely touches the validation code path. It also ensures that a service has an associated task name if it's not associated with the group.

The original PR https://github.com/hashicorp/nomad/pull/14033 includes this note:

> The jobspec validation needs to loosen up a bit - such that we accept setting the task name but only if it actually matches the task in which that service/check exists in.

But there may be additional validation changes we need to do here. I've pushed up a PR https://github.com/hashicorp/nomad/pull/14849 that in my testing here fixes the immediate problem. I'm going to get my colleagues @shoenig @jrasell to take a look at that change and see if I'm wildly off base, but just a fair warning a bunch of folks are traveling this week and so the PR review might not be done right away. You're welcome to build Nomad from source (`make bootstrap; make dev`) and help test though!

**Comment by tgross** [comment]
Hi @dani! I was able to reproduce this pretty easily with the example job you provided, so thanks for providing that.

```
$ nomad plan example.nomad
Error during plan: Unexpected response code: 500 (1 error occurred:
        * Task group traefik-test validation failed: 1 error occurred:
        * Task group service validation failed: 1 error occurred:
        * Check service: "traefik" check invalid: only script and gRPC checks should have tasks)
```

The reason we make that check that only script/gRPC checks have `task` set is because it's meaningless to have `task` set for a HTTP check -- the check gets sent to a _port_, not to a _task_. I'm not super familiar with why the Connect Native requires a task.

We added checks to Nomad native service discovery in Nomad 1.4.0, so I did a `git bisect` session to see if I could find where the problem was introduced. After each step I built Nomad, ran it in `-dev` mode, and then ran `nomad plan example.nomad` to see if the error above was hit again.


<details><summary>git bisect session</summary>

```
$ git bisect start
status: waiting for both good and bad commits
$ git bisect bad
status: waiting for good commit(s), bad commit known
$ git bisect good v1.3.6
Bisecting: a merge base must be tested
[4d404b3958aceea5b3cf746f632f4dcf01e276c2] Merge pull request #12740 from hashicorp/cleanup-makefile-help
$ git bisect good
Bisecting: 427 revisions left to test after this (roughly 9 steps)
[1a6880e05e3b0077f8d426b6643d104435991311] chore(deps): bump github.com/hashicorp/consul/api from 1.13.0 to 1.13.1
$ git bisect good
Bisecting: 213 revisions left to test after this (roughly 8 steps)
[3a4345ef328bbef941ad4e6617a87576e2cbdb82] docs: clarify CSI plugin compatibility (#14434)
$ git bisect bad
Bisecting: 106 revisions left to test after this (roughly 7 steps)
[934bafb9229b4aca7edcafcf995f62005c8510d6] template: use pointer values for gid and uid (#14203)
$ git bisect bad
Bisecting: 53 revisions left to test after this (roughly 6 steps)
[f6c5700b08e279ec5737ce349528b4c144702029] Merge pull request #14104 from hashicorp/f-consistent-makefile-arrows
$ git bisect bad
Bisecting: 26 revisions left to test after this (roughly 5 steps)
[0eb21949245b0e38b7a2ea22c9f64fee9120e68d] Update index.mdx
$ git bisect bad
Bisecting: 13 revisions left to test after this (roughly 4 steps)
[6b4de8cc6637e74eaacee4b4527d4534dae68c03] ui:  handle error messages for when filtering doesn't return matches (#14048)
$ git bisect bad
Bisecting: 6 revisions left to test after this (roughly 3 steps)
[279631eeb56ef7d722095fbcc6997db1d75711d4] Sweep of docs for repeated words; minor edits (#14032)
$ git bisect good
Bisecting: 2 revisions left to test after this (roughly 2 steps)
[312ee450c4ec87f07060f641689590a55f47f025] Merge pull request #14033 from hashicorp/f-plumb-task-names
$ git bisect bad
Bisecting: 1 revision left to test after this (roughly 1 step)
[ea3f4cd1f109bc9ece8963f10316543ba3b1cb59] Merge pull request #14026 from hashicorp/docs-tweak-readme
$ git bisect good
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[d6cb8927887623513cf2b0d0d3448b6687af388d] core: automatically plumb task name into task-level services and checks
```

</details>


That narrowed it down to https://github.com/hashicorp/nomad/commit/d6cb8927887623513cf2b0d0d3448b6687af388d which seems innocuous but definitely touches the validation code path. It also ensures that a service has an associated task name if it's not associated with the group.

The original PR https://github.com/hashicorp/nomad/pull/14033 includes this note:

> The jobspec validation needs to loosen up a bit - such that we accept setting the task name but only if it actually matches the task in which that service/check exists in.

But there may be additional validation changes we need to do here. I've pushed up a PR https://github.com/hashicorp/nomad/pull/14849 that in my testing here fixes the immediate problem. I'm going to get my colleagues @shoenig @jrasell to take a look at that change and see if I'm wildly off base, but just a fair warning a bunch of folks are traveling this week and so the PR review might not be done right away. You're welcome to build Nomad from source (`make bootstrap; make dev`) and help test though!

**Comment by tgross** [comment]
Hi @dani! I was able to reproduce this pretty easily with the example job you provided, so thanks for providing that.

```
$ nomad plan example.nomad
Error during plan: Unexpected response code: 500 (1 error occurred:
        * Task group traefik-test validation failed: 1 error occurred:
        * Task group service validation failed: 1 error occurred:
        * Check service: "traefik" check invalid: only script and gRPC checks should have tasks)
```

The reason we make that check that only script/gRPC checks have `task` set is because it's meaningless to have `task` set for a HTTP check -- the check gets sent to a _port_, not to a _task_. I'm not super familiar with why the Connect Native requires a task.

We added checks to Nomad native service discovery in Nomad 1.4.0, so I did a `git bisect` session to see if I could find where the problem was introduced. After each step I built Nomad, ran it in `-dev` mode, and then ran `nomad plan example.nomad` to see if the error above was hit again.


<details><summary>git bisect session</summary>

```
$ git bisect start
status: waiting for both good and bad commits
$ git bisect bad
status: waiting for good commit(s), bad commit known
$ git bisect good v1.3.6
Bisecting: a merge base must be tested
[4d404b3958aceea5b3cf746f632f4dcf01e276c2] Merge pull request #12740 from hashicorp/cleanup-makefile-help
$ git bisect good
Bisecting: 427 revisions left to test after this (roughly 9 steps)
[1a6880e05e3b0077f8d426b6643d104435991311] chore(deps): bump github.com/hashicorp/consul/api from 1.13.0 to 1.13.1
$ git bisect good
Bisecting: 213 revisions left to test after this (roughly 8 steps)
[3a4345ef328bbef941ad4e6617a87576e2cbdb82] docs: clarify CSI plugin compatibility (#14434)
$ git bisect bad
Bisecting: 106 revisions left to test after this (roughly 7 steps)
[934bafb9229b4aca7edcafcf995f62005c8510d6] template: use pointer values for gid and uid (#14203)
$ git bisect bad
Bisecting: 53 revisions left to test after this (roughly 6 steps)
[f6c5700b08e279ec5737ce349528b4c144702029] Merge pull request #14104 from hashicorp/f-consistent-makefile-arrows
$ git bisect bad
Bisecting: 26 revisions left to test after this (roughly 5 steps)
[0eb21949245b0e38b7a2ea22c9f64fee9120e68d] Update index.mdx
$ git bisect bad
Bisecting: 13 revisions left to test after this (roughly 4 steps)
[6b4de8cc6637e74eaacee4b4527d4534dae68c03] ui:  handle error messages for when filtering doesn't return matches (#14048)
$ git bisect bad
Bisecting: 6 revisions left to test after this (roughly 3 steps)
[279631eeb56ef7d722095fbcc6997db1d75711d4] Sweep of docs for repeated words; minor edits (#14032)
$ git bisect good
Bisecting: 2 revisions left to test after this (roughly 2 steps)
[312ee450c4ec87f07060f641689590a55f47f025] Merge pull request #14033 from hashicorp/f-plumb-task-names
$ git bisect bad
Bisecting: 1 revision left to test after this (roughly 1 step)
[ea3f4cd1f109bc9ece8963f10316543ba3b1cb59] Merge pull request #14026 from hashicorp/docs-tweak-readme
$ git bisect good
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[d6cb8927887623513cf2b0d0d3448b6687af388d] core: automatically plumb task name into task-level services and checks
```

</details>


That narrowed it down to https://github.com/hashicorp/nomad/commit/d6cb8927887623513cf2b0d0d3448b6687af388d which seems innocuous but definitely touches the validation code path. It also ensures that a service has an associated task name if it's not associated with the group.

The original PR https://github.com/hashicorp/nomad/pull/14033 includes this note:

> The jobspec validation needs to loosen up a bit - such that we accept setting the task name but only if it actually matches the task in which that service/check exists in.

But there may be additional validation changes we need to do here. I've pushed up a PR https://github.com/hashicorp/nomad/pull/14849 that in my testing here fixes the immediate problem. I'm going to get my colleagues @shoenig @jrasell to take a look at that change and see if I'm wildly off base, but just a fair warning a bunch of folks are traveling this week and so the PR review might not be done right away. You're welcome to build Nomad from source (`make bootstrap; make dev`) and help test though!

**Comment by dani** [comment]
Thanks for your time and the analysis. I'm unsure if this check should be loosen only for connect enabled service. IMHO, if a task is set at the service level, it should just be ignored for tcp/http checks (it's meaningless, but armless). What if I have say 10 scripts check, and 1 tcp check for a service ? It makes more sense to define the task once at the service level, so all my 10 script checks inherit it, and the single tcp check just ignores it.

**Comment by shoenig** [comment]
I'm starting to agree with that idea @dani; IIRC the assertion on `task` was only ever about minimization rather than functionality. As we add more functionality that assertion is just causing latent bugs. 

> I'm not super familiar with why the Connect Native requires a task.

When there is more than 1 task in the group, we need to know into which task environment to set the `connectNativeHook`.
