### ISSUE TITLE
Support ip / virtual ip per task group

### ISSUE THREAD

**Issue by F21** [hashicorp/nomad#149]
In kubernetes, there is the idea of services. Essentially, it assigns a virtual ip (from a range) to each task launched in the cluster.

This means, that if we launch task, we do not have to ask nomad to dynamically assign a port, or force it to assign a port and hope it exists. Since each task has a virtual ip, we can access all http services on 80, https on 443, etc.

**Comment by mgenov** [comment]
+1

**Comment by troyswanson** [comment]
I could be completely off base here, but isn't this what Consul is about?

**Comment by jayunit100** [comment]
My understanding is as follows.

- Consul does have a registration functionality which is sort of similar to kube services : nodes can say they provide a service and then be discovered as necessary.
- Meanwhile, kube services find labelled pods and load balance across them.  

So:

- You could **sort of** build your own cabernets on top of consul and docker, I think 
- but of course you'd be missing the scheduling functionality, which gaurantees that a certain replication level of those services is online.

This is an interesting issue - because it helps to define how the emerging hashicorp ecosystem of distributed computing tools will live alongside what is provided in the kubernetes world.

**Comment by F21** [comment]
@jayunit100 is pretty much correct. However, if you use services, you would not lose any scheduling functionality. 

In most cases you would schedule your services using a replication controller. This would set up the constraints, number of instances etc for your pods.

You would then set up labels for those running containers and then add a service that will load balance the appropriate pods by matching their labels.

The benefits are tremendous, because each service is assigned a virtual ip, so we do not need to assign "weird" port numbers and discover they by talking to the consul api. Hitting port 80 on a virtual ip (for a service) will always be a http service (if you set up your pods to run http on 80).

**Comment by jayunit100** [comment]
Hmmm.. Is this about Kube or nomad? I think I see what you mean but seems like we are talking more about kubernetes specific components now....

**Comment by F21** [comment]
My response was regarding kubernetes.

Anyway, the point of this issue is to hopefully have some sort of service/load balancer ala kubernetes in nomad.

**Comment by armon** [comment]
With Nomad, the approach as mentioned will be to lean on Consul. Consul gives a service a logical name like "foo.service.consul". Load balancing is done automatically via DNS, or Consul-template can be used with an LB.

We don't plan on incorporating virtual networking directly into Nomad. However, we can support IP-per-task in IPv6 very naturally since each machine has a large block of IPs available.

**Comment by F21** [comment]
@armon Any ETA for when this ip-per-task feature? I think that coupled with consul for discovery, health checks and load balancing would be a really awesome and powerful combination.

**Comment by armon** [comment]
The main things needed to support it are already done. However, the bigger issue is that IPv6 is not broadly supported in datacenters.

**Comment by c4milo** [comment]
I applaude the decision of keeping Nomad simple! I don't think baking everything inside Nomad is the way to go either. I can see how one could make the load balancer part of the tasks of a job, with consul-template to update backend servers. It is a much more cleaner and modular approach compared to that of K8s.

**Comment by F21** [comment]
What's the nomad team's view on how this would be implemented? Docker has landed overlay networking support in 1.9. Qemu and other executors would still need coordination by nomad. I am assuming nomad will not manage the overlay networking component of docker and we are expected to have that configured outside of nomad, right?

**Comment by pires** [comment]
> the bigger issue is that IPv6 is not broadly supported in datacenters.

Indeed :-1: 

Personally, and having run Kubernetes in production, I agree _Service_ is an interesting concept that just works. However, if one's looking to provide more powerful load-balancing techniques or remove the extra hop, one needs to query and watch the Kubernetes API for service changes. How does this differ from querying and watching the Consul _catalog_ API?

Now, what Kubernetes provides that I'm a big fan is [`cloud-providers`](https://github.com/kubernetes/kubernetes/tree/master/pkg/cloudprovider) API and a few key implementations for anyone to use or implement their own stuff.
I'd like to see something like that. Then, I could implement my own load-balancing Nomad jobs.

Disclaimer: I am currently doing this for GCE.

**Comment by nickethier** [comment]
Nomad 0.10 brings shared network namespaces for tasks within a task group. This enables each allocation to have their own isolated network stack. Nomad 0.10 brings the [bridge networking mode](https://www.nomadproject.io/docs/job-specification/network.html#bridge) and further customization of the network will be possible with CNI in a future release. With that, I'm going to close this issue. There is alot of discussion here so for any edge use cases that this does not cover please feel free to open a new issue.
