### ISSUE TITLE
Unable to delete external volume because of special character in secret key/value pair

### ISSUE THREAD

**Issue by digi-talo** [hashicorp/nomad#15663]
### Nomad version
Output from `v1.4.3`

### Operating system and Environment details
Debian buster -  3 node dev environment running both server and client mode

### Issue

Can't delete an external storage volumes because the `adminKey` contains an `=` sign.

### Reproduction steps

`nomad volume delete -secret adminID=csiAdmin -secret adminKey=xxxxxxxxxxxxxxxxxx== vol-test`

Using quotes around the key=value renders the same result. There seems to be no way to have the value correctly interpreted when it contains an equal sign.
When I remove the equal signs from the adminKey I get a rados authentication error as expected.

#### Expected Result

Deleted volume

#### Actual Result

`Secret must be in the format: -secret key=value`

**Comment by tgross** [comment]
Hi @digi-talo! This looks like a bug in the command line parsing of the k/v format. See [`volume_delete.go#L105-L114`](https://github.com/hashicorp/nomad/blob/v1.4.3/command/volume_delete.go#L105-L114) but it looks like we have the exact same bug in `volume snapshot create`, `volume snapshot list`, and `volume snapshot delete` as well.

The fix for this should be straightforward: we need to grab only the first `=` and not the rest of them. I'll try to get a patch up shortly for this.
