### ISSUE TITLE
Broken links in index.mdx

### ISSUE THREAD

**Issue by Jupiter-Nomad** [hashicorp/nomad#15705]
Following index.mdx links are broken and lead to 404. 

[Quickstart](https://github.com/hashicorp/nomad/blob/main/docs/install/quickstart)

[precompiled binary](https://github.com/hashicorp/nomad/blob/main/downloads)

**Comment by lgfa29** [comment]
Hi @Jupiter-Nomad 👋 

Which links are you referring to? Could you link to the page where you noticed these broken links? 

Thanks!

**Comment by Jupiter-Nomad** [comment]
Hi @lgfa29,

https://github.com/hashicorp/nomad/blob/a8b8892388bd51c4b688ab57eacd3f8b18a50172/website/content/docs/install/index.mdx

Thanks for looking into it.

**Comment by lgfa29** [comment]
Thanks for the extra info.

Are you accessing the files directly from the Markdown source? The file you linked is the source for our website, so the links are not expected to work if not viewed there. 

The page you linked is https://developer.hashicorp.com/nomad/docs/install, which does have working links.

I'm going to close this one for now since this is expected, but let me know if I'm missing something 🙂

**Comment by Jupiter-Nomad** [comment]
I see, yes I was accessing them from github directly, not the site itself.Sorry for the confusion.

**Comment by lgfa29** [comment]
No worries, glad you're able to ready it properly now.
