### ISSUE TITLE
Support for SMB File Share in Artifacts stanza

### ISSUE THREAD

**Issue by apkrymov** [hashicorp/nomad#15725]
### Proposal

I'd like to download [artifacts ](https://developer.hashicorp.com/nomad/docs/job-specification/artifact)directly from SMB File Shares.

### Use-cases

* Enterprise file shares

### Attempted Solutions

* Put an HTTP server in front of the file storage -> Expensive to support
* Lifecycle Init Task Pattern with custom downloader -> Overcomplicated Job config

### Research

Feature already implemented in [go-getter](https://github.com/hashicorp/go-getter) (v2.0.0+) by hashicorp/go-getter#255
It`s absolutely safe (considering the known issue #1897) because of https://github.com/hashicorp/go-getter/pull/240#discussion_r415768795

### Steps to achieve
- [ ] Bump [go-getter to v2.1.1](https://github.com/hashicorp/go-getter/releases/tag/v2.1.1)
- [ ] Fix breaking changes in go-getter API
- [ ] [Add SMB handler](https://github.com/hashicorp/nomad/blob/main/client/allocrunner/taskrunner/getter/params.go#L146)

**Comment by tgross** [comment]
Hi @apkrymov! I'm not sure how https://github.com/hashicorp/go-getter/pull/240#discussion_r415768795 actually resolves the problems that @schmichael raised. Just because that's the customary way of getting files on Windows doesn't mean it's any less of a problem for all the same reasons that accessing local files would be on Unix systems. I don't think we're inclined to make this change without more discussion about why it might be safe (or safe only on Windows? It's unclear whether that's you're argument here).

**Comment by tgross** [comment]
It's been a month without a reply asking for clarification, and it doesn't look like the go-getter feature can address the security concerns here. Closing this out.
