### ISSUE TITLE
`nomad fmt -check` flag doesn't return error code

### ISSUE THREAD

**Issue by WebLeash** [hashicorp/nomad#15740]
I'm using nomad verision v1.4.2
$ nomad --version
Nomad **v1.4.2** (039d70eeef5888164cad05e7ddfd8b6f8220923b)

https://developer.hashicorp.com/nomad/docs/commands/fmt#check
The documentation says it will not change and return value 1.
Observing the behaviour this doesn't look to be working. 

I want to fail our CI process if the nomad **fmt** command detects any issue with the source file (HCL).

Currently the output of the _$ nomad fmt -check_ command lists the file in the output and returns 0 value to the shell if issues with formatting detected. 

 $ nomad fmt -check   http.nomad
http.nomad
$ echo $?
0

**Comment by tgross** [comment]
Hi @WebLeash! Yup, I just checked the source and we're completely ignoring that argument. Embarrassing for me because I reviewed that PR https://github.com/hashicorp/nomad/pull/14779 :blush: 

I'm going to reword the title a bit here and mark this as a bug to get fixed. We'd also be happy to review a patch if you want to have a go at one.

**Comment by dttung2905** [comment]
Hi @tgross I can help with this.
