### ISSUE TITLE
Refresh option for artifactes from s3

### ISSUE THREAD

**Issue by suikast42** [hashicorp/nomad#15917]
I uploaded a template file to my local minio installation and refrence it over artifact stanza like this:
```hcl
artifact {
   source  = "s3://minio.cloud.private/test/test.tpl"
   mode= "file"
   destination = "local/test.tpl"
  options {
    aws_access_key_id     = "<key>"
    aws_access_key_secret = "<sec>"
  }
}

    template {
      change_mode   = "restart"
      right_delimiter = "++"
      left_delimiter = "++"
      source        = "local/test.tpl"
      destination = "local/test.txt"
    }
```

But  I don't see an option like a refresh or check for file changes on the template form s3 bucket.

**Comment by lgfa29** [comment]
Hi @suikast42 👋 

In Nomad the job file is the kind of the source of truth, so anything that you would like to cause a redeployment needs to cause the job file to change. 

For artifacts the best way to do this is to use [checksums](https://github.com/hashicorp/go-getter#checksumming) in your artifacts, that way you will need to update the job file when the artifact changes. Using the checksum has the added benefit of protecting your workloads from file corruption during transit.

Does this fit your needs?

**Comment by suikast42** [comment]
> Does this fit your needs?

That make sense. Thanks for clarification. 


Alternatively  for holding the job file slim as possible I find a way to read the template file from a relative path to the nomad job file.


I think this is worth documenting, isn't it?

```hcl

    template {
      change_mode   = "restart"
      data = file(abspath("./configs/my.tpl"))
      destination = "local/my.yml"
    }
```

**Comment by lgfa29** [comment]
Ah interesting! I think the problem with that approach is that it's not quite applicable in many scenarios since it requires access to the file system and the file itself, and this is often not the case:

> Functions are evaluated by the CLI during configuration parsing rather than job run time, so this function can only be used with files that are already present on disk on operator host.

In general we either recommend keeping the job file as the full source of truth (meaning having the file content directly in the jobspec) or fetching it from a remote source using an `artifact` (with checksuming to detect changes).

But I'm glad this works well for your need!

I'm going to close this one for now, but let me know if there's anything else missing 🙂
