### ISSUE TITLE
java application on docker cannot calculate reserved CPU after JDK-8281181

### ISSUE THREAD

**Issue by iadllabagnara** [hashicorp/nomad#16476]
In versions 18.0.2+, 17.0.5+ and 11.0.17+, OpenJDK will no longer take CPU shares settings into account for its calculation of available CPU cores. See [JDK-8281181](https://bugs.openjdk.java.net/browse/JDK-8281181) for details.

### Proposal
It seems the simplest way is to add `cpu-quota` options in Resource block and use it in docker command launched by nomad.

### Attempted Solutions
In versions 18.0.2+, 17.0.5+ and 11.0.17+, they add `-XX:+UseContainerCpuShares` JVM flags but it is already deprecated and it will be removed on version 20+.

```
# Without -XX:+UseContainerCpuShares flag on 16-cores server
$ java -XshowSettings:system -version
Operating System Metrics:
    Provider: cgroupv1
    Effective CPU Count: 16
 
# With -XX:+UseContainerCpuShares flag on 16-cores server
$ java -XX:+UseContainerCpuShares -XshowSettings:system -version
Operating System Metrics:
    Provider: cgroupv1
    Effective CPU Count: 2
```

In versions 20+, we need to use `-XX:ActiveProcessorCount` or add `--cpus` flag on docker command.

Useful link to understand JVM active process count: https://developers.redhat.com/articles/2022/04/19/java-17-whats-new-openjdks-container-awareness#opinionated_configuration

**Comment by tgross** [comment]
I don't have an immediate long-term solution here but wanted to leave a note that the value of `resource.cpu` and `resource.cores` are exposed as environment variables. So the application could use `$NOMAD_CPU` or `$NOMAD_CORES` environment variables as values to configure the JVM. We don't actually schedule based on "cores" unless you've passed `resource.cores`, so configuring `--cpus` would be incorrect without that.

(Frankly, it's totally incorrect to map cpu shares to "cores" the way the JDK is doing because that's not what a cpu share is and there is such a thing as big.LITTLE to contend with these days. But I realize that we can't change the JVM :grin: )

**Comment by tgross** [comment]
I just spun up a Docker container on Nomad to check and it looks like the env vars are actually `NOMAD_CPU_LIMIT` and `NOMAD_CPU_CORES`, which is exactly what's documented in [Runtime Environment](https://developer.hashicorp.com/nomad/docs/runtime/environment#job-related-variables) so I dunno why I told you the wrong thing there. :facepalm:
