### ISSUE TITLE
Upgrading from v1.4.3 to v1.5.1: Nomad Job that uses a remote artifact, that requires SSH auth fails after upgrade

### ISSUE THREAD

**Issue by CarelvanHeerden** [hashicorp/nomad#16477]
### Nomad version
v1.5.1

### Operating system and Environment details
Ubuntu 20.04

### Issue
A Nomad job, that downloads artifacts from Gitlab using SSH auth, that was working fails after the upgrade to v1.5.1

### Reproduction steps
Nomad job, that has an artifact block that requires SSH auth fails after upgrade

#### Expected Result
Nomad Job to Continue as per normal

#### Actual Result
Job Fails
```
msg="failed to download artifact \"git::git@gitlab.com:xxxxxxxxxxxx.git\": getter subprocess failed: exit status 1" 
```

### Job file
Removed some tags that are not relevant
```
job "JOB" {
  type = "batch"
    periodic {
    cron = "5 10 * * 2"
    prohibit_overlap = true
  }

  group "JOB" {
    count = 1
    task "JOB" {
      driver = "docker"


      artifact {
          source      = "git::git@gitlab.com:XXXXXXXXXX.git"
          destination = "local/repo"
          options {
            ref = "main"
            depth = 1
            sshkey = "${ID_RSA_BASE64}"
          }
        }

      config {
        image        = "dockerrepo/XXXX/docker:${DOCKER_VERSION}"
        force_pull = "false"
        auth {
          username = "XXXXXXX"
          password = "${DOCKER_REPO_TOKEN}"
        }

        dns_servers = ["$${attr.unique.network.ip-address}"]

        volumes = [
          "local/repo:/tmp",
        ]

      }


      resources {
        cpu    = 1024
        memory = 2056

        network {
        }
      }
    }
  }
}


```

### Nomad Client logs 
```
Mar 14 11:43:38 nomad-client-secure00000V nomad[2878]:     2023-03-14T11:43:38.109Z [INFO]  client.alloc_runner.task_runner: Task event: alloc_id=901ad884-9552-2228-aa74-10cbe023a856 task=Ansible-CIS type="Downloading Artifacts" msg="Client is downloading artifacts" failed=false
Mar 14 11:43:38 nomad-client-secure00000V nomad[2878]:     2023-03-14T11:43:38.868Z [ERROR] client.artifact: sub-process: OUTPUT="failed to download artifact: error downloading 'ssh://git@gitlab.com/xxxxxxxxxxxx.git?depth=1&ref=main&sshkey=redacted': /usr/bin/git exited with 128: Cloning into '/opt/nomad/alloc/901ad884-9552-2228-aa74-10cbe023a856/JOB/local/repo'..."
Mar 14 11:43:38 nomad-client-secure00000V nomad[2878]:     2023-03-14T11:43:38.869Z [ERROR] client.artifact: sub-process: OUTPUT="warning: templates not found in /usr/share/git-core/templates"
Mar 14 11:43:38 nomad-client-secure00000V nomad[2878]:     2023-03-14T11:43:38.869Z [ERROR] client.artifact: sub-process: OUTPUT="No user exists for uid 65534"
Mar 14 11:43:38 nomad-client-secure00000V nomad[2878]:     2023-03-14T11:43:38.869Z [ERROR] client.artifact: sub-process: OUTPUT="fatal: Could not read from remote repository."
Mar 14 11:43:38 nomad-client-secure00000V nomad[2878]:     2023-03-14T11:43:38.869Z [ERROR] client.artifact: sub-process: OUTPUT=""
Mar 14 11:43:38 nomad-client-secure00000V nomad[2878]:     2023-03-14T11:43:38.869Z [ERROR] client.artifact: sub-process: OUTPUT="Please make sure you have the correct access rights"
Mar 14 11:43:38 nomad-client-secure00000V nomad[2878]:     2023-03-14T11:43:38.869Z [ERROR] client.artifact: sub-process: OUTPUT="and the repository exists."
Mar 14 11:43:38 nomad-client-secure00000V nomad[2878]:     2023-03-14T11:43:38.869Z [ERROR] client.artifact: sub-process: OUTPUT=""
Mar 14 11:43:38 nomad-client-secure00000V nomad[2878]:     2023-03-14T11:43:38.869Z [INFO]  client.alloc_runner.task_runner: Task event: alloc_id=901ad884-9552-2228-aa74-10cbe023a856 task=JOB type="Failed Artifact Download" msg="failed to download artifact \"git::git@gitlab.com:xxxxxxxxxxxx.git\": getter subprocess failed: exit status 1" failed=false
```

**Comment by CarelvanHeerden** [comment]
Might be related to:
https://github.com/hashicorp/nomad/issues/16475

**Comment by shoenig** [comment]
Hi @CarelvanHeerden 

This line is very odd 

```
Mar 14 11:43:38 nomad-client-secure00000V nomad[2878]:     2023-03-14T11:43:38.869Z [ERROR] client.artifact: sub-process: OUTPUT="No user exists for uid 65534"
```

What user is Nomad agent running as?

Can you show the output of

```
id 65534
```

And lastly are you 100% sure this is Nomad 1.5.1 and not 1.5.0 (which had a regression in this area).

**Comment by CarelvanHeerden** [comment]
Hello @shoenig 

Nomad is running as root

```
$ps aux | grep nomad
root        2878  0.4  0.5 1380440 88132 ?       Ssl  Mar13   5:30 /usr/local/bin/nomad agent -config /etc/nomad.d
```

```
$id 65534
uid=65534(nobody) gid=65534(nogroup) groups=65534(nogroup)
```

```
$nomad --version
Nomad v1.5.1
BuildDate 2023-03-10T22:05:57Z
Revision 6c118ddaf95e9bfd3d85f488f255fdc5e14129c7
```

**Comment by shoenig** [comment]
Thanks, I was able to reproduce using this toy job

```hcl
job "bug" {
  group "group" {

    task "task" {
      driver = "docker"
      artifact {
        source      = "git@github.com:shoenig/ssh-key-sync.git"
        destination = "local/repo"
      }
      config {
        image   = "bash:5"
        command = "sleep"
        args    = ["infinity"]
        volumes = [
          "local/repo:/tmp"
        ]
      }
      resources {
        cpu    = 100
        memory = 32
      }
    }
  }
}
```

```
$ grep PRETTY /etc/os-release
PRETTY_NAME="Ubuntu 20.04.5 LTS"
```

```
ubuntu@ip-172-31-13-235:~$ nomad version
Nomad v1.5.1
BuildDate 2023-03-10T22:05:57Z
Revision 6c118ddaf95e9bfd3d85f488f255fdc5e14129c7
```

We should be able to track down the root cause from here.

**Comment by jedd** [comment]
I'll preemptively apologise for some potentially confusing data points around what looks like the same problem.

I've spent a day trying to resolve similar issues in our environment, and still haven't got a solid lead.

Up until last week we've been using 1.4.3 in test and prod clusters, and several nomad jobs that call in artifacts using sshkey based access to a bitbucket repository (ours, not SaaS). 

Last week I upgraded these environments to 1.5.0, and have since gone to 1.5.1

This week I noticed on restarts of some jobs that we are unable to download the artifacts at job start time, and the job fails.  We haven't resolved this yet, so we're in a precarious situation.

We haven't done OS patching in the past few weeks, but at some point last month, our bitbucket was patched in response to the git CVE described here:  https://confluence.atlassian.com/security/multiple-products-security-advisory-git-buffer-overflow-cve-2022-41903-cve-2022-23521-1189805967.html

The atlassian supported git versions is at:  https://confluence.atlassian.com/bitbucketserver0721/supported-platforms-1115666749.html   but as I understand it, git 2.31 through 2.39 have minor version patches around this  (refer:  all the last 9 rows with release date of 2023-02-17 at https://en.wikipedia.org/wiki/Git#Releases   )

The timing of *that* does not match the timing of my Nomad artifact failures though.

Errors appearing on 1.5.1  (GUI) are:

`failed to download artifact "git::git://git@bitbucket.INTERNALDOMAIN:7999/obs/prometheus-configuration.git": getter subprocess failed: exit status 1
`

Our /var/log/messages are a bit more informative:


```
Mar 15 16:00:39 tl0992obscol01.OURDOMAIN nomad[15874]: 2023-03-15T16:00:39.750+1100 [ERROR] client.artifact: sub-process: OUTPUT="failed to download artifact: error downloading 'git://git@bitbucket.OURDOMAIN:7999/obs/prometheus-configuration.git?sshkey=re
dacted': /usr/bin/git exited with 128: Cloning into '/opt/nomad/alloc/7277c085-b12b-6132-1904-2da72be1dbd5/prometheus/local/prometheus-configuration'..."
Mar 15 16:00:39 tl0992obscol01.OURDOMAIN nomad[15874]: client.artifact: sub-process: OUTPUT="failed to download artifact: error downloading 'git://git@bitbucket.OURDOMAIN:7999/obs/prometheus-configuration.git?sshkey=redacted': /usr/bin/git exited with 128
: Cloning into '/opt/nomad/alloc/7277c085-b12b-6132-1904-2da72be1dbd5/prometheus/local/prometheus-configuration'..."
Mar 15 16:00:39 tl0992obscol01.OURDOMAIN nomad[15874]: client.artifact: sub-process: OUTPUT="fatal: unable to look up git@bitbucket.OURDOMAIN (port 7999) (Name or service not known)"
Mar 15 16:00:39 tl0992obscol01.OURDOMAIN nomad[15874]: 2023-03-15T16:00:39.750+1100 [ERROR] client.artifact: sub-process: OUTPUT="fatal: unable to look up git@bitbucket.OURDOMAIN(port 7999) (Name or service not known)"
Mar 15 16:00:39 tl0992obscol01.OURDOMAIN nomad[15874]: client.artifact: sub-process: OUTPUT=""
Mar 15 16:00:39 tl0992obscol01.OURDOMAIN nomad[15874]: 2023-03-15T16:00:39.750+1100 [ERROR] client.artifact: sub-process: OUTPUT=""
Mar 15 16:00:39 tl0992obscol01.OURDOMAIN nomad[15874]:  client.alloc_runner.task_runner: Task event: alloc_id=7277c085-b12b-6132-1904-2da72be1dbd5 task=prometheus type="Failed Artifact Download" msg="failed to download artifact \"git::git://git@bitbucket.OURDOMAIN:7999/obs/prometheus-configuration.git\": getter subprocess failed: exit status 1" failed=false
Mar 15 16:00:39 tl0992obscol01.OURDOMAIN nomad[15874]: 2023-03-15T16:00:39.750+1100 [INFO]  client.alloc_runner.task_runner: Task event: alloc_id=7277c085-b12b-6132-1904-2da72be1dbd5 task=prometheus type="Failed Artifact Download" msg="failed to download artif
act \"git::git://git@bitbucket.OURDOMAIN:7999/obs/prometheus-configuration.git\": getter subprocess failed: exit status 1" failed=false
Mar 15 16:00:39 tl0992obscol01.OURDOMAIN nomad[15874]: client.alloc_runner.task_runner: prestart failed: alloc_id=7277c085-b12b-6132-1904-2da72be1dbd5 task=prometheus error="prestart hook \"artifacts\" failed: failed to download artifact \"git::git://git@bitbu
cket.OURDOMAIN:7999/obs/prometheus-configuration.git\": getter subprocess failed: exit status 1"
```

Which looks like an 'us' problem, but I can checkout from the same version of git / ssh at the CLI on these hosts to the same bitbucket endpoint.

I did have one older box still on 1.4.1 which has the same problem, but provides more verbose errors:

[failed to download artifact "git::ssh://git@bitbucket.OURDOMAIN:7999/obs/prometheus-configuration.git": error downloading 'ssh://git@bitbucket.OURDOMAIN:7999/obs/prometheus-configuration.git?sshkey=redacted': Error using ssh key: Required git version = 2.3.0, have 1.8.3.1](url)

I note on that box we really do have 1.8.3 of git (they're all RHEL7) - and I'm looking to get that updated to something more modern.

As I understand it, Nomad uses go-getter library, which in turn calls out to an os.() function to use local installed git version.

I've confirmed /etc/ssh/ssh_known_hosts include our bitbucket endpoint on its custom port (they've been there for ~ 2 years) and I've confirmed that key still matches a recent ssh-keyscan of that endpoint.

Naturally I'm happy to provide more info if it'll help.  As noted, I'm still not 100% sure I'm looking at a single root cause here.

**Comment by shoenig** [comment]
> As I understand it, Nomad uses go-getter library, which in turn calls out to an os.() function to use local installed git version.

Indeed @jedd, when using the `git-ssh` protocol, the `go-getter` will fork/exec the `git` executable on the process `$PATH`. Since you're seeing the download error on 1.4.1 we can rule out the artifact sandbox being the problem since it was introduced in 1.5.0. I would suggest maybe installing a modern version `git` on the system (you could put it in `/opt` and then run Nomad with a modified `$PATH`) and seeing if that works - but that's all orthogonal to the problem in this issue.
