### ISSUE TITLE
deps: investigate steps needed for updating go-getter

### ISSUE THREAD

**Issue by shoenig** [hashicorp/nomad#16541]
If/When https://github.com/hashicorp/go-getter/pull/300 is merged, we need to be careful in understanding the implications on Nomad's use of `go-getter` for artifact downloading. In particular

1) If `git` is now going to lookup the user's `.gitconfig`, is it going to error when landlock blocks that access?

2) Regardless of 1, now that `go-getter` would be _able_ to access the user `.gitconfig`, should we go ahead and allow that to happen?

**Comment by picatz** [comment]
⚠️ **FYI**: it was [merged](https://github.com/hashicorp/go-getter/pull/300#pullrequestreview-1346372297) today after this issue was created.

**Comment by crw** [comment]
Just FYI https://github.com/hashicorp/terraform/issues/28968 is blocked on having a new release cut for go-getter (v1), which my understanding is the Nomad team will create when you have resolved the questions in this issue. Linking these issues so I can more easily check in on status. :)

**Comment by crw** [comment]
Hi @shoenig, @picatz: according to @kmoe, the Nomad team agreed to make a new release of `go-getter` when the Nomad team was ready to accept the change. Given the previous comment, is that time now? :) I ask because we have an issue on the Terraform side that is blocked on the next release of `go-getter` (https://github.com/hashicorp/terraform/issues/28968). It looks like there was an additional PR merged since the above-mentioned, see: https://github.com/hashicorp/go-getter/compare/v1.7.1...main. Thanks for any info.

**Comment by tgross** [comment]
Hi @crw! Sorry, I think there was a miscommunication and we're fine with the change. We just need to figure out whether or not to special case the Landlock config in Nomad for it, but that's not something we need to block on at all.

I've had a quick look at the go-getter repo and how the releases work and I think I've got a handle on that. I've just pushed the 1.7.2 tag and waiting for the release action to complete.

**Comment by crw** [comment]
@tgross thank you so much for your very prompt response! I appreciate it.

**Comment by tgross** [comment]
go-getter release done: https://github.com/hashicorp/go-getter/releases/tag/v1.7.2

**Comment by tgross** [comment]
This has been long-since updated. Closing it out.
