### ISSUE TITLE
[CLI] - Json format option with nomad job status

### ISSUE THREAD

**Issue by Lord-Y** [hashicorp/nomad#16566]
Hello guys,

Is it possible to have the `json`  format option when doing `nomad job status example-job-name`.  That will be great in order to manipulate allocations with JQ instead of using `grep`

**Comment by jrasell** [comment]
Hi @Lord-Y thanks for raising this issue. This is an interesting one because most other `json` flag implementations dump a single object or array of objects in json format, whereas this command and implementation would likely wrap a number of related objects such as jobspec, allocations, evaluations, and deployments. I do think this would be very useful to have, so thanks again.

**Comment by sharmaansh21** [comment]
@jrasell  I would like to pick this up, do you have any pointers for me ?

**Comment by 0xMALVEE** [comment]
is this issue fixed already?

**Comment by Lord-Y** [comment]
@0xMALVEE I can confirm that with nomad `1.7.7` it's working: `nomad job status -json`. 
The only thing is it's not mentionned in the help which is too bad.
I'll close this issue then.
