### ISSUE TITLE
Restoring a Nomad Snapshot into a fresh cluster with new clients breaks jobs in the cluster

### ISSUE THREAD

**Issue by megalan247** [hashicorp/nomad#16640]
### Nomad version
1.5.2 

### Operating system and Environment details
Ubuntu Linux (ARM64) running in AWS

### Issue
When restoring a snapshot of the nomad state, nomad also restores all the clients and where the allocs are placed. However, when using an AWS autoscaling group, often we have a situation where the "old" clients no longer exist. Therefore Nomad "hangs" in a situation where it thinks all the allocs are running, but they are not. 

The clients then after a long time (5 mins) eventually transition to a "down" state, however the allocs are never marked as "lost" and therefore are never rescheduled. This results in a broken cluster where none of the running jobs can be interacted with as no evaluations for them can be processed.

There are logs about 
```
nomad.keyring.replicator: failed to fetch key from any peer: key=9cc16249-4278-53c6-f0a7-50101efa705b error="rpc error: no such key \"9cc16249-4278-53c6-f0a7-50101efa705b\" in keyring"
```
After running a `nomad operator root keyring rotate -full` it appeared to "free" up the allocs and they were all rescheduled. 

### Reproduction steps
- Create two autoscaling groups in AWS, one for nomad servers, one for nomad clients. 
- Run some jobs and take a nomad snapshot. 
- Terminate all the nomad servers and clients at the same time in AWS, which will result in the servers being recreated, and a fresh cluster bootstrapped
- Restore the nomad snapshot to the cluster, and observe no rescheduling taking place.

#### Expected Result
On restore of the state, the jobs would be immediately marked as "lost" and rescheduled onto new nodes.

#### Actual Result
The allocs are never rescheduled and the cluster is broken

N/A

### Nomad Server logs (if appropriate)
Mar 24 16:47:05 s-i-085b661d4ea83f713 nomad[4235]:     2023-03-24T16:47:05.492Z [ERROR] nomad.keyring.replicator: failed to fetch key from any peer: rpc error: no such key "9cc16249-4278-53c6-f0a7-50101efa705b" in keyring: key=9cc16249-4278-53c6-f0a7-50101efa705b
Mar 24 16:47:05 s-i-085b661d4ea83f713 nomad[4235]:     2023-03-24T16:47:05.689Z [WARN]  nomad.keyring.replicator: failed to fetch key from current leader, trying peers: key=9cc16249-4278-53c6-f0a7-50101efa705b error="rpc error: no such key \"9cc16249-4278-53c6-f0a7-50101efa705b\" in keyring"

**Comment by tgross** [comment]
Hi @megalan247! There are likely two different problems here. 

First, let's address the keyring problem.

> Terminate all the nomad servers and clients at the same time in AWS, which will result in the servers being recreated, and a fresh cluster bootstrapped

You _can_ do this but you need to ensure you're restoring the keyring as well. The [Key Management docs](https://developer.hashicorp.com/nomad/docs/operations/key-management#restoring-the-keyring-from-backup) have this to say:

> However, this means that to restore a cluster from snapshot you need to also provide the keystore directory with the .nks.json key files on at least one server. The .nks.json key files are unique per server, but only one server's key files are needed to recover the cluster. Operators should include these files as part of your organization's backup and recovery strategy for the cluster.

It looks like we should add that directly to the upgrade guide docs for folks who are destroying the cluster and restoring from snapshot to upgrade like this. Upcoming work in https://github.com/hashicorp/nomad/issues/14852 will also make your workflow a lot nicer by letting you use an external wrapper like AWS KMS to wrap the keyring.

---

Next, let's talk about the allocs that don't reschedule.

> The clients then after a long time (5 mins) eventually transition to a "down" state, however the allocs are never marked as "lost" and therefore are never rescheduled. This results in a broken cluster where none of the running jobs can be interacted with as no evaluations for them can be processed.

What should be happening here is:

* The new leader comes up and initializes the heartbeat timers for all nodes in the cluster in [`initializeHeartbeatTimers`](https://github.com/hashicorp/nomad/blob/v1.5.2/nomad/heartbeat.go#L56). This will of course be just the old clients.
* The [Client Heartbeats](https://developer.hashicorp.com/nomad/docs/configuration/server#client-heartbeats) logic dictates how long to wait for clients to miss heartbeats before declaring them `down`. The exact time varies depending on config and cluster size, but will be unusually long in your case because as far as the servers know the cluster has just doubled in size.
* At this point you should see a [`node TTL expired`](https://github.com/hashicorp/nomad/blob/v1.5.2/nomad/heartbeat.go#L153) message at WARN level in the server logs.
* The heartbeater will call [`Node.UpdateStatus`](https://github.com/hashicorp/nomad/blob/v1.5.2/nomad/node_endpoint.go#L479)
* We check to see if the node should be drained by [`ShouldDrainNode`](https://github.com/hashicorp/nomad/blob/v1.5.2/nomad/structs/structs.go#L1873-L1884) and emit the evals for any allocs on that node. The resulting evals should have the triggered-by field set to `node-update`.
* The evaluations result in new allocations being rescheduled.

With what you've provided, I can't say for sure which step is failing here. What I'd want to look at next is to use the [`nomad eval list`](https://developer.hashicorp.com/nomad/docs/commands/eval/list) command to see whether evaluations are happening at all. You should be able to filter evaluations by those associated with node events with a filter like: ` nomad eval list -filter 'NodeID != ""'`. If there are evaluations getting created for the missing nodes, then the next thing to do is look at the server logs for messages from the scheduler. If not, that tells us that the problem is earlier in the workflow.

In addition to debugging, there's a couple things you could do to workaround in the meanwhile:
* Set all the client to drain before shutting them down. That will leave a backlog of evaluations to get picked up when the servers come back online.
* Call [`nomad job eval`](https://developer.hashicorp.com/nomad/docs/commands/job/eval) for every job in the cluster.

**Comment by megalan247** [comment]
Hiya, thanks for the very fast and in-depth reply! 

I forgot to mention: This is not for upgrades, rather was done for disaster recovery, whereby in the event of a a cluster outage due to too many servers being brought down, the state can easily be restored from a daily backup we create. This is significantly faster (and easier to write an SOP for) than deploying each job individually. In this case, there was a cluster outage due to multiple failed servers.

Ah, it seems that the 5 minutes that I mentioned above may have been coming from the `failover_heartbeat_ttl` variable that is mentioned in the Heartbeats Logic page you linked. I will reduce this in our configuration to speed up the restore process. Thanks for the hint!

I checked again our logging system for the logs related to this incident, and it appears as though the evals were emitted, however they could not be processed due to the missing key

```
2023-03-24T16:46:06.637Z [ERROR] worker: error invoking scheduler: worker_id=0b30dc9a-ccae-8ea9-4366-9dddc5c490f1 error="failed to process evaluation: no such key \"9cc16249-4278-53c6-f0a7-50101efa705b\" in keyring"
```

So it seems that when restoring the Nomad state, it requires the keyring before processing any evals related to the currently "running-but-not-really-running" jobs. 

Eventually it seems they emitted a log line similar to `eval reached delivery limit`, but as the logs were spammed with the `failed to fetch key from any peer` ERROR message, it was hard to see as the `eval reached delivery limit` message is only a WARN.

Is there a way to include the .nks.json file as part of the nomad snapshot? Perhaps optionally? 

Or is there any other way to retrieve and restore this information via the HTTP API? Unfortunately SSH-ing into the box is a little tricky for us, as we run hundreds of clusters that are generally only accessible via the HTTP API, or AWS SSM. Having the entire state backed up in a single file was really handy :)

Alternatively, I guess we can just fire a key rotation call after the restore to "fix" the issue. What would you recommend?

Thanks again for the quick response.

**Comment by tgross** [comment]
> I checked again our logging system for the logs related to this incident, and it appears as though the evals were emitted, however they could not be processed due to the missing key

:facepalm: Of course! The root key ID is in raft, so the servers were expecting to be able to sign with that key and it was missing, so none of the allocations could have their identities signed.

> Is there a way to include the .nks.json file as part of the nomad snapshot? Perhaps optionally?
>
> Or is there any other way to retrieve and restore this information via the HTTP API? Unfortunately SSH-ing into the box is a little tricky for us, as we run hundreds of clusters that are generally only accessible via the HTTP API, or AWS SSM. Having the entire state backed up in a single file was really handy :)
>
> Alternatively, I guess we can just fire a key rotation call after the restore to "fix" the issue. What would you recommend?

There's no way to do that currently via the API, and exposing the root keys directly is something we're hesitant to provide because it's used to encrypt Variables. For your use case the external KMS provider will be the _perfect_ solution once we've implemented that. 

In the meantime you could either fire the key rotation call, or you could have a periodic backup script running on the server host that backs up the keystore externally (perhaps writing into a cluster-specific key in AWS Secrets Manager or Parameter Store). And then your system unit file (or whatever) could pull the same key down from Secrets Manager on startup too, which would reduce some toil of restoring the keystore.

**Comment by megalan247** [comment]
OK great, for now I will add a key rotation call to our backup restore script because I am lazy :D

 I think, however, it might be a good idea to add a sentence or two to the `nomad operator snapshot restore` documentation that mentions that it needs the old keyring, or to rotate the keyring on restore for the restore to work. 

For now I am happy to close this issue if you like, or I can keep it open. Whichever is best for you.

**Comment by tgross** [comment]
Ok, great! I'm going to keep this open just long enough to remind me to write that docs update on Monday. :grinning:

**Comment by tgross** [comment]
I've opened #16663 and a PR in the internal repo for the Tutorials, to clarify the docs. Thanks!
