### ISSUE TITLE
Artifact fails to download 

### ISSUE THREAD

**Issue by ScatteredRay** [hashicorp/nomad#16698]
### Nomad version
Nomad v1.4.3 (f464aca721d222ae9c1f3df643b3c3aaa20e2da7)

### Operating system and Environment details
NixOS on channel nixos-unstable, same issue on 22.05

### Issue

Unable to download an artifact.

### Reproduction steps

On a cluster running on NixOS a job with an artifact step e.g.

```
      artifact {
        source = "http://artifacts.my.url/artifacts/test/build.zip"
        destination = "local/artifact"
      }
```

#### Expected Result

The artifact should download and extract

#### Actual Result

The job fails with the error:

`failed to download artifact "http://artifacts.my.url/artifacts/test/build.zip": exec: "getent": executable file not found in $PATH`

This was previously recorded in [#12096](https://github.com/hashicorp/nomad/issues/12096) which was closed because it's similar to [#8410](https://github.com/hashicorp/nomad/issues/8410) However the fix in [#14851](https://github.com/hashicorp/nomad/pull/14851) doesn't apply since it appears the it requires PATH to be included which isn't an option in the artifact stanza.

**Comment by tgross** [comment]
@ScatteredRay the error message you're seeing says the `getent` isn't available on Nomad's PATH. I see you're on NixOS; it `getent` available in the environment where Nomad is running?

**Comment by ScatteredRay** [comment]
Yeah, I'm pretty sure it is... I've investigated further and was worried that maybe it wasn't included in the derivation path of nomad, but I'm pretty sure it is now.

For the nix inclined, I ran:

` nix-shell --pure -E 'with import <nixpkgs> {}; nomad'` which as far as I know, should put you in the environment in which nomad is being built (I also tried `nix-shell --pure -p nomad`, which just invokes the nomad env) and in both cases, `getent` returns as expected:

```getent: wrong number of arguments
Try `getent --help' or `getent --usage' for more information.```

Based on the other bugs, is it possible that the artifact stanza is introducing a new chroot that is being put together incorrectly?

**Comment by tgross** [comment]
Going back to this:
> This was previously recorded in #12096 which was closed because it's similar to #8410 However the fix in #14851 doesn't apply since it appears the it requires PATH to be included which isn't an option in the artifact stanza.

Yeah I'm not sure why #12096 was closed. The artifact download itself was fine in #8410, the problem there was about running an executable from there for the `exec` driver. That's totally unrelated other than "Nix was involved."

> in both cases, getent returns as expected:

Hm, but the error message you're seeing is pretty straightforwardly about not being able to find it though? The weird thing is I can't find anywhere in the [`go-getter`](https://github.com/hashicorp/go-getter) library where we're directly calling `getent`. I might expect to see that getting called from a child-child process if it were a git artifact (because we rely on the host's `git` binary for that), but not for https.

> Based on the other bugs, is it possible that the artifact stanza is introducing a new chroot that is being put together incorrectly?

In Nomad 1.4.x there's no sandbox for the artifact; the file is just dropped in the task directory. The task driver hasn't been called at that point so there's no bind-mounting for that either. (In Nomad 1.5.0 this has changed so that we download from a restricted subprocess using Landlock if available on the host.) But we test on standard Linux distributions; NixOS is weird and opinionated about how things look on disk. It wouldn't surprise me if Nix just doesn't like something here.

It might help if you could run [statsnoop](https://github.com/iovisor/bpftrace/blob/master/tools/statsnoop.bt) on the client host while the task is getting spun up. That'd help figure out what's going on with go-getter in your particular environment -- I'd expect to see errors there and maybe more than one, which would let us know what's happening leading up to this point.

**Comment by shoenig** [comment]
I suspect the use of `getent` from `go-getter` (for HTTP) stems from

https://github.com/hashicorp/go-getter/blob/v1.6.2/get_http.go#L213

https://github.com/hashicorp/go-getter/blob/ef2fcc6c2f8ee034f76b3c25cd0bce26155f1e08/netrc.go#L32
https://github.com/mitchellh/go-homedir/blob/main/homedir.go#L71
https://github.com/mitchellh/go-homedir/blob/main/homedir.go#L89
and finally
https://github.com/mitchellh/go-homedir/blob/main/homedir.go#L114

If that's the case, seems like setting a `$HOME` would be an easy way to avoid the `getent` call.

Like @tgross mentioned there is no sandboxing for artifact in Nomad 1.4.x; and in Nomad 1.5 if the sandbox were mis-configured the error would be about permissions rather than file not found.

**Comment by ScatteredRay** [comment]
Ok, thanks for this help, I think I figured out a solution.

So, running statsnoop, I saw these files getting snooped

```883    nomad              2 /nix/store/m3p9za90q4m78l1y5i1sgg7zlign1dqr-coreutils-9.1/bin/getent
883    nomad              2 /nix/store/zhi359vqbm2wmwhmkpma3kpbc4xsgyml-iproute2-6.2.0/bin/getent
883    nomad              2 /nix/store/0zjgp2x4qsnad19x3jmn9wgwwczyri5x-iptables-1.8.8/bin/getent
883    nomad              2 /nix/store/m3p9za90q4m78l1y5i1sgg7zlign1dqr-coreutils-9.1/bin/getent
883    nomad              2 /nix/store/6ivyyf7cqfmgy7vgrvmjfdrdxbsir113-findutils-4.9.0/bin/getent
883    nomad              2 /nix/store/ckj3dd75h2n72snwb80sxq4fqgcnsc4q-gnugrep-3.7/bin/getent
883    nomad              2 /nix/store/qx45g8112ghmc84zzjplg76d0dpfahlq-gnused-4.9/bin/getent
883    nomad              2 /nix/store/rqmshkzl2a2cbxf1q1570zz6gwlrgykh-systemd-253.1/bin/getent
883    nomad              2 /nix/store/m3p9za90q4m78l1y5i1sgg7zlign1dqr-coreutils-9.1/sbin/getent
883    nomad              2 /nix/store/zhi359vqbm2wmwhmkpma3kpbc4xsgyml-iproute2-6.2.0/sbin/getent
883    nomad              2 /nix/store/0zjgp2x4qsnad19x3jmn9wgwwczyri5x-iptables-1.8.8/sbin/getent
883    nomad              2 /nix/store/m3p9za90q4m78l1y5i1sgg7zlign1dqr-coreutils-9.1/sbin/getent
883    nomad              2 /nix/store/6ivyyf7cqfmgy7vgrvmjfdrdxbsir113-findutils-4.9.0/sbin/getent
883    nomad              2 /nix/store/ckj3dd75h2n72snwb80sxq4fqgcnsc4q-gnugrep-3.7/sbin/getent
883    nomad              2 /nix/store/qx45g8112ghmc84zzjplg76d0dpfahlq-gnused-4.9/sbin/getent
883    nomad              2 /nix/store/rqmshkzl2a2cbxf1q1570zz6gwlrgykh-systemd-253.1/sbin/getent
```

Which lead me to notice it was in fact missing the bath with getenv in it. So, it turns out I was able to resolve it via:

```
config.services.nomad.extraPackages = [ pkgs.glibc ];
```

It seems that this should probably be added to the path by default, so I'll see about submitting a PR to nixpkgs for this.

**Comment by tgross** [comment]
Oh, Nomad should typically be built with CGO enabled, so having glibc is going to be critical for things like the `exec` driver to work correctly. Submitting a PR to nixpkg would probably fix other issues for folks on NixOS.

But glad to hear you've got this resolved!
