### ISSUE TITLE
Unable to create a Nomad variable scoped to job with periods

### ISSUE THREAD

**Issue by h4ckninja** [hashicorp/nomad#16778]
### Nomad version
```
# nomad version
Nomad v1.5.2
BuildDate 2023-03-21T22:54:38Z
Revision 9a2fdb5f53dce81edf2802f0b64962e07596fd03
```

### Operating system and Environment details
```
# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```

### Issue
I have jobs in Nomad deployed as `application.example.com` which works just fine for my needs. I can easily and readily see what the application is, the subdomain it lives on, and I just like the visual usability of that naming scheme.

Just recently, I started moving my jobs' service provider from Consul Catalog to Nomad as my needs are fairly small - it's a home lab, so it doesn't really make sense to have Vault, Consul, and Nomad all running when Nomad service catalog is available and Nomad variables are available for my basic needs.

The problem is coming in, and I searched for it in issues so apologies if I missed it, is the `nomad/job/<job name>` scoping. For example, here's my home lab:

`dns.home.lan`: Pi-hole
`automation.home.lan`: N8n
`traefik.home.lan`: Traefik
...

The jobs deployment and running all works great. But creating scoped variables to `nomad/jobs/dns.home.lan` for example, causes Nomad to throw a 500 error. If I create a scoped variable to `nomad/jobs/dns`, however, it works just fine.

So, if jobs can contain periods in the job name, why can't variables?

The workaround for now is for me to redeploy my jobs to not have periods in the name, or to not scope them and instead have names that don't contain periods. But I quite like the naming scheme I have as it works for my needs.

### Reproduction steps
See above description.

#### Expected Result
See above description.

#### Actual Result
The UI displays the following error message:

```
Error: Ember Data Request PUT /v1/var/nomad%2Fjobs%2Fdns.home.lan?cas=0 returned a 500 Payload (text/xml) invalid path "nomad/jobs/dns.home.lan"
```

Taking out the periods scoped or unscoped allows the variable to be saved.

**Comment by schmichael** [comment]
Unfortunately variables are restricted from containing periods due to conflicts with the syntax of our template blocks. The `var put` docs go into this: https://developer.hashicorp.com/nomad/docs/commands/var/put#restrictions

In hindsight we should have put some restrictions on job names as the lack of restrictions has caused a lot of unfortunate surprises like this (and even uglier things like when we allowed null characters in job names!).

I'm afraid we're stuck with this restriction and you'll either need to rename your jobs or manually grant them access to variables on a different path: https://developer.hashicorp.com/nomad/docs/concepts/workload-identity#using-workload-identity
