### ISSUE TITLE
SHA256 Checksum for AMD64 is off.

### ISSUE THREAD

**Issue by darron** [hashicorp/nomad#168]
Got the Checksum from here:

https://dl.bintray.com/mitchellh/nomad/nomad_0.1.0_SHA256SUMS?direct

It says `6d48846e40a44449f2b84eb37f32859eff98468ebffef3b4475d7a060f14fa32`

But when I download to verify it's actually:

```
[staging]darron@i-86402c2e:~$ wget https://dl.bintray.com/mitchellh/nomad/nomad_0.1.0_linux_amd64.zip
--2015-09-30 04:58:49--  https://dl.bintray.com/mitchellh/nomad/nomad_0.1.0_linux_amd64.zip
Resolving dl.bintray.com (dl.bintray.com)... 108.168.194.92, 108.168.194.91
Connecting to dl.bintray.com (dl.bintray.com)|108.168.194.92|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4357811 (4.2M) [application/zip]
Saving to: ‘nomad_0.1.0_linux_amd64.zip’

100%[====================================================================================================================================================>] 4,357,811   5.18MB/s   in 0.8s

2015-09-30 04:58:50 (5.18 MB/s) - ‘nomad_0.1.0_linux_amd64.zip’ saved [4357811/4357811]

[staging]darron@i-86402c2e:~$ sha256sum nomad_0.1.0_linux_amd64.zip
0c41b5b804089e3f776998fb6e03815e9862580ca953dd39ee822d71fde51e70  nomad_0.1.0_linux_amd64.zip
```

Not a huge deal - but should be corrected.

I haven't checked the other versions.

**Comment by dadgar** [comment]
Thanks! Will fix this soon

**Comment by schmichael** [comment]
Just following up on this ancient ticket since I actually bumped into it while attempting some archaeology. It appears that the `nomad_0.1.0_linux_amd64.zip` archive was truncated during some data migration between 2015 and 2017. We removed the empty zip from https://releases.hashicorp.com/nomad/0.1.0/ and will not attempt to rebuild given its age and the confusion around what the proper hash should be anyway.
