### ISSUE TITLE
Reschedule workloads after dynamic node metadata update

### ISSUE THREAD

**Issue by valodzka** [hashicorp/nomad#16834]
### Proposal

Nomad's current behavior is to not automatically reschedule workloads even when their metadata is updated (per https://mastodon.cloud/@schmichael@hachyderm.io/109955071628997099. While this behavior is sensible by default, there are cases where it would be useful to automatically stop/move allocations based on metadata updates (automatically or via api call).

### Use-cases

For example, imagine a job that should only run on nodes where the `${meta.gateway}` constraint is `true`. If you need to update this metadata to false, you would currently have to manually stop the allocations or perform a full redeploy. However, it would be less error-prone and more practical to have the ability to automatically stop or move allocations based on metadata updates.

### Attempted Solutions

It is possible to achive reschedule buy running full redeploy (via altering some meta key for example), but it isn't optimal as it will reschedule all allocations, not only affected.

**Comment by lgfa29** [comment]
Hi @valodzka 👋 

I think this is a similar request to https://github.com/hashicorp/nomad/issues/1635. Although not exactly about dynamic node metadata (since it's a new feature 😄) they are all affinities and constraints that need to be reevaluated.

A possible workaround for now is the new [`nomad job restart -reschedule` command](https://github.com/hashicorp/nomad/pull/16278) that will be released in the next version of Nomad.

I'm going to close this as a duplicate, but feel free to reach out if there's something I'm missing 🙂
