### ISSUE TITLE
[question] Nomad 0.5 volume support - Hashiconf announcement

### ISSUE THREAD

**Issue by hgontijo** [hashicorp/nomad#1708]
This is a follow-up on this [post](https://groups.google.com/forum/#!topic/nomad-tool/tHiq4kg-N-k) since there seems to be a Google Group issue auto deleting all subsequent posts in there.

--- My original question ---
Hi,

What should we expect from this Hashiconf announcement "sticky volumes allow Nomad to migrate application data between nodes, enabling support for applications requiring data such as Cassandra and HDFS"?

--- Diptanu Choudhury ---
Hi,

Currently, there is no way to make Nomad restart an allocation on the same node if it has to be updated. With sticky volumes Nomad will prefer the same node to create the updated allocations and migrate any data in the shared directory and the task-local directories to the new allocation.

--- My 2nd question --- 
Hi,
Please help me to understand it better. It looks to me a feature where Nomad cluster will take advantage of distributed/network file system (i.e. Nomad data dir configured on an arbitrary volume) in order to improve the allocation restart process?
Are you guys also considering the arbitrary volume configuration on job/task level?

**Comment by dadgar** [comment]
Hey,

So they are somewhat tangential. We will be bringing volume plugins in 0.6 which will allow you to mount persistent volumes that your tasks can write to. This will solve the persistent volume case.

Sticky is for applications that can handle data failure but would prefer to avoid it. As such it is a best effort. Two examples are as follows:

1) Imagine you have a cache such as redis. It has persisted to disk and then you update it to give it more memory while running. Without sticky the cache would be wiped when it was placed again. With sticky it will be attempted to be placed on the same node and reuse the written cache. If it can't be the data will be copied.

2) Similar case but you have a database which can do the replication in app but if the data is there it only has to ship the delta from the WAL rather than a full replication

**Comment by dadgar** [comment]
If those answer your question feel free to close this issue

**Comment by hgontijo** [comment]
Great, thanks for clarifying and also for providing those features!
