### ISSUE TITLE
Task leak if alloc prerun hook fails after client restart

### ISSUE THREAD

**Issue by gulducat** [hashicorp/nomad#17102]
If a prerun hook fails when restoring alloc state, as with a client agent restart, tasks don't get fully cleaned up and may leave orphan resources like a running container and network configuration (e.g. iptables rules).

This was pointed out in #13028 where specifically a CSI prerun hook fails, but it's an issue more generally with alloc runner prerun hooks.

I encountered it myself while investigating that issue, and as @ygersie put it,

> The worst thing is that Nomad garbage collects the failed allocation but doesn't actually shutdown the docker container (checked the docker logs it never received the api call to stop it either), leaving a zombie container.

### Reproduction steps

I made a strange hook to be able to poison an alloc on disk, so it can succeed first pass but fail after a client agent stop/start.

#### Expected Result

All of the failed task's resources are cleaned up.

#### Actual Result

The task is marked as failed and dead and gets replaced, but the old container remains running.

Also if the task uses a static port, the new one will fail to start because the port is held by the "failed" task.

**Comment by suikast42** [comment]
have maybe some paralles with https://github.com/hashicorp/nomad/issues/17079 ?

**Comment by suikast42** [comment]
Ok. I have put in a little effort to get to the bottom of it. 

I enable the `drain_on_shutdown ` on the agent node with 

```hcl
  drain_on_shutdown {
    deadline           = "2m"
    force              = false
    ignore_system_jobs = true
  }
```

But that's dont make the situation better.  My epectation is that the `drain_on_shutdown ` drains all allocs and shudiwn the agent after that. But it does not tollerate the 2m deadline. 

My second approach is to call a script over systemd Stop hook.

```
ExecStop={{nomad_conf_dir}}/nomad_node_drain.sh
```
nomad_node_drain.sh
```shell
#!/bin/bash

if [ ! -f "/home/{{ansible_user}}/notdrain" ] ; then nomad node drain -enable -self -deadline "2m"  -m "Node shutdown" -yes -address=https://localhost:4646 -ca-cert=/usr/local/share/ca-certificates/cloudlocal/cluster-ca-bundle.pem -client-cert=/etc/opt/certs/nomad/nomad.pem -client-key=/etc/opt/certs/nomad/nomad-key.pem;fi
```
With that approch I have never seen the dead allocations. But I must start the master node first. Otherwise the issue is the same. 

The approach to drain the node over script comes with the caveat that the node is not eligable after boot. 

my workarround for make the node eligable again is described here. 

https://github.com/hashicorp/nomad/issues/17093

**Comment by gulducat** [comment]
@suikast42 There are some conceptual parallels, in that both cases result in stuff getting left behind unexpectedly.

However in #17079 your logs indicate that task "Killing" is starting, which is one of the things that is currently _not_ happening under the specific circumstances that cause this issue here.  And one of the things that _does_ happen appropriately in this case are task stop hooks, which include service deregistration.

So good keeping watch, but these cases are definitely unrelated!
