### ISSUE TITLE
ui: Variables are not visible when token is bound to a role instead of a policy

### ISSUE THREAD

**Issue by michael-strigo** [hashicorp/nomad#17312]
### Nomad version
```
Nomad v1.5.6
BuildDate 2023-05-19T18:26:13Z
Revision 8af70885c02ab921dedbdf6bc406a1e886866f80
```

### Issue
The variable section in the UI won't show up if the token is bound to a role instead of a policy, no matter in question actually allows variable access or not.

### Reproduction steps

1. Create a policy that allows variable access:
`nomad acl policy apply test @policy.hcl`

policy.hcl:
```
namespace "*" {
  policy = "write"

  variables {
    path "*" {
      capabilities = ["write", "read", "list"]
    }
  }
}
```

2. Create a role and attach the policy:
`nomad acl role create -name=test -policy=test`

3. Create a token:
`nomad acl token create -role-name=test`

4. Sign in with the token to the web ui.

5. Repeat the above only with attaching policy directly to the token:
`nomad acl token create -policy=test`

#### Expected Result
See the Variables section on the left menu bar.

#### Actual Result
No variables section available.

**Comment by lgfa29** [comment]
Hi @michael-strigo 👋 

Thanks for the report. I believe this is the same problem as described in https://github.com/hashicorp/nomad/issues/16361, where the UI is not able to properly handle ACL roles. I'm going to close this as a duplicate but note the problem you reported here so we can validate the fix for variables as well.
