### ISSUE TITLE
add a link in the missing driver placement error in the UI

### ISSUE THREAD

**Issue by juliezzhou** [hashicorp/nomad#17325]
### Proposal
Add client link on the placement failure in the UI
<img width="811" alt="Screenshot 2023-05-25 at 4 21 39 PM" src="https://github.com/hashicorp/nomad/assets/90711359/feac8e70-7e8b-466f-8d43-71eb2a7f8ac3">
and the link should go to the client related to this error

### Use-cases
People, specially new users, don't understand what this missing drivers error means. And proving a link to the client, will help them see the drivers that are healthy vs unhealthy.

**Comment by philrenaud** [comment]
Hi @juliezzhou , I spent a little time looking into this this morning. The message here is driven from the `/evaluations` endpoint, and while I expected some of it to be derived (like the node count, etc.) it turns out it's returned very explicitly as shown:

<img width="287" alt="image" src="https://github.com/hashicorp/nomad/assets/713991/b76b41b0-f933-4a31-a10f-9f2b8dd212ea">


The entire evaluation block that drives the placement failure you've included in your screenshot above looks something like this:

```
{
  "priority": 50,
  "type": "service",
  "triggeredBy": "queued-allocs",
  "status": "blocked",
  "statusDescription": "created to place remaining allocations",
  "failedTGAllocs": [
    {
      "Name": "app",
      "CoalescedFailures": 4,
      "NodesEvaluated": 1,
      "NodesExhausted": 0,
      "NodesAvailable": {
        "dc1": 1
      },
      "ClassFiltered": null,
      "ConstraintFiltered": {
        "missing drivers": 1
      },
      "ClassExhausted": null,
      "DimensionExhausted": null,
      "QuotaExhausted": null,
      "Scores": null
    }
  ],
  "previousEval": "49f9ffae-314a-30aa-a519-3e11f0615883",
  "nextEval": null,
  "blockedEval": null,
  "modifyIndex": 9804,
  "modifyTime": "2023-07-07T01:25:12.185Z",
  "createIndex": 9804,
  "createTime": "2023-07-07T01:25:12.185Z",
  "waitUntil": null,
  "namespace": "default",
  "plainJobId": "hello_world",
  "job": "[\"hello_world\",\"default\"]",
  "node": null
}
```

I think if we wanted this, we'd have to refactor our [AllocationMetric](https://github.com/hashicorp/nomad/blob/main/api/allocations.go#L284-L302) struct that gets returned from the `/evaluations` endpoint to do something like return metadata information about failures (a block like `Meta: { NodeID: <id>, DriverName: <name>}` would get us what we want, but there are probably good (perf) reasons why we wouldn't want to do that. I'll confer with some of devs would know more about this and see if that's doable.

**Comment by philrenaud** [comment]
Closing this; after some discussion internally, this would require a pretty significant re-work of how we pass failure statuses.
