### ISSUE TITLE
CSI documentation leads to gRPC socket issue - is it required to run nomd as root in order to use CSI volumes?

### ISSUE THREAD

**Issue by josh-m-sharpe** [hashicorp/nomad#17333]
https://developer.hashicorp.com/nomad/tutorials/stateful-workloads/stateful-workloads-csi-volumes?in=nomad%2Fstateful-workloads 

I get this error when launching the controller job:

`Error: CSI plugin failed probe: timeout while connecting to gRPC socket: failed to create gRPC connection: failed to open grpc connection to addr: /mnt/nomad/client/csi/plugins/ff0c25b8-c647-d9c7-9f53-d63dba1b7b3a/csi.sock, err: context deadline exceeded`

**Comment by josh-m-sharpe** [comment]
![Cursor_and_Notification_Center](https://github.com/hashicorp/nomad/assets/39473/3770a759-dae8-40ea-b9ae-f725158682dd)

**Comment by josh-m-sharpe** [comment]
The [docs](https://developer.hashicorp.com/nomad/tutorials/stateful-workloads/stateful-workloads-csi-volumes?in=nomad%2Fstateful-workloads) suggest that only the node system jobs need to run with `privilieged = true` -- but I was having trouble getting the single controller instance running.  It was failing with the above error.  I noticed that `csi.sock` was created and owned by `root:root` -- my nomad agent was running a the unprivilieged `nomad` user, but relaunchig it as root seems to have resolved this.

Seems much better to not run it as root.  Is there a workaround?

**Comment by lgfa29** [comment]
Hi @josh-m-sharpe 👋 

While, in theory, I think the socket could be mounted under any user (I'm not too sure if there's any CSI specific requirements here), there are other reasons why Nomad clients should run as `root`. Check the [Permissions](https://developer.hashicorp.com/nomad/docs/operations/nomad-agent#permissions) section of the Nomad agent operations for mode details.

Since running the Nomad client as root fixes the problem (and is the expected deployment model), I'm going to close this, but feel free to add any more info if you find this is not the case.

Thanks!
