### ISSUE TITLE
update stagger is not explained in the job specification docs

### ISSUE THREAD

**Issue by JensRantil** [hashicorp/nomad#174]
I just read https://www.nomadproject.io/docs/jobspec/index.html#update. I have no idea what `stagger` does/means. Maybe it's my bad English, don't know.

Suggestion: Improve description what it does/means.

**Comment by reidja** [comment]
It says exactly what it does:

update - Specifies the task update strategy. This requires providing max_parallel as an integer and stagger as a time duration. If stagger is provided as an integer, seconds are assumed. Otherwise the "s", "m", and "h" suffix can be used, such as "30s". Both values default to zero, which disables rolling updates.

Stagger is the time duration between updates, and max_parallel is the number of nodes to act upon.

What it means is that if you have stagger set to a value, it will wait that many seconds before updating another node.

**Comment by dadgar** [comment]
@JensRantil I am going to close this. If the answer given didn't explain it to you feel free to post on the user group: https://groups.google.com/group/nomad-tool

**Comment by JensRantil** [comment]
@dadgar I opened this issue not because I didn't understand, but more so that the documentation was lacking. ;)

The only thing the documentation states about `stagger` is that 1) it is a time duration and 2) can be specified in various time units. The documentation does not explain, in any way, what `stagger` influences. I suggest reopening this issue until the documentation actually states what `stagger` does/means.

**Comment by cbednarski** [comment]
Thanks for following up. I think we can clarify the phrasing here.

**Comment by sheerun** [comment]
Indeed

**Comment by grobinson-blockchain** [comment]
What's unclear to me is how Nomad behaves under stagger when you have either of the following failure situations:

1. An unscheduable job because the docker image doesn't exist, or there are no clients to run the instance on, or all resources are constrained, etc. Will Nomad detect this, pause the rollout and keep the other instances running in order to maintain uptime, or will it fail, move on, etc, and remove all running instances before declaring the job as failed?

2. A bad build is run with Nomad such that the docker container exits with error code 1. When provided with a stagger policy, will Nomad detect that containers are crashing and pause the rollout from affecting the rest of the instances?

**Comment by dadgar** [comment]
@grobinson-blockchain Both of these issues will be fixed once Nomad uses Consul health checks to gate rolling updates. Currently the behavior is only time based
