### ISSUE TITLE
High memory usage on servers due to client registration

### ISSUE THREAD

**Issue by jorgemarey** [hashicorp/nomad#17595]
### Nomad version
v1.4.3

### Issue
Our nomad servers stated using a lot of memory.

We saw a rapid increase in memory usage in our nomad servers.

![memory_usage](https://github.com/hashicorp/nomad/assets/6938602/2f8d916a-a171-4deb-a097-e59675658f59)

Look up what could have caused this we saw an increase in  client registrations, but no new clients we're added to the cluster. Maybe a client lost up network connection and when joining up again it was stuck in some loop?

![register_count](https://github.com/hashicorp/nomad/assets/6938602/a0c6302a-e68e-407e-b56e-0bed2264ded6)

I think the problem is that on every client register new evaluations are created for the node and this is what ended up filling up the memory.

![eval_create](https://github.com/hashicorp/nomad/assets/6938602/b48be522-aea6-4d18-b1d7-885a8de3b50b)

Would be possible to avoid that a client is constantly registering with the servers?

We currently have the eval_gc_threshold to 24h. Would mitigate the problem lowering this to a couple of hours? Doing that, would also gc the allocations that were in terminal state for that couple hours, is that right?

### Reproduction steps
We're not able to reproduce it currently, but it happened several times already.

### Nomad Server logs (if appropriate)
There're no unusal logs in the server.

**Comment by tgross** [comment]
Hi @jorgemarey!

> Look up what could have caused this we saw an increase in client registrations, but no new clients we're added to the cluster. Maybe a client lost up network connection and when joining up again it was stuck in some loop?
> ...
> I think the problem is that on every client register new evaluations are created for the node and this is what ended up filling up the memory.
> ...
> Would be possible to avoid that a client is constantly registering with the servers?

That `Node.Register` RPC gets sent whenever the fingerprint on the client changes. We need to send that to ensure that the scheduler knows what workloads the client can accept. And we need to emit the eval so that the schedulers can, for example, schedule a system job on the client if the client is newly eligible for one.

So there's two things to figure out here:
* (1) What's causing the client to change its fingerprint frequently?
* (2) Can adjusting the eval GC help control memory growth?

For (1), you'll want to look at the client debug-level logs to see if there's any clue as to what's changing.

For (2), the graph you're showing with eval growth shows only 6k evaluations but the server memory has grown by roughly 2GiB, which is far too much to be accounted for by the evals. But note that the graph you're showing for memory usage is for `nomad.client.host.memory.used`, which is for _all_ processes on that client, not just Nomad. It looks like you're using the same agent for both client and server? Can you isolate the memory usage of the Nomad process from the background of the allocations on that host? It's entirely possible that whatever's causing the fingerprint to change could be causing problems with your allocations as well. If it is Nomad, it would be helpful if you could take a heap profile (`/v1/agent/pprof/heap`).

**Comment by jorgemarey** [comment]
Hi @tgross, thanks for your answer.

I understand the use for the `Node.Register` RPC. 
The thing is that this happened to us in production and we lost leadership so we restarted the servers, we couldn't get the to debug level to see anything at that point. I'll try to monitor the logs and make a heap profile next time it happens. 

If I remenber correctly, another time that this happened, the begging of this happen at the same time as we changed the active in out vault cluster. Could that have an impact in the fingerprint? 
Is there any log I can find to see the node that were constantly making the RPC call?

We do have the server running as a client (to launch log and metric recollection) but I don't think those processes would have been impacted, in any case I'll monitor them also if we see the memory grow again. 

As you can see in the next graph the memory of the servers is growing at the same time the memory on the instance. 

![memory_nomad](https://github.com/hashicorp/nomad/assets/6938602/aa12a381-70d2-487c-8532-4f94d4022c2e)

Thanks!

**Comment by jorgemarey** [comment]
Hi @tgross, the servers are v1.4.3, but some clients are still on 1.2.8 and 1.3.4. I guess that maybe one of those clients that doesn't have the fix for #14673 could be the origin of this problem? 

Even with that issue, I don't understand how a client without the fix (or several clients) can be constantly changing the fingerprint for vault or consul.

**Comment by tgross** [comment]
> Even with that issue, I don't understand how a client without the fix (or several clients) can be constantly changing the fingerprint for vault or consul.

The problem we fixed in #14673 was that if the connectivity to Vault was flapping, then the client would send a fingerprint update for each time it changed. So for each client that dropped connectivity with Vault and then reconnected, it would send 2 fingerprints. Each of those 2 fingerprints would create 1 evaluation for every job running on the node + 1 evaluation for every system job that has datacenters that include the node's datacenter.

So for example, suppose you have 10 nodes each running 5 service jobs, and there are 5 system jobs that are running on all the nodes. If all 10 of those nodes lose their connection to Vault and then reconnect, you'll get 20 fingerprints sent to the server. The server will turn those 20 fingerprints into (20 * (5+5)) = 200 evaluations. 

In your metrics we can see a lot more fingerprint RPCs than that, so that'd account for why you see so many evaluations. I'm not sure how many nodes are involved to be able to say whether that number of fingerprint RPCs would be unexpected.

**Comment by jorgemarey** [comment]
Hi @tgross. I understand.  We have nearly 300 clients in the cluster (same datacenter) with ~150 not yet on 1.4.X . We have over 200 service jobs and ~100 system jobs (that have constraints for running on a specific set of nodes). I guess that with this magnitude we could have reached a lot of evaluation in the event of a problem in vault, as it afects all nodes.

Once we update to 1.4.3 or newer, this problem "should" not happen, if this is really the problem.
One question that I have from this, looking at the code, the vault fingerprint will change when the version changes. So when we update vault to a different version, all this evaluations for all the nodes will be created in any case, am I right?

Thanks a lot for the explanation.
