### ISSUE TITLE
agent: advertise and addresses configuration is confusing

### ISSUE THREAD

**Issue by macb** [hashicorp/nomad#178]
It's unclear why both are required in addition to `bind_addr` and `port` configuration. I think collapsing advertise and address into a single configuration of `addresses` that documents that it will bind there and be advertised there.

**Comment by ryanuber** [comment]
@macb it is sometimes useful to advertise a different address than you bind to, for example in NAT cases. The advertise addresses are not required, and are automatically set to the bind address if unspecified. We still expose the functionality to handle more complex networks, though.

**Comment by ryanuber** [comment]
After reading the docs over I can see how it might be confusing. I think this might have been copy-paste error. I'll get that sorted so it is more clear.

**Comment by ryanuber** [comment]
I've updated the descriptions for these options in 3a69532. @macb does that clear things up?

**Comment by macb** [comment]
That makes sense and that commit is a lot more clear. If its only applicable to `servers` would it be worth nesting it under the `servers` key to make that clear?

**Comment by ryanuber** [comment]
We intentionally didn't nest that block since we currently have network settings in the outermost layer. If clients need to support an advertise address at some point we wanted to just have the single block for specifying all of the options, even in cases where a node might be a client and a server simultaneously.

I'm going to close this one out, but feel free to ask any other questions if that doesn't cover it!
