### ISSUE TITLE
Nomad job stop/start loses submission

### ISSUE THREAD

**Issue by mikenomitch** [hashicorp/nomad#17806]
In the Nomad 1.6 Beta, when I stop a job from the UI and then restart it, I lose the HCL file associated with the job. I still see a "Job Spec" field in the Definition tab, but it contains a big JSON object, rather than HCL.

![oh noes](https://github.com/hashicorp/nomad/assets/2732204/67c4f094-cc4c-4931-ab9f-ff456440da0f)

Given the JSON object, this feels more frontendy, so labeled as UI, but not sure.

**Comment by sevensolutions** [comment]
Wasn't this always a json? I think this is not a bug.

**Comment by philrenaud** [comment]
Hey @sevensolutions — one of the new things coming out in [Nomad 1.6](https://www.hashicorp.com/blog/nomad-1-6-adds-node-pools-ux-updates-and-more) is Jobspec Sources in the UI. The tab shown above should be showing the job spec in HCL, rather than the full definition object that is shown in the screenshot above. As such, this appears to be a bug in the upcoming functionality.
