### ISSUE TITLE
Modify a job if it is non-pending only

### ISSUE THREAD

**Issue by Kamilcuk** [hashicorp/nomad#17810]
### Proposal
When posting a job modification, there is a race condition. When a particular job is still pending, I want to update its version, but once it is running, I do not want to stop it. Getting the job current state and posting an update is a non-atomic operation. If a job starts in between me getting the current job specification and state and updating it, the job will be stopped, processes will be killed and the job will restart.

In other words, my proposal is to generally to increment JobModifyIndex when job starts running.

### Use-cases
The use case is when the processes run are precious, and we do not want to kill them or run them twice. Pending jobs are not run yet, so it is fine to modify them. Running jobs should not be touched.

### Attempted Solutions
There is no solution. Solution is to be real fast.

Using `EnforceIndex=True, JobModifyIndex=current_job.JobModifyIndex` when updating the job does not work, because `JobModifyIndex` is not incremented when a job starts.

### To reproduce ^^

```
job "test_nostoprunning" {
  datacenters = [
    "....",
  ]
  type = "batch"
  namespace = "dev"
  priority = 1
  reschedule { attempts = 0 }
  group "test_nostoprunning" {
    constraint {
      attribute = "....."
      operator = "set_contains_any"
      value = "${meta.hostname}"
    }
    restart { attempts = 0 }
    task "test_nostoprunning" {
      driver = "docker"
      config {
        image = "busybox"
        args = ["sh", "-xc", "sleep 100"]
      }
      resources {
        memory = 90000
      }
    }
  }
  meta {
    something = "something"
  }
}
```

```
# Makefile
define API
env -i curl -sSH "X-Nomad-Token: $$NOMAD_TOKEN" "http://localhost:4646/v1/$1?namespace=dev"
endef
define WAIT_FOR_RUNNING
while ! nomad status $1 | grep 'Status.*=.*running'; do sleep 1; done
endef
export NOMAD_NAMESPACE=dev
all: stop
        # Let's run one job named test_nostoprunning2 and wait until it starts.
        sed 's/test_nostoprunning/test_nostoprunning2/' ./test_nostoprunning.nomad.hcl | nomad run --detach -
        $(call WAIT_FOR_RUNNING, test_nostoprunning2)
        # Schedule a second job named test_nostoprunning
        nomad run --detach ./test_nostoprunning.nomad.hcl
        # Get the job test_nostoprunning json and prepare a json to update the job.
        $(call API,job/test_nostoprunning) > test_nostoprunning_job.json
        jq .JobModifyIndex test_nostoprunning_job.json
        jq \
                '.Meta += {"var": "val"} | {"EnforceIndex": true, "JobModifyIndex": .JobModifyIndex, "Job": .}' \
                test_nostoprunning_job.json > test_nostoprunning_job_modified.json
        # Stop test_nostoprunning2 and wait until test_nostoprunning starts running.
        # This is to present the race condition.
        nomad stop test_nostoprunning2
        $(call WAIT_FOR_RUNNING, test_nostoprunning)
        # Get the new JobModifyIndex
        $(call API,job/test_nostoprunning) > test_nostoprunning_job.json
        jq .JobModifyIndex test_nostoprunning_job.json
        # Post the job update. Note that JobModifyIndex is fixed.
        $(call API,job/test_nostoprunning) -XPOST --data @test_nostoprunning_job_modified.json && echo
        $(call WAIT_FOR_RUNNING, test_nostoprunning)
        # The status shows __two__ allocations.
        sleep 5
        nomad status test_nostoprunning

stop:
        set -x ; if nomad status test_nostoprunning2 || nomad status test_nostoprunning; then \
                yes | nomad stop -purge test_nostoprunning2 & \
                yes | nomad stop -purge test_nostoprunning & \
                wait ; \
        fi
```

```
$ make
# Let's run one job named test_nostoprunning2 and wait until it starts.
sed 's/test_nostoprunning/test_nostoprunning2/' ./test_nostoprunning.nomad.hcl | nomad run --detach -
Job registration successful
Evaluation ID: 134078be-1cd5-5147-036c-6946b5dfc812
while ! nomad status  test_nostoprunning2 | grep 'Status.*=.*running'; do sleep 1; done
Status        = running
# Schedule a second job named test_nostoprunning
nomad run --detach ./test_nostoprunning.nomad.hcl
Job registration successful
Evaluation ID: b56636f6-0c60-363e-bb3f-681f89afa751
# Get the job test_nostoprunning json and prepare a json to update the job.
env -i curl -sSH "X-Nomad-Token: $NOMAD_TOKEN" "http://localhost:4646/v1/job/test_nostoprunning?namespace=dev" > test_nostoprunning_job.json
jq .JobModifyIndex test_nostoprunning_job.json
7299345
jq \
        '.Meta += {"var": "val"} | {"EnforceIndex": true, "JobModifyIndex": .JobModifyIndex, "Job": .}' \
        test_nostoprunning_job.json > test_nostoprunning_job_modified.json
# Stop test_nostoprunning2 and wait until test_nostoprunning starts running.
# This is to present the race condition.
nomad stop test_nostoprunning2
==> 2023-07-06T04:35:59-04:00: Monitoring evaluation "3f3b2bda"
    2023-07-06T04:35:59-04:00: Evaluation triggered by job "test_nostoprunning2"
    2023-07-06T04:36:00-04:00: Evaluation status changed: "pending" -> "complete"
==> 2023-07-06T04:36:00-04:00: Evaluation "3f3b2bda" finished with status "complete"
while ! nomad status  test_nostoprunning | grep 'Status.*=.*running'; do sleep 1; done
Status        = running
# Get the new JobModifyIndex
env -i curl -sSH "X-Nomad-Token: $NOMAD_TOKEN" "http://localhost:4646/v1/job/test_nostoprunning?namespace=dev" > test_nostoprunning_job.json
jq .JobModifyIndex test_nostoprunning_job.json
7299345
# Post the job update. Note that JobModifyIndex is fixed.
env -i curl -sSH "X-Nomad-Token: $NOMAD_TOKEN" "http://localhost:4646/v1/job/test_nostoprunning?namespace=dev" -XPOST --data @test_nostoprunning_job_modified.json && echo
{"EvalID":"38b13943-0272-9abc-401f-75c2ce14f7c1","EvalCreateIndex":7299359,"JobModifyIndex":7299359,"Warnings":"","Index":7299359,"LastContact":0,"KnownLeader":false,"NextToken":""}
while ! nomad status  test_nostoprunning | grep 'Status.*=.*running'; do sleep 1; done
Status        = running
# The status shows __two__ allocations.
sleep 5
nomad status test_nostoprunning
ID            = test_nostoprunning
Name          = test_nostoprunning
Submit Date   = 2023-07-06T04:36:06-04:00
Type          = batch
Priority      = 1
Datacenters   = wee-dev
Namespace     = dev
Status        = running
Periodic      = false
Parameterized = false

Summary
Task Group          Queued  Starting  Running  Failed  Complete  Lost  Unknown
test_nostoprunning  0       1         1        0       0         0     0

Allocations
ID        Node ID   Task Group          Version  Desired  Status   Created  Modified
abb187db  c1907b96  test_nostoprunning  1        run      pending  5s ago   5s ago
12db1d82  c1907b96  test_nostoprunning  0        stop     running  5s ago   3s ago
```

^^ The job has two allocations, not one. Also, JobModifyIndex stayed at 7299345 after the job started running. Is it possible to pass a ModifyIndex to the request to make sure it is fully stateful?

**Comment by tgross** [comment]
@Kamilcuk I think the trouble you're going to have with this proposal is that it's not just the server state that's not atomic. The processes of the allocations aren't going to be atomic with the server state either. So you can get the following interleaving:

* Client starts a task process
* A request to the server checks that the job isn't running and registers a new version of the job
* The client updates the server with the task process health, and the server marks the job as running

So even if we set the `JobModifyIndex` as you've described, it wouldn't prevent the problem you're describing.

But maybe we can brainstorm a better solution if you can describe the underlying problem a little more. Why are you trying to update the job destructively while it's in a pending state to begin with?

**Comment by Kamilcuk** [comment]
> Why are you trying to update the job destructively while it's in a pending state to begin with?

We have a task scheduling service built on top of Nomad. I am scheduling jobs with parameters defined by the user. Then the user comes, and changes the parameters, or parameters change because the time of the day has changed.

I do not use nomad run job + wait for evaluation to finish, because it would take days to schedule 10s thousands of tasks. Instead, in Nomad, I keep a list of pending tasks in Nomad and Nomad can schedule them when something is free. When the service notices that the list of pending tasks in Nomad is lower, it schedules new tasks to keep the pending list utilized.

I do not want to stop user tasks once they start running. But, if a task is still pending in Nomad, I want to modify it to react to changing input parameters.

**Comment by tgross** [comment]
@Kamilcuk just wanted to follow-up on this.

For some background, the `JobModifyIndex` is the index at which we last modified the _definition_ of the job, which is why that's what the check index uses. It's so that you can say "only update this job definition if another user hasn't since I ran `nomad job plan`".

The job's `ModifyIndex` will in turn be updated whenever we write changes to the Job object of any kind. So when the job's evaluation is planned by the scheduler, the job is changed to `running` but that does not mean that any of its Allocations have started, only that they've been accepted by the leader and when the clients check in for new allocations they'll get placed.
So the `ModifyIndex` on the Job is not the same as the `ModifyIndex` of the Allocation objects that make up the job, and that's what you actually care about from what I can tell.

So for example, if I run a job and then query for the various indexes, I get a few different answers:

```sh
$ nomad operator api /v1/job/example | jq .JobModifyIndex
11

$ nomad operator api /v1/job/example/allocations | jq '.[].ModifyIndex'
16

$ nomad operator api /v1/job/example | jq .ModifyIndex
18

$ nomad operator api /v1/job/example/deployments | jq '.[].ModifyIndex'
18
```

The `JobModifyIndex` is 11, and that's the Raft index of when I wrote the definition for the job. The allocation's `ModifyIndex` is 16, because that's when the last allocation event got written from the client. And the job and deployment's `ModifyIndex` is 18, because that's when the deployment was marked complete (and the job was marked as finished deploying in the same transaction).

We're definitely not going to want to change the definition of `JobModifyIndex`, as that's used for the current [`-check-index`](https://developer.hashicorp.com/nomad/docs/commands/job/run#check-index) and changing it now would break a lot of existing behaviors and the entire plan-to-run workflow. 

I think would be open to having a new CLI flag (and associated API changes) for `-check-modify-index` that's more strict and checks the `ModifyIndex` field. But I don't think it actually helps you here, as that would only prevent someone from running the job if the allocation states have changed since you last checked them _and_ that results in write to the Job object, which we can't guarantee has happened. Allocations can enter the `running` state without updating the Job in the same Raft index.

**Comment by tgross** [comment]
Following up on this. This problem is fairly esoteric and doesn't have a good solution _in Nomad_ with the architecture we have. The best way to solve this is going to be adding locking to the application and then having something upstack that checks those locks before deploying. Going to close this out.
