### ISSUE TITLE
Support SuccessBeforePassing and FailuresBeforeCritical in the scripts checks

### ISSUE THREAD

**Issue by tatototino** [hashicorp/nomad#18029]
### Use-cases

Try to use  "SuccessBeforePassing" and "FailuresBeforeCritical" options > 0 in the job, example:

    {
                  "Name": "Check X table",
                  "Type": "script",
                  "Command": "/opt/mssql-tools/bin/sqlcmd",
                  "Args": [
                    "-S",
                    "localhost",
                    "-U",
                    "x",
                    "-P",
                    "x",
                    "-Q",
                    "USE X; SELECT * FROM XX"
                  ],
                  "Path": "",
                  "Protocol": "",
                  "PortLabel": "mssql-port",
                  "Expose": false,
                  "AddressMode": "",
                  "Interval": 9000000000,
                  "Timeout": 2000000000,
                  "InitialStatus": "",
                  "TLSServerName": "",
                  "TLSSkipVerify": false,
                  "Method": "",
                  "Header": null,
                  "CheckRestart": null,
                  "GRPCService": "",
                  "GRPCUseTLS": false,
                  "TaskName": "X-server",
                  "SuccessBeforePassing": 3,
                  "FailuresBeforeCritical": 3,
                  "Body": "",
                  "OnUpdate": "require_healthy"
                }

**Comment by jrasell** [comment]
Hi @tatototino, these parameters are supported. Could you clarify how you are registering the job specification, what version of Nomad you are using, and any errors you are receiving? Thanks.

**Comment by tatototino** [comment]
Hi Jrasell, I just have a service with some checks like bellow:

![image](https://github.com/hashicorp/nomad/assets/10597278/487a7d44-e58d-4c77-a0f5-bdb74ebaba27)

when I change the paramenter to greatest 0 like image bellow:

![image](https://github.com/hashicorp/nomad/assets/10597278/4b2fe0ff-8482-4a9d-9e7c-4ad919511098)

and When I plan the job  I got the error bellow:

![image](https://github.com/hashicorp/nomad/assets/10597278/ee072741-aacd-4ba8-9c73-142566829ed4)


All nodes running the nomad v1.6 (latest one) on windows server 2022

**Comment by jrasell** [comment]
Hi @tatototino and thanks for the clarification. Consul does not support setting [`SuccessBeforePassing`](https://developer.hashicorp.com/consul/api-docs/agent/check#successbeforepassing) or [`FailuresBeforeCritical`](https://developer.hashicorp.com/consul/api-docs/agent/check#failuresbeforewarning) on script checks which is why the plan returns the validation error.

This is unfortunately a limitation on Consul rather than Nomad. I would suggest raising a GitHub feature request against the [Consul repo](https://github.com/hashicorp/consul/issues/new/choose) detailing your request and any use cases you have, to help the team understand the addition. When this is released within Consul, it would be possible to update Nomad to utilise this feature.
