### ISSUE TITLE
task option to not split stdout and stderr

### ISSUE THREAD

**Issue by jippi** [hashicorp/nomad#1810]
Hey

For some processes, it's really inconvenient to have stdout and stderr in two different files, with no way to merge them into one continuous stream of events.

Having an option to tell nomad to dump stderr into stdout (Similar to `2>&1`) would be nice to have.

**Comment by dadgar** [comment]
How are you consuming logs? Would it be fine if we logged timestamps so that it was mergable and/or if `nomad logs` combined them?

**Comment by jippi** [comment]
i consume them from both `nomad logs` and `nomad-ui` - having nomad do the heavy lifting would be nice.. though my logs already contain a timestamp.

Ideally i would just have nomad merge the streams into one file and not splitting it at all :)

**Comment by dadgar** [comment]
@jippi To be honest, from the systems standpoint I prefer what it is doing. With a timestamp any tool can merge them but it is better to keep the different streams separate. Otherwise you have to increase write volume to tag each line with which stream it came from.

I am going to close this for that reason.
