### ISSUE TITLE
api: Stub() method causes panic when Allocation has a nil job

### ISSUE THREAD

**Issue by gabrielaccelbyte** [hashicorp/nomad#18134]
When using the Nomad SDK, I've encountered an issue where the Stub() method causes a panic if the Allocation object it's called on has a nil Job.

https://github.com/hashicorp/nomad/blob/2fd508d4f12fec139e495041b5ee1314eb1cd1dd/api/allocations.go#L322

https://github.com/hashicorp/nomad/blob/2fd508d4f12fec139e495041b5ee1314eb1cd1dd/api/allocations.go#L323

**Comment by tgross** [comment]
Hi @gabrielaccelbyte yeah that should be handled more gracefully for sure but generally the expectation is that the `Allocation` object you'd call `Stub()` on came from the server where it's been canonicalized. Otherwise it doesn't have much use?

Certainly something to fix. I guess we can simply not set those fields and then the resulting stub is an invalid allocation stub, but that's ok because the original allocation was invalid as well.

**Comment by gabrielaccelbyte** [comment]
Hi @tgross,

Thank you for your response. I understand the expectation for the Allocation object to come from the server where it's been canonicalized. However, in my specific use case, I'm receiving the Allocation object from the Nomad event stream, which doesn't always include the Job information.
