### ISSUE TITLE
Nomad renders incorrect service address and ports in template.

### ISSUE THREAD

**Issue by blmhemu** [hashicorp/nomad#18203]
### Nomad version
Output from `nomad version`
1.6.1

### Operating system and Environment details
Fedora 38

### Issue
Here is the template in the nomad job
```
reverse_proxy {{ range nomadService "svc" }}{{ .Address }}:{{ .Port }} {{ end }}{
  fail_duration 30s
}
```
here is what is rendered
```
reverse_proxy 10.1.1.3:29154 10.1.1.3:30574 10.1.1.3:30306 {
   fail_duration 30s
}
```

But the thing is only one of the above ip:port is valid. There is only one service (count==1) and even nomad shows only one allocation. This leads to the situation where my reverse proxy fails to get upstream 66% of the time.

This happens not just for one service, but for multiple services. I had to manually delete (cleanup) the services from nomad to fix this.

**Comment by jrasell** [comment]
Hi @blmhemu, what does the CLI output of the [`nomad service info some-service`](https://developer.hashicorp.com/nomad/docs/commands/service/info) show? The template process and CLI both use the same API call, so I would expect these to match.

**Comment by blmhemu** [comment]
Yup it does match - The service info shows three IDs

**Comment by blmhemu** [comment]
FWIW, I tried `nomad system gc && nomad system reconcile summaries`, but it did not help.

**Comment by lgfa29** [comment]
#16616 is a longer issue about services failing to be removed, which smells a lot like the problem here. Others in that thread have also reported the problem happening with Nomad service discovery so I will update the title.

@blmhemu I will close this one as duplicate to focus the discussion in a single place. Feel free to 👍 and add any additional comments there.

Thanks for the report!
