### ISSUE TITLE
Atlas integration not taken by servers

### ISSUE THREAD

**Issue by timfallmk** [hashicorp/nomad#183]
I'm setting up a 3 server cluster for bootstrapping and I've tried passing the `atlas` config in through a config file or through command line arguments, and neither seem to be picked up by the agent. I've tried the following:

``` shell
nomad agent <extra flags here> -atlas=timfall/nomad -atlas-token="<token>" -atlas-join 
```

And also passing it in `config.hcl`

``` hcl
atlas {
    infratstructure = "timfall/nomad-cluster"
    token = "<token>"
    join = true
}

The agent still shows as `Atlas: <disabled>` when running.
```

**Comment by ryanuber** [comment]
Hey @timfallmk,

The Atlas side of things doesn't yet support Nomad, but it is a feature which should be introduced in a coming release. We added all of the internals to Nomad to make that work, but we are still working on the Atlas side to tie it all together.

**Comment by alanwill** [comment]
Hey @ryanuber any idea when this should be addressed?

**Comment by ryanuber** [comment]
Work is being done on this internally, but we are still deciding what the final UX will look like and polishing things up. If you attach your Nomad infrastructure to Atlas using the latest release you should see the settings reflected in the CLI output, and you will probably notice REST API queries coming through from Atlas once in a while. You can disable the Atlas integration to stop this for now since it is still not visible to users. The main answer to your question is "soon", but with no concrete dates set. Hang in there!

**Comment by timfallmk** [comment]
We're all waiting @ryanuber!

**Comment by alanwill** [comment]
Thanks @ryanuber I'm less interested in the UI and more interested in getting auto-join capability :)

**Comment by gerard-veyos** [comment]
same here for auto-join capability.

**Comment by schmichael** [comment]
Atlas supported has been deprecated for some time and will be removed in 0.7.1. See #3493 for details.
