### ISSUE TITLE
Improve error message 'unsupported protocol scheme ""'

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#18308]
### Proposal
```
$ nomad plan postgres.nomad.hcl
Error during plan: Put "/v1/job/nomad-postgres/plan": unsupported protocol scheme ""
```

It is not clear what does this message mean.

**Comment by lgfa29** [comment]
Hi @EugenKon 👋 

This message comes from within [Go's standard library](https://github.com/golang/go/blob/738d2d9068492dfb81dc350db005fdd52f2481b6/src/net/http/transport.go#L560) and we can't modify it. 

It means that the URL you are using to connect to Nomad is missing the protocol component and, from the rest of the error message, it also seems to be missing the hostname and port.

Check if you have an environment variable named `NOMAD_ADDR` set and make sure it's a full URL, such as `https://nomad.my-domain.com:4646`.

**Comment by EugenKon** [comment]
@lgfa29 Ok, but if error occur nomad could display a hint, eg.:
```
HINT: URL should be in format https://nomad.my-domain.com:4646
HINT: Check your NOMAD_ADDR
```

You are not limited to display error messages from system libraries as is.

**Comment by lgfa29** [comment]
Hi @EugenKon 👋 

Apologies for the delay here. We could wrap errors at the `api` package to deal with common messages like this. Then this type of hint systems could be centralized in a specific place instead of sprawled over the code. 

We would need to think through the design a little better, but I will reopen this to keep the discussion going.

Thanks again for the suggestion!
