### ISSUE TITLE
bubble up the go-getter failure reason

### ISSUE THREAD

**Issue by shantanugadgil** [hashicorp/nomad#18442]
### Proposal
Currently the failure reason for go-getter is shown in agent logs, but not in the `alloc status`. bubbling it up to the `alloc status` would be useful for debugging.

### Use-cases
If I have a tar archive with too many files (> 4096), and the extraction fails, the reason for failure is not shown in `alloc status`, although the error message is seen in agent logs.

### Attempted Solutions
N/A. The solution would be do patch some function definitions; to propagate the error upto alloc status.

EDIT: changed the `logs` to `status`, which is what I actually was trying to do! :man_facepalming:

**Comment by tgross** [comment]
From a design standpoint, I'm not sure we ever want anything happening in the agent to go to the allocation logs rather than the agent's logs, because that will interfere with application logging formats. The Task Events are where we typically want to send this sort of thing, and I think that's what you've done in https://github.com/hashicorp/nomad/pull/18444 anyways.

**Comment by shantanugadgil** [comment]
> From a design standpoint, I'm not sure we ever want anything happening in the agent to go to the allocation logs rather than the agent's logs, because that will interfere with application logging formats. The Task Events are where we typically want to send this sort of thing, and I think that's what you've done in #18444 anyways.

I got `alloc status` and `alloc logs` mixed up.

Showing the actual reason for the error in the *status* is what I meant to type. (I'll update the description above)

**Comment by tgross** [comment]
Closed by #18444, which shipped today in Nomad 1.6.2
