### ISSUE TITLE
Nomad alloc logs -f not working as expected

### ISSUE THREAD

**Issue by jurealeksic** [hashicorp/nomad#18550]
### Nomad version
Nomad v1.6.2
BuildDate 2023-09-13T16:47:25Z
Revision 73e372ad94033db2ceaf53468b270a31544c23fd

### Operating system and Environment details
Ubuntu 22.04
### Issue
nomad logs -f <allocation_id> does not show any logs. 
### Reproduction steps
Run: 
nomad alloc logs -f <allocation_id> 
#### Expected Result
Allocation logs from beginning till end and would stream new logs as they are generated.
#### Actual Result
One new line is generated and nothing afterwards.

**Comment by jurealeksic** [comment]
Update: 
It works as expected when -stdout flag is supplied. 
`nomad logs -f -stdout 296e72c5 |head -1
Zookeeper configuration:
`
However that seems to conflict with the commit below as it's expected to stream both stout and stderr when -f flag 
 is supplied 
 
 https://github.com/hashicorp/nomad/commit/4848bfadec59fe2736541607a73f9f2e54e8fd7c

**Comment by jrasell** [comment]
Hi @jurealeksic and thanks for raising this issue. The difference is caused as a result of using different offsets when following either a single file (such as when specifying `-stdout`) or multiple files which is the standard when no file is specified. While this made sense when the feature was implemented, I can see how this would be confusing. I'll look into raising a PR, so that the same offset is used in either case, to provide consistency.
