### ISSUE TITLE
Conditional operators in node constraints

### ISSUE THREAD

**Issue by gaetanww** [hashicorp/nomad#18792]
### Proposal

`IF` and `ELSE` logic in constraints. For example, `IF` we have nodes that verify a constraint, `ELSE` allocate to other nodes. 

### Use-cases

In our use case, a job MUST be allocated to a node with a specific resource (e.g., a device or a file is present) if it's available. If it's not available, then it can be allocated to other nodes.

### Attempted Solutions

In our current solution, we're using affinities to suggest a strong preference for a node with an available resource. That way, jobs can still be scheduled on other nodes if the resource is not present anywhere. However, this does not capture the following requirement since affinities are not hard constraints:
- a job MUST be allocated to a node with a specific resource if it's available

**Comment by jrasell** [comment]
Hi @gaetanww and thanks for raising this issue. When using affinities, are you using [`affinity.weight`](https://developer.hashicorp.com/nomad/docs/job-specification/affinity#weight), this might help describe the placement solution you desire where the allocation has a very strong affinity for placement on particular set of clients.

The current design of job specification constraints means adding some form of `if/else` logic would break backwards compatibility and require rewriting the block design. The logic would also impact the scheduler efficiency as the feasibility checking would  need to be run twice when the first conditional block did not find a match. This would be particularly computationally expensive when using features such as spread scheduling.

Please let me know if you have further thoughts, otherwise I plan to close this issue seeing as affinities seem to be the correct approach.

**Comment by jrasell** [comment]
Close due to lack of update and interaction.
