### ISSUE TITLE
Expand on `fail` restart mode

### ISSUE THREAD

**Issue by sethvargo** [hashicorp/nomad#1885]
From https://github.com/hashicorp/nomad/pull/1883#discussion_r85465530, @dadgar said:

> I think you need to expand on this point. Since that statement is only true when attempts = 0, since it doesn't allow the job to restart. It is also useful when the job doesn't have dependencies such that a failure is likely to occur every time.

But I need a little bit of guidance on how to make that clearer. The old documentation just said:

> - `fail` - `fail` will not restart the task again.

**Comment by dadgar** [comment]
Sure. So the current documentation is: 
```
Instructs the scheduler to not attempt to restart the task on failure. This mode is useful for non-idempotent jobs which are not safe to simply restart.
```

The point I was trying to make is that the statement "this is useful for jobs that are not safe to simply restart" only is true when the restart policy specifies `attempts = 0`. That is because if `attempts = n`  then the task would still be restarted up to `n` times. This is in contradiction to the statement that this mode is useful for tasks that can not handle restarts.

I was suggesting that we document this mode as being useful for tasks were if it failed a few times it is unlikely to ever succeed.
