### ISSUE TITLE
Invalid memory reservation calculation

### ISSUE THREAD

**Issue by kinnalru** [hashicorp/nomad#18872]
### Nomad version
Nomad v1.6.2
BuildDate 2023-09-13T16:47:25Z
Revision 73e372ad94033db2ceaf53468b270a31544c23fd

### Operating system and Environment details
Debian 5.10.149-2 (2022-10-21) x86_64
Docker Driver
Memory oversubscription enabled
 
### Issue

Client memory reservation  is not used for job allocation.
```
  reserved {
    memory = "2048"
  }
```
Total memory:   ` 7,957 MiB Total`
Jobs allocated: `6,446 MiB`

Memory oversubscription enabled.

#### Expected Result
Total memory allocated by jobs **must not** be greater than 5909 ( 7957 MiB - 2048MiB)

#### Actual Result
Total memory allocated by jobs **IS** greater than 5909 ( 7957 MiB - 2048MiB)

![Screenshot_20231026_150640](https://github.com/hashicorp/nomad/assets/1270997/4944dc53-8f95-421d-a40c-4cae1ea712e1)
![Screenshot_20231026_130846](https://github.com/hashicorp/nomad/assets/1270997/0914062b-bdb7-4c1d-a862-fdf026cea523)

**Comment by tgross** [comment]
@kinnalru you're saying "jobs allocated" here, but is that the amount of memory the tasks are _using_ or the sum of their `memory` fields? Because I would expect that with memory oversubscription enabled that:

`sum('memory' field of all tasks) < total memory - client reserve`

And that the value of `max_memory` would allow the _usage_ by tasks to exceed that reserve. So for a simplified example, suppose I have a single allocation with multiple tasks:

```hcl
task "a" {
  resources {
    memory = 2000
    max_memory = 3000
  }
}

task "b" {
  resources {
    memory = 2000
    max_memory = 3000
  }
}

task "c" {
  resources {
    memory = 2000
    max_memory = 3000
  }
}
```

And the client has 9000 MiB of memory, with 2000 MiB reserved. In this case, this allocation can be placed because `2000 + 2000 + 2000 < 9000 - 2000`. But because the memory is oversubscribed, the allocation risks using up memory that has been reserved.

**Comment by tgross** [comment]
Didn't get a reply back on this so I'm going to close it out. If you've got an answer to the open question I'll be happy to re-open.
