### ISSUE TITLE
Add support for fractional `cores`

### ISSUE THREAD

**Issue by slonopotamus** [hashicorp/nomad#18911]
### Proposal

Currently, `resources { cores: N }` only accepts an integer. In contrast, in Kubernetes, `resources: limits: cpu:` supports fractional values like `0.1`. This feature request is about adding the same functionality to Nomad.

### Use-cases

I have a job that needs 0.5 of a core, but it is currently impossible to describe that in Nomad, so I end up with underutilization of machine resources because cannot run two jobs per core.

### Workarounds

I could use `resources { cpu: N }`, but that is much less convenient.

**Comment by shoenig** [comment]
Using fractional cores seems more convenient at first, but as we enter a world with heterogeneous cores on a single processor I believe specifying CPU resources in terms of bandwidth is more sensible.

In Nomad, `cores` should only be used for reserving (as in _isolating_) CPU cores for a task. For less demanding tasks, use `cpu` so that those tasks can share the remaining pool of CPU cores.
