### ISSUE TITLE
Nomad does not re-create connect-proxy docker containers on envoy version changes

### ISSUE THREAD

**Issue by scor2k** [hashicorp/nomad#19095]
### Nomad version
```
$ nomad version
Nomad v1.6.1
BuildDate 2023-07-21T13:49:42Z
Revision 515895c7690cdc72278018dc5dc58aca41204ccc
```

```
$ consul version
Consul v1.16.2
Revision 68f81912
Build Date 2023-09-19T19:29:18Z
```

### Operating system and Environment details

```
$ cat /etc/*release*
CentOS Linux release 7.9.2009 (Core)
```

### Issue

We did an upgrade of the Consul version on the cluster. At the same time, we upgraded the Envoy version to the compatible one. After the components were upgraded and both consul and nomad clusters restarted we did the product rollout. We use consul-connect. If the product version was changed - all was good, the new Envoy was delivered. In the case when the product version was the same - Envoy was also the old one. 

### Reproduction steps

```
$ /opt/nomad/current/nomad init -connect
$ /opt/nomad/current/nomad job run example.nomad.hcl

# compare the Envoy versions
$ sudo cat /opt/nomad/conf.d/nomad.hcl | grep envoy
$ docker ps | grep envoy

# update the Envoy version in the nomad.hcl file, do nomad restart

$ sudo vim /opt/nomad/conf.d/nomad.hcl
$ sudo cat /opt/nomad/conf.d/nomad.hcl | grep envoy

$ /opt/nomad/current/nomad job run example.nomad.hcl
$ docker ps | grep envoy

# As a result, the Envoy version will be the same as it was before the upgrade

```

#### Expected Result

The Envoy version be updated 

#### Actual Result

The Envoy version stays the same.

**Comment by tgross** [comment]
Hi @scor2k! This is expected behavior. We try _very_ hard in Nomad to ensure that once an allocation has been placed, we don't interrupt it as long as it's healthy, unless there's explicit user intervention (ex. kicking off a new deployment, just as you've seen). There's no way to replace the Envoy container in-place without interrupting traffic to the application, so that'd be a "destructive" update and require replacing the allocation. If you want to upgrade a job, you'll need to re-deploy it.

**Comment by scor2k** [comment]
Hi @tgross, thank you for a really quick answer. But the problem is - I did re-deploy =) 

```
$ /opt/nomad/current/nomad job run example.nomad.hcl
```

I did re-deploy again after the upgrade.

**Comment by tgross** [comment]
Ok, given that context it's definitely working as I'd expect but that's definitely not _good_ behavior. The workflow for the Envoy proxy is roughly this:

1. You register a job
2. The RPC handler injects the sidecar with with the version left open for interpolation
3. The resulting job and an evaluation get written to Raft
4. A scheduler worker picks up the evaluation and determines the job is new or something in the state has changed
5. The scheduler creates a plan, that results in an allocation being placed on a client
6. A hook on the client interpolates the Envoy version based on what the local Consul agent allows (or what the the client has configured in its [`meta`](https://developer.hashicorp.com/nomad/docs/configuration/client#meta) block for `meta.connect.sidecar_image`).

So in this case, we're getting stuck at step 4, because as far as the scheduler is concerned you haven't pushed any changes to the job. Your workaround of adjusting the CPU allocation will work because the scheduler sees a change (you can also do this by having an `env` block that has an environment variable that you increment).

The challenge with fixing this is that until we've decided on a placement on a specific client, we don't know that the version has changed, but we don't decide on a placement unless we know a version has changed! So there's a circular dependency on the data we'd need to detect the change. There's been some discussion of having a `job run -force` flag that would let us bypass that scheduler logic, but evaluations are idempotent over server state -- adding a flag to an evaluation to change the behavior of the scheduler doesn't work reliably because Nomad de-duplicates evaluations when feasible.

Which is all to say, this is definitely unfortunate behavior. I'll mark it for further discussion and roadmapping, but I just wanted to let you know the fix is surprisingly non-trivial.

**Comment by scor2k** [comment]
Thank you for your clarification, @tgross, it was really interesting and helpful to understand Nomad even more =) 

>  the fix is surprisingly non-trivial.

haha, yeah, it's expected. The workaround with the CPU resources is the easiest and best way to implement it (from the end user perspective for sure).
