### ISSUE TITLE
Latest documentation build breaks indexed pages

### ISSUE THREAD

**Issue by timperrett** [hashicorp/nomad#1918]
The latest update to the Nomad documentation site does not properly redirect from old pages that were indexed from google. Given this is how people typically discover things, and the nomad site should at least add redirects from the old pages to the new, can this be addressed? It's frustrating for users as its not clear where things got re-located. Example:

https://www.google.com/search?q=nomad+attributes&oq=nomad+attributes&aqs=chrome..69i57.1990j0j1&sourceid=chrome&ie=UTF-8

https://www.nomadproject.io/docs/jobspec/interpreted.html

I'm not even sure where this got relocated too.

**Comment by sethvargo** [comment]
Hi @timperrett 

Thank you for reaching out. This is a known issue. We do not have a good way to do redirects right now, since the sites are statically hosted on S3. We are doing a lot of work to improve the SEO of the sites, which includes breaking up content into other pages.

I've submitted the new site index to google, so that should be updated shortly. The exact page you are looking for is now here:

https://www.nomadproject.io/docs/runtime/interpolation.html

Again, sorry about the breaking change. We are working to clear up the old indexes as quickly as possible.

**Comment by timperrett** [comment]
@sethvargo absolutely there's a solution, even if you're hosted on S3. You just need to take a trip back to the 90s:

```
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="refresh" content="0;URL='https://nomadproject.io/page/thats/new/'" />
    <title>Nomad Redirect</title>
  </head>
  <body>
    Redirecting to <a href="https://nomadproject.io/page/thats/new/">nomadproject.io</a>
  </body>
</html>
```

We had this same problem with Github Pages, and the above solution - whilst hacky - solves the issue and massively eases transition pain for users.

**Comment by sethvargo** [comment]
Okay thanks for the feedback - we will try to get these redirects in place asap.

**Comment by sethvargo** [comment]
This is fixed
