### ISSUE TITLE
Create a search field in Nomad by tags

### ISSUE THREAD

**Issue by eduardosramos** [hashicorp/nomad#19256]
I would like to search for a job in Nomad using tags, just like there is in Consul. Tnks

![image](https://github.com/hashicorp/nomad/assets/4673992/29312f39-ef28-4790-93c9-fadf89dcd755)

**Comment by jrasell** [comment]
Hi @eduardosramos, not a problem.

On the jobs page the Nomad UI has the ability to filter and search for jobs as shown below. I don't think it would make sense to be able to search via service tags here and computationally any implementation would be very expensive due to the nested nature of services and tags.
![image](https://github.com/hashicorp/nomad/assets/2980562/0d468e2d-21c3-4add-834d-bc285f7e4f08)

When looking at a jobs services, we can see the tags, but there is no ability to filter based on these. Would this request therefore be to filter this page based on tags?
![image](https://github.com/hashicorp/nomad/assets/2980562/ddca125e-bb3d-494d-bebc-d58d491cb007)

**Comment by jrasell** [comment]
Closing due to no response to followup comment.
