### ISSUE TITLE
Troubleshooting blocked evaluation

### ISSUE THREAD

**Issue by suikast42** [hashicorp/nomad#19446]
I have had played with  the cpu settings of my vm. After that some allocations can't be placed.  

![image](https://github.com/hashicorp/nomad/assets/5046525/5ac8a245-ad6a-4d8e-8e12-5be56003660f)

With that Evaluation Response. 

```json
{
  "priority": 50,
  "type": "service",
  "triggeredBy": "queued-allocs",
  "status": "canceled",
  "statusDescription": "existing blocked evaluation exists for job \"observability\"",
  "failedTGAllocs": [
    {
      "Name": "mimir",
      "CoalescedFailures": 0,
      "NodesEvaluated": 1,
      "NodesExhausted": 0,
      "NodesAvailable": {
        "nomadder1": 1
      },
      "ClassFiltered": null,
      "ConstraintFiltered": null,
      "ClassExhausted": null,
      "DimensionExhausted": null,
      "QuotaExhausted": null,
      "Scores": null
    }
  ],
  "previousEval": "13dc8866-7b53-a94a-4d35-868913816f80",
  "nextEval": null,
  "blockedEval": null,
  "modifyIndex": 2518,
  "modifyTime": "2023-12-12T10:09:42.439Z",
  "createIndex": 2512,
  "createTime": "2023-12-12T10:09:35.334Z",
  "waitUntil": null,
  "namespace": "default",
  "plainJobId": "observability",
  "relatedEvals": [
    "13dc8866-7b53-a94a-4d35-868913816f80"
  ],
  "job": "[\"observability\",\"default\"]",
  "node": null
}
```

Nomad logs 

[Explore-logs-2023-12-12 11_11_32.txt](https://github.com/hashicorp/nomad/files/13646809/Explore-logs-2023-12-12.11_11_32.txt)

But how can I find the exact error for the placement error. 

An information like not enough RAM or CPU could be very helpful.

**Comment by tgross** [comment]
Hi @suikast42! Nomad tries to keep only 1 evaluation per job in each stage of the eval broker, so that the scheduler doesn't have to run lots of no-op evaluations. (See [Load Shedding in the Nomad Eval Broker](https://www.hashicorp.com/blog/load-shedding-in-the-nomad-eval-broker) if you want to learn more about this.) 

So the evaluation you've got here was _canceled_, not blocked, because there was another blocked eval already:

> "statusDescription": "existing blocked evaluation exists for job \"observability\"",

What you'll want to do is [`nomad eval list -job $jobid`](https://developer.hashicorp.com/nomad/docs/commands/eval/list) to find the blocked eval. Then you can `nomad eval status` on that evaluation to find out what it's blocked on.

**Comment by jrasell** [comment]
Hi @suikast42, I am going to close this issue as we have not heard back and the comment Tim seems accurate in describing the steps to take to understand the blocked eval. Thanks.

**Comment by suikast42** [comment]
Thanks. Butr I can'T reproduce this anymore. Will look at back if that occurs again.
