### ISSUE TITLE
Nomad server locks up on disk I/O when stopping lots of batch jobs

### ISSUE THREAD

**Issue by MattJustMatt** [hashicorp/nomad#19489]
### Nomad version
1.6.3

### Operating system and Environment details
Linux / CentOS / Google Cloud Engine VMs
4 core VM, networked SSD

### Issue
Nomad hangs when stopping a 5,000 allocation batch job and seems to get stuck with the primary node reading an (presumably) excessive amount of data from disk. 

### Reproduction steps
- Spin up a 3 node cluster with networked storage and N2 (high-cpu) GCE VMs
- Launch a batch job with 5,000 nodes
- Stop that job

#### Expected Result
- Despite the under sized cluster, given no other input, _eventually_ the allocations stop.

#### Actual Result
One of the server nodes falls behind in Raft applied index, last contact time for a node goes up, and elections are triggered.
<img width="946" alt="image" src="https://github.com/hashicorp/nomad/assets/5265661/dd3bb6c7-0aae-4e2d-a19d-bcaed9f8a6b6">
... but the cluster after hours does not recover from this and stays in a "no leader" state with 280MiB/s of disk throughput constantly thrashing on one of the servers.

<img width="756" alt="image" src="https://github.com/hashicorp/nomad/assets/5265661/7c2cdcfc-a0aa-498d-bc9d-8c344f2a9a53">

Given it's 280MiB/s of reads for ~1 hour, I'm thinking there may be a bug here (in addition to the obvious under sizing of the cluster for this workload)

I'm guessing the overall solution is more IOPS/Disk throughput (local SSDs on GCE), but I'm wondering how to recover from this scenario (restarting the server cluster and clients returns to the same state). Clearing the data dir is the only thing that has worked so far.

**Comment by tgross** [comment]
@MattJustMatt something a little unclear from your description: are the Nomad server nodes also being used as the clients running those 5000 batch allocations? Because if so, it's important to keep in mind we don't recommend this specifically because the client state changes and workloads will conflict with the Raft throughput.

In terms of debugging, as one of the servers falls _very_ far behind the others it's going to try to load state from snapshots from the other servers. If those reads are saturating disk (which seems likely given the flatline in your graph), that may be preventing the server from joining Raft and then no forward progress can be made. You should find server logs indicating the state of replication.

I suspect that you've also got logs warning you about large Raft log entries, because those 5000 allocations belong to a single job, perhaps have a large payload attached, and are all being marked as "stop" in a single plan apply from the scheduler once you  stop the job.

**Comment by MattJustMatt** [comment]
Thanks for taking a look!

The clients and allocations are running on separate dedicated hardware (10 nomad clients on bare metal)

This is the job file:
`job "spark" {
  type = "batch"

  parameterized {
    meta_required = ["gameId", "connectTime"]
  }

  // Strongly prefer nodes named spark
  affinity {
    attribute = "${node.unique.name}"
    operator  = "regexp"
    value     = "spark"
    weight    = 100
  }

  group "spark-players" {
    scaling {
      enabled = true
      min     = 0
      max     = 1024
    }

    ephemeral_disk {
      migrate = false
      size    = 10
      sticky  = false
    }

    reschedule {
      attempts = 0
      unlimited = false
    }

    restart {
      attempts = 0
    }

    task "spark-player" {
      driver = "docker"

      logs {
        max_files     = 1
        max_file_size = 5
        disabled      = false
      }

      env {
        GAME_VERSION     = "NA"
        GAME_ID          = "${NOMAD_META_gameId}"
        CONNECT_TIME     = "${NOMAD_META_connectTime}"
        REST_API_KEY     = "redacted"
      }

      resources {
        cpu    = 1024
        memory = 1024
      }

      config {
        image = "redacted"
      }
    }
  }
}`

And here is the full log from the server nodes:

[iofreeze.txt](https://github.com/hashicorp/nomad/files/13689652/iofreeze.txt)

I do see the large raft entry warning, but I'm confused why the entry would be so large given this job (there is no payload)

The disk is definitely saturated trying to load the snapshot, but I left it going for > 1 hour at > 200MB/s last night and made no progress.

**Comment by tgross** [comment]
> I do see the large raft entry warning, but I'm confused why the entry would be so large given this job (there is no payload)

Sometimes that's going to be from the plan applier (see [scheduling internals](https://developer.hashicorp.com/nomad/docs/concepts/scheduling/scheduling). A scheduler gets the job and then generates 5000 allocation objects. Those allocation objects all go into a plan that gets submitted to the leader, and that's going to be a single large Raft entry to write. But you could also get large Raft entries if, for example, 100s of allocations all started simultaneously on a client and then the client updates a batch of allocation status updates for all of them at once. In your case:

> 2023-12-15T08:32:02.706Z [WARN]  nomad: attempting to apply large raft entry: raft_type=9 bytes=1086798

That `raft_type=9` refers to the [`AllocClientUpdateRequestType`](https://github.com/hashicorp/nomad/blob/main/nomad/structs/structs.go#L79), so that's the updates from the client. Each allocation will end up sending a handful of updates on its status, although we batch them up on the client to reduce overall load.

I see a lot of these errors:

> 2023-12-15T08:31:07.788Z [INFO]  nomad: plan for node rejected, refer to https://www.nomadproject.io/s/port-plan-failure for more information: node_id=3edee205-fe97-ef5c-36b4-d08a5b0817fb reason=disk eval_id=3b92a502-ef90-c37c-aeb8-686920dbcaa7 namespace=default

The link in the logs is referring to a known bug, but given the scenario you're seeing here you're almost certainly hitting a legitimate "plan for node rejected" failure. Falling behind in Raft means that the schedulers on the followers are using stale information to determine if a given client node has enough resources (`reason=disk`, in this case). When the plan applier on the leader tries to serialize the resulting plans, it rejects them. But the followers are still behind so the schedulers are getting their plans for a given evaluation rejected multiple times. This causes a new evaluation to be written with a delay. A new evaluation is another Raft write. So this spirals a bit. You should be able to confirm this by looking at the evaluation backlog.

I'm unfortunately out of time for this week and won't be back online until after the new year. But this preliminary look suggests to me that the number of allocations being submitted greatly exceed the amount of resources available, and you're expecting them to gracefully queue-up. Nomad can handle that to some degree so long as the server resources are not being overloaded in the process.

**Comment by MattJustMatt** [comment]
No worries on vacation, hope you have a great holiday season! 

What you're saying generally makes sense, but I'm observing this in some scenarios and to a degree where I'm not sure it's the full story. 

For example today with nothing unusual running (a few jobs here and there for testing with a few allocs) I randomly observed the leader present the same symptoms to a degree where I couldn't access the box and unfortunately lost logs (didn't catch early enough to get from disk)
<img width="1491" alt="image" src="https://github.com/hashicorp/nomad/assets/5265661/7555ee72-f7cd-4857-a670-33fa4028c42e">

This state continued for nearly 12 hours thrashing the disk. The other two nodes in the cluster were able to elect a leader and continue. 

I do have _some_ Prometheus metrics reported from the other healthy nodes if there's anything I can grab. I'm having trouble reconstructing exactly what precipitated this spike (I know one job with one allocation was started at 10am before this happened). 

It's a mystery to me what's causing the primary to go into an unrecoverable state. In the earlier case, it was the **stopping** of the allocations that caused the lockup, so with no extra pressure on the cluster since, I would expect it to eventually recover (e.g. the plan rejection -> replanning doesn't make as much sense for the job stop). (The 4,000 allocations were running for ~30m with no issues, stopping the allocations caused the block. I'm guessing the plan rejection was from a separate but similar job that spins up in lower quantities in response to the primary job's traffic)

In this case it's even more confusing since the cluster was not under load. I have a _theory_ that it's "ghosts from the past" coming back, because yesterday I successfully ran the 4,000 allocation job by scheduling in 500 allocation steps up/down. Maybe there was something today that triggered all that data to get flushed back into the raft state?

A hard reset of the VM is required to get the server to rejoin. 

I guess the principle question is: what is actually being read from the disk for those 10 hours at 240MB/s? The storage attached to this node is only 20GB, so I'm thinking it must be thrashing rather than doing something productive.

**Comment by MattJustMatt** [comment]
Mystery solved...

The missing metric there... memory... turns out to be pretty important! Sitting directly on the box when this happened it consumed all of the (undersized) available memory and locked up. I'm guessing the disk usage we're seeing is some desperate attempt at swapping.

Without knowing enough about the oom mechanics, I am surprised the kernel didn't kill the Nomad process.

Thanks again for taking a look and happy holidays + Merry Christmas!

**Comment by tgross** [comment]
Ah, that makes sense. Especially if you used the official package to install, as it sets a OOM score adjustment for the Nomad process: https://github.com/hashicorp/nomad/blob/main/.release/linux/package/usr/lib/systemd/system/nomad.service#L40
