### ISSUE TITLE
Nomad 1.7.2 logs trying to fetch resource on advertised address

### ISSUE THREAD

**Issue by perbly** [hashicorp/nomad#19523]
Hi

My client does not have connection to the ip showed in the screenshot so this results in a blank page or 500 error.
Tried this locally aswell and then it looks like nomad tells the client to fetch resources at localhost:4646.

### Nomad version
Nomad v1.7.2
BuildDate 2023-12-13T19:59:42Z
Revision 64e3dca9274b493e38a49fda3a70fd31d0485b91

### Operating system and Environment details
Ubuntu 22.04

### Reproduction steps
Clicking "logs" on a job i UI

#### Expected Result
Get logs

#### Actual Result
Nomad sends the servers private ip to client to fetch resources

![Screenshot 2023-12-19 at 14 46 30](https://github.com/hashicorp/nomad/assets/5936850/461c794b-5b9e-4c0a-9554-c1cb8191c265)

**Comment by kaspergrubbe** [comment]
It's normal that it tries to talk to a local IP (at least back in the day): https://github.com/hashicorp/nomad/issues/6454 does it retry and do you get any logs?

**Comment by tgross** [comment]
As noted above, this is expected behavior. The Alloc Logs, Alloc FS, and Alloc Exec APIs all need to get forwarded to the client; the server doesn't have all logs itself. So as an optimization, we try to reach the client node directly so that we can avoid going through the server and using up resources there. You can see in the following example.

I'm running a set of nodes and a set of servers, and start a job which we can see is at `10.37.105.101` (the client's address).

```
$ nomad alloc status 4c25
...
Allocation Addresses (mode = "bridge"):
Label  Dynamic  Address
*www   yes      10.37.105.101:27873 -> 8001
...

$ curl 10.37.105.101:27873
<html>hello, world</html>%

$ nomad alloc logs -stderr 4c25
[::ffff:10.37.105.1]:47598: url:/
[::ffff:10.37.105.1]:47598: response:200
```

When I visit one of the servers in the web UI (`nomad3.local`), I see the following requests happen:

* `OPTIONS http://10.37.105.101:4646/v1/client/fs/logs/4c256d45-7085-60cc-7a15-75751d65b263?follow=true&offset=50000&origin=end&task=http&type=stdout`
* `GET http://nomad3.local:4646/v1/client/fs/logs/4c256d45-7085-60cc-7a15-75751d65b263?follow=true&offset=50000&origin=end&task=http&type=stdout`
