### ISSUE TITLE
List services from 'nomad service list' when a service is scaled down to 0

### ISSUE THREAD

**Issue by chrispruitt** [hashicorp/nomad#19731]
### Proposal
```nomad service list``` and associated API endpoint call returns all services including services that are scaled down to zero.
```nomad service info <service_name>``` and associated API endpoint returns info on a service that is scaled to zero.

### Use-cases
When you want to get ALL valid services in nomad.
When you want to get all tags associated with a service scaled to zero.
This is useful when you have services that scale down to zero when not in use. It would allow 3rd party software (such as traefik) to gather information on valid services and scale them up once a user attempts to make a request to the service.

### Attempted Solutions
I have not found a way to do this via the CLI, however, it looks like this could be achieved with 2 API calls.

1. `http://localhost:4646/v1/jobs` to get a list of jobs
2. `http://localhost:4646/v1/jobs/<job-name>` to get the job info and parse out the services

**Comment by jrasell** [comment]
Hi @chrispruitt and thanks for raising this issue.

The `nomad service list` and `nomad service info` commands return active and registered services currently running within Nomad. In order to register a service, Nomad must know what IP and Port, among other information the service registration has. This matches with how Consul services work. It is therefore not possible to return services for jobs/task groups that have been scaled to zero, because they do not have any active services running.

> I have not found a way to do this via the CLI, however, it looks like this could be achieved with 2 API calls.
>
> http://localhost:4646/v1/jobs to get a list of jobs
> http://localhost:4646/v1/jobs/<job-name> to get the job info and parse out the services

This would be the correct way to detail the service blocks for jobs that have been registered in the Nomad cluster and the approach I would suggest to take. I don't feel extending the commands and the backend processes that populate the state that this information is fetched from would be a suitable feature and feel the two APIs detailed above provide enough ability to do this if required. I am therefore going to close this issue, although please feel free to respond if I am missing some context.

**Comment by chrispruitt** [comment]
That makes sense. It's simple enough to use the alternate method. Thanks!
