### ISSUE TITLE
Nomad not mounting local directory properly

### ISSUE THREAD

**Issue by nilansaha** [hashicorp/nomad#19751]
I am trying to run Caddy using Nomad. I basically write the config file to the local directory and then try to mount that inside the container but every time I get the error

```
run: reading config file: open /data/Caddyfile: no such file or directory
run: reading config file: open /data/Caddyfile: no such file or directory
run: reading config file: open /data/Caddyfile: no such file or directory
```

I am running Nomad itself on Docker as well but not sure if that has anything to do with this issue.

Here is my job file

```
job "ingress" {
  datacenters = ["dc1"]
  type        = "service"

  group "proxy" {
    count = 1

    network {
      mode = "host"
      port  "ingressHttp"{
         static = 80
         to = 80
      }
      port  "ingressHttps"{
         static = 443
         to = 443
      }
    }

    service {
      name = "http"
      provider = "nomad"
      port = "ingressHttp"
    }
    service {
      name = "https"
      provider = "nomad"
      port = "ingressHttps"
    }

    task "server" {
      driver = "docker"
      config {
        image = "caddy/caddy:2.2.1-alpine"
        ports = [
          "ingressHttp",
          "ingressHttps"
        ]
        volumes = ["local:/data"]
        args = [
          "caddy",
          "run",
          "--config",
          "/data/Caddyfile",
          "--adapter",
          "caddyfile",
        ]
      }
      resources {
        cpu    = 1000
        memory = 2048
      }
      template {
        data = <<EOH
        domain.com {
          reverse_proxy 0.0.0.0:26134 {
            header_down Strict-Transport-Security max-age=31536000
          }
        }

        EOH

        destination = "local/Caddyfile"
      }
    }
  }
}
```

**Comment by tgross** [comment]
Hi @nilansaha that jobspec looks fine to me and I was able to run it without issue.

> I am running Nomad itself on Docker as well but not sure if that has anything to do with this issue.

This is most likely the problem, and we document that this is an [unsupported configuration](https://developer.hashicorp.com/nomad/docs/install/production/requirements#running-nomad-in-docker). Nomad is creating the allocation directories in its own mount namespace (see the [Filesystem](https://developer.hashicorp.com/nomad/docs/concepts/filesystem) docs for details). Template rendering happens within the Nomad process and not inside the task container. The Docker daemon is running in the root mount namespace (unless you've got some Docker-in-Docker thing going too). And Docker has a fun quirk where you can tell it to bind-mount volumes and it'll just create a local directory if it doesn't exist and bind-mount that in. So what you likely get from all of that is:

* Nomad creates the allocdir in its own mount namespace
* Nomad renders the template into that allocdir
* Docker looks for the `local` directory and can't find it, so it creates one and bind-mounts that into the task
* The task can't find the file at `/data` because it's the wrong absolute directory on the host

Or something similar. You'll need to look at the various bind-mounts that are getting created here to debug this.
