### ISSUE TITLE
nomad 0.4.1 can't got server members from nomad server 0.5

### ISSUE THREAD

**Issue by kak-tus** [hashicorp/nomad#1976]
### Nomad version
Client 0.4.1
Server v0.5.0-rc2 ('019e2442cc3ddccfa9cd485a41f2f6564f122c71+CHANGES')

### Operating system and Environment details
Ubuntu server 16.04

### Issue
I've updated nomad server on one node to 0.5.
After that my local nomad client 0.4.1 can't get server-members info from 0.5 nomad server, but can get it from 0.4.1 server.
And local nomad client 0.5 gets server-members info without problems from both versions of nomad server.

### Reproduction steps
1. Update nomad server to 0.5 on one cluster node.
2. Try to get server-members from this node.

### Nomad Client logs (if appropriate)

0.4.1
```
$ nomad server-members
Error querying servers: json: cannot unmarshal object into Go value of type []*api.AgentMember
```

0.5
```
$ ~/Downloads/nomad server-members
Name                   Address         Port  Status  Leader  Protocol  Build     Datacenter    Region
...
nodes
...
```

**Comment by dadgar** [comment]
Hey,

You should not run a mixed cluster of 0.5.0 or 0.4.1 servers (you should always roll all at once). We merged this PR https://github.com/hashicorp/nomad/pull/1947 which makes the CLI work from both servers and clients but as a side-effect will only be usable on a fully rolled cluster.

If this addresses your question/concern would you mind closing? Otherwise let me know!

**Comment by kak-tus** [comment]
@dadgar All nodes (servers/agents) in cluster must be same version?
Is it possible in this case, to transparently (without services stopping) migrate from 0.4 to 0.5?

I thought that it shall be easy: marks node as drain (services gone to another node), update to 0.5, unmark drain (services may go come back to this node).

**Comment by dadgar** [comment]
@kak-tus To be specific I meant all servers should be on the same version.

It is okay to have servers ahead of the clients but not recommended. You can either upgrade the clients in place by replacing the nomad binary and then killing nomad and starting it again. It will do a best effort to re-attach to everything it was running. Otherwise you can do as you described.

**Comment by kak-tus** [comment]
@dadgar I understand. Thank you.
