### ISSUE TITLE
Stop Nomad from exposing services to the Internet

### ISSUE THREAD

**Issue by nilansaha** [hashicorp/nomad#19771]
I have Nomad installed on a VPS. When I run a task nomad creates a docker container which is directly exposed to the public internet. 

### Current Behaviour
However if I try to reach it on `127.0.0.1:<port>` or `0.0.0.0:<port>` it is not available. It is available from inside the VPS and outside using `<public_ip>:<port>`.

### Expected Behaviour
It cannot be reached from the internet using `<public_ip>:<port>` but it can be reached from inside the VPS using `127.0.0.1:<port>` or `0.0.0.0:<port>`

#### Nomad Config File
```
data_dir  = "/root/nomad/data"
bind_addr = "0.0.0.0"

server {
  enabled          = true
  bootstrap_expect = 1
}

client {
  enabled = true
  servers = ["127.0.0.1"]
}

acl {
  enabled = true
}
```

#### Job File
```
job "echo-app" {
  datacenters = ["dc1"]

  group "web" {
    count = 1

    network {
      port "appHttp" {
        to = 8080
      }
    }

    service {
      provider = "nomad"
      port     = "appHttp"
      name     = "echo-web-http"
    }

    task "echo-server" {
      driver = "docker"
      config {
        image          = "mendhak/http-https-echo:26"
        ports          = [
          "appHttp"
        ]
      }

      resources {
        cpu    = 100
        memory = 200
      }
    }

  }

}
```

#### How my network interfaces look

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether 00:50:56:4e:2e:6f brd ff:ff:ff:ff:ff:ff
3: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default 
    link/ether 02:34:7a:1d:69:e9 brd ff:ff:ff:ff:ff:ff
7: veth0ad3ded@if6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP mode DEFAULT group default 
    link/ether 12:d7:56:da:bc:5f brd ff:ff:ff:ff:ff:ff link-netnsid 0
```

**Comment by tgross** [comment]
@nilansaha What you're seeing is what I'd expect to see. Here's why:
* `bind_addr = "0.0.0.0"` just tells Nomad to bind on all interfaces, which it's doing.
* you don't have [`network.mode`](https://developer.hashicorp.com/nomad/docs/job-specification/network#mode) set, so it defaults to `"host"`
* you have a port mapping in `task.config.ports`, which is telling Nomad to expose that port. It exposes it for the network namespace the task is running in, which is the _root_ network namespace because you have `network.mode = "host"`

If you really want to use `network.mode = "host"` and not expose the ports, you need your `mendhak/http-https-echo` workload to bind to localhost.

But if you want network isolation for your workloads, you should probably use [Bridge Networking](https://developer.hashicorp.com/nomad/docs/networking#bridge-networking) follow the guidance there around binding to the bridge IP or not forwarding ports.

(Aside, just a note that having the server and client running together on the same instance is strongly recommended against, as the two components will compete for resources with each other and with your workloads in a way that's extremely hard to debug.)

**Comment by nilansaha** [comment]
Appreciate the insights @tgross 

Yes I do want the containers to be accessible from the host so I ended up adding

```
  host_network "localhost" {
  	interface = "lo"
  }
```

to the client stanza in nomad config

and added

```
network {
      port "appHttp" {
        to = 8080
        host_network = "localhost"
      }
}
```
in the job file. 

Now, it seems to not be accessible from the internet but is accessible from inside the host. 
Is this a good way of achieving what I want? Also will this stop one container to communicate with the other in the future?

Just trying to wrap my head around Nomad networking

Thanks.

**Comment by tgross** [comment]
> Now, it seems to not be accessible from the internet but is accessible from inside the host.
Is this a good way of achieving what I want? Also will this stop one container to communicate with the other in the future?

So long as the other containers are also using `network.mode = "host"`, yes that should work.

**Comment by nilansaha** [comment]
> > Now, it seems to not be accessible from the internet but is accessible from inside the host.
> > Is this a good way of achieving what I want? Also will this stop one container to communicate with the other in the future?
> 
> So long as the other containers are also using `network.mode = "host"`, yes that should work.

@tgross I just tried creating another job with the exact same config (except names)
Went into the docker container using `docker exec -it <id> sh` and tried to connect to the other container using both `wget --spider 0.0.0.0:30211` and `wget --spider 127.0.0.1:30211` and it can't connect to the that url. 30211 is the port on the host the other job is binded to.

Any ideas?

**Comment by tgross** [comment]
Hm, sorry about that @nilansaha. Looks like I gave you some bad advice here:

* First, I forgot to mention that in order to tell Docker to use host-mode networking we need to add [`network_mode = "host"`](https://developer.hashicorp.com/nomad/docs/drivers/docker#network_mode) to the `task.config` block. Once you've done that, you don't need the `host_network` field at all.
* But more importantly, if we're using host-mode networking everywhere, we're sharing the host network namespace so anything that's bound to 0.0.0.0 will be accessible from the host's IP address as well. So you need to make sure the application is binding to 127.0.0.1.

I couldn't figure out how to get the Docker image you're using to bind to the right IP, but here's an example with busybox httpd:

<details><summary>jobspec</summary>

```hcl
job "httpd" {

  group "web" {

    network {
      mode = "host"
      port "www" {
        to = 8001
      }
    }

    service {
      provider = "nomad"
      port     = "www"
    }

    task "http" {

      driver = "docker"

      config {
        image        = "busybox:1"
        command      = "httpd"
        args         = ["-vv", "-f", "-p", "127.0.0.1:8001", "-h", "/local"]
        network_mode = "host"
      }

      template {
        data        = "<html>hello, world</html>"
        destination = "local/index.html"
      }

      resources {
        cpu    = 100
        memory = 100
      }

    }
  }
}
```

</details>

The important bits here:
* `network.mode = "host"`, no `host_network` required
* no `ports` field required for the Docker config
* `task.config.network_mode = "host"` for the Docker task config
* application binds to 127.0.0.1

If I then run the following job:

<details><summary>curl jobspec</summary>

```hcl
job "curl" {

  group "group" {

    network {
      mode = "host"
    }

    task "task" {

      driver = "docker"

      config {
        image        = "curlimages/curl:latest"
        command      = "tail"
        args         = ["-f"]
        network_mode = "host"
      }

      resources {
        cpu    = 128
        memory = 256
      }

    }
  }
}

```

</details>

I can reach the httpd service on localhost:8001 from the curl container:

```
$ nomad alloc exec 0f6 /bin/sh
~ $ curl localhost:8001
<html>hello, world</html>
```

And I can reach the service on localhost:8001 from the host:

```
$ curl 127.0.0.1:8001
<html>hello, world</html>%
```

But I can't reach it from the host's routable IP:

```
$ curl 192.168.1.77:8001
curl: (7) Failed to connect to 192.168.1.77 port 8001 after 0 ms: Connection refused
```

Something to keep in mind is that if you're using host networking that applications won't be able to bind to the same port. You might want to use `network.static = "8001"` so that Nomad service discovery picks up the right IP.

If you _don't_ want to use host networking and want to use bridge networking without exposing the tasks to outside the host, then you'd need to set up a separate bridge network with its own IP, use that as a `host_network`, and establish a firewall rule on the host to prevent outside traffic from hitting that bridge.

**Comment by tgross** [comment]
> I guess I was hoping that even if the application binds to 0.0.0.0 by default Nomad can somehow force it to bind to 127.0.0.1 and still be reachable from other containers and from the host itself but seems there is no magical solution there? (Mostly because all applications try to bind to 0.0.0.0 by default)

Ok, yeah. That "magical way" is basically exactly what `network.mode = "bridge"` is for. That way tasks bind to 0.0.0.0 and they're each in their own network namespace. It's just that normally when folks do this they want to expose those tasks outside the host.

Effectively what you're trying to do here is a docker-compose-like setup for a single node. And our docs and examples are sparse-to-none here because our focus is more on production use cases with multiple nodes.


> Suppose if I do end up binding to 0.0.0.0 in which case it will be accessible from the Internet. I have read that I can't use firewall rule to block access to that port from the internet because Docker overrides those firewall rules. Do you have any thoughts on this?

In Nomad, we append to the iptables chain `NOMAD-ADMIN` instead of inserting rules at the top of that chain. That will allow you to add a rule that gets evaluated _before_ the rules that Nomad adds, and that should solve the problem that Docker runs into.

Another design issue for you to consider is whether or not the tasks need NAT to access the internet. If you don't need NAT, then you could make an extra network interface (I think a [dummy](https://developers.redhat.com/blog/2018/10/22/introduction-to-linux-interfaces-for-virtual-networking#dummy) interface will do the job here) and attach a network bridge to it and use that. But if your tasks need outbound requests, this won't work.

As an aside, if you get a setup you're happy with here, we'd love to have a PR from you to the [Networking docs](https://developer.hashicorp.com/nomad/docs/networking) so that other folks can benefit from what you learn about this particular setup.
