### ISSUE TITLE
Update cpuset_cpus in documentation

### ISSUE THREAD

**Issue by neomantra** [hashicorp/nomad#19815]
This is a documentation-bug regarding this entry in the Nomad docs related to `cpuset_cpus`:

https://github.com/hashicorp/nomad/blob/8f564182efb24d04e7ff8cd6864e9c519d6cd7a7/website/content/docs/drivers/docker.mdx#L87C3-L87C16

The docs currently  describe a *Beta* behavior -- however as of the `1.7` [release series](https://github.com/hashicorp/nomad/commit/2e1974a5747d81332b2a26658f73e78a662dbb20) it is no longer supported.

I was discussing this feature with @tgross on this  [this PR](https://github.com/hashicorp/nomad/pull/16069#issuecomment-1901259851)  -- my understanding was based on that documentation page.

 I have been operating with `cpuset_cpus` fine for a while (years for my specific use case?), but had not upgraded any HPC-ish clusters to `1.7` until yesterday.   That's when I saw the line [from here](https://github.com/hashicorp/nomad/blame/543ba16e61af2c0d7194eb1371451895ebf86d1e/drivers/docker/driver.go#L1005) : `cpuset_cpus is no longer supported` and in fact they aren't!  =)   Which is different than `Beta` and in that case removing `cpuset_mems` also makes sense.

I didn't PR the docs because I wasn't exactly sure what it should say.  But it did lead me astray in my outlook in the conversation.  Thanks!

**Comment by lgfa29** [comment]
Hi @neomantra 👋 

Thanks for the report, and apologies for the confusion in our documentation. Since we now have versioned documentation, I think we can just remove this configuration from the documentation. 

This comment mentions that this config has not worked since Nomad 0.12, but it seems to have been added in Nomad 1.0 (https://github.com/hashicorp/nomad/pull/8291), so the comment may seem inaccurate?

https://github.com/hashicorp/nomad/blob/543ba16e61af2c0d7194eb1371451895ebf86d1e/drivers/docker/driver.go#L1003

So I think removing the config in the 1.7.x series is probably enough for now. I've opened https://github.com/hashicorp/nomad/pull/19882 to do this.
