### ISSUE TITLE
HTTP API /v1/nodes endpoint fails filtering by the Address selector

### ISSUE THREAD

**Issue by agarfer1** [hashicorp/nomad#19871]
### Nomad version
Output from `nomad version`

```
Nomad v1.7.3
BuildDate 2024-01-15T16:55:40Z
Revision 60ee328f97d19d2d2d9761251b895b06d82eb1a1
```

### Operating system and Environment details

Ubuntu minimal 22.04 cloud image amd64

Using nomad-pack and dante services. No Consul integration.

### Issue

Using the HTTP API, trying to filter a node by the Address selector returns an error

### Reproduction steps

```
curl -s --get $NOMAD_ADDR/v1/nodes --data-urlencode 'filter=Address == "10.1.7.131"'
```
or

```
curl -s --get $NOMAD_ADDR/v1/nodes --data-urlencode 'filter=Address contains "10.1.7.131"'
```

or

```
curl -s --get $NOMAD_ADDR/v1/nodes --data-urlencode 'filter="10.1.7.131" in Address'
```

#### Expected Result
```
[
  {
    "Address": "10.1.7.131",
    "ID": "00f6c407-26df-e18f-52e1-abc",
    "Attributes": null,
    [...CONT...]
```

#### Actual Result

```
failed to read result page: error finding value in datum: /Address at part 0: couldn't find key: struct field with name "Address"
```

#### Additional information

The same Address selector filter, but for the v1/service/:service endpoint, works correctly

In the same endpoint as the issue, filtering by the ID selector does not cause this error.

**Comment by lgfa29** [comment]
Hi @agarfer1 👋 

This is indeed very weird and an unfortunate consequence of how our internal fields were named.

The short answer is that you should `HTTPAddr` instead of `Address` in the filter.

The long answer, in case you're curious, is that Nomad has two representation for some objects: one for a specific instance of the object and another that is used when returning a list. This is done for large objects to reduce the amount of data returned on list requests. 

For nodes, these two structures ended up with different names for the address:
https://github.com/hashicorp/nomad/blob/5825cefe5127ada52c1ad9a7e540258e004a1b6e/nomad/structs/structs.go#L2098-L2100

https://github.com/hashicorp/nomad/blob/5825cefe5127ada52c1ad9a7e540258e004a1b6e/nomad/structs/structs.go#L2391-L2394

So while the API does return `Address` as the field name for a list request, internally, Nomad filters objects using its full instance struct.

Changing this would be a significant API breaking change, so we will probably need to live with this weirdness for a while 😞 

But I hope that using `HTTPAddr` solves the issue for you.

**Comment by agarfer1** [comment]
Hello @lgfa29

Muito obrigado for your quick triage, the detailed explanation and temporary fix :smiley: 

I have created an imperfect bash script to identify this issue in other endpoints and this problem is sadly present in other endpoints and other fields of this same endpoint.

This script skips the key/values that are objects, and it is also probably returning some false positives due to the type of comparison(s) and the original data types. To account for this last problem, each filter is tested twice with 2 expressions (`== and in`).

### Bash script

```
#!/bin/bash

#No errors detected:
#ENDPOINT="deployments"         #I dont think this error is happening
#ENDPOINT="jobs"                #I dont think this error is happening 
#ENDPOINT="service/:service_name"       #I dont think this error is happening 
#ENDPOINT="evaluations"         #I dont think this error is happening 


ENDPOINT="nodes"               #At least 2 more selectors affected
#ENDPOINT="allocations"         #At least 2 selectors affected
#ENDPOINT="node/pool"           #Could not test this endpoint(s)
#ENDPOINT="vars"                #Every selector fails?
#ENDPOINT="volumes"            #Could not test this endpoint

#Requires the second elements statement:
#ENDPOINT="evaluations/count"   #I dont think this error is happening, but not sure if the filter actually filters

###########################

shared_request=$(curl -s --get $NOMAD_ADDR/v1/$ENDPOINT)

elements=$(echo "$shared_request" | jq '.[0] | to_entries | map(select(.value | type != "object") | .key)')
#elements=$(echo "$shared_request" | jq '. | to_entries | map(select(.value | type != "object") | .key)')   #For the v1/evaluations/count endpoint

echo $elements

echo -e "\n"

elements_array=($(echo "$elements" | jq -r '.[]'))

for key in "${elements_array[@]}"; do

  echo $key

  #curl --cert $NOMAD_CLIENT_CERT --key $NOMAD_CLIENT_KEY --cacert $NOMAD_CACERT --get "$NOMAD_ADDR/v1/$ENDPOINT" --data-urlencode "filter=$key == \"10\""
  output1=$(curl -s --get "$NOMAD_ADDR/v1/$ENDPOINT" --data-urlencode "filter=$key == \"10\"")
  output2=$(curl -s --get "$NOMAD_ADDR/v1/$ENDPOINT" --data-urlencode "filter=\"10\" in $key")
  
  echo ${output1:0:200}
  echo ${output2:0:200}
  
  echo -e "\n"
done
```

### Results running this for the v1/nodes endpoint

```
[ "Address", "ID", "Attributes", "Datacenter", "Name", "NodePool", "NodeClass", "Version", "Drain", "SchedulingEligibility", "Status", "StatusDescription", "HostVolumes", "NodeResources", "ReservedResources", "LastDrain", "CreateIndex", "ModifyIndex" ]


Address
failed to read result page: error finding value in datum: /Address at part 0: couldn't find key: struct field with name "Address"
failed to read result page: error finding value in datum: /Address at part 0: couldn't find key: struct field with name "Address"


ID
[]
[]


Attributes
failed to read result page: unable to find suitable primitive comparison function for matching
[]


Datacenter
[]
[]


Name
[]
[]


NodePool
[]
[]


NodeClass
[]
[]


Version
failed to read result page: error finding value in datum: /Version at part 0: couldn't find key: struct field with name "Version"
failed to read result page: error finding value in datum: /Version at part 0: couldn't find key: struct field with name "Version"


Drain
failed to read result page: error finding value in datum: /Drain at part 0: couldn't find key: struct field with name "Drain"
failed to read result page: error finding value in datum: /Drain at part 0: couldn't find key: struct field with name "Drain"


SchedulingEligibility
[]
[]


Status
[]
[]


StatusDescription
[]
[]


HostVolumes
failed to read result page: unable to find suitable primitive comparison function for matching
[]


NodeResources
failed to read result page: unable to find suitable primitive comparison function for matching
failed to read result page: Cannot perform in/contains operations on type struct for selector: "NodeResources"


ReservedResources
failed to read result page: unable to find suitable primitive comparison function for matching
failed to read result page: Cannot perform in/contains operations on type struct for selector: "ReservedResources"


LastDrain
failed to read result page: unable to find suitable primitive comparison function for matching
failed to read result page: Cannot perform in/contains operations on type invalid for selector: "LastDrain"


CreateIndex
[]
failed to read result page: Cannot perform in/contains operations on type uint64 for selector: "CreateIndex"


ModifyIndex
[]
failed to read result page: Cannot perform in/contains operations on type uint64 for selector: "ModifyIndex"

```

I believe that all the errors that start with `failed to read result page: error finding value in datum: ...` are the same as the original problem reported.

Thank you again, if there is anything I could help you with, please let me know.

P.S. And thank you for your videos, I have learnt a lot about Nomad thanks to you :smile:

**Comment by lgfa29** [comment]
Opa, tudo bom? 😄 

&lt;tecla SAP>

I actually thought of a solution for this, but I think the result is arguably worse and more confusing than what we have.

In https://github.com/hashicorp/nomad/commit/b79da7e0e5f92a09db8f70581068b36f09f0c8ec I wrapped the list of nodes in an iterator that returns the stub instead of the full node. This means that filter operation is applied to the stub, not the full object, which, at first, is what we would expect to have.

But the downside is that the stub doesn't have all the fields the node has, so you would no longer be able to filter the list by values in `Meta` for example, which is something that can be quite useful.

In https://github.com/hashicorp/nomad/commit/dcf9497189834d8db50c3755838e348030a9705e I tried to embed the structs in hopes that you would be able to access the sub field by default, but also have access to something like `Node.Meta`, but in reality both structs need a prefix and adding `NodeListStub.*` in front to every filter operation feels quite unnatural.

But we should document this, since it's an unexpected behaviour, so I opened https://github.com/hashicorp/nomad/pull/19902 to update our docs.

Thanks for detailed report and all the help!

</tecla SAP>
