### ISSUE TITLE
executable as job.

### ISSUE THREAD

**Issue by seczoid** [hashicorp/nomad#19997]
i want to specify a job in nomad which does this:

i have a executable abcd i want to run it. after its exits the first time itself, i want the job to be completed

**Comment by jrasell** [comment]
Also raised via Discuss: https://discuss.hashicorp.com/t/executable-as-job-task-in-nomad/62799

Hi @seczoid; for this you could use the [batch scheduler](https://developer.hashicorp.com/nomad/docs/schedulers#batch) and either the [exec](https://developer.hashicorp.com/nomad/docs/drivers/exec) or [raw_exec](https://developer.hashicorp.com/nomad/docs/drivers/raw_exec) driver depending on your exact requirements.

An example job specification snippet is included below, although you'll need to modify this in order to meet your requirements, specific cluster setup, and other factors.
```
job "abcd" {
  type = "batch"
  group "abcd" {
    task "abcd" {
       driver = "raw_exec"
       config {
         command = "abcd"
      }
    }
  }
}
```
