### ISSUE TITLE
bug: developer.hashicorp.com/nomad/s/port-plan-failure webpage is no longer available.

### ISSUE THREAD

**Issue by Kamilcuk** [hashicorp/nomad#20070]
### Nomad version
1.7.5

### Operating system and Environment details
Fedora27

### Issue
The URL https://developer.hashicorp.com/nomad/s/port-plan-failure is mentioned in logs, but is no longer available.

It is in several places in source code https://github.com/search?q=repo%3Ahashicorp%2Fnomad%20https%3A%2F%2Fdeveloper.hashicorp.com%2Fnomad%2Fs%2Fport-plan-failure&type=code .

### Reproduction steps
Go to https://developer.hashicorp.com/nomad/s/port-plan-failure . It's not there.

#### Expected Result
The page should be there.

Thanks.

**Comment by schmichael** [comment]
Good catch! We recently fixed another broke `/s/` link: https://github.com/hashicorp/nomad/pull/20015

The correct URL is: https://developer.hashicorp.com/nomad/docs/operations/monitoring-nomad#progress

I'll get it fixed up ASAP.

**Comment by schmichael** [comment]
The fix is deployed. Thanks again!

Also please open a new issue if you suspect you've hit a plan-for-node-rejected bug. Since it's normal to encounter _some_ plan for node rejected occurrences during periods of busy scheduling, it can be hard to know if you've hit a bug. The best way to determine it is if scheduling cannot progress despite ample cluster resources being disabled, or some nodes never receive workloads when you suspect they're the best option. In the absence of those issues, flurries of plan-for-node-rejected errors during times of busy scheduling are likely just a side effect of Nomad's optimistically concurrent schedulers.
