### ISSUE TITLE
logmon: Unrecognized remote plugin message

### ISSUE THREAD

**Issue by lmorel3** [hashicorp/nomad#20091]
Hi,

My cluster is running Nomad 1.4.3 and I'm trying to update to the latest stable version (1.7.5), but on some servers, jobs can't start because of "logmon".

It might be related to the OS version. Indeed, it works well on Windows Server 2016, but it doesn't on Windows Server 2012.

I've also tried a fresh install but the behavior is the same. So, we're stuck on 1.4.3... :/

### Nomad version
1.7.5 or 1.5.15

### Operating system and Environment details
Windows Server 2012 (x64)

### Issue

Jobs fail to start.

### Nomad Client logs

> logmon: Unrecognized remote plugin message: The parameter is incorrect. This usually means the plugin was not compiled for this architecture, the plugin is missing dynamic-link libraries necessary to run, the plugin is not executable by this process due to file permissions, or the plugin failed to negotiate the initial go-plugin protocol handshake Additional notes about plugin: Path: D:\Application\nomad\nomad.exe Mode: -rw-rw-rw- PE architecture: amd64 (current architecture: amd64)

**Comment by shoenig** [comment]
Hi @lmorel3 the error message suggests some dynamic libraries might not be available which could make sense if the newer versions of Nomad have been compiled on newer versions of Windows with libraries not available on older versions of Windows.

Since Windows Server 2012 is [no longer supported by Microsoft](https://learn.microsoft.com/en-us/lifecycle/announcements/windows-server-2012-r2-end-of-support) it's also no longer supported by Nomad. Probably your best bet is to compile Nomad yourself on an older version of Windows, or to upgrade the OS.

**Comment by lmorel3** [comment]
Hi!

Thanks for you answer. In fact, I've already asked our sysadmins to upgrade this VM so that Nomad should work properly. 

I hope this issue will help others who don't have another version of Windows for testing :)


Laurent
