### ISSUE TITLE
Describe why we do not bootstrap ACL on Nomad clients

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#20127]
This page https://developer.hashicorp.com/nomad/tutorials/access-control/access-control-bootstrap#enable-acls-on-nomad-clients
does not describes why we do not do `nomad acl bootstrap` on nomad clients

[This repository](https://github.com/hashicorp/learn-nomad-cluster-setup) also does not mention why bootstrap performed only for servers. Eg. The [script to provision client instance ](https://github.com/hashicorp/learn-nomad-cluster-setup/blob/main/shared/data-scripts/user-data-client.sh) do not call `nomad acl bootstrap` in compare to the [script to provision a server](https://github.com/hashicorp/learn-nomad-cluster-setup/blob/main/shared/data-scripts/user-data-server.sh) instance.

Describe how ACL bootstrapped for clients.

**Comment by EugenKon** [comment]
I found also that there is no description why we do not bootstrap Consul client. I can not understand from the documentation how Consul client is authorized to Consul server and how Nomad client is authorized to Consul client. Are the requests done without authorization?

**Comment by tgross** [comment]
@EugenKon you bootstrap the servers earlier in that tutorial. Clients don't need bootstrapping because they don't control ACLs, just use them with the servers. I'm not sure what information you're looking to have added here?

**Comment by EugenKon** [comment]
So why they do not control? And how they use ACL with the servers?

**Comment by jrasell** [comment]
Hi @EugenKon, the Nomad clients do not control ACL or any cluster state objects because that is the responsibility of Nomad servers. I believe the Nomad concepts documentation amongst others has enough information available to describe this behaviour and detail. The clients utilise ACL by making queries to the Nomad servers when required in the same way they do with any other cluster information such as allocations.

I will go and close this issue as I feel the information is covered. If you do have a need or wish for additional documentation, please feel free to open a new issue to detail what is missing.

**Comment by EugenKon** [comment]
@jrasell Thank you for providing additional info. I described what was missed and where. May you point me where that information was covered?
