### ISSUE TITLE
CSI plugin is not deregistered when a new version of the plugin job changes the CSI plugin id

### ISSUE THREAD

**Issue by Jamesits** [hashicorp/nomad#20225]
### Nomad version
1.7.6

### Operating system and Environment details
Ubuntu 22.04

### Issue
When a CSI job has a new version with a different CSI plugin id, Nomad is unable to unregister the storage plugin with the old id cleanly.

### Reproduction steps

0. Submit a working CSI storage plugin job
1. Submit a new version of the job with `job.group[].task[].csi_plugin.id` changed directly

#### Expected Result

Web UI -> Storage -> Plugins shows only the new id

#### Actual Result

Web UI -> Storage -> Plugins have both the old id and new id showing up, and you have no way to remove the old one

I've tried changing the CSI plugin id back, stopping all the plugin jobs, purging the related jobs completely. It worked for one cluster, but does not on another cluster of the same configuration (created with near identical Terraform plans). This might be caused by an unknown issue.

![Screenshot from 2024-03-26 17-41-04](https://github.com/hashicorp/nomad/assets/1297257/9d6f121b-427c-4d98-b8cb-c75fb4bbf31e)

### Job file (if appropriate)
N/A

### Nomad Server logs (if appropriate)
N/A

### Nomad Client logs (if appropriate)
N/A

Related https://github.com/hashicorp/nomad/issues/7306

**Comment by jrasell** [comment]
Hi @Jamesits and thanks for raising this issue. It looks like we are not correctly handling the ID update, to perform destructive actions on the original CSI ID. I'll add this to our roadmap.

**Comment by tgross** [comment]
I've had a look at this and some of the behavior we're seeing here is intentional. We don't clean up the plugin until it's jobs are completely deleted, because we need to account for the delay between allocations coming up and down and the plugin being fingerprinted by the node. That being said, what _should_ be working is garbage collection. But in this case, we detect the plugin as still having the job even though it has no allocations for the job _and_ there's a more current version of the job.

I'm working on a patch that will update the logic for GC to account for that.

What you've done here as a workaround should work:
> I've tried changing the CSI plugin id back, stopping all the plugin jobs, purging the related jobs completely

So if you didn't see that work on one cluster, there may be an unrelated issue where the plugin thinks its still in use. I'd need to see the plugin status / logs for more details.

**Comment by tgross** [comment]
PR is up here: https://github.com/hashicorp/nomad/pull/20555

**Comment by tgross** [comment]
#20555 has been merged and will ship in Nomad 1.8.0 (with backports to supported versions)
