### ISSUE TITLE
Read node resources returns 0 in values while NodeReources return different values 

### ISSUE THREAD

**Issue by noamSpot** [hashicorp/nomad#20347]
### Nomad version
Output from `1.7.x`

### Operating system and Environment details
Linux

### Issue
when using `/v1/node/:node_id`, `NodeResources.cpuShares` and `NodeResources.memory` values are > 0 but `resources.cpu`
and `reources.memory` values are 0 at the same time. 
1. I would like to know if there is a difference between `Reources` and `NodeResources`? 
2. if not, then way one of them is 0 while the other isn't? 

Also, What can be the reason for empty value in the `status` filed of the node? 
### Reproduction steps
use the route `/v1/node/:node_id`
#### Expected Result
...
"NodeResources": {
  "Cpu": {
    "CpuShares": 4400,
    "TotalCpuCores": 2,
    "ReservableCpuCores": [
      0,
      1
    ]
  },
  "Processors": {
...
  },
  "Memory": {
    "MemoryMB": 15775
  },
  "Disk": {
    "DiskMB": 27999
  },
...
},
...
"Resources": {
"CPU": 4400,
"Cores": 0,
"MemoryMB":15775,
"MemoryMaxMB": 0,
"DiskMB": 0,
"IOPS": 0,
"Networks": null,
"Devices": null,
"NUMA": null,
}
#### Actual Result
"NodeResources": {
  "Cpu": {
    "CpuShares": 4400,
    "TotalCpuCores": 2,
    "ReservableCpuCores": [
      0,
      1
    ]
  },
  "Processors": {
...
  },
  "Memory": {
    "MemoryMB": 15775
  },
  "Disk": {
    "DiskMB": 27999
  },
...
},
...
"Resources": {
"CPU": 0,
"Cores": 0,
"MemoryMB":0,
"MemoryMaxMB": 0,
"DiskMB": 0,
"IOPS": 0,
"Networks": null,
"Devices": null,
"NUMA": null,
}

**Comment by tgross** [comment]
Hi @noamSpot! Yeah that `Node.Resources` field in the API response is a leftover from a very long time ago https://github.com/hashicorp/nomad/pull/6241 that never got fully removed from the API. Actually removing it from the API will require removing it from our state store first, which is a little more fraught with peril and that's why we haven't got around to it yet.

You'll want to use the `Node.NodeResources` block for anything you're querying.

**Comment by noamSpot** [comment]
Hi @tgross , Thank you for your help! 
What about `status`? what can be the reason this field return empty?
