### ISSUE TITLE
Strange behavior between 'docker run' and 'nomad run'

### ISSUE THREAD

**Issue by mikamakusa** [hashicorp/nomad#2059]
### Nomad version
Nomad v0.5.0
### Operating system and Environment details
CentOS 7 + Docker v1.12
----------------------
Hi guys, I hope you can help me.

I'm using a customized Dockerfile like the following : 
`FROM centos:7`  
`RUN groupadd appserv && useradd -g appserv appserv && mkdir -p /lsf/opt`  
`RUN yum upgrade -y && yum install -y tar curl wget epel-release unzip cronie cronie-anacron sudo crontabs`  
`RUN yum install -y salt-minion && yum clean all -y`  
`CMD ['salt-minion']`

My command to deploy the container with this image is the following : 
`docker run -dit --hostname test01 salt-minion salt-minion`

The nomad file I'm using to deploy the same container is the following : 
`job "deploy-zookeeper" {`
	`datacenters = ["dc1"]`
	`group "zookeeper" {`
		`count = 1`
		`task "zookeeper" {`
			`driver 	= "docker"`
			`config {`
				`image 	= "salt-minion"`
	        	`port_map {`
	        		`salt01 	= 4505`
			        `salt02 	= 4506`
			        `salt03 	= 4507`
			        `salt04 	= 14506`
	        	`}`
	        	`command 	= "salt-minion"`
	        	`tty 		= true`
	        	`interactive = true`
	        	`hostname 	= "test01"`
			`}`
			`resources {`
				`cpu 	= 90`
				`memory	= 10`
				`network {`
					`mbits = 10`
					`port "salt01" {}`
		          	`port "salt02" {}`
	    	  		`port "salt03" {}`
		          	`port "zk_01" {}`
		          	`port "zk_2" {}`
		          	`port "zk_3" {}`
		          	`port "hz_01" {}`
				`}`
			`}`
			`service {`
				`tags = ["zookeeper"]`
				`port = "zk_01"`
				`check {`
					`type 		= "tcp"`
					`port 		= "zk_01"`
					`interval 	= "10s"`
					`timeout 	= "2s"`
				`}`
			`}`
		`}`
	`}`
`}`

Strangely, I never obtain the same result with Nomad as the one obtained using Docker.
With Nomad, the container unexpectedly always restart and when i replace the line command by "/bin/bash", I can't launch any command from the container...i just get "killed" when I try to launch "salt-minion" or "yum".

Did I've forgot something ?
And can you help me to make it work ?

**Comment by jippi** [comment]
My guess it that it gets killed by OOM killer (you've only allocated 10 MB for a java app?)

**Comment by schmichael** [comment]
Ah, you caught an ugly corner case in the way Nomad uses Docker images. If you don't specify an image version it defaults to `latest` (as in `salt-minion:latest`). When you tell Nomad to run the `latest` version of an image it *always* tries to download the image (in case the local one is out of date).

This works great when using a repository, but when using a locally created image the pull will always fail.

The easiest workaround is to add a version to your Docker image:

```
docker build -t salt-minion:v1 path/to/Dockerfile
```

And then run that image with Nomad:

```hcl
config {
    image = "salt-minion:v1"
    ....
}
```


One other thing to note is that it looks like you're creating an image with just salt-minion running but the nomad job is called "zookeeper". I'm assuming you're planning on deploying zookeeper in the image with salt? A simpler workflow might be to create the salt-minion docker image, salt it to install zookeeper, commit that container to a Docker image, and then deploy that.

That way you're deploying an *immutable* Zookeeper Docker image that doesn't even need to have salt-minion running (hopefully). Otherwise if a Zookeeper node dies or you update the Nomad job and Nomad has to reschedule it, Nomad will be running the empty salt-minion container. You'll have to make sure to re-salt every time a Zookeeper job in Nomad gets updated which is error prone at best.

**Comment by mikamakusa** [comment]
Thanks for your help.
What i'm trying to do is to reproduce what i've already done with our dev environment.
I made a first docker image (salt-minion) with which i created 3 new docker images (zookeeper, hazelcast and tomcat).
And we deploy the instances (not the middleware) with salt on these containers.

I did it with docker-compose on one host...what we need now is to do it with more than one.
I know i can do it with swarm or kubernetes (and we already tried it)...but, nomad is the first tool with which i succeed in deploying docker images from a private repository.
