### ISSUE TITLE
Nomad didn't forget changed server IP

### ISSUE THREAD

**Issue by kak-tus** [hashicorp/nomad#2076]
### Nomad version
0.5

### Operating system and Environment details
Linux

### Issue
Nomad didn't forget changed server IP and trying to connect to it infinitely.

### Reproduction steps
1. Run nomad cluster.
2. Change IP of one server.
3. Nomad will infinitely trying to connect to old IP, but server with new IP will succesfully register this IP in cluster.
4. When master nomad server will changing, new master will trying to reconnect to old IP.

### Nomad Server logs (if appropriate)
```
2016-12-09 13:33:25 c1 [nomad 6839]  raft: Failed to AppendEntries to 46.188.48.241:4647: dial tcp 46.188.48.241:4647: i/o timeout
2016-12-09 13:33:38 c1 [nomad 6839]      2016/12/09 13:33:38 [ERR] raft: Failed to heartbeat to 46.188.48.241:4647: dial tcp 46.188.48.241:4647: i/o timeout
```

**Comment by dadgar** [comment]
Hey @kak-tus,

This is expected behavior. If the server was networked partitioned for a bit you would not want it to leave the cluster. There are two options:

1) Set leave_on_terminate: https://www.nomadproject.io/docs/agent/configuration/index.html#leave_on_terminate 

2) `nomad server-force-leave` to leave the old version.

Both of these are just ways to tell the Raft system that server no longer is a member.

Hope that helps,
Alex!

**Comment by kak-tus** [comment]
Both of these options have not helped.

**Comment by dadgar** [comment]
@kak-tus Retro-actively a different step has to be taken. The address get written to a file inside the servers data directory called raft/peers.json. If you look in the file you may see addresses of the old servers that should not be part of the cluster. To recover you stop the servers and then remove the old servers from this file and start up again.

You can see the guide Consul has as it is very similar:
https://www.consul.io/docs/guides/outage.html#peers.json

**Comment by kak-tus** [comment]
Thank you, it works.

**Comment by dadgar** [comment]
@kak-tus Great glad to help!
