### ISSUE TITLE
Can not run a batch job twice (nomad run / stop / run ) ...

### ISSUE THREAD

**Issue by tiagoalves83** [hashicorp/nomad#2149]
I have a simple job file "sleep.nomad" that basically runs a "raw_exec" task that sleeps for 15 seconds. The type of job is "batch"

I run the job, wait for it to finished and then try to run again. A new Evaluation is placed, but no new Allocation is generated. The Eval ID of the previous allocation is updated. 

Is this the right behavior ? Is it possible to run the same job file (not changed) multiple times ?

### Nomad version
Nomad v0.5.2

### Operating system and Environment details
Mac OS X - Sierra

### Issue
Can not run the same batch job file twice even when I stop the job and run again.

### Reproduction steps
`nomad run sleep.nomad `
`nomad status -verbose sleep`

Wait until job is completed (dead)
`nomad stop sleep`
`nomad run sleep.nomad`   

New evaluation is placed, the Eval ID of previous allocation is changed but task does not run again
`nomad status -verbose sleep`

Is this the right behavior ? Is it possible to run the same job file (unchanged or with minimal changes) multiple times ?

I believe a new Allocation should be placed.
### Job file
```
job "sleep" {
  datacenters = ["dc1"]

  type = "batch"

  update {
    stagger = "10s"
    max_parallel = 1
  }

  group "sleep-group" {
    count = 1

    restart {
      attempts = 10
      interval = "5m"
      delay = "25s"
      mode = "delay"
    }

    ephemeral_disk {
      size = 300
    }

    task "sleep-task" {
      driver = "raw_exec"

      config {
        command = "/bin/sh"
        args = ["-c", "sleep 15"]
      }

      resources {
        cpu    = 200
        memory = 32
      }

    }
  }
}
```

**Comment by dadgar** [comment]
Hey @tiagoalves83,

The job name is a unique identifier in Nomad and represents an instance of a job. In order to re-run the same job we suggest appending a unique value/timestamp to the end of the job. You can see this being done if you run a periodic job. In the future when we have more advanced interpolation and functions in the job file, we will be able to make this easier. `job "test-${timestamp_unixsecond()}"` (spit balling syntax).

Hope that helps and let me know if you have any questions,
Alex
