### ISSUE TITLE
Service registration with fqdn rather than ip address

### ISSUE THREAD

**Issue by turkenh** [hashicorp/nomad#2166]
While registering services with nomad, service address is always set to ip of the service.

It would be very handy if there is an option to register services with fully qualified domain names especially when there is a proxy in the environment. 

Do you consider adding such an option in the near future? 

### Nomad version
Output from `nomad version`
Nomad v0.5.2-rc1

**Comment by derzufall** [comment]
+1 we so need this. Right now the auto-registry feature with IPs is broken for us since we need proper hostnames for TLS and stuff. A configurable template for what should be used to register a service from a specific node would solve this nicely.

There are very similar requests to this:
https://github.com/hashicorp/nomad/issues/2770
https://github.com/hashicorp/nomad/issues/4815

**Comment by roman-vynar** [comment]
We also need to register Consul services using FQDN by Nomad because we want to use HTTPS with TLS verify for discovered services.
Also a service healthcheck address should be also configurable and allow us to set FQDN to do an internal consul http check using https://hostname address w/o any InsecureVerify True because it's insecure :)

Currently, we patched Nomad like this https://github.com/Quiq/nomad/commit/a081ee28ad22dc1acc0a8c3fde7b063b7809c4aa

**Comment by tomiles** [comment]
I support this idea, would be good if the `tls_server_name` option that exists in consul for checks would also be configurable in the nomad _check_ stanza. So we can verify TLS certs based on FQDN of the service.

**Comment by beautifulentropy** [comment]
@tgross I've filed a PR for this today 🤞🏻.

**Comment by tgross** [comment]
#17334 has been merged and will ship in Nomad 1.6.0
