### ISSUE TITLE
[Feature request] allow system tasks on "drain" or idle type of nodes

### ISSUE THREAD

**Issue by salkin** [hashicorp/nomad#2188]
A use case where system task should be scheduled on every node where drain is set to allow monitoring tasks to exist but not normal service/batch jobs

In the following example:

nomad node-status
ID        DC   Name         Class  Drain  Status
3294fd72  dc1  necc3.local  aux    false  ready
f3c05335  dc1  necc2.local  aux    false  ready
f653ee86  dc1  necc0.local  cm     true   ready
9e83a18d  dc1  necc4.local  aux    false  ready
c9bc4fbc  dc1  necc1.local  cm     true   ready

aux nodes take normal service/batch jobs. As we don't want to put constraints on the class for the jobs due to jobs need to be scheduled on "cm" class where drain is removed if "aux" nodes fails. 

### Nomad version
nomad --version
Nomad v0.5.0

**Comment by dadgar** [comment]
Maybe a `nomad node-drain --all` and `--exclude-system`

**Comment by dvusboy** [comment]
I'm confused. What's then the purpose of the drain? Are you, instead, asking for drain order?

**Comment by salkin** [comment]
I did not come up with a good name what to call it. 

The purpose in this case is couple of nodes run resources not yet moved to Nomad so those should be "idle" from taking Nomad jobs, but for system jobs it would simplify if the nodes in "idle"  by having drain enabled would take the system job also. 

This way monitoring jobs would go to all nodes.

**Comment by burdandrei** [comment]
I'll piggyback on this one instead of opening a new issue.

As of `0.10.4` there is an option to `nomad node drain -ignore-system` to leave system jobs running.
In our use case when we roll out a new version of AMI (nomad upgrade or any other update), we mark old instances as ineligible, that leads to failure of deploying the system jobs across the fleet if some of our monitoring tools needs to be updated, and they are running as **system** jobs.

We'd like to propose an enhancement when eligibility will affect only service/periodic/batch schedulers, but system scheduler will remain fully functional to keep these jobs updatable.

**Comment by tgross** [comment]
@burdandrei I think @josegonzalez has it right that the original issue should have been closed. Can you open a new issue so your feature request can be discussed in more detail and not get lost amidst the original request?
