### ISSUE TITLE
Disk space allocation issues with exec driver

### ISSUE THREAD

**Issue by Ashald** [hashicorp/nomad#2296]
### Nomad version
`Nomad v0.5.4`

### Operating system and Environment details
CentOS 7

### Issue
Nomad supports `ephemeral_disk` stanza that can be specified on the group level and essentially controls the `alloc` directory which is shared across all tasks within groups. Except the `alloc` dir, there are 2 more things that are present for each task: `local` and `chroot`. The latter one is essentially a number of dirs & hardlinks so it doesn't consume much space (presumably) and the former one is... just a dir on FS, right?
By default, Nomad download artifacts to to the `local` dir. Didn't try that yet but presumably, if the disk space is exhausted after allocating space for `alloc` and there is not enough space to download artifact the job will fail and Nomad will re-schedule it.
Though the most interesting part begins here. In our use-case, the artifacts that are downloaded have to be "installed". Although it's possible it doesn't make much sense to install artifacts into `alloc` as they're unique to each task and we don't need to move them around (in case of sticky/migratable disks). But if we will try to install them into `local` or `virtual root` dirs/sub-dirs (which would require at least as much space as artifacts take), we don't have any guarantees that there will be enough space to actually install them.

*Proposed solution*
Allow `ephemeral_disk` stanza (or something similar) on the `task` level that would allow for allocation of space for individual tasks.

**Comment by dadgar** [comment]
@Ashald Hey we actually moved away from specifying the disk resources at the task level in 0.5.0. The reason for this is since there is a shared directory there is no way to account which task is writing to the allocation directory. So we pushed it up to the group.

Further, right now we do not enforce the quota but use it for bin-packing. In the future this will be enforced via file system drivers. I am going to close this issue since we have been down this path already :). 

Please let me know if you have any questions!
Alex
