### ISSUE TITLE
Node status does not report allocations in json format

### ISSUE THREAD

**Issue by burdandrei** [hashicorp/nomad#2317]
### Nomad version
0.5.4
### Operating system and Environment details
Ubuntu 16.04.1
### Issue
running nomad node-status -self -json doesn't report allocations
### Reproduction steps
nomad node-status -self -json

**Comment by dadgar** [comment]
Hey,

Nomad 0.6.0 is going to do a redesign of the CLI and introduce more granular commands. So something like `nomad node allocs -self -json` would likely be the command. I am going to close this issue since we will not be bring allocs to the json output of the existing command.

Thanks! If my response doesn't make sense let me know! Not at all being dismissive, we agree the CLI should make accessing what you need easier 👍

**Comment by burdandrei** [comment]
I just tried to make temporary workaround for this https://github.com/hashicorp/nomad/issues/2191
I saw it was marked to 0.5.4 milestone, but as long as it's not implemented I started to work on PR for this, cause as it looks like everything needs to be done is  to add data from https://github.com/hashicorp/nomad/blob/master/command/node_status.go#L319  to https://github.com/hashicorp/nomad/blob/master/client/client.go#L2206

Correct me if it's wrong, otherwise I can provide PR in couple of days.

**Comment by dadgar** [comment]
@burdandrei Yeah would love a PR!

**Comment by burdandrei** [comment]
I saw you made the job @dadgar , but here is a bit more https://github.com/hashicorp/nomad/pull/2330
