### ISSUE TITLE
Intermittent JWT failures with Vault

### ISSUE THREAD

**Issue by elburb** [hashicorp/nomad#23387]
### Nomad version

Nomad: Servers 1.8.1 / Agents 1.8.1
Vault version: 1.17.0

### Operating system and Environment details

Debian bookworm 12.5 for all servers

Nomad environment:
 - 3 node server cluster accessed via a traefik endpoint 'https://nomad.burble.dn42'
   - note the server nodes are on a WAN with ~20ms latency between nodes
   - there are also multiple traefik instances, each traefik instance will load balance across the nomad cluster members
 - ~16 nomad agents distributed globally

Vault environment:
 - 3 node cluster, also accessed via traefik,'https://vault.burble.dn42'
   - the cluster nodes are also on a WAN with ~20 ms latency between nodes
   - traefik directs requests to the active vault node

mTLS is configured between all nomad server/agent and vault cluster members using a vault managed certificate. 

### Issue

Tasks requiring vault secrets sometimes fail to start, with the following error:

_Killing: Vault: failed to derive vault token: failed to derive Vault token for identity vault_default: failed to login with JWT: Error making API request. URL: PUT https://vault.burble.dn42/v1/auth/jwt-nomad-bdn42/login Code: 400. Errors: * error validating token: error verifying token signature: failed to verify id token signature_

### Reproduction steps

The issue manifests against any tasks with vault secrets configured but without any pattern that I have been able to identify.

When the task fails to start it will then fail repeatedly for some period, but will eventually work. This period could be anywhere from a few minutes to several hours. The same task (running with the same agent/node/server combination) can start normally at other times, without issue. This would seem to rule out a fixed configuration issue and point towards a transient network, latency or load balancing problem.

Other tasks, that also have vault dependencies, started at the same time as the failing tasks will happily work.
 
Whilst traffic between cluster members (both for nomad and vault) is over a WAN, there are no apparent connectivity, or DNS issues at the times of failures. Bandwidth between cluster members is ~gbit with ~20ms latency (latency to nomad agents can be up to 250ms though). I have run continuous checks from nomad servers and agents to vault and from vault to the nomad https://nomad.burble.dn42/.well_known/jwks.json endpoint with no issues. The jwks.json returned is the same across all 3 cluster nodes.

#### Expected Result

JWT login should be successful and vault secrets obtained all the time

#### Actual Result

Tasks sometimes work, sometimes fail.

### Job file (if appropriate)

Task config

```
    task "xxx" {
...
      vault {}

      template {
        destination = "secrets/xxxx"
        env = true
        change_mode = "restart"
        perms = "600"
        data = <<EOF
SECRET="{{ with secret "burble.dn42/secrets" }}{{ .Data.data.SECRET }}{{
 end }}"
EOF
      }
    }
```

Server config

```
vault {
  enabled = true
  address = "https://vault.burble.dn42/"
  create_from_role = "nomad-cluster"

  default_identity {
    aud = ["vault.io"]
    ttl = "48h"
    file = false
    env = false
  }
}
```

Vault JWT endpoint:

```
https://nomad.burble.dn42/.well-known/jwks.json
```

The JWT endpoint is a traefik instance which will load balance across all 3 nomad cluster members.

**Comment by tgross** [comment]
@elburb there are a lot of components at play here, and it would help to know where the failure is actually happening. Can you provide relevant sections of the logs for the Nomad client, and the Vault instance it's reaching? It would also help to see logs from the traefik instance that's handling the JWT key verification request (if that's being refreshed here), and the Nomad server that's handling that request.

**Comment by elburb** [comment]
Yes, its not very clear to me at all where the failure could happening, so I appreciate the help in narrowing this down.

I managed to reproduce the issue in a slightly simpler environment, by forcing all traffic through a single traefik instances and only to the nomad and vault leaders. So the environment now looks like this:

- There are two servers 'de-fra1' and 'de-fra2', with ~1ms latency between them.
- The traefik instance is located on de-fra1
- The nomad cluster leader is on de-fra1 (nomad.tier2.de-fra1.burble.dn42) and traefik is sending all requests to this instance.
- The vault cluster leader is on de-fra2 (vault.tier2.de-fra2.burble.dn42) and again traefik is sending all requests to this instance.
- Both servers have nomad agents running on them ('containerd.tier2.de-fra[12].burble.dn42')

My 'workstation' is used to run a job that has allocations on both de-fra1 and de-fra2. 
The job has multiple tasks which require vault secrets (3 in total)
- I start the job
- The allocation on de-fra1 completes successfully
- The allocation on de-fra2 fails
- I then stop the job

Attached are:
- The job .hcl file ('cloudflared-de.hcl')
- The traefik logs, covering all vault and nomad requests. This is an active cluster and I've removed all the '/v1/service*' requests from the log for other services but you can still see other unrelated requests in there. I've also replaced the IP addresses of the relevant nodes with their hostnames to make it easier to pick out the releveant requests.
- The nomad client logs for de-fra1 and de-fra2
- There was nothing logged on the nomad server
- There was nothing logged on the vault server
- 
[cloudflared-de.hcl.txt](https://github.com/user-attachments/files/15925323/cloudflared-de.hcl.txt)
[traefik.log.txt](https://github.com/user-attachments/files/15925331/traefik.log.txt)
[client-de-fra1.log.txt](https://github.com/user-attachments/files/15925309/client-de-fra1.log.txt)
[client-de-fra2.log.txt](https://github.com/user-attachments/files/15925310/client-de-fra2.log.txt)


The traefik log is able to show the failure from de-fra2:

```
vault.tier2.de-fra2.burble.dn42 - - [20/Jun/2024:14:33:03 +0000] "GET /.well-known/jwks.json HTTP/2.0" 200 171 "-" "-" 2027 "nomad-router@file" "http://nomad.tier2.de-fra1.burble.dn42:4646/" 0ms
containerd.tier2.de-fra2.burble.dn42 - - [20/Jun/2024:14:33:03 +0000] "PUT /v1/auth/jwt-nomad-bdn42/login HTTP/2.0" 400 108 "-" "-" 2026 "vault-router@file" "https://vault.tier2.de-fra2.burble.dn42:
8200/" 12ms
vault.tier2.de-fra2.burble.dn42 - - [20/Jun/2024:14:33:03 +0000] "GET /.well-known/jwks.json HTTP/2.0" 200 171 "-" "-" 2029 "nomad-router@file" "http://nomad.tier2.de-fra1.burble.dn42:4646/" 0ms
containerd.tier2.de-fra2.burble.dn42 - - [20/Jun/2024:14:33:03 +0000] "PUT /v1/auth/jwt-nomad-bdn42/login HTTP/2.0" 400 108 "-" "-" 2028 "vault-router@file" "https://vault.tier2.de-fra2.burble.dn42:8200/" 4ms
vault.tier2.de-fra2.burble.dn42 - - [20/Jun/2024:14:33:03 +0000] "GET /.well-known/jwks.json HTTP/2.0" 200 171 "-" "-" 2031 "nomad-router@file" "http://nomad.tier2.de-fra1.burble.dn42:4646/" 0ms
```

together with the successful de-fra1

```
containerd.tier2.de-fra1.burble.dn42 - - [20/Jun/2024:14:33:03 +0000] "PUT /v1/auth/jwt-nomad-bdn42/login HTTP/2.0" 200 727 "-" "-" 2025 "vault-router@file" "https://vault.tier2.de-fra2.burble.dn42:8200/" 94ms
containerd.tier2.de-fra1.burble.dn42 - - [20/Jun/2024:14:33:03 +0000] "PUT /v1/auth/jwt-nomad-bdn42/login HTTP/2.0" 200 722 "-" "-" 2040 "vault-router@file" "https://vault.tier2.de-fra2.burble.dn42:8200/" 89ms
containerd.tier2.de-fra1.burble.dn42 - - [20/Jun/2024:14:33:03 +0000] "PUT /v1/auth/jwt-nomad-bdn42/login HTTP/2.0" 200 718 "-" "-" 2041 "vault-router@file" "https://vault.tier2.de-fra2.burble.dn42:8200/" 91ms
```

**Comment by tgross** [comment]
Thanks @elburb. As you said, there's not a whole lot there but we can see that this is heading into Vault and returning an error from there. It doesn't look like there are any proxy-related errors because of traefik, because we're getting a consistent application-level error here.

I hunted down the specific error message you're seeing from Vault to the Vault JWT plugin to HashiCorp's [`cap`](https://github.com/hashicorp/cap) library to the `coreos/go-oidc` library. The error is coming from [`oidc/jwks.go#L179`](https://github.com/coreos/go-oidc/blob/6b94bec0d3f54b3546c663f6c1f4dd2620bf5d49/oidc/jwks.go#L179). From the surrounding context, we can see that this function:
* Looks for the key ID in the header.
* Looks up that key in its local cache of keys.
* If found, verify the signature with that key.
* If not found, or _if that verification fails_, try to get the key from the remote (JWKS endpoint in this case).
* If found on the remote, verify the signature with that key.
* If not found, or _if that verification fails_, return the error you're seeing.

Somewhat frustratingly, this function swallows all its internal errors, so there's no way for Vault to tell us what went wrong! There could be something wrong with the structure of the signature (ex. missing key ID header), something wrong with the key material, the JWKS endpoint request could have failed, or the structure of the signature is ok but it otherwise failed validation (ex. its expired).

Sorry I don't have an answer for you yet here. But here's some next steps for debugging:
* Verify that all 3 Nomad servers have an identical keyring store file (see the [Key Management / Backup](https://developer.hashicorp.com/nomad/docs/operations/key-management#restoring-the-keyring-from-backup) docs). Keys are replicated and I'd expect all kind of other problems if they weren't, but it's not a bad place to check.
* Verify that all the Nomad and Vault servers have their clocks aligned with NTP or chrony or the like.
* For an allocation that's failed the JWT, grab the token from the allocation's `/secrets` directory and see if you can verify the signature yourself.
  * You can check the structure with something like https://jwt.io/
  * You can check the validity from Nomad's perspective by using it as a HTTP token for an API that jobs have access to like [`nomad operator api /v1/services`](https://developer.hashicorp.com/nomad/api-docs/services)).

**Comment by elburb** [comment]
Thanks again for the comprehensive response.

I can confirm all servers run chrony and are stratum 2 (albeit to different ref-clocks). Each server has the others configured as 'noselect' and the maximum offset between any pair of servers is less than 10ms. 

More interesting is the keyring information. Here I checked the contents of the `server/keystore` directory together with the output of `nomad operator root keyring list` and the `.well-known/jwks.json` endpoint for each server.

The outputs from keyring list and the jwks.json are consistent for each server:

```
$ nomad operator root keyring list

Key       State   Create Time
6c6e457c  active  2023-09-13T11:20:17+01:00

$ wget -q -O- "[ server address]/.well-known/jwks.json" | jq .
{
  "keys": [
    {
      "use": "sig",
      "kty": "OKP",
      "kid": "6c6e457c-3bbc-8f69-5ffd-0ae9a1de2a07",
      "crv": "Ed25519",
      "alg": "EdDSA",
      "x": "nzE7apbfhPe33BNKjzyrWHgS6JflZirW4yXg3qAURww"
    }
  ]
}
```

However, the keystore contents are not. 
One server (de-fra1 - the cluster leader at this time) has a different key than the others:

```
de- fra1: 6c6e457c-3bbc-8f69-5ffd-0ae9a1de2a07.nks.json
fr-par1: 4a7d8f64-ecb5-b3c4-ebca-bc6f4cd94705.nks.json
uk-lon4: 4a7d8f64-ecb5-b3c4-ebca-bc6f4cd94705.nks.json
```

I tried transferring the leadership to a different node (fr-par1). Again the outputs from keyring list and the jwks.json are consistent, but now reflect the key available in the keystore for that server:

```
$ nomad operator root keyring list

Key       State   Create Time
4a7d8f64  active  2023-09-13T11:07:01+01:00

$ wget -q -O- "[ server address]/.well-known/jwks.json" | jq .
{
  "keys": [
    {
      "use": "sig",
      "kty": "OKP",
      "kid": "4a7d8f64-ecb5-b3c4-ebca-bc6f4cd94705",
      "crv": "Ed25519",
      "alg": "EdDSA",
      "x": "VMDwNUl8BtFjrmeKtiW-nMzSisCyGJ2duQJc3CTsVm0"
    }
  ]
}
```

It's not clear to me if this is actually a problem or not, or how this could lead to JWT failures. Different keys on each server appears to be part of the design (ref the linked Key Management/Backup docs), but in that case, it's then not clear why two servers have the same key !

The also appears to be a lack of key rotation ? note that both keys appear to be ~9 months old. 

I'm happy to try a manual key rotation (keyring rotate -full) but wanted to check first that this was a safe thing to do.

**Comment by elburb** [comment]
After a few attempts, I was able to capture a failed and successful JWT.
I was unsuccessful at getting either token to work via the API though, so I'm missing something there.

Failed jwt:

```
{
  "alg": "EdDSA",
  "kid": "4a7d8f64-ecb5-b3c4-ebca-bc6f4cd94705",
  "typ": "JWT"
}

{
  "aud": "nomadproject.io",
  "iat": 1719571963,
  "jti": "295160bc-[removed]",
  "nbf": 1719571963,
  "nomad_allocation_id": "522f47a4-558d-d373-644b-abc7e79cf009",
  "nomad_job_id": "cloudflared-ch",
  "nomad_namespace": "default",
  "nomad_task": "cloudflared",
  "sub": "eu:default:cloudflared-ch:cloudflared:cloudflared:default"
}
```

A few seconds later the same task on the same node successfully worked

```
{
  "alg": "EdDSA",
  "kid": "4a7d8f64-ecb5-b3c4-ebca-bc6f4cd94705",
  "typ": "JWT"
}

{
  "aud": "nomadproject.io",
  "iat": 1719572204,
  "jti": "27928341-[removed]",
  "nbf": 1719572204,
  "nomad_allocation_id": "92e91e4f-85cb-436d-6418-808eeba52159",
  "nomad_job_id": "cloudflared-ch",
  "nomad_namespace": "default",
  "nomad_task": "cloudflared",
  "sub": "eu:default:cloudflared-ch:cloudflared:cloudflared:default"
}

```

```
$ export NOMAD_TOKEN="295160bc-[removed]"
$ nomad operator api /v1/services
Permission denied

$ export NOMAD_TOKEN="27928341-[removed]"
$ nomad operator api /v1/services
Permission denied
```

**Comment by tgross** [comment]
> However, the keystore contents are not.
> One server (de-fra1 - the cluster leader at this time) has a different key than the others:

Ok, that's almost certainly the issue. The key material is split between key metadata (what you get when you run `nomad operator root keyring list`) which is replicated via Raft, and the key material, which is replicated out of band. We intend to change this at some point because the key management and backups are more of an operator burden than we expected. See https://github.com/hashicorp/nomad/issues/14852. 

What's complicating debugging here is that Nomad servers forward requests to the leader. So when you ran `wget` to each server in turn, that server was always forwarding to the leader. To get a view from the follower, you'd need to pass the [`stale`](https://developer.hashicorp.com/nomad/api-docs#consistency-modes) query parameter.

Nomad servers can have multiple keys but only one will be the "active" key which is used for signing requests. Labeling the key as active is part of the metadata, so at this point we know that the `de-fra1` server has an "active" key that is has no key material for. Now that we know that, the only thing that smells weird to me is that I would not expect either the signing request or the JWKS endpoint to hit the non-leader instance. But it could be that the Vault made the JWKS request, a leader was elected that moved the `de-fra1` server into play, and then subsequent signed Workload Identities would be with the wrong key.

In any case, performing a key rotation should ensure that all machines have the same active key, although you may need to update the Auth Method in Vault to make sure it picks up the new key (improving that story is also on our TODO list). It's also entirely safe for you to simply copy those `nks.json` files around so that everyone has all the keys, and the metadata in Raft should sort that out after a restart.

**Comment by elburb** [comment]
> Now that we know that, the only thing that smells weird to me is that I would not expect either the signing request or the JWKS endpoint to hit the non-leader instance. 
> But it could be that the Vault made the JWKS request, a leader was elected that moved the de-fra1 server into play, and then subsequent signed Workload Identities would be with the wrong key.

No, this is definitely not the case. The leader role is quite stable and won't typically change without intervention. I have watched the cluster several times whilst the issue has occured and it happens way too frequently to be explained by leadership changes.

Sorting the keys out looks really promising, is there any more debug I can help get before having a go at fixing it ?

**Comment by tgross** [comment]
> No, this is definitely not the case. The leader role is quite stable and won't typically change without intervention. I have watched the cluster several times whilst the issue has occured and it happens way too frequently to be explained by leadership changes.

Oh wait, the signing request is potentially made to a follower! See [`signer.go#L70-L76`](https://github.com/hashicorp/nomad/blob/v1.8.1/client/widmgr/signer.go#L70-L76), where we have `AllowStale: true`. The client requests the signed identity from whichever server it happens to be currently connected to. We just make sure that the server is caught up enough in Raft to know about the allocation. A different in key _material_ shouldn't make a difference though because the follower with the wrong active key should not be able to sign with the old key; it should be returning an error! So that points to a potential bug for sure.

> Sorting the keys out looks really promising, is there any more debug I can help get before having a go at fixing it ?

It'd definitely be worth verifying what each server's keyring looks like with that `stale` query parameter (both `/.well-known/jwks.json?stale` and `/v1/operator/keyring/keys?stale`). If that `de-fra1` server has a different "active" key, then that's going to be a smoking gun here.

**Comment by elburb** [comment]
Yes, as you suspected using ?stale returns the local key and its different on de-fra1. 
I will rotate the keys and I expect that will resolve the issue. 

Thinking more about the root cause though, there is definitely something else going on. 

Note in the first debug I provided I had disabled the traefik loadbalancer so that _only_ the nomad cluster leader was accessible. The requests show a failure, then success, then failure again in quick succession, and neither the vault and nomad leaders changed within this time (nor could they, the time window is too short). Specifically the nomad leader was on de-fra1 throughout the test and you can see all the API requests go to this server in the traefik logs. 

However, the cluster comms don't use the load balancer, both the nomad clients and servers have the cluster members configured statically:

```
client {
  enabled = true 
  servers = [
    "nomad.tier2.de-fra1.burble.dn42:4647",
    "nomad.tier2.fr-par1.burble.dn42:4647",
    "nomad.tier2.uk-lon4.burble.dn42:4647"    
  ]
```

I understand the design is that all crypto requests should be forwarded to the leader (de-fra1), but this can't be true. The only way the error could possibly have occured in this configuration is if one of the followers (fr-par1 or uk-lon4) had picked up the request and signed the JWT using its local key material ?

**Comment by elburb** [comment]
> Oh wait, the signing request is potentially made to a follower! 

Missed that bit ;) 

yes agree. I think the first bit of debug proves that the signatures appear to be made with the follower key material without showing errors.

**Comment by elburb** [comment]
ok, so I did an `operator root keyring rotate -full`, all nodes picked up the new key and the first vault job that I ran worked ok and without issues, so I count that as success so far. 

A couple of notes:

The rotation automatically created a new RSA key (it was originally ed25519). That's not really a problem for me but it might be for someone else. I didn't spot anything in the docs (https://developer.hashicorp.com/nomad/docs/commands/operator/root/keyring-rotate) to suggest any way of specifying the key type.

Running `operator root keyring list` suggests the original key is still rekeying after >40mins which seems a while. There's no log or excessive cpu to suggest that nomad is actually doing anything though and it doesn't appear to be impacting anything.

**Comment by tgross** [comment]
> The rotation automatically created a new RSA key (it was originally ed25519).

Right, we updated that in Nomad 1.7.0. See the [upgrade notes](https://developer.hashicorp.com/nomad/docs/upgrade/upgrade-specific#rs256-jwt-signing-algorithm-support). As of today there's no way to set the key type.

> Running operator root keyring list suggests the original key is still rekeying after >40mins which seems a while

Did you use the `-full` parameter on that command? That could be https://github.com/hashicorp/nomad/issues/19368, but you're right there's no resource use happening because of it. It's just a state flag that's not getting properly set.

**Comment by elburb** [comment]
great, thanks @tgross for the support and patience working through this issue and getting to the root cause. Your help has been much appreciated. 

As far as I'm concerned my specific issue is resolved and can be closed.
