### ISSUE TITLE
Can not create the empty file from template: Must specify a source path or have an embedded template

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#23415]
### Nomad version
```
v1.8.0
```

### Issue
I am trying to create the empty file
```
      template {
        destination = "$NOMAD_ALLOC_DIR/creds.env"
        data = ""
      }
```
but have got the error:
```
Error during plan: Unexpected response code: 500 (1 error occurred:
	* Task group postgres-db validation failed: 1 error occurred:
	* Task postgres-task validation failed: 1 error occurred:
	* Template 2 validation failed: 1 error occurred:
	* Must specify a source path or have an embedded template)
```

[The documentation says](https://developer.hashicorp.com/nomad/docs/job-specification/template#data):
> One of source or data must be specified, but not both.

I have specified `data` option and I provided the explicit value `"" `. 

### Reproduction steps
nomad plan ...

#### Expected Result
I should be able to create the empty file.

#### Actual Result
An empty file was not created. The user should not be restricted from a creation of empty files.

**Comment by tgross** [comment]
Hi @EugenKon! Go's deserialization of JSON to a string can't differentiate between an empty string and unset, so when the `template` block is parsed we always end up with an empty string for that field. We need to validate that one of `source` vs `data` is set, so that's why you're getting that error. There are ways we could have designed the API around this but changing it now would break backwards compatibility.

You can workaround this by having the template `data` contain something that evaluates to an empty body. For example, something like:

```hcl
template {
  data = "{{ \" \" | trimSpace }}"
}
```
