### ISSUE TITLE
add back filter by "datacenter" in  the 1.8.1 UI

### ISSUE THREAD

**Issue by thefallentree** [hashicorp/nomad#23446]
this feature was removed in 1.8.1 but we still kind of needs it

**Comment by tgross** [comment]
@thefallentree I've flagged this for our UI folks, but just so you know, you can use a filter expression to find datacenters:

![datacenter-filters](https://github.com/hashicorp/nomad/assets/1409219/12179985-3d23-4f18-ad37-ac70f86383d7)

**Comment by philrenaud** [comment]
Hi @thefallentree , @tgross' suggestion about using filter expressions in the search box for this is the best way to handle it.

In a previous version of the UI, we pre-fetched every job in the cluster and pored over their datacenters in order to build a dropdown to select from. Nomad 1.8 made a change to how we display jobs (we now only show you a paginated subset of jobs, in order to cut down on initial load time) and as such we don't know the entire set of possible datacenters ahead of time.

**Comment by thetoothpick** [comment]
hey @philrenaud @tgross - I'd like to respectfully disagree with closing this.  the clients page still has this dropdown (which I assume it calculates from the full list of client nodes).  while that approach might not be the best use of bandwidth for the jobs page, it seems reasonable to add a REST endpoint to the cluster to return the list of available datacenters.
