### ISSUE TITLE
"port" seems not working when exec nc within nomad job

### ISSUE THREAD

**Issue by jzhao20230918** [hashicorp/nomad#23461]
hello,

I was testing the pretask example from the doc:
```
      driver = "exec"
      config {
        command = "sh"
        args    = ["-c", "while ! db.internal 3306; do sleep 1; done"]
      }
```
Everthing worked as expected until I accidentally changed the port from 3306 to 3333, which the port was not open, and I got a succeed message as well: "Connection to db.internal (10.31.140.41) 3333 port [tcp/*] succeeded!!"

I tried the command on my host machine and it failed as it should be.

Is this a bug of exec driver? The Nomad version is 1.8.1.

Thanks,

**Comment by tgross** [comment]
@jzhao20230918 the example in the documentation is running the [`nc(1)`](https://linux.die.net/man/1/nc) command with the `-z` parameter that makes it scan. You'd omitted the command entirely from your example, which means it's not a valid shell script at all, but if you're seeing that success message you've probably omitted the `-z` flag (or are using `busybox` for your `nc` instead of GNU `nc`, in which case there is no `-z` flag).

In any case, Nomad is just running the command you gave it. If that command is connecting to an address, there's definitely something listening at that address. This isn't an issue with Nomad at all.

**Comment by jzhao20230918** [comment]
![1719585625509](https://github.com/hashicorp/nomad/assets/145320661/5c522d92-08fa-447f-b2ff-55771487e1a9)
result from my host machine.

**Comment by tgross** [comment]
@jzhao20230918 your screenshot doesn't match your report; you're connecting to port 3306 successfully as I'd expect, and not 1111. In any case, this is not a Nomad issue and is out of scope here.

**Comment by jzhao20230918** [comment]
The screen shot was I did testing on my host machine not in docker and nc can connect with 3306 but not 1111. In the Nomad job, both 1111 and 3306 gave a successful connection message.
