### ISSUE TITLE
Server - Voting-only member / Arbitrator-only

### ISSUE THREAD

**Issue by EtienneBruines** [hashicorp/nomad#23542]
### Proposal

Have a `only_voting_server`  option in the `server` block which makes sure that the server never becomes a leader (e.g. never reaches `candidate` or `leader` states in the Raft protocol).

This way, that server can remain relatively lightweight and will only function as an *arbitrator*. 

I'm unfamiliar with the Raft consensus protocol, so I do not know whether those arbitrators should replicate the log entries (probably yes), but at least the node does not need CPU horsepower to be capable of scheduling jobs / managing the cluster. 

### Use-cases
- Added resilience in case of outages, where (given enough of these lightweight arbitrator-nodes) only one "chunky" server has to survive during an outage.
- Clients do not have to be able to reach those arbitrator nodes, so they can be added with more ease.

### Attempted Solutions
- Simply adding more "chunky" servers.

**Comment by tgross** [comment]
Hi @EtienneBruines! The Raft consensus algorithm requires that voting servers are potential candidates, because voters always propose themselves as candidates first. I believe what you may be looking for here is the Nomad Enterprise feature referred to as "Enhanced Read Scability": https://developer.hashicorp.com/nomad/docs/enterprise#enhanced-read-scalability

**Comment by EtienneBruines** [comment]
@tgross Thank you for your quick reply! I did not know  (but was mentally prepared for) it being a limitation of Raft itself.

Enhanced Read Scalability is a nice feature, but not what we were wondering about here. More specifically we were thinking: What if they didn't read-replicate (so no need for them to handle any traffic), but instead just helped figure out who should be the next leader in case of an outage.

Feel free to close this - probably not worth it to deviate from the Raft protocol to satisfy my curiosity.

**Comment by tgross** [comment]
> What if they didn't read-replicate (so no need for them to handle any traffic), but instead just helped figure out who should be the next leader in case of an outage.

Ah, I see the difference. Yeah, it's an interesting idea, for sure. Some thoughts that come to mind...

The quorum size ("q") is the same when you have voting-only nodes, and not all members are eligible candidates. Which means it's arguably less resilient to failure than an equivalent-size cluster of normal nodes, because you need to maintain the quorum size but only a subset of that quorum is useful for recovery. Ex. if you have 5 nodes you have q=3. If 2 nodes fail, you have 3 possible candidates in the normal case but between 1 and 3 possible candidates in the case of 2 voter-only nodes. (Depending on which types of nodes fail.)

That also suggests that voter-only nodes would increase the rate at which you'd have election timeouts relative to a same-sized cluster with normal nodes. Consider a cluster of 3 normal nodes and 2 voter-only nodes (q=3). If the leader fails and both normal nodes have a collision on their heartbeat timeout, each of the voter-only nodes could vote for different normal nodes. This can also happen in a cluster of 5 normal nodes, which is why Raft has randomization of the timeout and re-runs the election, but in a normal 5 node cluster you've got 4 potential candidates to break the tie, rather than only 2. 

> Feel free to close this - probably not worth it to deviate from the Raft protocol to satisfy my curiosity.

Aye, a feature like this would need to be implemented at the Raft level, and that'd require a much deeper analysis than the random musings I've done here :grin: I'm going to close this out, but thanks for the suggestion!
