### ISSUE TITLE
A lot of inconsistent information. It is not clear what is true

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#23584]
### Proposal
`nomad job run` shows that Deployment is failed, but in the UI interface it is healthy.

![image](https://github.com/user-attachments/assets/f9872479-08d7-4cae-a80e-a38bf64b339c)

1. We can see that nginx was placed 2 times and Unhelthy 2 times. It is not Heasthy
2. Deployment status failed
3. Another info that deployment failed
4. On the WebUI we also can see that something is failed
5. But, in compare to (1), nginx is running and healthy
6. Though it was failed before I run `nomad job run` (I think here it would be nice to display `check-index`. So we can understand they are related or not.
7. It is not clear what that means. Is it war 'running' then 'failed'??
8. Here we can see that nothing was failed. But what about (2) and (3)??
9. Everything is running, but what about (1), (2) and (3)??

**Comment by tgross** [comment]
@EugenKon Nomad reports fairly fine-grained status so that you can debug what's going on, and you can click on elements of the UI to give you more information. But here's what I see:
* The UI and CLI both show the deployment failed.
* The CLI gives the additional detail that deployment failed _due to progress deadline_. 
* The CLI shows that the `wi-nginx` task group placed 2 allocations, with 2 failed allocations and 0 healthy. Note this is _at the time the deployment failed_. Once the deployment fails, the CLI returns a non-zero exit code.
* The UI shows that the `wi-nginx` task group has 2 allocations, one is failed and the other is healthy.

From that, we can conclude that `wi-nginx` allocation `c998635d` did not become healthy before the progress deadline for the deployment expired, but became healthy afterwards. That results in a running allocation but an unhealthy deployment. 

You haven't provided the job spec, but f this deployment was an update and you had [`auto_revert`](https://developer.hashicorp.com/nomad/docs/job-specification/update#auto_revert), then we would instead see the deployment get rolled back to the previous version. We don't see that so either this is version 0 of the job or the `update.auto_revert = false`.
