### ISSUE TITLE
support running within a snap

### ISSUE THREAD

**Issue by stuart-warren** [hashicorp/nomad#23619]
### Proposal

We'd like to see support for running nomad within a snap (https://snapcraft.io/about)

There are only minimal tweaks required for this to function and maintaining our own patches is obviously undesirable
* unable to chown directories to `nobody` https://github.com/hashicorp/nomad/blob/v1.8.2/client/allocdir/fs_unix.go#L36-L66
* tmpfs volumes created by a snap are unavailable to the docker snap due to mount namespaces https://github.com/hashicorp/nomad/blob/v1.8.2/client/allocdir/fs_linux.go#L65-L109

### Use-cases

Permits running on operating systems that support snaps, this includes Ubuntu Core

### Attempted Solutions

Have tried running as a non-root user, however docker support on Ubuntu Core requires root or sudo access

We are currently maintaining our own patches

Happy to contribute a PR

**Comment by tgross** [comment]
Hi @stuart-warren! Running Nomad in a container is not supported. See [running Nomad in Docker](https://developer.hashicorp.com/nomad/docs/install/production/requirements#running-nomad-in-docker). https://github.com/hashicorp/nomad/issues/13669 describes some longer-term thinking around making this feasible (that issue is for rootless Nomad but most of the same problems apply when running in a container).

**Comment by stuart-warren** [comment]
Hi @tgross thanks for the reply

I'm not quite sure I follow what the problem is with this?

Are you happy for me to submit some PRs for changes that work for us and discuss any issues with them there?

**Comment by tgross** [comment]
@stuart-warren we _might_ be open to patches if they don't otherwise increase our burden of maintenance, but that's not going to change whether we officially support running Nomad in containers (ex. OCI images, snaps, flatpak, etc.). 

What tends to happen with these proposals is that folks submit patches that work in their environment with a specific task driver they use but will break a bunch of other task drivers. So then at the very least those patches need to have new config flags, and those configurations come with expectations around supporting those deployments. While teams like yours are obviously experienced enough and have a deep-enough understanding of cgroups, namespaces, seccomp, apparmor, etc. to make this work... many users do not and this increases the maintenance burden on our small team significantly.
