### ISSUE TITLE
Incorrect behavior of Nomad when disabling Consul.

### ISSUE THREAD

**Issue by uranru** [hashicorp/nomad#23821]
I am checking the operation of docker services in a Nomad cluster.
My services are running in Nomad and use DNS requests in Consul to work.
I turn off Consul.
I see errors in the Nomad logs.

`{"@level":"error","@message":"still unable to update services in Consul","@module":"consul.sync","@timestamp":"2024-08-15T10:34:03.875593+03:00","error":"failed to query Consul services: Get \"http://10.1.1.82:8500/v1/agent/services\": dial tcp 10.1.1.82:8500: connect: connection refused","failures":30}`

But the Nomad node does not take any action.
I think it should be marked as not working.
The services should restart.
Otherwise, the applications in the cluster stop working.
Consul is not available, Nomad cannot re-register services.

### Nomad version
Nomad v1.8.1
BuildDate 2024-06-19T06:43:57Z
Revision 5022543e4b7b8dcec9df123f86630ae3fdcffbe6

**Comment by pkazmierczak** [comment]
Hi @uranru, thanks for reporting this. I want to understand the issue better: are your jobs failing because they cannot register Consul services? Nomad will only fail service jobs if their [health checks](https://developer.hashicorp.com/nomad/docs/job-specification/service#check) fail. Do your health checks fail and Nomad still doesn't mark the jobs as failing?

**Comment by uranru** [comment]
If Consul is running, Nomad registers a service in it.
This service is accessible via DNS name.
For example, pbouncer.grafana.service.consul.
If Consul is disabled, Nomad cannot renew the service registration.
The service disappears from Consul.
The DNS name pbouncer.grafana.service.consul is not available.
Other services cannot connect to the database.
At the same time, the Job with pbouncer is green and continues to work on the Nomad node.

I think the Nomad and Consul bundle is critical.
If the Nomad node cannot connect to Consul, then after N attempts the node should be marked as faulty.
Jobs should start on other nodes where the Nomad and Consul bundle is working.

**Comment by pkazmierczak** [comment]
Thanks for clarifying, @uranru, I misunderstood the issue. 

In the past, Nomad would indeed clear node attributes on Consul/Vault failures, but it [no longer does that](https://github.com/hashicorp/nomad/pull/14673) since 1.4. The rationale is that if we change node attributes on every failed fingerprint to Consul/Vault, it significantly degrades cluster performance. Thus we decided that we will require Nomad client restarts to pick up Consul/Vault node attributes.

**Comment by uranru** [comment]
Thanks for your answer.
But I'm sad to know this.
It means I'll have to have additional scripts to check each job.
And this complicates the architecture.

**Comment by pkazmierczak** [comment]
Yeah sorry this complicates your arch, but these are the trade-off we settled for.
