### ISSUE TITLE
Backwards Incompatible Changes in Nomad 1.7 Driver RPC API

### ISSUE THREAD

**Issue by jseba** [hashicorp/nomad#23847]
There was a change to the Nomad Driver config sent by SetConfig in 1.7 that breaks running drivers built with the 1.7 APIs against a Nomad cluster running on previous versions. There is an API version field in the base config struct sent by Nomad and it was not incremented with this breaking change. This makes it impossible for the driver to decide if it should attempt to parse the Topology field in `ClientDriverConfig`.

The driver RPC version should have been incremented [here](https://github.com/hashicorp/nomad/blob/main/plugins/drivers/versions.go) so that drivers could determine what version of the struct they are getting from Nomad.

**Comment by jseba** [comment]
Furthermore, the executor interface never validates the information that it gets from the driver in CreateExecutor. It should be calling the Fallback NUMA scanner if it doesn't receive valid data or return an error telling the caller that the parameters were invalid.

https://github.com/hashicorp/nomad/blob/v1.7.7/drivers/shared/executor/utils.go#L50

**Comment by jrasell** [comment]
Hi @jseba and thanks for raising this issue. Incrementing the RPC version is something that we don't have an internal process for and has not been done since it was added. From internal discussions we had expected that adding fields to a protobuf API definition would be safe for downstream consumers. Could you describe a little more the problem is is causing and whether your driver is sniffing the version identifier to understand what actions it should perform?

> Furthermore, the executor interface never validates the information that it gets from the driver in CreateExecutor. It should be calling the Fallback NUMA scanner if it doesn't receive valid data or return an error telling the caller that the parameters were invalid.

If you could raise a separate issue for this that would be great. Keeping an issue to a single problem really helps.
