### ISSUE TITLE
UI: Support sorting jobs by columns in the jobs view

### ISSUE THREAD

**Issue by urusha** [hashicorp/nomad#23853]
### Proposal
Support sorting jobs by columns in the jobs view. That was supported before 1.8.

### Use-cases
Click (or two) on the column header is simpler/faster than putting ticks in the additional menu.

### Attempted Solutions
Downgrade to 1.7?

**Comment by philrenaud** [comment]
Hi @urusha , thanks for raising this. We made this choice deliberately when implementing pagination in 1.8.0; any column-based sorting we did in 1.7.x was doable because we pre-loaded all jobs into the client. This made sorting work, but prevented many-job-havers from being able to use the UI at all.

To try to offset this, we made the search/filter interface more robust with 1.8; you can now use more advanced filter expressions to pare your jobs list down. It's not the same as being able to sort, but I hope you'll find it useful.
