### ISSUE TITLE
WebUI: Hot key hint does not disappear when pressed combination was changed

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#24164]
### Nomad version
N/A

### Issue
When I press and hold SHIFT key I can see these hint:
![image](https://github.com/user-attachments/assets/f95bd840-7886-4d5d-a9c3-4c0d1a9e9369)

### Reproduction steps
But if I press SHIFT+CTRL the hint does not disappear regardless changed combination.

#### Expected Result
This hint should be active only when alone SHIFT is hold.

#### Actual Result
This hint is visible when CTRL+SHIFT are hold

**Comment by philrenaud** [comment]
Hi @EugenKon , thanks for the report. This is tricky because certain system hotkeys will take you out of the browser focus, and then the browser has no more ability to "see" the keyUp event on the shift key. On a mac, holding down the "screenshot" hotkeys (shift, command, 3/4) with shift will do this, for example.

The quickest way out of this is to give the browser focus again (ESC out of the screenshot context, in the example above; or click on the browser window again) and hit Shift again.

I'm going to mark this as closed/wont-fix, as I think any attempt to fix this will be adverse for other scenarios (fade out hints after ~5 seconds wouldn't fly, for example)
