### ISSUE TITLE
nomad node pool list does not return any pools, though Web UI does

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/nomad#24211]
### Nomad version
v1.8.2

### Operating system and Environment details
Linux nomad-consul-server-0-4b72 6.8.0-1016-aws #17-Ubuntu SMP Mon Sep  2 13:48:07 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Issue
`nomad node pool list` command return nothing
![image](https://github.com/user-attachments/assets/07b7e055-562f-47fd-8418-b8af93e4e9b1)

But through WebUI I can see default pool:
![image](https://github.com/user-attachments/assets/3651f39f-0454-47a5-9ee4-d4dd2a27fd0a)

### Reproduction steps
See above

#### Expected Result
I expect to see default node pool like here: 
https://developer.hashicorp.com/nomad/docs/commands/node-pool/list#examples

#### Actual Result
No pools are listed

**Comment by EugenKon** [comment]
@tgross Because I use the same token for nomad cli and nomad web ui and I am able to list pools via WebUI I expect to see the list for nomad cli command. The permission sets are the same for WebUI and CLI. Right?

Anyway here is my ACL file. I have `write` policy for `node`: https://developer.hashicorp.com/nomad/tutorials/access-control/access-control-policies#node-rules
```
namespace "*" {
    policy = "read"
    capabilities = [
      "submit-job", "read-logs", "read-fs", "dispatch-job",
      # `nomad alloc exec` requires
      # https://developer.hashicorp.com/nomad/docs/commands/alloc/exec#usage
      "alloc-exec", "read-job", "list-jobs"
    ]
}

node {
  policy = "write"
}

agent {
  policy = "write"
}

operator {
  policy = "write"
}

quota {
  policy = "write"
}

host_volume "*" {
  policy = "write"
}

plugin {
  policy = "read"
}
```

**Comment by tgross** [comment]
> Because I use the same token for nomad cli and nomad web ui and I am able to list pools via WebUI I expect to see the list for nomad cli command. The permission sets are the same for WebUI and CLI. Right?

ACLs are identical between the web UI and the CLI, yes, because they both use the same HTTP API. But that doesn't mean you're making the same HTTP request between them. When you're seeing the name of the node pool in the node list view in the web UI, you're looking at a field value from the [List Nodes API](https://developer.hashicorp.com/nomad/api-docs/nodes#list-nodes) which requires `node:read`. Listing the node pools is the [List Node Pools API](https://developer.hashicorp.com/nomad/api-docs/node-pools#list-node-pools) which as you can see requires `node_pool:read`.

So that'll require a policy that includes (ref https://developer.hashicorp.com/nomad/docs/other-specifications/acl-policy#node-pools-rules):

```hcl
node_pool "*" {
  policy = "read"
}
```



> btw. Why I can not select you from the list as I can do for other users?

No idea. This isn't the repo for GitHub Support. You'd need to take it up with them.

**Comment by EugenKon** [comment]
@tgross should `node_pool` be mentioned on this page too? https://developer.hashicorp.com/nomad/tutorials/access-control/access-control-policies
