### ISSUE TITLE
UI: can no longer sort columns on Jobs page on 1.8.x, 1.9.x

### ISSUE THREAD

**Issue by roman-vynar** [hashicorp/nomad#24278]
For some reason, you can no longer sort columns on Jobs page.
It was fine up to 1.7.x (confirmed with 1.7.5).

Then since 1.8.x after some UI changes this functionality was removed (confirmed with 1.8.4, 1.9.1).
Moreover, Jobs table header looks different and not consistent with other tables, i.e. on Clients, Servers pages.

What's the reason for that? It is very inconvenient there is no way to sort columns on Jobs page.

Jobs (columns are non-clickable):
<img width="1338" alt="Screenshot 2024-10-23 at 13 21 28" src="https://github.com/user-attachments/assets/53eeb53c-4364-463c-a5df-4cafb30cd4de">
Clients (columns are clickable):
<img width="1341" alt="Screenshot 2024-10-23 at 13 21 13" src="https://github.com/user-attachments/assets/c72fe06b-8214-4b3b-9057-2796936685e5">
Servers (columns are clickable):
<img width="1336" alt="Screenshot 2024-10-23 at 13 20 58" src="https://github.com/user-attachments/assets/4703de16-7b2f-4c21-9afb-f0f111775878">

**Comment by philrenaud** [comment]
Hi @roman-vynar, thanks for raising this.

We made the choice to remove sorting deliberately when implementing pagination in 1.8.0; any column-based sorting we did in 1.7.x was doable because we pre-loaded all jobs into the client. This made sorting work, but prevented many-job-havers from being able to use the UI at all.

To try to offset this, we made the search/filter interface more robust with 1.8; you can now use more advanced filter expressions to pare your jobs list down. It's not the same as being able to sort, but I hope you'll find it useful.
