### ISSUE TITLE
Ability to list all regions and their datacenters

### ISSUE THREAD

**Issue by F21** [hashicorp/nomad#243]
It would be nice if there's a way (using the cli and the http api) to get a list of all regions and their datacenters.

**Comment by cbednarski** [comment]
Thanks for the suggestion! We would like to add more ways to inspect Nomad's internal state, including datacenters and regions. We haven't scheduled work on this yet but we'd be happy to look at a PR for it.

**Comment by ryanuber** [comment]
Regions are now query-able, however the individual datacenters within each region are not currently available. This is a little more involved because we don't have the convenience of the gossip protocol for the client nodes, and by design only a single datacenter per region should have servers deployed in it. Nomad's API calls are all driven by the region ID and not the datacenter, so I'm not sure how useful it would even be. @F21 let me know if there is a specific use case you have in mind.

**Comment by F21** [comment]
@ryanuber My usecase is to build a web UI to perform monitoring and show the status of the nomad cluster. One of the key features would be to have a dashboard that shows all the clients and servers from all regions, and to be able to filter them by region and datacenter.

**Comment by ryanuber** [comment]
For the time being, with the addition of the `/v1/regions` endpoint, you can now get a complete world view by first querying the region ID's, and then querying the individual nodes, jobs, and allocations endpoints using the `?region=` parameter. Does that satisfy the use case? We might add specialized API's later on if needed, but there currently are no plans for this.

**Comment by F21** [comment]
I think that should be sufficient for now, however querying each node poses a scalability issue if we have got loads of nodes. Maybe an endpoint to get the status of nodes in 1 go would be nice, but I think we should open another issue for that.

**Comment by schmichael** [comment]
The [`/v1/agent/members` API](https://www.nomadproject.io/api/agent.html#list-members) and [`nomad server-members` CLI](https://www.nomadproject.io/docs/commands/server-members.html) includes this information.
