### ISSUE TITLE
use CPU base freq instead Max freq

### ISSUE THREAD

**Issue by vincentDcmps** [hashicorp/nomad#24302]
### Nomad version
v1.8.4

### Operating system and Environment details

Archlinux kernel 6.10.10

### Issue

I use on client with a processor intel n100 to calcul cpu.totalcomputer nomad seem use base frequency and not max frequency.
problem is on N100 processor base frequency is set to 800MHZ and max frequency is set to 3.4 GHZ this is a big gap.
Why don't use max frequency ?

**Comment by shoenig** [comment]
Hi @vincentDcmps, we use base frequency (when available) because your CPU cannot actually sustain the max frequency for more than small bursts of time. Nomad's goal is to do accurate resource accounting relative to what the hardware can actually provide.

You can always override the fingerprinted total compute value to a higher value if you prefer.
