### ISSUE TITLE
artifacts: does not automatically unpack .tar archives

### ISSUE THREAD

**Issue by stefreak** [hashicorp/nomad#2443]
### Nomad version
Nomad v0.5.4

### Operating system and Environment details
Ubuntu

### Issue
Does not unpack .tar, only zipped archives.

Expected behaviour: also unpack .tar archives

### Reproduction steps
```
      artifact {
        source      = "https://example.com/file.tar"
      }
```

**Comment by dadgar** [comment]
Hey can you file and cross link against https://github.com/hashicorp/go-getter

**Comment by stefreak** [comment]
go-getter issue: https://github.com/hashicorp/go-getter/issues/19

**Comment by ketzacoatl** [comment]
AFAICT, this is still an issue in that Nomad does not yet support unpacking `.tar` archives, and while https://github.com/hashicorp/go-getter/issues/19 is still open, it seems that `go-getter` _does_ now support `.tar` archives (see https://github.com/hashicorp/go-getter/blob/master/decompress_tar.go).

@dadgar, does nomad support decompressing `.tar` archives, or should this ticket be re-opened?

**Comment by tgross** [comment]
This was a very old bug that got re-opened, so I wanted to make sure it hadn't been opened accidentally. But I was able to confirm this is still broken! The specific behavior is with _uncompressed_ `.tar` archives and not with compressed `.tar.gz` archives, which is probably why no one has realized this was still a problem years later.

<details><summary>artifact to run</summary>

```sh
#!/usr/bin/env sh

while :
do
    echo "sleeping..."
    sleep 2
done
```

</details>

On our Vagrant development box, you can prep this artifact to be served as follows:

```sh
tar -cf sleeper.tar ./sleeper.sh
tar -czf sleeper.tar.gz ./sleeper.sh
sudo mkdir -p /srv/artifacts
sudo mv sleeper.tar* /srv/artifacts
```

Run the artifact server:

<details><summary>jobspec for an artifact server</summary>

```hcl
job "artifacts" {
  datacenters = ["dc1"]
  type        = "system"

  group "artifacts" {

    network {
      mode = "bridge"
      port "www" {
        static = 15101
        to     = 8000
      }
    }

    task "httpd" {

      driver = "docker"

      config {
        image   = "busybox:1"
        command = "httpd"
        args = [
          "-v", "-f",
          "-p", "8000",
          "-u", "www-data:www-data",
          "-h", "/srv",
          "-r", "artfiacts",
          "-c", "/local/httpd.conf",
        ]

        mount {
          type     = "bind"
          target   = "/srv"
          source   = "/srv/artifacts"
          readonly = true
        }

        ports = ["www"]
      }

      template {
        # HTTP Basic Auth username: "artifacts", password: "supersecret"
        data = <<EOT
/:artifacts:$1$iSV64UXs$IWot5UKWBzka6VskUSFWm0
EOT

        destination = "local/httpd.conf"
      }

      resources {
        cpu    = 128
        memory = 128
      }

    }
  }
}
```

</details>

And then try to run the following job:

<details><summary>jobspec that uses this artifact</summary>

```hcl
locals {
  auth_header = base64encode("artifacts:supersecret")
}

job "example" {
  datacenters = ["dc1"]

  group "sleeper" {

    task "sleeper" {

      artifact {
        source      = "http://localhost:15101/sleeper.tar"

        # but .tar.gz works:
        # source      = "http://localhost:15101/sleeper.tar.gz"

        headers {
          Authorization = "Basic ${local.auth_header}"
        }
      }

      driver = "exec"
      config {
        command = "/local/sleeper.sh"
      }

    }
  }
}
```

</details>

If the `.tar` file is used, it'll be dropped as-is into `/local` and fail. Whereas if the `tar.gz` file is used, it'll be decompressed and unpacked so that the task can use it.

**Comment by ketzacoatl** [comment]
Yay! Thank you!
