### ISSUE TITLE
ipc_mode = "host" doesn't work in the exec task driver

### ISSUE THREAD

**Issue by kpweiler** [hashicorp/nomad#24439]
### Nomad version
1.8.4

### Operating system and Environment details
Ubuntu 24.04.1

### Issue
When I set `ipc_mode = "host"`, I don't observe that I have access to the `/dev/shm` on the host sytem.

### Reproduction steps
1. Create a test file in `/dev/shm` on a client system
2. Run the following job spec (task spec only shown) on that client system
```
    task "shm-list" {
      driver = "exec"
      config {
        ipc_mode = "host"
        command = "ls"
        args    = ["-l", "/dev/shm/"]
      }
    }
```
3. Note that the test file doesn't show up in the logs

#### Expected Result
I expect to have access to `/dev/shm` on the system.

#### Actual Result
I do not have access to `/dev/shm` on the system

It's worth noting that this will work with the docker task driver.

**Comment by tgross** [comment]
Hi @kpweiler! I wasn't able to reproduce this behavior.

<details><summary>jobspec</summary>

```hcl
job "example" {

  group "web" {

    task "httpd" {

      driver = "exec"

      user = "ubuntu"

      config {
        command  = "busybox"
        args     = ["httpd", "-vv", "-f", "-p", "8001", "-h", "/local"]
        ipc_mode = "host"
        pid_mode = "host"
      }

    }
  }
}
```

You'll see why I set `pid_mode = host` below, but that's just for demonstration.

</details>

```sh
$ nomad alloc exec 
$ ls -lah /dev/shm
total 0
drwxrwxrwt 2 root root  40 Nov 12 08:56 .
drwxr-xr-x 5 root root 340 Nov 12 08:56 ..
```

Just to quickly verify that the IPC namespace was working as I'd expect, I also fired up a netcat process on the host so that I could verify that IPC can cross over to it (ex. via posix signals).

```sh
$ ps -ef | grep nc
...
ubuntu      2748    2611  0 08:59 ?        00:00:00 nc -lvp 9999

$ kill 2748
```

Back on the host:

```sh
$ nc -lvp 9999
Listening on 0.0.0.0 9999
Terminated
```

So I suspect the issue here isn't IPC namespacing but the filesystem the task driver is setting up for you. Do you see anything of note in the logs for either the client or the executor? Are you running Nomad as root?

**Comment by tgross** [comment]
Glad to hear you've got it worked out!
