### ISSUE TITLE
[question] How does the Client-side GC work?

### ISSUE THREAD

**Issue by oribaldi** [hashicorp/nomad#2448]
Can you please explain how the GC works?, specially the allocations cleanup. 

In the docs I haven't found anything, except the HTTP API call (https://www.nomadproject.io/docs/http/system.html). Which I have found that it doesn't work in every case. For instance, if an allocation never enters the "running" state and the job gets stopped (or the job is in the "dead" state), the corresponding allocation directory is never removed. Is this the expected behavior?

Other questions I have:
- Does the Client-side GC runs automatically in a period of time or do we have to run it through the HTTP API call?
- How long does it take to remove the jobs/allocs/evals? By doing some tests I found that it takes around 4 hours. Is this correct?
- What can we do with those allocations that never get GC?

I would really appreciate if you can explain this in the docs.

### Nomad version
Nomad v0.5.4

### Operating system and Environment details
Ubuntu 14.04

**Comment by dadgar** [comment]
Hey @oribaldi,

That is not expected behavior. We just released 0.5.5 which fixes a case in which stopped batch jobs were not being garbage collected. Are the jobs you talking about batch? If so can you try 0.5.5 and report back?

For your other questions:
1/2) There are two GC systems in Nomad. The servers run a GC that removes dead jobs/evals/allocations every five minutes and it cleans up objects that can be GC'd and are older than 4 hours.

The client also runs a GC loop that ensures that the node doesn't run out of disk space/inodes as well. Both of these have endpoints to manually trigger the GCs but you do not need to as they happen automatically!
3) Unfortunately if there is a bug in the GC logic, they will remain until we get a new version of Nomad out that fixes the GC code and then it will be GC'd.

**Comment by dvusboy** [comment]
@dadgar So for "garbage" left behind by previous versions of Nomad, would they be GC'd by 0.5.5?

**Comment by dadgar** [comment]
@dvusboy Hopefully! If not please report an issue!

**Comment by oribaldi** [comment]
Hi @dadgar,

Thanks for your prompt response and the explanation about GC. 

Yes, the jobs I mentioned are batch jobs. I will try 0.5.5 this week and let you know if it works as expected.

**Comment by dadgar** [comment]
@oribaldi Sweet! I am going to close this issue and if 0.5.5 doesn't solve the issue lets reopen with the server logs from the GC and dump the allocation details of what couldn't be collected!
