### ISSUE TITLE
nomad job change with tags orphans services

### ISSUE THREAD

**Issue by holtwilkins** [hashicorp/nomad#2458]
Probably related to https://github.com/hashicorp/nomad/issues/2150.

### Nomad version
0.5.5

### Issue
`nomad run` on a job that's already running but with different tags, creates orphaned services in consul.  Doing this usually creates your new service(s), but all the tags of the most recent invocation along with all the previous invocations are concatenated together.  Also, all the previous instances of the service are still listed, though with the `service` being down and the `Serf Health Status` up.

### Reproduction steps
Deploy a job with a tag, wait for it to be running and registered successfully with consul.  Add a new tag or alter an existing one in the job file and issue a `nomad run` on the altered job file _without_ running a `nomad stop` in between.

**Comment by schmichael** [comment]
I couldn't reproduce this with a trivial setup (consul & nomad dev agents + example file). See what I did here: https://gist.github.com/schmichael/d36dbbdfecf0df33f977c6aef1e02f07

I fixed a bug in this path before though, so I can believe there might be more bugs.

In fact all of the consul service advertisement code is getting rewritten in this branch and should be landing :soon: https://github.com/hashicorp/nomad/tree/f-consul-refactor

Please feel free to reopen with more details, but even if we find a bug it probably will just be replaced by that branch instead of fixed directly.
