### ISSUE TITLE
Nomad 1.8.4 `failed to exec into task: No path to region`

### ISSUE THREAD

**Issue by mcphailtom** [hashicorp/nomad#24609]
### Nomad version
Nomad v1.8.4
BuildDate 2024-09-17T20:18:34Z
Revision 22ab32e6cff66cf52f5e3f115b93de776bc09583

### Operating system and Environment details

Linux 20.04.1-Ubuntu

### Issue

As part of regular releases we are upgrading our shipped versions of Nomad. In our latest release candidates we have attempted a two step move from 1.15.17 -> 1.7.7 -> 1.8.4.

During testing we have performed this upgrade on a sample set of clusters and in all cases the upgrade is completely successfully. We have also attempted the 1.5.17 -> 1.8.4 upgrade without issue. Jobs are running as expected.

Several tests in our test suite use the `nomad alloc exec` command for test execution and we are seeing intermittent failures of the tests with the error message: `failed to exec into task: No path to region`

After some initial investigation it appears the command fails on all nodes of the cluster except the node where the allocation is actually running.

This behaviors is not consistent with previous versions of nomad.

### Reproduction steps

Using a sample job:

```
admin@app1:~$ nomad job status mysql
ID            = mysql
Name          = mysql
Submit Date   = 2024-12-05T01:13:35Z
Type          = system
Priority      = 50
Datacenters   = primary
Namespace     = default
Node Pool     = default
Status        = running
Periodic      = false
Parameterized = false

Summary
Task Group  Queued  Starting  Running  Failed  Complete  Lost  Unknown
mysql       0       0         3        0       0         0     0

Allocations
ID        Node ID   Task Group  Version  Desired  Status   Created    Modified
37e41f01  520855e6  mysql       0        run      running  10h7m ago  10h7m ago
69195c2c  8c55b7e6  mysql       0        run      running  10h7m ago  23m38s ago
8cf697a1  9da121d6  mysql       0        run      running  10h7m ago  10h7m ago
admin@app1:~$ nomad node status
ID        Node Pool  DC       Name   Class   Drain  Eligibility  Status
8c55b7e6  default    primary  data1  <none>  false  eligible     ready
0abc5c85  default    primary  app1   <none>  false  eligible     ready
520855e6  default    primary  data2  <none>  false  eligible     ready
9da121d6  default    primary  data3  <none>  false  eligible     ready
8f82e4c6  default    primary  app2   <none>  false  eligible     ready
admin@app1:~$
```

Running an `alloc exec` on the `app1` node where no allocation is running produces the following result:

```
admin@app1:~$ nomad alloc exec -job mysql /bin/bash
failed to exec into task: No path to region
admin@app1:~$
```

Running it again on the data3 node where an allocation is running will function as expected:

```
admin@data3:~$ nomad alloc exec -job mysql /bin/bash
root@data3:/#
```

Running from another node with an explicit `-region` set to the default region functions as expected.

```
admin@app1:~$ nomad alloc exec -region primary -job mysql /bin/bash
root@data3:/#
```

#### Expected Result

The command should exec on any node/agent in the cluster in the default region (since agents default to the region they are connected to in the case of no flag)

#### Actual Result

An error is produced unless running on the node on which the allocation exists.

**Comment by mcphailtom** [comment]
cc @half-ogre

**Comment by tgross** [comment]
Hi @mcphailtom! The error you're seeing (`ErrNoRegionPath`) comes from only a few places in the code. Each Nomad client agent is connected to exactly one Nomad server at a time (rotating between servers as needed to rebalance and handle failures). When you call `nomad alloc exec`, the HTTP API call gets transformed into a RPC call. The RPC call is forward from that agent to the server the agent is connected to. That server forwards the RPC to the leader (if it's not the leader). The leader looks up which server the destination allocation is on, and forwards the RPC to that server. And finally, the RPC is forwarded from that node to the client where the allocation is running. This is why you can make a request to any node anywhere and it makes its way to the correct place.

The `ErrNoRegionPath` error appears in only 3 places: 
* [`rpc.go#L702`](https://github.com/hashicorp/nomad/blob/v1.9.3/nomad/rpc.go#L702)
* [`rpc.go#L730`](https://github.com/hashicorp/nomad/blob/v1.9.3/nomad/rpc.go#L730)
* [`client_rpc.go#L170`](https://github.com/hashicorp/nomad/blob/v1.9.3/nomad/client_rpc.go#L170)

In all 3 locations, we're looking up a server from the list of Raft peers. 

That you're getting an error here suggests that there's a problem in your cluster topology. One or more servers are not showing up in the list of Raft peers. I suspect you've either got a split brain in the cluster during your upgrade or you've got one peer that's not joining (maybe it's got a configuration or networking issue).

To help diagnose:
* The error should be showing up in the logs of the host that's hitting it. Is that error happening on a client or a server?
* Use `nomad server members` to verify the health of servers.
* The [Autopilot Read Health API](https://developer.hashicorp.com/nomad/api-docs/operator/autopilot#read-health) will tell you which servers the cluster thinks it knows about.
* The [Read Raft Configuration API](https://developer.hashicorp.com/nomad/api-docs/operator/raft#read-raft-configuration) should match that.
* The [List Members API](https://developer.hashicorp.com/nomad/api-docs/agent#list-members) will give you the list of servers in the gossip pool (this is a lot of the same information in `nomad server members` but more detail).

**Comment by tgross** [comment]
I suspect https://github.com/hashicorp/nomad/issues/24635 is related and I have a reproduction for that and a culprit commit. Working on figuring out the underlying problem now.

**Comment by tgross** [comment]
Fix up here for review: https://github.com/hashicorp/nomad/pull/24644

**Comment by SteveCulver** [comment]
> We were planning on releasing yesterday but were delayed because of GitHub / release infrastructure issues. Should land today if there are no other snafus.
> 
> Just in general, we try to release a patch version monthly. There's a public announcements-only mailing list https://groups.google.com/g/nomad-tool, the `nomad-release` tag on Discuss here https://discuss.hashicorp.com/tags/c/nomad/28/nomad-release, and the RSS (well, Atom) feed for the GitHub releases here: https://github.com/hashicorp/nomad/releases.atom

Thanks @tgross! 

As @mcphailtom mentioned in the original description, our team found this issue while attempting to upgrade from our current version (1.5.17) to 1.8.4 (directly, and also with a jump to 1.7 in the middle).

I noticed that this issue was fixed in [1.9.4](https://github.com/hashicorp/nomad/releases/tag/v1.9.4) and [1.8.8 Enterprise](https://github.com/hashicorp/nomad/releases/tag/ent-changelog-1.8.8) but the older community versions still in SLA haven't had any updates for a while.

A few questions:
1) From what I gathered from the links above and a [forum post](https://discuss.hashicorp.com/t/release-information-on-1-6-and-1-7-community-versions-of-nomad/68970), there seems to have been a change with community edition support in the last year - e.g. went from [support period and EOL policy](https://support.hashicorp.com/hc/en-us/articles/360021185113-Support-Period-and-End-of-Life-EOL-Policy), which indicated support for up to two releases, to [long term support](https://www.hashicorp.com/long-term-support), which indicates community edition users need to upgrade to the most current release to get bug fixes and patches. Is that right? Do you happen to have any more info on that? 
2) (Assuming the above is correct) The community fix for this issue is in 1.9.4 and our current cluster is on 1.5.14, so to upgrade our cluster to pick up these changes within the 2 minor version rule, we'd need to update to at least 1.7.2, and then again to 1.9.4. However, from looking at the code changes (please correct me if I'm wrong), the code that was removed as part of #24644 to fix this issue was added in 1.7.0 with #16872 - and since there are no 1.7 community patches with the fix, the first upgrade to 1.7.x would cause this very issue (and prevent us from verifying before upgrading again to 1.9.4). Is that right? Do you have any guidance on how to proceed?

Thank you!

**Comment by tgross** [comment]
Hi @SteveCulver! Unfortunately as of the LTS releases, the EOL policy changed and we're no longer backporting any fixes for Community Editions except for the most current version. So there's not going to be a CE version with the fix you need. The LTS policy puts CE users on a fairly rapid major version upgrade treadmill.  I definitely realize the bind this puts you in (and this kind of thing was debated at length internally, tbh).

It's actually somewhat worse than you may think (sorry!). Jumping from 1.5.14 to 1.9.x will potentially cause a workload outage. Because as of 1.9.0, clients older than 1.6.0 will fail heartbeats (ref [1.9 release notes](https://developer.hashicorp.com/nomad/docs/release-notes/nomad/v1_9_x#what-s-removed)). And 1.10 LTS will be released in only a few months, at which point you'll have breaking changes around Vault/Consul to potentially worry about (ref [upcoming in 1.10](https://developer.hashicorp.com/nomad/docs/release-notes/nomad/upcoming#nomad-1-10-0-lts)), which you can only prepare for in >1.7.x.

You've got a few options here:
* I'd strongly consider grabbing the [v1.7.7](https://github.com/hashicorp/nomad/tree/v1.7.7) tree and manually backporting the patch from https://github.com/hashicorp/nomad/pull/24644. That way you can do the upgrade to 1.7.x, validate it, and then upgrade to 1.9.x.
* You could do the same for 1.9.x but instead of backporting that patch, backport a revert of https://github.com/hashicorp/nomad/pull/23838, which might allow you to skip directly to 1.9.x. (I would recommend then upgrading to an official release immediately afterwards.)
* Depending on what kind of workloads you're running and your infrastructure setup, migrating all the workloads on client upgrade may be something you do anyways (for example, our HCP folks use "immutable" client hosts so they do a rolling replacement of the VMs). In which case, going from 1.5.15 directly to 1.9.x without any patches may not be too bad for you. You'll want to take a look through the [CHANGELOG](https://github.com/hashicorp/nomad/blob/main/CHANGELOG.md) file for anything marked "breaking" to see if it impacts you, as well as the [CHANGELOG-unsupported](https://github.com/hashicorp/nomad/blob/main/CHANGELOG-unsupported.md) for those changes in the 1.6.x release.

For any option you choose, I'd strongly encourage you to test it in a pre-production environment before putting production at risk.

**Comment by SteveCulver** [comment]
> Hi [@SteveCulver](https://github.com/SteveCulver)! Unfortunately as of the LTS releases, the EOL policy changed and we're no longer backporting any fixes for Community Editions except for the most current version. So there's not going to be a CE version with the fix you need. The LTS policy puts CE users on a fairly rapid major version upgrade treadmill. I definitely realize the bind this puts you in (and this kind of thing was debated at length internally, tbh).
> 
> It's actually somewhat worse than you may think (sorry!). Jumping from 1.5.14 to 1.9.x will potentially cause a workload outage. Because as of 1.9.0, clients older than 1.6.0 will fail heartbeats (ref [1.9 release notes](https://developer.hashicorp.com/nomad/docs/release-notes/nomad/v1_9_x#what-s-removed)). And 1.10 LTS will be released in only a few months, at which point you'll have breaking changes around Vault/Consul to potentially worry about (ref [upcoming in 1.10](https://developer.hashicorp.com/nomad/docs/release-notes/nomad/upcoming#nomad-1-10-0-lts)), which you can only prepare for in >1.7.x.
> 
> You've got a few options here:
> 
> * I'd strongly consider grabbing the [v1.7.7](https://github.com/hashicorp/nomad/tree/v1.7.7) tree and manually backporting the patch from [Allocation API: fix "no path to region" errors for non-global regions #24644](https://github.com/hashicorp/nomad/pull/24644). That way you can do the upgrade to 1.7.x, validate it, and then upgrade to 1.9.x.
> * You could do the same for 1.9.x but instead of backporting that patch, backport a revert of [auth: enforce use of node secret and remove legacy auth #23838](https://github.com/hashicorp/nomad/pull/23838), which might allow you to skip directly to 1.9.x. (I would recommend then upgrading to an official release immediately afterwards.)
> * Depending on what kind of workloads you're running and your infrastructure setup, migrating all the workloads on client upgrade may be something you do anyways (for example, our HCP folks use "immutable" client hosts so they do a rolling replacement of the VMs). In which case, going from 1.5.15 directly to 1.9.x without any patches may not be too bad for you. You'll want to take a look through the [CHANGELOG](https://github.com/hashicorp/nomad/blob/main/CHANGELOG.md) file for anything marked "breaking" to see if it impacts you, as well as the [CHANGELOG-unsupported](https://github.com/hashicorp/nomad/blob/main/CHANGELOG-unsupported.md) for those changes in the 1.6.x release.
> 
> For any option you choose, I'd strongly encourage you to test it in a pre-production environment before putting production at risk.

@tgross Thank you so much for the really thorough and thoughtful response 🙇
