### ISSUE TITLE
[exec driver] nomad fs exposes all files within allocation

### ISSUE THREAD

**Issue by ashald** [hashicorp/nomad#2476]
### Nomad version
`0.5.4`

### Operating system and Environment details
`Centos 7`

### Issue
In order to use Nomad with `exec` driver we have to run it as `root`. Nomad creates allocation directory by linking dirs and files from host operating system into the chrooted environment. When exploring the filesystem with `fs` (cli or HTTP api), we can see contents of all files regardless of their access mode.

Expected behavior: Nomad assumes `user` specified in task description when file is requested so that files that are unavailable for user that is used for task cannot be exposed.

**Comment by henrikjohansen** [comment]
@tgross I am not sure that people grasp the severity of this issue ? Essentially I can read **any** file inside the chroot **regardless** of what user I am running under? The `exec` driver defaults to `nobody` yet I can read `/etc/shadow` inside the chroot? :thinking: 

### OS Info
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
```

```
$ uname -a
Linux prappnmd101v 5.15.0-86-generic #96-Ubuntu SMP Wed Sep 20 08:23:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```


### Nomad version
Nomad v1.6.2+ent
BuildDate 2023-09-13T17:11:57Z
Revision a93af012175baf56ed529b9f97e24afbf3415738

### Job File
```
job "example" {

  group "example" {

    task "test" {
      driver = "exec"
      user   = "nobody"

      config {
        command = "/bin/sleep"
        args    = ["1800"]
      }
     
      resources {
        cpu    = 500
        memory = 256
      }
    }
  }
}

```

### Nomad alloc exec commands
```
$ nomad alloc exec 571dd21e whoami                                           
nobody                                                                                             
``` 

```
$ nomad alloc exec 571dd21e id
uid=65534(nobody) gid=65534(nogroup) groups=65534(nogroup)  
```                                                                                      

```
$ nomad alloc exec 571dd21e ls -alh /etc/shadow       
-rw-r----- 4 root shadow 1.4K Oct 24 15:25 /etc/shadow  
```

```
$ nomad alloc exec 571dd21e cat /etc/shadow
...
daemon:*:19579:0:99999:7:::
bin:*:19579:0:99999:7:::
sys:*:19579:0:99999:7:::
sync:*:19579:0:99999:7:::
games:*:19579:0:99999:7:::
man:*:19579:0:99999:7:::
lp:*:19579:0:99999:7:::
mail:*:19579:0:99999:7:::
news:*:19579:0:99999:7:::
uucp:*:19579:0:99999:7:::
...
```

**Comment by linuxmail** [comment]
hi,

I saw this issue also now .. with Nomad 1.5.8 what is .. **WTF** ... can I avoid it? is it related to allow docker volumes ?

**Comment by henrikjohansen** [comment]
@linuxmail This has nothing to do with docker volumes - you might be able to avoid this by customizing the chroot environment (although it seems to be a configuration nightmare) or simply disable the **exec** driver .

I can't find a disclaimer about this behavior anywhere in the documentation ... perhaps @mikenomitch can elaborate if this has been looked at by the Nomad team and what the status of this issue is?

**Comment by tgross** [comment]
Sorry to have left this open for so long, but this is working as intended. I think perhaps confusing is that there's a difference between what the _task_ can see and _you, a human user_, can see. The [List Files](https://developer.hashicorp.com/nomad/api-docs/client#list-files), [Read Files](https://developer.hashicorp.com/nomad/api-docs/client#read-file), etc. APIs allow access to everything in the allocation working directory by design, gated by the `read:alloc-fs` ACL. 

That's not the same as what the processes in the workload can access with their own user! You could have multiple processes running in a task, each with their own user and their own filesystem access rules. 

Closing this as working as intended, and again apologies for not wrapping this up sooner.
