### ISSUE TITLE
configure size of secrets directory

### ISSUE THREAD

**Issue by ashald** [hashicorp/nomad#2481]
### Nomad version
`0.5.4`

### Operating system and Environment details
`CentOS 7`

### Issue
When isolated exec driver is used, size of the `secrets` dir is limited to 1 mb. It'd be nice if it was configurable at least on the level of the agent configuration. In our case all secret data do not fit into 1 mb (we'd need about 50 mb) so sensitive data are lying on plain fs and are available via fs cli or http api.

**Comment by dadgar** [comment]
@Ashald You realize that data is being stored in memory? Is all 50 MBs actually sensitive?

**Comment by Ashald** [comment]
Yeah, that's the case. Actually, our biggest issue is files with sensitive content exposed via FS api/cli. And `secrets` sounds like easiest way to handle that.

**Comment by dadgar** [comment]
@Ashald Okay. Reasonable request but unfortunately not super trivial to do correctly so hang tight on this one! Got to plumb through memory accounting so that server's don't over allocate.

**Comment by Ashald** [comment]
Ok, I'll be patiently waiting. :)

**Comment by josegonzalez** [comment]
Hi ya'll! This is something we'd love to also have in Nomad. Our use case is storing ssl certificates securely for a service mesh implementation. With potentially hundreds of slightly differing certificates, its basically impossible to store these in 1mb of disk.

Being able to configure this would be ideal.

**Comment by UUIDNIE** [comment]
It would be great if this was configurable!  There are use cases that require more than 1MB of /secrets space.

**Comment by tgross** [comment]
I'm picking this issue up next. Note this won't be exclusive to the `exec` driver, as the same code is used everywhere to size the tmpfs. This is where the 1MiB limit is hard-coded: [`fs_linux.go#L19`](https://github.com/hashicorp/nomad/blob/v1.8.2/client/allocdir/fs_linux.go#L19)  (on Linux; macOS and Windows don’t use a tmpfs so this issue is irrelevant for those platforms).

Pros and cons of setting it at the agent config level:
* Easy to implement!
* Keeps control in the cluster admin's hands
* Allows workloads to land on different agents with different sizes where they won't have enough space, unless it's also fingerprinted so that job authors can use it as a constraint. Which then runs into a long-running pain point that our constraints don't work well for numeric values.
* Cluster admins need to reserve an extra amount per client equal to the size * expected number of allocs per node, which is a capacity planning pain.
* Reduces the amount of memory available even when tasks don't need it, which hurts density.

Pros and cons of setting it at the jobspec level:
* Allows each job to use the amount of temp space it really needs
* The tmpfs space is not controlled by the task driver, so we can't blindly add it to the `resource` block without doubling the extra resources needed
* So we'll need to add it as a scheduling consideration? Maybe just add it to the allocation resources without adding it to the individual task resource blocks that control what's happening in the task driver?
* Space will need to be accounted for in quotas as well.

**Comment by UUIDNIE** [comment]
I'm excited to see some movement on this! 

Tmpfs memory is allocated as needed by default.  This might already be known, but I wanted to make sure since it might impact risk tolerance somewhat.  

Container example:

`
docker run -it --name tmpfs-test --tmpfs /mnt:rw,size=50m ubuntu

<inside container with a tmpfs mount>
df -h | grep "/mnt$"
tmpfs                                         50M     0   50M   0% /mnt

<docker stats from container host>
CONTAINER ID   NAME         CPU %     MEM USAGE / LIMIT   MEM %     NET I/O       BLOCK I/O   PIDS
a8d60a020ee0   tmpfs-test   0.00%     600KiB / 7.638GiB   0.01%     2.49kB / 0B   0B / 0B     1

cd /mnt/
dd if=/dev/urandom of=rand-bytes.img bs=1M count=40

CONTAINER ID   NAME         CPU %     MEM USAGE / LIMIT     MEM %     NET I/O       BLOCK I/O   PIDS
a8d60a020ee0   tmpfs-test   0.00%     40.59MiB / 7.638GiB   0.52%     2.49kB / 0B   0B / 0B     1

`


Also, I like the idea of setting this at the jobspec level.   Probably makes the most sense in the long haul IMO!  Thank you!

**Comment by tgross** [comment]
> Tmpfs memory is allocated as needed by default. This might already be known, but I wanted to make sure since it might impact risk tolerance somewhat.

That's a good point, but there's a catch... :grinning: Templates and artifacts.

Your example looks right on it's face. It isn't quite how Nomad does it, because we have to support multiple task drivers. And that turns out to be subtly important here. What we're really doing is something more like this:

```sh
$ sudo mkdir -p /mnt/mytmpfs
$ sudo mount -t tmpfs -o size=500M tmpfs /mnt/mytmpfs

$ docker run -m 50m -it --rm -v /mnt/mytmpfs:/mnt busybox:1
# cd /mnt
# dd if=/dev/urandom of=rand-bytes.img bs=1M count=100
Killed
```

As long as the task driver has working resource isolation (all of them do but you could build a custom one that ignored `resource` blocks of course), the cgroup we create for `resource.memory` will control the amount you can write to. I've just verified that works as expected for `raw_exec` as well.

The scheduler can then be blissfully unaware of the size of the secrets directory, because it only needs to care about what the `resource` block says. That would simplify things a good bit. It also suggests we should validate on job submit that the secret dir size is no larger than `resource.memory` (or `resource.max_memory`), as you can't usefully use a larger tmpfs allocation so that's a user error.

But! Templates and artifacts get written by the Nomad agent, which isn't in the same cgroup as the workload. (That templates and artifacts don't themselves run inside the task is a long-standing topic of internal debate... I'd love to see it changed but it would be a huge breaking change.)

For example, I built a version of Nomad that sets the size of the tmpfs to 200MB. Then I run the following jobspec:

<details><summary>example jobspec</summary>

```hcl
job "example" {

  group "group" {

    task "task" {

      artifact {
        # a 26M file served from a local server
        source = "http://192.168.1.117/tinycore.qcow2"
        destination = "secrets"
      }

      driver = "docker"

      config {
        image   = "busybox:1"
        command = "httpd"
        args    = ["-vv", "-f", "-p", "8001", "-h", "/local"]
      }

      resources {
        cpu    = 50
        memory = 20
      }

    }
  }
}
```

</details>

We end up with more data in the tmpfs than allowed by the task's resource constraint, which is different behavior than if the task itself were trying to write into the secrets dir.

```sh
$ nomad alloc exec e970f49c ls -lah /secrets
total 26M
drwxrwxrwx    2 nobody   nobody       100 Jul 25 19:39 .
drwxr-xr-x    1 root     root        4.0K Jul 25 19:39 ..
-rw-r--r--    1 root     root           0 Jul 25 19:39 .nomad-mount
srw-rw-rw-    1 root     root           0 Jul 25 19:39 api.sock
-rw-r--r--    1 root     root       25.6M Jul 25 19:39 tinycore.qcow2
```

Any data written by an artifact or template block won't be written from the task's cgroup and so that memory gets taken from the host.

So we need to account for that somehow so that a task can't "attack" the memory usage of the host via this tmpfs through abusing artifacts and templates. But given this should be the same hunk of memory "inside" and "outside" the container, I'd hope the OS memory accounting has something sensible for us to look at. I'm going to need to do a little more experimentation and kernel docs reading to make sure there's a way to do this safely.

**Comment by tgross** [comment]
I've opened a draft PR here: https://github.com/hashicorp/nomad/pull/23696 to discuss some of the internals of this design with the team
