### ISSUE TITLE
raw_exec driver not initializing correctly upon reboot

### ISSUE THREAD

**Issue by lolovarga** [hashicorp/nomad#2557]
### Nomad version
Nomad v0.5.5

### Operating system and Environment details
Windows Server 2012 running on Azure
Nomad is configured to use the raw_exec driver

### Issue
Sometimes after the server restarts, the raw exec driver is not getting initialized properly. The node does show as ready and the server tries to allocate jobs to it, but they always fail. In the agent logs we can see: "error connecting to plugin: error creating rpc client for executor plugin: OpenProcess: The parameter is incorrect." whenever a job attempts to start here.
The node never recovers by itself. In order to get it back, I drained the node and then restarted the agent service.
Since only restarting the agent service was sufficient for it to start up properly, I wonder if there is any startup dependency for the nomad service.
### Reproduction steps
The issue does not occur at every restart, but it does happen fairly often. In order to reproduce, have a windows 2012 server with nomad agent configured as a service and having the raw_exec plugin configured. Periodical reboots of the server will probably soon take the node in that state.
### Nomad Client logs (if appropriate)
```    Loaded configuration from C:\nomad\client.conf
==> Starting Nomad agent...
==> Nomad agent configuration:

                 Atlas: <disabled>
                Client: true
             Log Level: INFO
                Region: eastus2 (DC: qa)
                Server: false
               Version: 0.5.5

==> Nomad agent started! Log data will stream in below:

    2017/04/12 12:31:02.807096 [INFO] client: using state directory D:\nomad\client
    2017/04/12 12:31:02.833097 [INFO] client: using alloc directory D:\nomad\alloc
    2017/04/12 12:31:09.745579 [INFO] fingerprint.consul: consul agent is available
    2017/04/12 12:31:14.672947 [INFO] fingerprint.vault: Vault is available
    2017/04/12 12:31:14.677946 [WARN] driver.raw_exec: raw exec is enabled. Only enable if needed
    2017/04/12 12:31:14.685946 [INFO] client.consul: discovered following Servers: 1.1.1.1:4647,1.1.1.2:4647,1.1.1.3:4647
    2017/04/12 12:31:14.692948 [ERR] driver.raw_exec: error connecting to plugin so destroying plugin pid and user pid
    2017/04/12 12:31:14.692948 [ERR] driver.raw_exec: error destroying plugin and userpid: 2 error(s) occurred:

* OpenProcess: The parameter is incorrect.
* OpenProcess: The parameter is incorrect.```

**Comment by dadgar** [comment]
Hey that log line is not surprising. The client tries to connect to process it was running when it comes back up but since you restart the client all the process are gone.

As to the client not being able to recover itself can you file another issue with more information as to why it can't recover. Thanks.

**Comment by lolovarga** [comment]
Hi @dadgar ,

what kind of detailed information do you need? Also, why do you need another issue opened? 

Thanks

**Comment by dadgar** [comment]
Hey @lolovarga,

We can re-use the issue if you'd like when you post more information. It may just be easier with a new issue since the original report doesn't include much that would help debug.

What would be ideal is the clients logs from when it was working through the restart that causes it to not "recover". Then a zip of the `data_dir` would be nice ( this contains the clients knowledge of each allocation it is running)
