### ISSUE TITLE
Nomad Client crashes on startup failing to restore allocations with empty state files

### ISSUE THREAD

**Issue by ashald** [hashicorp/nomad#2560]
### Nomad version
`0.5.6`

### Operating system and Environment details
`Centos 7`

### Issue
Nomad agent crashes on startup after the reboot say it cannot restore some allocations.

### Nomad Client logs (if appropriate)
```
Apr 13 11:27:01 nomad-agent-02 nomad[1657]: client: failed to restore state for alloc 48a4b655-d25c-21e5-4dce-a2f03d610a43: failed to decode state: unexpected end of JSON input
Apr 13 11:27:01 nomad-agent-02 nomad[1657]: client: failed to restore state for alloc 6a25c5d7-d4a7-3ef3-df2a-1ca60eeab51d: failed to decode state: unexpected end of JSON input
Apr 13 11:27:01 nomad-agent-02 nomad[1657]: client: failed to restore state for alloc a95c1022-9a70-62a4-b440-76ea711d86ab: failed to decode state: unexpected end of JSON input
Apr 13 11:27:01 nomad-agent-02 nomad[1657]: client: failed to restore state for alloc c6785f33-9f18-095b-3682-6962c2b1157d: failed to decode state: unexpected end of JSON input
Apr 13 11:27:01 nomad-agent-02 nomad: ==> Error starting agent: client setup failed: failed to restore state: 4 error(s) occurred:
Apr 13 11:27:01 nomad-agent-02 nomad: * failed to decode state: unexpected end of JSON input
Apr 13 11:27:01 nomad-agent-02 nomad: * failed to decode state: unexpected end of JSON input
Apr 13 11:27:01 nomad-agent-02 nomad: * failed to decode state: unexpected end of JSON input
Apr 13 11:27:01 nomad-agent-02 nomad: * failed to decode state: unexpected end of JSON input
```

**Comment by dvusboy** [comment]
This has happened to me numerous time with earlier versions, such as 0.4.1. The way I work around that is to nuke everything under `/var/lib/nomad/client/alloc/`. After that, the nomad client starts fine. I've notice 0.5.6 improved GC a lot. By chance, could this be during an upgrade cycle of Nomad? Did you do a node-drain prior to reboot?

**Comment by dadgar** [comment]
@Ashald Can you tar up and share the data directory?

**Comment by Ashald** [comment]
Unfortunately we cleaned it up to bring revive the agent. but if something like that will happen again I'll share it with you.

**Comment by dadgar** [comment]
@Ashald Okay lets re-open this with more detail. Unfortunately there isn't too much that is actionable without more data 👍

**Comment by Ashald** [comment]
@dadgar it just happened again after host was rebooted. :(

```
Apr 20 14:43:58 nomad-agent01 nomad: Loaded configuration from /etc/nomad/config.hcl
Apr 20 14:43:58 nomad-agent01 nomad: ==> Starting Nomad agent...
Apr 20 14:44:01 nomad-agent01 nomad: ==> Error starting agent: client setup failed: failed to restore state: 2 error(s) occurred:
Apr 20 14:44:01 nomad-agent01 nomad: * failed to decode state: unexpected end of JSON input
Apr 20 14:44:01 nomad-agent01 nomad: * failed to decode state: unexpected end of JSON input
Apr 20 14:44:01 nomad-agent01 nomad: 2017/04/20 14:43:58.739422 [INFO] client: using state directory /var/lib/nomad/client
Apr 20 14:44:01 nomad-agent01 nomad: 2017/04/20 14:43:58.739673 [INFO] client: using alloc directory /srv
Apr 20 14:44:01 nomad-agent01 nomad: 2017/04/20 14:43:58.755586 [INFO] fingerprint.cgroups: cgroups are available
Apr 20 14:44:01 nomad-agent01 nomad: 2017/04/20 14:43:58.760798 [INFO] fingerprint.consul: consul agent is available
Apr 20 14:44:01 nomad-agent01 nomad: 2017/04/20 14:43:58.776327 [WARN] fingerprint.network: Unable to parse Speed in output of '/usr/sbin/ethtool eth0'
Apr 20 14:44:01 nomad-agent01 nomad: 2017/04/20 14:44:01.887324 [ERR] client: failed to restore state for alloc 21522dd5-b002-0f35-9a4b-f498454fbc3e: failed to decode state: unexpected end of JSON input
Apr 20 14:44:01 nomad-agent01 nomad: 2017/04/20 14:44:01.887421 [ERR] client: failed to restore state for alloc 379ebc00-1c12-fed3-3239-3c23b3b8e95b: failed to decode state: unexpected end of JSON input
Apr 20 14:44:01 nomad-agent01 systemd: nomad.service: main process exited, code=exited, status=1/FAILURE
Apr 20 14:44:01 nomad-agent01 systemd: Unit nomad.service entered failed state.
Apr 20 14:44:01 nomad-agent01 systemd: nomad.service failed.
```

Data directory:
```
/var/lib/nomad $ tree
.
└── client
    ├── alloc
    │   ├── 21522dd5-b002-0f35-9a4b-f498454fbc3e
    │   │   ├── state.json
    │   │   └── task-484cbd7aea50a707eca9796a0b7e34f8
    │   │       └── state.json
    │   └── 379ebc00-1c12-fed3-3239-3c23b3b8e95b
    │       ├── state.json
    │       └── task-aa3a0177193f5479812eadbbb3e6c303
    │           └── state.json
    ├── client-id
    └── secret-id
```

All `.json` files are empty, `client-id` and `secret-id` contain UUIDs.

**Comment by dadgar** [comment]
@Ashald Do you have logs before the node restarted?

**Comment by Ashald** [comment]
Looking for them this very moment... Is there is something I should look for or just any logs?

**Comment by Ashald** [comment]
Hm.... Interesting, the only thing that I found in logs is:
```
Apr  4 15:38:24.839 nomad-agent01 nomad: client: marking allocation 379ebc00-1c12-fed3-3239-3c23b3b8e95b for GC
Apr  4 15:38:24.839 nomad-agent01 nomad: client: marking allocation 379ebc00-1c12-fed3-3239-3c23b3b8e95b for GC
Apr  4 15:38:24.835 nomad-agent01 nomad: client: marking allocation 21522dd5-b002-0f35-9a4b-f498454fbc3e for GC
Apr  4 15:38:24.834 nomad-agent01 nomad: client: marking allocation 21522dd5-b002-0f35-9a4b-f498454fbc3e for GC
```

But that happened several week before the reboot. And now nomad tries to restore allocations that were supposed to be cleaned up?..

**Comment by Ashald** [comment]
BTW, those allocation directories are there in place on the disk and are not cleaned.

**Comment by dadgar** [comment]
@Ashald Yeah we are planning on improving the error handling during restores to not bail the whole client and to delete corrupt state.

**Comment by Ashald** [comment]
Is it something that will be part of `0.6`? Can we please re-open the issue?
At this point, considering that we ran into the issue couple of times by now, it's pretty critical for us as we are not sure we can rely on Nomad at this time unless we fix the issue... Unless we run only stateless applications and wipe out both data and allocation dirs before Nomad start...

**Comment by dadgar** [comment]
Sure. Will update this issue when the work is complete and we can post a test binary that you can play with.

Also why are you restarting the host machine so much?

**Comment by Ashald** [comment]
Hosts are restarted every now and then when we apply security patches and so on. But since we're not 100% sure what causes the issue my assumption is that the issue might manifest during the regular service restart as well.

**Comment by dadgar** [comment]
@Ashald Steady state client behavior is pretty solid. The recovery code is quite complex and I believe that is where this bug is cropping up.

**Comment by Ashald** [comment]
Yeah, but as far as I understand, recovery mode is triggered during Nomad startup and therefore will be activated after each Nomad process restart (that might happen more often if you need to adjust config)

**Comment by Ashald** [comment]
I will try to ensure that node drained each time Nomad is shut-down - maybe it will help to avoid the issue for now.

**Comment by dvusboy** [comment]
@Ashald I'm just curious, but do you do a `nomad drain-node` before restart?

**Comment by Ashald** [comment]
@dvusboy that's what I want to do

**Comment by andrewduch** [comment]
Just wanted to add that we saw a similar issue on a Windows client (running 0.5.6) today. After a restart of the system (without draining), nomad client can't start up with below error message. 

Ideal option would be that if state is corrupted it gets wiped out as assumption is scheduler would have already scheduled these jobs on another node. I can provide state directory as well if that is helpful.

```
> ==> Error starting agent: client setup failed: failed to restore state: 48 error(s) occurred:
> 
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> * failed to decode state: invalid character '\x00' looking for beginning of value
> 
```

**Comment by sirkjohannsen** [comment]
same happens still with nomad 0.6.0-dev

**Comment by opaugam-unity** [comment]
It does happen for us on 0.6.0: gracefully shutting down the agent leads to a 80+ % probability the next time the agent starts we hit somehing like "* failed to read allocation state: failed to read alloc runner alloc state: no data at key alloc".

Cleaning up the mounts + state db is ok-ay but any left-over running container will not be handled upon restart and lead to error if ever you use static ports.

**Comment by else** [comment]
I also get this on v0.7.1.

**Comment by volodymyr-f** [comment]
Got the same on Nomad v0.8.0

**Comment by momania** [comment]
I'm getting this too on v0.8.4
Allocation ids that it tries to recover don't match with the ids found in `/var/lib/nomad/alloc`

**Comment by shantanugadgil** [comment]
I too face this issue often, if I abruptly reboot my client nodes.
I have updated my scripts to stop the docker daemon altogether (my use case is dockers), stop Consul and Nomad, sync a few times (for good luck), and then reboot.

Since this modification, I haven't hit the issue.

**Comment by qkate** [comment]
Thanks all for the reports!  We're in the middle of some refactoring work right now that we are hoping will resolve this (and other!) issues.

**Comment by capone212** [comment]
Same problem, waiting for the solution/

**Comment by onlyjob** [comment]
I get this very often on v0.8.4 after restarting _nomad_ after full drain: daemon just fails to start (after clean shutdown) with the following error:

~~~~
[ERR] client: failed to restore state: 1 error occurred:
* failed to read allocation state: failed to read alloc runner alloc state: no data at 
key alloc
~~~~

Removing `/var/lib/nomad/client/state.db` helps but should not be necessary...

**Comment by kcwong-verseon** [comment]
Just to echo @onlyjob and #4748, the corrupt state is different from before where clearing the `alloc` directory resolve the issue. The new behavior with 0.8.x is the state DB is corrupted and either removing it or `cat /dev/null >/var/lib/nomad/client/state.db` is needed, clearing `alloc` does not address the state.

**Comment by jozef-slezak** [comment]
I am facing the similar problem. I have a fix: https://github.com/hashicorp/nomad/pull/4739
@qkate the fix is being implemented against (I hope so)

@dadgar I would suggest handling missing key like this:
1. like this https://github.com/hashicorp/nomad/pull/4739/commits/ffdbbcebad83788b5203d186ce611650ac1dc137
2. It might be better if GetTaskRunnerState(), GetAllAllocations() would not return error if a key (local_state, task_state etc.) is missing (the key might not have been written)

@dadgar what about having 0.8.7 (it would help for our deployment) with the fix ported to master branch (boltdb, no error if key is missing, cherrypick ffdbbcebad83788b5203d186ce611650ac1dc137)


I was able to reproduce the problem in:

Nomad version
0.8.6

Operating system and Environment details
Centos 7

Issue
Nomad agent crashes on startup after the reboot say it cannot restore some allocations.

Nomad Client logs (if appropriate)
no data at key local_state

**Comment by jozef-slezak** [comment]
This problem is still reproducible even today (with the latest commit) on 0.9.0-dev just by restarting the cluster. Please see my fix #4807.

Nomad version
0.9.0-dev

Operating system and Environment details
Centos 7

Issue
Nomad agent crashes on startup after the reboot say it cannot restore some allocations.
failed to read local task runner state: no data at key local_state"
bucket: Task bucket doesnt exists

Nomad Client logs (if appropriate)
 ==> Starting Nomad agent...
2018/10/19 16:29:08 [INFO] agent: Deregistered service "_nomad-task-inhseqgfpo432j5iihs2d7lwcpve7gpb"
==> Error starting agent: client setup failed: failed to restore state
2018-10-19T16:29:08.636+0200 [INFO ] agent: detected plugin: name=raw_exec type=driver plugin_version=0.1
2018-10-19T16:29:08.636+0200 [INFO ] agent: detected plugin: name=mock_driver type=driver plugin_version=
2018-10-19T16:29:08.636+0200 [INFO ] client: using state directory: state_dir=/var/lib/innovatrics/nomad/
2018-10-19T16:29:08.636+0200 [INFO ] client: using alloc directory: alloc_dir=/var/lib/innovatrics/nomad/
2018-10-19T16:29:08.638+0200 [INFO ] client.fingerprint_mgr.cgroup: cgroups are available
2018-10-19T16:29:08.641+0200 [INFO ] client.fingerprint_mgr.consul: consul agent is available
2018-10-19T16:29:08.642+0200 [WARN ] client.fingerprint_mgr.network: unable to parse speed: path=/usr/sbi
2018-10-19T16:29:08.652+0200 [ERROR] client: error restoring alloc: error="failed to read local task runn
2018-10-19T16:29:08.652+0200 [ERROR] client: failed to restore state: error="1 error(s) occurred:
* failed to read local task runner state: no data at key local_state"
2018-10-19T16:29:08.652+0200 [ERROR] client: Nomad is unable to start due to corrupt state. The safest wa
2018-10-19T16:29:08.652+0200 [ERROR] client: Corrupt state is often caused by a bug. Please report as muc

2018-10-19T16:43:44.230+0200 [ERROR] client: error restoring alloc: error="failed to get task "IDispatcher" bucket: Task bucket doesn
2018-10-19T16:43:44.230+0200 [ERROR] client: error restoring alloc: error="failed to get task "IDispatcher" bucket: Task bucket doesn
2018-10-19T16:43:44.232+0200 [ERROR] client: error restoring alloc: error="failed to get task "activemq515" bucket: Task bucket doesn
2018-10-19T16:43:44.233+0200 [ERROR] client: error restoring alloc: error="failed to get task "activemq515" bucket: Task bucket doesn
2018-10-19T16:43:44.233+0200 [ERROR] client: failed to restore state: error="4 error(s) occurred:
 * failed to get task "IDispatcher" bucket: Task bucket doesn't exist and transaction is not writable
 * failed to get task "IDispatcher" bucket: Task bucket doesn't exist and transaction is not writable
 * failed to get task "activemq515" bucket: Task bucket doesn't exist and transaction is not writable
 * failed to get task "activemq515" bucket: Task bucket doesn't exist and transaction is not writable"
2018-10-19T16:43:44.233+0200 [ERROR] client: Nomad is unable to start due to corrupt state. The safest way to proceed is to manually
2018-10-19T16:43:44.233+0200 [ERROR] client: Corrupt state is often caused by a bug. Please report as much information as possible to

**Comment by robloxrob** [comment]
I ran into this issue on nodes where my disk ended up filling up.

Nomad version
0.8.6

Operating system and Environment details
Ubuntu 16.04

**Comment by shantanugadgil** [comment]
@robloxrob 
I use CentOS7 (systemd)
I run a cron job which checks the status of the service named "Nomad" to see if it is unhealthy/dead
If it is dead, I proceed to stop Nomad, Consul, Docker daemons, wipe out the "datadir" and reboot the machine.

This is a workaround, but keeps machine chugging along rather than having to debug this issue :)

HTH,
Shantanu

P.S.
I haven't implemented it yet, but I have an idea to parse the output of the command "systemctl status nomad" for specific error strings rather than the return value of systemctl.

**Comment by schmichael** [comment]
[Nomad 0.9.0-rc1](https://releases.hashicorp.com/nomad/0.9.0-rc1/) was recently released which should address state corruption issues. Please open a new issue if you run into problems and thanks for your patience! I know this took a while to get fixed.

**Comment by vkiranananda** [comment]
Hello!
I have same problem. Nomad v0.9.0. Run docker service (memcached) and restart linux server. 
logs:
Apr 13 16:01:17 beta-docker nomad[8199]: ==> Loaded configuration from /etc/nomad.d/server.hcl
Apr 13 16:01:17 beta-docker nomad[8199]: ==> Starting Nomad agent...
This is client...
ps uax |grep noma
root      8199  0.2  0.3 1933276 38040 ?       Ssl  16:01   0:01 /usr/local/bin/nomad agent -config /etc/nomad.d
root      8246  0.0  0.3 1416256 31988 ?       Sl   16:01   0:00 /usr/local/bin/nomad docker_logger

port 4646 don't opened. ss -lntp|grep nom
service nomad stop
ps uax |grep noma
root      8246  0.0  0.3 1416256 31924 ?       Sl   16:01   0:00 /usr/local/bin/nomad docker_logger

If I delete dir "/var/lib/nomad/client/", then nomad starting is normal .

This is real problem for me :(

**Comment by vkiranananda** [comment]
I deleted files  *.fifo in /var/lib/nomad/alloc/45be141a-b9ff-0312-0e64-866852ceae31/alloc/logs and nomad started  well

**Comment by vkiranananda** [comment]
Bug fix :)

```
echo "[Unit]
Description=Nomad fix start
Before="nomad.service"

[Service]
ExecStart=/usr/bin/find /var/lib/nomad/alloc/ -type p -delete

[Install]
WantedBy=multi-user.target" > /etc/systemd/system/nomad-fix.service

systemctl daemon-reload
systemctl enable nomad-fix
```
