### ISSUE TITLE
ability to use native consul-template rendering with alternate delimiter

### ISSUE THREAD

**Issue by avinson** [hashicorp/nomad#2565]
consul-template has a lot of functionality that would be useful to render nomad job spec files. an alternate delimiter is necessary to avoid collisions with inline nomad task templates for vault secrets. using an alternate delimiter like `{{{{` and `}}}}` would allow to pre-render configurations like these without having to render secrets to local storage:
```
job "myapp"
  task "myapp" {
    driver = "docker"
    config {
      image = "myapp:{{{{ env "GIT_COMMIT" }}}}"
     }
   }
}
```
or
```
job "myapp"
  task "myapp" {
    driver = "docker"
    config {
      image = "myapp:{{{{ key "service/myapp/git_commit" }}}}"
     }
   }
}
```

**Comment by dadgar** [comment]
@avinson Hey,

Consul-template has this: https://github.com/hashicorp/consul-template#configuration-file-format (search left_delimiter)

And so does Nomad: https://www.nomadproject.io/docs/job-specification/template.html#left_delimiter

You can run consul-template to generate your Nomad files if you like. If this issue is getting at broader interpolation in the job file, there are a number of open issues tracking that and the approach we plan on tacking is embedding HIL similar to terraform.

**Comment by avinson** [comment]
@dadgar thanks for your response.. i ended up doing exactly as you suggested which is to use consul-template to generate the nomad file with an alternate delimiter
