### ISSUE TITLE
Upgrading clusters using blue/green style of underlying clients.

### ISSUE THREAD

**Issue by dadgar** [hashicorp/nomad#2584]
Upgrading a cluster can be challenging because when a node is drained, all allocations are immediately stopped and attempted to migrate. The below is just thinking but I believe it could greatly mitigate the challenge.

1) Add ability to disable nodes from accepting new placements. To start upgrade mark all existing nodes with this.
2) Bring up new set of nodes.
3) Mark all original nodes for drain. However make drain only stop the allocations if a new placement is possible. This avoid service outages.
4) Introduce a force to node-drain to force stopping of allocations even if replacement isn't possible. 

Below is the initial discussion:

> Thinking through this a little more "Bring up a new set of hosts and drain the old set and then shutdown the old set" seems like some of my problems are that I am trying to do this 1 server at a time. This means that it takes a very long time to do this transition.
> 
> We run lots of very tiny services, so there are multiple services running per machine. I use the "distinct_hosts" attribute to make sure that only 1 is running per machine.
> 
> To help both of us maybe it would be best to work through a small example.
> 
> If I have 3 services (lets call them A,B,C) running 2 instances each across 4 machines (lets call them 1,2,3,4) then a possible configuration could be.
> 
> 1:AB
> 2:BC
> 3:A
> 4:C
> 
> In this configuration if I spun up 2 new servers, 5 and 6 nothing would migrate to the new servers. If I shutdown servers 2,3 at the same time that would periodically take out service B. If I shutdown servers 1,3 that would take out A. It is non trivial to figure out which servers can be shutdown and continue to have full service. This means that I have to shut down 1 server at a time and wait for all of the health checks for every single service (because I don't know what was on that machine) to be healthy. This means I have to write a whole bunch of scripts to do this very carefully, and/or watch it very carefully during the process which could take a very long time with lots of machines (especially since currently there is about a 5% failure rate on docker which causes the task to die and requires operator intervention). Also health checks do not tell me if my desired number of instances are running, they just give me a yes/no things are healthy. I would have to reconcile how many are healthy verse the nomad configuration.
> 
> I think that my ideal would be some way to ensure that some minimum number of services was running before shutting it down during a drain? Or maybe some way to have more services instances running while attempting to drain? So in my example above if I started up server 5 and 6 then drained 1 and 2 B would not shutdown until 2 more were running on 5 and 6. This is probably a typical blue green but instead of deploying the service to the new machines as a new color, nomad is doing it? I have something like 300 services running, so am not really wanting to deploy all of them in order to update nomad if can be avoided.
> 
> Alex, does that provide some color as to what I am talking about?
>

**Comment by dvusboy** [comment]
I run Nomad on a bare-metal cluster. "Bring up new sets of nodes" is not really an option for me. So far, I've been doing in-place update by:

1. Drain the node
2. Upgrade OS + Nomad (I built Nomad RPM) on the clients
3. Reboot

And it's worked well most of the time. Every once in a while, the Nomad daemon doesn't stay up because of the the empty JSON problem (#2560); I just remove everything under `/var/lib/nomad/client/alloc/`. It has resolved the issue every time. After the clients, I upgrade the servers.

I understand the immense gravitational pull of the Cloud and microservices, but they are definitely not the only use cases for Nomad. Thank you for your great work! Your team has been fantastically responsive to the user community.

**Comment by a86c6f7964** [comment]
@dadgar I think that you mostly captured what I was saying, but I would propose one thing different. In step 3 if it is able to place the new allocation it may still cause a service outage if that allocation does not start up very quickly. Lets say it takes 30 seconds. Maybe in step 3 it could respect the `update` job stanza such as `max_parallel` and `stagger`. (which I am also hoping will include health checks https://github.com/hashicorp/nomad/issues/317 in the future)

@dvusboy while you would not benefit from the proposal above it would not harm you?

**Comment by dvusboy** [comment]
I sure hope not. As long as "new node" is not a requirement for upgrade, I'm copacetic. My usage has been primarily batch jobs. The drain and in-place upgrade introduces some flagging to the few services I have, mostly because they got reallocated to nodes that are later on my upgrade path. I'd actually like to see alternative allocation algorithm than binpacking and that may actually alleviate the issues on that drain + upgrade model.

**Comment by rickardrosen** [comment]
@dadgar This tangents to some extent what I'm proposing in the comments of #2736.

I'd really like to see a drain flag that simply excludes the node from accepting further allocations, letting it drain all by itself.
Would help with all kinds of maintenance of the agent nodes a great deal!

**Comment by a86c6f7964** [comment]
IMHO bullet 1 would require an API that can do that. It needs to be able to place the node into a state such that it cannot accept any new placements. Otherwise as you shutdown servers nomad could just place it on another soon to be shutdown server

**Comment by dadgar** [comment]
@rickardrosen Yeah bullet one would be what you are suggesting as well!

**Comment by jgadling** [comment]
This workflow isn't just for blue/green deployments of an entire fleet. It's also vital to being able to run production services on nomad when worker nodes are being autoscaled (a la ASG in AWS) or replaced in batches.  However, it's more complicated than the four bullet points above because old allocations should not be stopped until their replacements are healthy:

1. Mark N hosts as unavailable for new placements
2. Bring up new nodes (though this could also happen before 1)
3. Mark unavailable hosts for drain
    1. Any allocations that can't be placed shouldn't be stopped (is this seriously something that happens when draining nodes now?!)
    2. Any allocations that are successfully placed on other hosts shouldn't be stopped until their replacements are healthy
    3. Health and replacement status should be taken into account when shrinking taskgroups - unhealthy allocations should be stopped first, followed by allocations that are waiting for their replacements to start/go healthy, and then other allocations are fair game
4. There will need to be tools available to handle force-draining nodes when some of their allocations can't be placed, or replacement allocations don't go healthy

There are some edge cases to consider depending on the implementation of allocation replacement - replacement allocations can themselves be replaced (more node-drain commands are issued) or killed (taskgroup size shrinks, job deleted), these situations needs to be handled.

Closely related, and also useful: #3230

**Comment by BSick7** [comment]
@dadgar I love this.

I expect the `update` stanza to be followed during node drains.
Just as during a new job deployment, the allocation would be not be terminated from the draining node until a matching allocation became healthy using the `update` stanza attributes.

**Comment by BSick7** [comment]
@dadgar Are there intentions of solving this soon?

**Comment by dadgar** [comment]
This work is stated for 0.8

**Comment by a86c6f7964** [comment]
https://www.hashicorp.com/blog/advanced-node-draining-in-hashicorp-nomad I haven't tried it yet but reading through this blog post looks like nomad can handle the cases that were enumerated! Thanks @dadgar

**Comment by schmichael** [comment]
@a86c6f7964 Yup! Expect more improvements to these features in the future, but I'm going to close this old issue. We can incrementally open specific issues as they appear.
