### ISSUE TITLE
[question] Docker volumes on Windows

### ISSUE THREAD

**Issue by rogeralsing** [hashicorp/nomad#2627]
I'm evaluating Nomad as the scheduler for our new infrastructure.
We are currently on Windows.

If I start Nomad with `nomad agent -dev`
and then run `nomad run example.nomad` (after creating the example file that is)

The Nomad agent will complain about:
`driver.docker: Failed to create container: API error (500): {"message":"invalid bind mount spec \"/C/Users/rojo01/AppData/Local/Temp/NomadClient371282422/26798d9b-10b5-90a7-67fc-1a40b4094d1b/alloc:c:\\\\alloc\": invalid mode: \\alloc"}`

Am I doing something wrong or is there some broken compatibility with windows?

**Comment by schmichael** [comment]
Hi @rogeralsing!

First off I'm afraid there's an incompatibility with our Docker client library and Go 1.8 which we started using in the 0.5.5 release. This will cause random panics when pulling/removing images. This has been fixed and will be released in Nomad 0.6. See #2343 for details and feel free to test with the attached binary there: https://github.com/hashicorp/nomad/issues/2343#issuecomment-299069571

Now on to your current issue!

```
driver.docker: Failed to create container: API error (500): {"message":"invalid bind mount spec \"/C/Users/rojo01/AppData/Local/Temp/NomadClient371282422/26798d9b-10b5-90a7-67fc-1a40b4094d1b/alloc:c:\\\\alloc\": invalid mode: \\alloc"}
```

It appears we're building the target path for the shared `alloc` directory incorrectly. It's being set as `c:\\\\alloc\` but Docker is splitting on the `:` in `c:` and considering the `\\\\alloc\` the volume's _mode_. This is an invalid mode and that's the error you're getting.

The strange thing is this should be preventing Docker on Windows from working at all, but I and users aren't seeing this issue.

Mind sharing what version of Windows, Docker, and Nomad you're on?

**Comment by rogeralsing** [comment]
Sure thing:

### nomad version
```
Nomad v0.5.6
```

### docker version
```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 21:43:09 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 21:43:09 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

Windows:
```
Windows 10 Enterprise 
Version 1607
Build 14393
```

**Comment by schmichael** [comment]
I'm running Windows 10 Enterprise 15063.rs2_release.170317-1834 and installed Docker from the stable channel msi: Docker for Windows 17.03.1-ce-win10 (11972).

I was able to confirm the issue you're running into. It appears to be related to running Linux containers with Docker for Windows in Linux container mode. We create Windows-style paths for volume binds, but we should create Linux-style paths if Docker (and/or the container?) are in Linux mode. At this point I don't know if we're able to detect the proper path style to use or will have to make it user configurable.

If you don't need to run Linux containers on Windows please switch Docker to Windows Container mode (an option in the Docker systray applet) and change the `image` to `image=redis:nanoserver`.

I filed #2633 to add Linux container support for Docker on Windows, please follow that for updates.

I'm going to close this issue since the question is answered (sadly that we don't support Linux containers on Docker for Windows), but thank you for reporting! All of our existing Nomad+Docker on Windows users must be using Windows images!

**Comment by madmagi** [comment]
One problem with this approach is that it is not uncommon for Windows 10 Developers to be creating and working with Linux containers.

It would seem to me a config option for the agent to override the default windows only container support would be a good idea.

**Comment by schmichael** [comment]
@madmagi That's #2633
