### ISSUE TITLE
Support Linux images in Docker for Windows

### ISSUE THREAD

**Issue by schmichael** [hashicorp/nomad#2633]
Nomad only supports Docker for Windows 17.03.1 in Windows Container mode. Attempting to run Linux containers will fail because Nomad will create Windows-style volume bind paths instead of Linux-style.

We should: 

* [ ] Detect Docker for Windows mode in the fingerprinter
  * [x] Requires updating go-dockerclient to support the [undocumented `Isolation` key in the `/info` API](https://docs.docker.com/engine/api/v1.29/#operation/SystemInfo)  - fsouza/go-dockerclient#649
    * `Isolation: "hyperv"` means Windows mode
    * `Isolation: ""` means Linux mode
  * [x] Add new `attr.driver.docker.os_type` to expose Docker mode to constraints
* [x] Create volume paths based on the image's OS
  * [x] Requires updating go-dockerclient to support the [1.29 InspectImage API](https://docs.docker.com/engine/api/v1.29/#operation/ImageInspect) - fsouza/go-dockerclient#649
* [ ] Adjust signal handling to be based on the runtime os, rather than the nomad-client os.

Stretch goal:

* [ ] Vary the output of `nomad init` based on Docker for Windows mode (`redis:3.2` for Linux, `redis:nanoserver` for Windows)

**Comment by krjensen** [comment]
Any news on this one, we could really use this!

**Comment by schmichael** [comment]
@krjensen I'm afraid we haven't prioritized it on our roadmap yet since a Windows node running Docker in Linux mode doesn't offer any functionality not already provided by running Docker on a Linux node. We were curious if there were enough people running in homogenous Windows environments to make Linux mode on Windows compelling.

**Comment by krjensen** [comment]
I totally understand that. 

So why do I need this: 
We are a .net developer house and has just begun to look at .net core that will run on Linux. 

So every developer use windows 10 with docker, to build .net core applikations. We are amning to use nomad in produktion and there for the need to test it local, so a developer can write and test the .nodmad file. Many services will contain multiple containers, so they need to compose.  I would prefer the need for only a nomad definition, that works both local and in production and not a situation where I need both a docker compose and a nomad definition.

**Comment by frundh** [comment]
We are also a Windows-shop facing the same issue when it comes to local development and testing, so this feature would be a nice addition.

Since this is only required for local development, I have experimented with some alternative solutions/hacks that I can share if anybody is interested: 

**Docker Image**
https://github.com/frundh/nomad-mobyvm

**Nomad.exe**
https://github.com/frundh/nomad/releases/tag/v0.6.2.1-moby

**Comment by thasmo** [comment]
Would love to see this supported too, although I don't use it in a business-context.

**Comment by bartuer** [comment]
It will became pretty common to run Linux docker image on Windows,  we seldom run Windows image on Windows inside Microsoft.

**Comment by automaticgiant** [comment]
just for tracking @schmichael, https://github.com/fsouza/go-dockerclient/issues/649 is done so the only work is in-repo now, right?

**Comment by adamsmithkld** [comment]
This is even more important now that Docker for Windows supports side-by-side Linux and Windows containers (via the experimental feature). We are also a Windows development shop that builds Linux Docker containers. The only thing missing is Nomad support for Linux containers on Docker for Windows.

**Comment by RenEvo** [comment]
Is there any traction on this, currently even with drive sharing in windows, nomad is unable to allocate a job due to permission denied on mounting drives.

```
2018-08-08T21:12:09.945-0700 [DEBUG] plugin: plugin process exited: path=D:\tools\nomad.exe
    2018/08/08 21:12:09.945889 [WARN] client: failed to start task "redis" for alloc "6354d373-9fd5-c0f3-a96c-09bf0a737f6f": Failed to create container: API error (500): Mount denied:
The source path "D:/nomad.d/nomad/alloc/6354d373-9fd5-c0f3-a96c-09bf0a737f6f/alloc:c"
```

I am able to mount volumes when running containers natively with docker for windows (linux containers, non-experimental), but nomad isn't able to mount.

PS: I am running nomad on windows, instructing to use the pipefile.

```
data_dir = "d:\\nomad.d\\nomad"
datacenter = "dc1"

client {
    enabled = true
    network_interface = "Ethernet"

    options {
        "docker.endpoint" = "npipe:////./pipe/docker_engine"
    }
}

server {
    enabled = true

    bootstrap_expect = 1
    data_dir = "d:\\nomad.d\\nomad\\server"
}
```

**Comment by jzupka** [comment]
exactly same to me

**Comment by sujeetsm** [comment]
upvote this one .. windows now supports homogeneous support for linux/windows containers.

**Comment by gblok** [comment]
How to make work nomad with Linux images in Docker for Windows?
It is already possible?

**Comment by cgbaker** [comment]
We don't have any immediate plans to support this, but we are tracking it in our backlog.

**Comment by atrauzzi** [comment]
Chiming in to say that I've just encountered this issue.  A bit disappointed after reading the last comment.

Not being able to run linux containers via nomad on Windows completely blocks what I'm currently working on.  Worse still is that the first container I tried to run doesn't even have bind mounts configured!

Microsoft and Docker have been putting a lot of work into ensuring that Docker Desktop gets as much out of the way as possible.  Even so far as allowing Windows and linux containers to run at the same time.
It doesn't feel like too much to suggest that nomad add support for this scenario.  Even if only to remain consistent with the direction of the ecosystem.

**Comment by schmichael** [comment]
> Even so far as allowing Windows and linux containers to run at the same time.

That's fantastic and was not the case when this ticket was originally written! Originally Docker on Windows was modal and only supported one image type at a time. That may nullify the `Add new attr.driver.docker.container_mode to expose Docker mode to constraints` checkbox above and make implementation even easier.

**Comment by nbpalomino** [comment]
I'm also waiting for implementing this feature... currently trying to use Nomad with Docker for Windows on my Windows 10 box...

**Comment by ilyaiqoqo** [comment]
I'm also waiting I am waiting for this feature. we are running batch jobs that should be agnostic to where they run

**Comment by amfern** [comment]
I am able to run Linux container when the daemon is in windows containers mode, by enabling experimental features in docker edge.

I think nomad should also support this and not set the driver to an unhealthy state

**Comment by ilyaiqoqo** [comment]
fixes invalid network mode when running linux container on windows https://github.com/hashicorp/nomad/pull/5999

**Comment by karlem** [comment]
Is there any update on this issue please?

We're planning to use Nomad for very interesting use case but support of Linux containers on Windows is must.

Thanks

**Comment by tgross** [comment]
Hi @karlem! The patches we received from @ilyaiqoqo should be enough to allow support, but I admit it's not an area we have well-tested yet. I recently added Windows 2016 (Datacenter) to our end-to-end test suite, but that supports only Windows containers on Windows. We've got upcoming work planned to add Windows 2019 targets to e2e testing that will make sure we've got well-tested support there as well.

(I have some open issues tracking that work on a private GitHub board that I'll move over into this repo shortly so that you can keep an eye on them.)

**Comment by karlem** [comment]
Hi @tgross!
Thank you very much for your response. That sounds pretty good. I will keep an eye on the issues.

Have a good day!

**Comment by atrauzzi** [comment]
@tgross - Is that using Docker for Windows (the desktop app)?

**Comment by tgross** [comment]
No, it's the engine for the server. My understanding is that the underlying virtualization problems to solve are the same so support for Windows 2019 production environments should solve for those desktop use cases as well. But the desktop app isn't likely to be something we'll fully support with testing from a practical standpoint.

**Comment by atrauzzi** [comment]
Hmm. I had been originally hoping this would be supported on desktop for local development.

**Comment by karlem** [comment]
Yeah I didn't manage to run Linux container on Windows 10 with Hyper-V at all.

Just got error message: `Docker is configured with Linux containers; only Windows containers are supported`

@tgross is there potentially a way we could contribute to make it happen??? Since my company is planning to use Nomad as a base for grid compute solution we would need to support Windows 10 as well.

Thanks

**Comment by tgross** [comment]
Looks like that error message is bubbling up from [fingerprint.go#L168-L178](https://github.com/hashicorp/nomad/blob/8b6a8c02ccebd5d269fee5eacd54413ffcc10aa9/drivers/docker/fingerprint.go#L168-L178) which was added in https://github.com/hashicorp/nomad/pull/5356 -- before the patches we merged from @ilyaiqoqo. 

We'll need to remove that check (at the very least), before Linux containers on Windows can be supported. It looks like we'll still need to have some fix for signal handling as well. I've moved this issue into a better spot in internal tracking to make sure we put some eyes on this.

**Comment by karlem** [comment]
Ok perfect.. I have spoken to team members and we're more than happy to help. We will have a look at it probably tomorrow. We will try to remove the fingerprint, schedule some Linux containers and see what happens.

Thanks @tgross for being responsive! Have a good day

**Comment by Ankurkh1** [comment]
Any update on this please. Because of this issue we are considering moving to docker swarm. I just love the Hashicorp stack. Badly want to stay with it.

**Comment by jlarriba** [comment]
I was digging into source code to see if I could help with this issue, and I have seen that there is already an experimental implementation of LCOW support:

```
func InitLCOW(experimental bool) {
	if experimental && osversion.Build() >= osversion.RS5 {
		lcowSupported = true
	}
}
```

But I do not manage to see how can I pass the experimental flag to Nomad. How is this functionality enabled?

**Comment by jlarriba** [comment]
I have been working on this issue a little bit and I managed to get Nomad to run a linux container in Windows Server 2019 correctly, in a very embrionary state. It does not accept extra volumes, I only solved the first step of the alloc, local and secrets mandatory volumes. But with my changes, the Windows containers stop working.

However, there is a bigger issue. In current Windows Server 2019, Docker runs Linux images and Windows images on a totally transparent way to fsouza/go-dockerclient. Currently, in the fingerprint, there is this check:

```
if runtime.GOOS == "windows" && dockerInfo.OSType == "linux"
```

which always fails in Windows Server 2019, as Docker for Windows reports OSType as "windows" even when running linux images. This means that the `Docker is configured with Linux containers; only Windows containers are supported` message is never shown on Server 2019 and we go directly to the volume mount errors.

I have reviewed back and forth the identification capabilities of fsouza/go-dockerclient, but I have not been able to discover a way to identify when a Windows server is running a Linux image, all the parameters are identical than the ones shown when running a Windows image. 

Any ideas?

**Comment by jlarriba** [comment]
OK, I found it. Inspecting a container gives us the "Platform" parameter, which is "linux" or "windows", depending on the type of image we are using.

**Comment by arieradle** [comment]
> OK, I found it. Inspecting a container gives us the "Platform" parameter, which is "linux" or "windows", depending on the type of image we are using.

Does this mean that there will be some basic solution for Linux containers on windows soon?
I think if you can roll out a very basic solution, even as beta, this would be a major step forward for Nomad.

**Comment by tgross** [comment]
@arieradle #7850 was just merged to master, so that'll go out in the next patch release 0.11.2 (I can't give you an exact date on that other than "soon"). I'd like to add some end-to-end testing of that patch in our nightly build as well.

**Comment by arieradle** [comment]
![tenor](https://user-images.githubusercontent.com/16779750/81011497-c4530080-8e60-11ea-8078-876cdaae1877.gif)

**Comment by jlarriba** [comment]
> Will this fix work on Win 10 (Hyper-V isolation)? If so, beginning at which release? 1703/1803/1903/1909.

Win10 was never a target of this feature, as the main way to run Linux containers is via the Hyper-V Linux VM ("Switch to Linux Containers"). However, motivated by the curiosity, I tried to schedule Linux containers in Windows 10 using Nomad and they ran flawlessly.

My Win10 version:
```
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      18363  0
```

**Comment by BasixKOR** [comment]
I think this is pretty crucial for developers using Windows to actually try Nomad. I'm currently launching client agent on WSL 2 as a workaround, and it is really a hassle to set up all of this.

**Comment by ansario** [comment]
@jlarriba how did you accomplish that?

**Comment by jlarriba** [comment]
@BasixKOR @ansario sorry, but I do not understand what you want.

A PR that fixes this issue was merged to master on May 4th: [Run Linux Images (LCOW) and Windows Containers side by side](https://github.com/hashicorp/nomad/pull/7850) and it was included from Nomad version 0.12 onwards. So any current version should be able to run both Linux Containers and Windows Containers side-by-side.

**Comment by ansario** [comment]
@jlarriba is it unsupported on Windows 10?

**Comment by jlarriba** [comment]
@ansario I am not the one who says what it is officially supported or not on Nomad, as I am not a Hashicorp employee. According to my tests (see [my previous comment on the subject](https://github.com/hashicorp/nomad/issues/2633#issuecomment-623973167)), the changes I implemented allows Nomad to schedule Windows Containers on Windows 10.

However, I still do not know what your intention is and what exactly do you expect from Nomad in Windows 10, so it is complicated to provide more help.

**Comment by tgross** [comment]
Officially we want to support Windows 2019; my understanding is that it should work but we haven't invested time into making certain of that. That's actually something I'm going to be working on over this week and next. Windows 10 isn't a production environment, so if we can get to a point where we're sure of Windows 2019 LCOW, we're likely to say "yes this should work on Windows 10 but it's considered a development environment," similar to our macOS support.

**Comment by jlarriba** [comment]
@tgross if you think I can help, please feel free to ping me.

**Comment by ansario** [comment]
Perfect, thanks for the response @tgross and @jlarriba, let me know if I can help with testing.

**Comment by avishnyakov** [comment]
This ticket summarises why I now have dual boot with Ubuntu on my Windows 10 laptop. At the end, it was worth it, less challenges with docker and other utilities is always good.

**Comment by BogusDude99** [comment]
Can we please have an update for this issue?

**Comment by tgross** [comment]
Hi @BogusDude99. Generally speaking if we have an update on the status of an issue, you'll see it in the issue. The work I referred to in https://github.com/hashicorp/nomad/issues/2633#issuecomment-717900145 got done but it's still not fully-tested E2E.

**Comment by lutetium174** [comment]
Hey @tgross 

Is there a preview version that we can test and provide feedback on in the meantime?

**Comment by tgross** [comment]
@lutetium174 the work described there was for testing, as the primary issue at this point is whether we're certain that LCOW is supported (mostly because testing LCOW means spinning up bare metal machines with Windows, which isn't part of our usual testing environment). You can already give Nomad 1.0.4 a spin today and see if LCOW is working for your environment.

**Comment by lutetium174** [comment]
@tgross Thanks for the suggestion but it seems, at least for Windows 10 using Linux containers WSL2, unfortunately not.

I'll continue to monitor this thread and issue.

**Comment by jlarriba** [comment]
@lutetium174 The feature target was not WSL2, but LCOW, a very promising feature included in Windows Server 2019 that allowed to run Windows Containers natively along with Linux Containers via the Hyper-V Containers feature. The API of LCOW is very similar to the one used by Docker in Windows, so supporting it took very little effort. Even if it was not the target, I checked (manually, this was never officialy tested as @tgross said) that it also made Nomad work with the Linux Containers feature provided by the Docker Desktop Windows 10 application.

Even if last year LCOW looked like a promising technology and the "way-to-go" for Docker on Windows support, it never left experimental phase, and it seems to look more and more abandoned. Since then, the Docker team focused their efforts for Linux Containers on WSL2. See this [issue](https://github.com/docker/for-win/issues/6470).

WSL2 however, is a completely different technology that has nothing to do with LCOW, so it would require additional effort to add support to that in Nomad.

**Comment by tomqwpl** [comment]
I'm also very interested in this functionality. I'm sure my set up is common, Windows 10 running Docker Desktop in WLS2 mode. I've used docker on Windows for some time and have never, ever run a Windows docker image, I've always run docker in Linux mode, scheduling linux containers. For me it's kind of surprising that nomad doesn't just support this, naively I assumed nomad just talked to the local docker daemon to schedule containers.

**Comment by tgross** [comment]
>  For me it's kind of surprising that nomad doesn't just support this, naively I assumed nomad just talked to the local docker daemon to schedule containers.

As mentioned several times in this issue, Nomad is shouldn't _need_ any particular support for launching Linux containers on Docker on Windows. It just hasn't been verified. There are lots of weird quirks to the WSL2 environment (ex. a monolithic kernel without modules we were at one point using to detect networking isolation support because that's how virtually every other Linux distro builds their kernel out). So we do want to make sure we have verifiable support for Windows Server 2019 environments. Windows 10 desktops, however, are not a production environment so it's just not likely to ever be a test target for us.

**Comment by tomqwpl** [comment]
@tgross  So if I ignore the warning and try to schedule a linux container anyway, it should work? I've read through the issue but been confused by the status of this.

**Comment by lutetium174** [comment]
@tomqwpl Not in my experience. The problem I've found is that the docker driver is marked `unhealthy` and any attempted use of the driver in my jobs fails. You would need to switch to Windows containers.

**Comment by tomqwpl** [comment]
@lutetium174 Right, that was mind of my impression too. I think hence my confusion here. There seemed to be talk earlier of it just working at some point, but it certainly doesn't appear to now for that reason.

**Comment by Brouilles** [comment]
I'm also very interested.

**Comment by dg-eparizzi** [comment]
We have a solution that's a mix of dockerized services (Linux) and some native .NET framework apps. I was under the impression that Nomad would be able to orchestrate both types of jobs without issue but I'm seeing Linux containers are not supported on Windows hosts? Linux containers have been supported in Docker for Windows for a while now so I don't understand why is this an issue for Nomad.

Can someone clarify whether this is a potential approach? We're using Windows 10 Enterprise 2019 LTSC, so we're not even running Docker using WSL2, but Hyper-V instead...

**Comment by gthieleb** [comment]
I want to showcase to windows guys how easy it is to get started with nomad together with docker to run some linux container workload on a windows box.

Installation of consul / nomad is very easy in windows and in this showcase I'd like to have both of them running in dev mode:

```
nomad agent -dev
consul agent -dev
```

Furthermore I'd like to use docker desktop (wsl2 engine) and run nomad/consul in dev mode. But this apparently fails due to this error message:
![image](https://user-images.githubusercontent.com/21332468/127301890-f2b0e0c0-aece-40fe-9ef5-c77606fd8e0f.png)

Can you shed some light on why this should not be supported/not work? With WSL2 I don't have any chance to either start docker natively or register another nomad client in consul.

**Comment by das974** [comment]
I has a similar need for showcasing Windows with the WSL 2 Docker backend.  I worked around this by running the server in WSL2 and a client on the Windows host.  This allows me to run .Net apps on the windows host and Linux Docker containers in the WSL backend.

You basically end up with 2 nodes with the same name.
![image](https://user-images.githubusercontent.com/7102917/129491720-a6ece2d3-2680-42c8-a21f-7d9b4d274ce6.png)

## Linux Nomad Server  
![image](https://user-images.githubusercontent.com/7102917/129490917-91d1ba38-82c3-4554-8330-e78b2103a092.png)
 
## Windows Nomad Client  
Enabled only raw_exec for Windows
![image](https://user-images.githubusercontent.com/7102917/129490934-c2a81f13-68bd-4453-b574-608a01e6888d.png)

## VSCode Tasks For Reference
This assumes you have downloaded nomad and is in the path (I use a separate task for this)
```
{
    "label": "Nomad WSL2",
    "type": "shell",
    "command": "bash",
    "args": [
        "-c",
        "sudo nomad agent -config=./nomad/linux/config -bind 0.0.0.0"
    ]
},
{
    "label": "Nomad Windows Client",
    "type": "shell",
    "command": "nomad",
    "args": [
        "agent",
        "-config=${workspaceFolder}\\nomad\\windows\\config"
    ]
}
```

**Comment by qagwaai** [comment]
any updates on this?

**Comment by FibreFoX** [comment]
I find it a bit frustrating, getting excited from the first blog-articles and tutorials about Nomad, which itself proclaimes to provide an easy developer experience, just to find out that this experience is "just" for Linux-based and MacOS(X) developer systems. Myself I am mostly using Windows as my daily driver, and having a mixed type of systems among our developers, I would like to have a shared configuration in our projects.

As "Docker-for-Windows" itself is provided in multiple ways (via HyperV or WSL) there probably is "just" a complexity-issue of the driver. I am confused why this is still an active issue at least for HyperV based Linux-containers.

Is there any plan to provide a workaround to this? Like "just" connecting to a docker-socket or remote-port?

I will look forward to use Nomad (mostly because I dislike the whole Kubernetes ecosystem due to its complexity and giant fragmenting YAML files), but will have to create separate VM for it. Or is there a "simple solution" via Vagrant? (I mean, its a HashiCorp-product, maybe the chances are good, hehe)

**Comment by Seikilos** [comment]
I also was happy to test drive it, only to find out, that docker on windows with linux containers does not work.
Since I am building linux docker images and use them, the vagrant option is not really a good one because I have to switch hyper visor modes and reboot the machine every time to either use vagrant with virtual box or be able to use docker.

**Comment by Seikilos** [comment]
A little update after toying around with nomad and only be using raw_exec. I would prefer nomad over k8s but regarding linux containers on a windows machine I will probably stick to Rancher Desktop, which brings a working k3s out of the box and Rancher Dashboard comes along to provide a nice web ui.

If I recall correctly, Armon Dadgar CTO of Hashicorp said, he regards nomad as a competitor to k8s.
I do not know, how big the "windows developer for linux containers" segment is (I would think it is largely growing since windows streamlines developing C#, etc. for linux containers), but as of now, I am one and nomad is unfortunately of no use for me. 😥

**Comment by gthieleb** [comment]
@Seikilos did you tested the solution of @das974 with using a seperate docker installation in WSL2 for the Linux Workload? . There is also the option to use podman [1] (or podman desktop) within WSL2 which also offers you running container workload with a (similar command line like docker) in Linux. For nomad a podman plugin exists [2].

[1] https://podman.io/docs/installation
[2] https://github.com/hashicorp/nomad-driver-podman

**Comment by Seikilos** [comment]
> @Seikilos did you tested the solution of @das974 with using a seperate docker installation in WSL2 for the Linux Workload? . There is also the option to use podman [1] (or podman desktop) within WSL2 which also offers you running container workload with a (similar command line like docker) in Linux. For nomad a podman plugin exists [2].
> 
> [1] https://podman.io/docs/installation [2] https://github.com/hashicorp/nomad-driver-podman

Hi, @gthieleb
thanks for replying. I did and it did not work, but it was user error. Now the workaround of nomad being an agent in wsl seems to work. I explain what I did wrong to help others:

When I tried this, I had *no* docker driver in my WSL2 linux. But the issue was: The docker enabled WSL Linux is an ubuntu 20.04. I later installed a WSL2 Ubuntu 22.04 via app store for other things.
The default setup was
* Ubuntu 20.04 with docker support
* Ubuntu 22.04 vanilla, no docker

So actually starting nomad client on 20.04 seems to work for now.

Another issue, we windows users are very likely to hit is: After rebooting our machine, the nomad server will go into recovery and lose all the data from the previous run. AFAIK this has something to do with its identity. The IP is part of it and since vEthernet WSL keeps assigning a new IP each time, I have to add a static IP to my windows host every time by calling

`netsh interface ip add address "vEthernet (WSL)" 172.19.200.1 255.255.255.0`

My client.hcl file then basically looks like

```hcl
client {
  enabled = true
  servers = ["172.19.200.1:4647"]
}
```

I have yet to test, whether this works.

**Comment by tgross** [comment]
Hi folks! The Docker ecosystem has moved a little bit since this issue was originally opened, so I wanted to summarize the current state of the world and recommendations for running containers on Windows.

* As of [Docker 23.0](https://docs.docker.com/engine/release-notes/23.0/#removed), Docker has removed support for the original implementation for Linux containers on Windows (called "LCOW"). Nomad never really supported this well.
* Running Linux containers on Docker Engine on Windows Server via WSL2 should work, assuming Nomad is running under WSL2 as well.
* Running Linux containers on Docker Desktop on Windows should also work, with the caveats described in our [FAQ for Docker Desktop](https://developer.hashicorp.com/nomad/docs/faq#q-how-to-connect-to-my-host-network-when-using-docker-desktop-windows-and-macos)
* Running Windows containers on Windows Server with either Hyper-V or [Process Isolation](https://learn.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/hyperv-container#process-isolation) mode should work. We consider this to be the expected production environment for Nomad clients on Windows.
 
We're going to close this issue out as resolved. If you run into issues with current versions of Nomad and the specific scenarios described above, please feel free to open a new issue describing the symptoms you're seeing (and which scenario you're deploying in) and we'll try to get that sorted. Thanks everyone!
