### ISSUE TITLE
Script check flapping

### ISSUE THREAD

**Issue by samber** [hashicorp/nomad#2635]
When I execute many times a ```nomad run``` of the same job file, without any change, my **script** check is registered, then deregistered, the registered, then deregistered...

Consul logs:

```
May 11 14:48:54 ip-10-42-31-160 consul[772]: 2017/05/11 14:48:54 [INFO] agent: Deregistered check 'fc2a94375ef72782c7ec678434e8eaca02d74ba3'
May 11 14:50:06 ip-10-42-31-160 consul[772]: 2017/05/11 14:50:06 [INFO] agent: Synced check 'fc2a94375ef72782c7ec678434e8eaca02d74ba3'
May 11 14:53:24 ip-10-42-31-160 consul[772]: 2017/05/11 14:53:24 [INFO] agent: Deregistered check 'fc2a94375ef72782c7ec678434e8eaca02d74ba3'
May 11 14:56:50 ip-10-42-31-160 consul[772]: 2017/05/11 14:56:50 [INFO] agent: Synced check 'fc2a94375ef72782c7ec678434e8eaca02d74ba3'
```

(please note the same CheckID)

Nomad check:

```
...
        check {
          name     = "testing"
          type     = "script"
          command  = "pwd"
          interval = "10s"
          timeout  = "2s"
        }
...
```

### Nomad version

Tested on a local, fresh consul + nomad setup
```
$ consul version
Consul v0.8.2
$ nomad version
Nomad v0.5.6
```

Also tested with nomad 0.5.4 (+nomad 0.5.3 as cli): same issue.

**Comment by schmichael** [comment]
Hi @samber, Nomad's Consul integration was recently extensively refactored due to bugs and performance issues in the 0.5.x code. See #2478 for details.

Would it be possible for you to test on master? A number of check flapping bugs have been fixed, but script checks are a bit unique.

[linux_amd64.zip](https://github.com/hashicorp/nomad/files/993985/linux_amd64.zip)
[windows_amd64.zip](https://github.com/hashicorp/nomad/files/993986/windows_amd64.zip)

**Comment by samber** [comment]
Looks like it's working well with master branch, but please note #2637

**Comment by schmichael** [comment]
@samber Thanks for checking! Sorry you hit that new bug.
