### ISSUE TITLE
(potential) scheduling conflicts with docker host networking

### ISSUE THREAD

**Issue by cbednarski** [hashicorp/nomad#264]
Based on discussion here https://github.com/hashicorp/nomad/pull/219/files#r41707947 I learned that the docker host networking option will cause a process to bind to all interfaces on a Nomad host.

I need to verify, but I think this will cause a scheduling conflict because Nomad only reserves a port on one interface when it makes an offer for the port allocation. I know there are several places that assume that an allocation has only one IP address, and are likely to break if this is not the case.

Our options in this case are to update the offer to include the same port on all interfaces (and audit the code to support this change), or to disallow docker host networking mode. The latter option is simpler and more consistent with the original design.

I will need to spend some time reviewing the network configuration options and design here.

**Comment by zenvdeluca** [comment]
I think docker host is a nice feature, but if you choose to use it, you need to know what you're doing since it can't live well with conflict, i.e: 

if you try bind two redis servers using tcp/6379 on same Host with an unique IP, the second job will fail (container goes down because it can't execute redis-server: 6379 port is already binded). 
one way to handle this on Nomad is detecting and sending this job to another Host, which may have this port free and can execute the job.

Another way to visualize this is similar to what I have here:
Each Host haves multiples IPs (eth0 10.10.10.10, eth0:1 10.10.10.11, eth0:2 10.10.10.12)
I can pass IP and PORT my application should bind to using environment variables, so I spin up 3 docker containers using --net=host, and the redis1 is binding to 10.10.10.10:6379, redis2 10.10.10.11:6379, redis3 10.10.10.12:6379

This way you can have multiple redis servers at a single Host, without need of flannel, weave, any fancy solution, but a simple IP alias. this is a desirable setup for simplifying networking on production datacenters, avoiding rocket science solutions, encapsulations, etc. The idea is having the server being a server (ip_forward=0), not a server + network gateway.

**Comment by F21** [comment]
Does this problem also exist if we use `reserved_ports` on a port? For example, I want to run nginx and have it server on port 80 of the client it's launched on.

**Comment by cbednarski** [comment]
@F21 With respect to the ip / port bid, reserved and dynamic ports work the same way.

**Comment by zenvdeluca** [comment]
Another good point to keep supporting Docker host mode, is when creating sidecart containers, like Docker ambassadors idea.

if I want to spin up a job where one task is the application, and the other task is a proxy to expose this app, docker host mode allows us to bind/connect sockets on localhost -- loopback shortcuts a lot of linux network stack, giving us a good performance.
case: app connects without credentials to the proxy-container; proxy injects credentials to app-container

Developers dont need to worry about authentication / etc.. the sidecar proxy-container handles that

**Comment by cetex** [comment]
A third good reason to support docker host mode is if you want to support hosts with larger traffic volumes. (2.5-20Gbit for reference, although it mostly depends on how many and how shortlived the connections are, not bandwidth)

If we run docker without --net=host (which means we run it "the docker way" = bridge + nat + portforward) we're wasting quite a lot of resources just for NAT / conntrack and such which affect latencies and throughput negatively.

We've tried to set connntrack table size to 1M records but we still fill the table very fast and end up in a self-inflicted DoS scenario where nothing can connect to/From the host. The simplest / most reliable setup is to disable all network virtualization and make sure people know what they're actually doing instead when they deploy stuff.

"docker daemon --bridge=none" (so no bridging / private network available) and "docker run --net=host" is the only combination entering our datacenters nowadays.

**Comment by c4milo** [comment]
Host networking is certainly the easiest and most efficient way to go, also the least secure. However, it makes a lot of sense in non multi-tenant environments. I'm curious, what's the problem with having the scheduler to allocate the port in all network interfaces?

**Comment by DanielDent** [comment]
"I'm curious, what's the specific concern with having the scheduler to allocate the port in all network interfaces?"

A host may have multiple IPs bound to it for the specific purpose of having different daemons (or different instances of the same daemon) binding to the same port on different IPs. We run different DNS daemons for different use cases, for example. Each needs port 53, so the host gets multiple IPs, and each daemon binds to 1 of the IPs.

**Comment by DanielDent** [comment]
And to add to @cetex 's point: we too have workloads where docker's networking is not good enough. The last thing a VoIP server needs is going through docker's proxy. Host-mode networking is nice there.

For other workloads, weave is great - containers get an IP. But the integration with Nomad is very awkward.  Take the following config for example:

    task "memcached" {
      driver = "docker"
      config { image = "memcached:1.4" network_mode = "weave" }
      service { port = "memcache"	check {	type = "tcp" delay = "30s"	timeout = "2s"}	}
      resources {	cpu = 50 memory = 11 network { mbits = 1 port "memcache" { static = 11211 } } }
    }

It would be nice to be able to do that without having the ports forwarded to the public interface via docker-proxy - we don't even actually want the docker bridge to be around. The private Weave IP is the one we'd like to see in Consul and really the only IP we'd like the container to have.

**Comment by dadgar** [comment]
Docker `host` mode networking means no network isolation. The bound IP will be whatever the task binds to so this is not an issue.
