### ISSUE TITLE
Ownership and Permissions are not copied when Rendering Template

### ISSUE THREAD

**Issue by jcua** [hashicorp/nomad#2670]
### Nomad version
Nomad v0.5.6

### Operating system and Environment details
Ubuntu 16.04 on AWS us-east-1 c3.xlarge

### Issue
When nomad renders a template, the file ownership and permissions from the original file are not copied over to the rendered file.

### Reproduction steps
1. Create the following files.
```
$ vi consul-template file.
{{ base64Encode "hello_nomad" }}

$ vi example.nomad
job "example" {
  datacenters = ["dc1"]
  type = "service"
  group "cache" {
    task "sleep" {
      driver = "raw_exec"
      config {
        command = "/bin/sleep"
        args  = ["2h"]
      }
      template {
       source      = "/tmp/test.cfg.ctmpl"
       destination = "/local/test.cfg"
       change_mode = "noop"
      }
    }
  }
}
```

2. Run the nomad job.
```
vagrant@nomad-server01:/opt/gopath/src/github.com/hashicorp/nomad$ nomad run example.nomad
==> Monitoring evaluation "6d7afa49"
    Evaluation triggered by job "example"
    Allocation "50271978" modified: node "297d72ae", group "cache"
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "6d7afa49" finished with status "complete"
```

3. Compare the ownership and permissions of the following files. 
```
vagrant@nomad-server01:/opt/gopath/src/github.com/hashicorp/nomad$ ls -l /tmp/test.cfg.ctmpl
-rw------- 1 www-data www-data 33 May 24 16:05 /tmp/test.cfg.ctmpl

root@nomad-server01:~# ls -l /tmp/NomadClient045035385/50271978-0006-46ef-7a85-938ed5499774/sleep/local/test.cfg
-rw-r--r-- 1 vagrant vagrant 17 May 24 16:07 /tmp/NomadClient045035385/50271978-0006-46ef-7a85-938ed5499774/sleep/local/test.cfg
```

I expect that `local/test.cfg` would have the same ownership and permission  as `/tmp/test.cfg.ctmpl`.

**Comment by dadgar** [comment]
Hey sorry that caught you by surprise. We actually default the permissions of the rendered template and allow you to override it with: https://www.nomadproject.io/docs/job-specification/template.html#perms.

Given that option I am going to close this as most people are either downloading the template or embedding it. The raw_exec case where the template can be accessed is rare.

**Comment by jcua** [comment]
Thanks for the quick reply. I was able to override the permissions with the additional setting that you specified. But I noticed that the ownership was not changed. In the above case, it was still owned by 'vagrant' and not 'www-data'. Is there a reason why the ownership was not copied over?

**Comment by jshuping** [comment]
Hi @dadgar 
> most people are either downloading the template
But that's in the artifact stanza which has its own lack of ownership/permissions, I think?
https://github.com/hashicorp/go-getter/issues/63

Our issue is just in the template stanza.
We are using the cgroups exec not raw_exec, and already have files on disk used by applications
that we are migrating to nomad, so the chrooted hardlinking is perfect for us.

But the lack of ability to set ownership on rendered templates prevents us from enforcing our existing
security model, which is to have some files readable only by the user running the application.

Don't specify perms => file is owned by user running nomad and world readable
Do specify restrictive perms like 0440 => file is owned by user running nomad and unreadable by the application user that the nomad task is running as.

Should we reopen this and reword to focus only own ownership?
Maybe a compromise is to make the rendered template be owned by the user running
the nomad task?

**Comment by dadgar** [comment]
@jshuping So are you all setting the user in the task as well. Trying to understand the model here.

You have a shared folder with template files that each are owned by specific users and you want that carried through to the rendered template.

**Comment by jshuping** [comment]
Yes, exactly!

Also I think I see that when we don't specify 'perms' to the template stanza, the perms are being dropped
to 0644.  See the perms in the original description above, went from 0600 to 0644, and now I have a new 
copy of my secret file on disk (inside /var/lib/nomad/alloc) that anyone can read, a bit of a security risk.

Thanks!

**Comment by dadgar** [comment]
@jshuping Not anyone can read that. The parent directory will be protected by the nomad user (usually root) such that you couldn't access that file unless you were root or chrooted into that directory.

I am not sure I honestly see how you are securing this. In the job file anyone could mark themselves as any user and read the template?

**Comment by dadgar** [comment]
In a way I am inclined to close this issue as the typical user/perms don't really apply with containerized applications. For example in Docker, you are running as root in the container and future versions of Nomad will probably have the same behavior for exec.

**Comment by jshuping** [comment]
Thanks for the insight @dadgar, I think I see where the confusion is stemming from.

We are trying to migrate a few existing applications to nomad with minimal friction. Part of our security model for these apps is standard unix permissions so that e.g., appuserA cannot see appuserB's files. Lots of our configs/keyfiles are 0400.

When we saw the exec driver, especially the word "chroot", we immediately assumed that ownership/permissions would be preserved in all of these cases, and that our existing app could be switched to running in nomad on the same box as the same user with minimal changes. Which led to us filing all these perms issues.

i now see your containerized mindset: each task is running in a separate chroot, so who cares? Lock down the data_dir, run the tasks as nobody, and don't worry about the perms on files inside.

We're happy to take that approach, it will be less headache for both of us :)

Feel free to close this out and thanks a bunch!

**Comment by dadgar** [comment]
Awesome! Thanks @jshuping for following up and glad the explanation made sense!

**Comment by Perados** [comment]
Hello @dadgar ! I am having a similar problem with `v0.5.6` here, but I think it is related to Nomad UI. I am using an inline template in order to have an ssh key inside the container. It looks something like this:
```
...
            template  {
                change_mode = "restart"
                data = "-----BEGIN RSA PRIVATE KEY----- ... ..."
                destination = "local/airflow/id_rsa"
                left_delimiter = "{{"
                perms = "0600"
                right_delimiter  = "}}"
                splay = 5000000000
}
```

When I run this through the CLI using, it works fine. I verified using `nomad inspect`.
In the UI, inside `Jobs > Manage > Advance edit`, I have the following:
```
...
                    "Templates": [
                        {
                            "SourcePath": "",
                            "DestPath": "local/airflow/id_rsa",
                            "EmbeddedTmpl": "-----BEGIN RSA PRIVATE KEY----- ... ...",
                            "ChangeMode": "restart",
                            "ChangeSignal": "",
                            "Splay": 5000000000
                        }
...
```
Note that `data` is translated to `EmbeddedTmpl` and that `perms` is missing. If I redeploy the container through the UI, perms are defaulted to 0644 (I verified again using `nomad inspect`) even if I try to set `"Perms": "0600"` in `Advaned edit`, and the changes are never displayed, perms are never displayed at all actually. So now I cannot deploy using the UI, and that is a problem. 
Do you have any workaround for this are have you seen this bug before? 

Thank you very much in advance!

**Comment by schmichael** [comment]
@Perados If the job looks correct in `nomad inspect` but not Nomad UI, that sounds like a Nomad UI issue and you should file an issue with that project. If inspecting the job doesn't produce the parameters you expect please open a new issue for Nomad with the job file (or relevant section) and output of inspect.

**Comment by Perados** [comment]
@schmichael Indeed, the problem was Nomad UI. We are running a fork from a very old version (v0.2.1) and we cannot upgrade for internal reasons. The workaround I have for this at the moment is to change the permissions of the file in my `docker-entrypoint.sh` file using `chmod`. Dirty, but it works...
