### ISSUE TITLE
rkt env vars are quoted

### ISSUE THREAD

**Issue by schmichael** [hashicorp/nomad#2686]
Because of the %q here rkt env vars values are still quoted: https://github.com/hashicorp/nomad/blob/master/client/driver/rkt.go#L314

@legeyda reported in gitter that `env { CONSUL_HTTP_ADDR = "${NOMAD_IP_app}:8500" }` sets the environment variables to `"10.0.2.15:8500"` (note the literal quotes) when it should be `10.0.2.15:8500`.

This may be as simple as switching %q to %s but requires some testing first.

**Comment by blalor** [comment]
I've been meaning to report this for some time.  For some reason it hasn't impacted my applications, but it is a problem when I `rkt enter` a Nomad-invoked container.  Thanks!

**Comment by schmichael** [comment]
Looks like it was as easy as changing `%q` to `%s`! Sorry for the delay. A test binary if you want it:

[linux_amd64.zip](https://github.com/hashicorp/nomad/files/1125390/linux_amd64.zip)

**Comment by kmalec** [comment]
When I tested that, with %s it only could support single-line vars without any escape chars; having \n there broke `rkt enter` for example (since their env parser reads line by line, looking for ENV=VALUE strings strictly). I was testing with yours crazy multiline env we discussed some time ago on gitter.
