### ISSUE TITLE
Improvement: recursively template files

### ISSUE THREAD

**Issue by gpaggi** [hashicorp/nomad#2725]
It would be extremely helpful to be able to have Nomad recursively template all files in a source directory when both source and destinations are directories.

I'm working on a use case where I have ten(s) of templates that I'm retrieving from github and they all need to be rendered by Nomad in a destination directory; this translates into tens of `template` blocks in my task. I use the same templates in multiple Nomad jobs and I need to edit all HCLs every time I want to add a new template.

Example of possible solution that would render all files in "local/templates/" into "local/service/":

```
[...]
task "service" {
            driver = "docker"
            config {
                image = "xxx"
                network_mode = "host"
                tty = true

                volumes = [
                    "local/service/:/etc/service",
                ]

            }
             artifact {
                source = "git::ssh://git@github.com/test/templates"
                destination = "local/templates"
                options {
                    sshkey = "xxx"
                }
            }
            template {
                source = "local/templates/"
                destination = "local/service/"
            }
```

At the moment this fails with:
```
failed to build task's template manager: failed to read template: read /var/lib/nomad/alloc/4d6222ab-d17a-a1e0-8dce-8394b294621f/service/local/templates: is a directory
```

Thanks!

**Comment by mikenomitch** [comment]
Hey @gpaggi, we discussed this a bit internally and we don't think this will be something we work on any time in the near future, so I'm planning to close it out.

While it's not a great UX right now, with [Nomad Pack](https://github.com/hashicorp/nomad-pack) or Levant hopefully you could templatize the template stanza (very meta 😄) and get around having to rewrite the template stanza too many times.

The other challenge is that Nomad wouldn't be able to detect if the templates in the remote `artifact` changed, so running the job again would not do anything because the jobspec would be the same.

Apologies for the delay on responding to this!
