### ISSUE TITLE
[Improvement] systemd Driver

### ISSUE THREAD

**Issue by dradtke** [hashicorp/nomad#2734]
To kick things off, here is my feeble attempt at building a Nomad driver as a proof-of-concept for this suggstion: https://github.com/hashicorp/nomad/compare/master...dradtke:systemd-driver

Now, a little backstory on my motivation for this. This whole thing may not end up being a good idea, but I think it's something at least worth considering.

---

In my spare time I am working on a project that uses Nomad to manage a cluster (currently just a local Vagrant cluster). In this cluster I have a few services, including a website and a database. The website is built in Go and is executed using Nomad's `raw_exec` driver (with Nomad itself running under an unprivileged user), which works wonderfully. Stateless services with a direct execution model such as that are very much in Nomad's wheelhouse.

The database, however, is trickier. It, like everything in the cluster, registers itself with Consul, which makes it easy for other services to locate the database node. However, since the database is installed via the distro's package manager, there's a bit of a disconnect between it and the other services when it comes to starting things up. Notably, the database does not exist at all according to Nomad, so  `nomad run` will only bring up most of the cluster, not all of it.

What I assume most people do is run their database under Docker, which gives Nomad full control over it as well as everything else in the cluster. However, for my own reasons, I'd prefer to stick with my existing approach, which uses custom Packer builds and direct execution instead of Docker or rkt.

Essentially, what I'm after is to incorporate some [fleet](https://github.com/coreos/fleet)-like functionality into Nomad. Naturally, this wouldn't be able to easily incorporate any strictly-enforced resource isolation, and frankly would be quite limited in its capabilities compared to the other drivers, but being able to spin up a cluster defined as a mix of custom executables and distribution-provided services with a single command would be a powerful tool.

You know what they say, a configuration file is worth a thousand words:

```hcl
job "cluster" {
    datacenters = ["dc1"]
    type = "service"

    group "webs" {
        count = 3

        task "web" {
            driver = "exec"
            config {
                command = "start-my-server"
            }

            # Place the web tasks anywhere but the database server.
            constraint {
                attribute = "${attr.unique.hostname}"
                operator = "!="
                value = "db01"
            }
        }
    }

    group "dbs" {
        task "db" {
            driver = "systemd"
            config {
                service = "postgresql"
            }

            constraint {
                attribute = "${attr.unique.hostname}"
                value = "db01"
            }
        }
    }
}
```

Running a `systemd` task would simply be a matter of running `service <service> start` on the relevant host; similarly, stopping would be `service <service> stop`. `journalctl -fu <service>` could tail logs and forward them to Nomad if necessary.

Feedback welcome!

**Comment by arianvp** [comment]
> this wouldn't be able to easily incorporate any strictly-enforced resource isolation

Systemd has more control over resources than most container tools ..  Actually, systemd is used as the container runtime for `rkt` behind the scenes ;)

Every unit runs in its own cgroup, with its own limits.  Every unit _can_ even run in its own device and network namespace, in its own chroot, and can be dynamically assigned new UIDs transparantly.   `.service` files are basically a container specification format without solving the packaging part these days.


Check out [man systemd.resource-control](https://www.freedesktop.org/software/systemd/man/systemd.resource-control.html)
and [man systemd.exec](https://www.freedesktop.org/software/systemd/man/systemd.exec.html)

Note that all the resource constraints can be changed while the unit is running, so we do not have to put them in the `service` file per se. We could also dynamically set them based on the `resource` stanza in nomad with little effort.    Either through the `DBus` API or with `systemctl set-property NAME ASSIGNMENT`

**Comment by arianvp** [comment]
Also of use, the `fleet` guys made a beautiful wrapper around the `systemd` `DBus` API that you could use for this driver. https://github.com/coreos/go-systemd

**Comment by arianvp** [comment]
I'll start working on a prototype with resource constraints and using dbus directly instead.

**Comment by dadgar** [comment]
Hey all,

Just want to set expectations a bit. We are going to be working on making drivers extensible as plugins. As such we have no intention of upstreaming any more drivers. As such any implementation of this would remain as a fork until there are plugins so I may suggest waiting for the plugin system.

**Comment by arianvp** [comment]
Thanks for the heads up!

**Comment by Mayeu** [comment]
Hello :wave:,

What is the status of this project/issue, and by extension the status of the plugin system from Nomad's Driver?

**Comment by mikepii** [comment]
looks like the plugin system "is planned for 0.9": https://github.com/hashicorp/nomad/issues/468#issuecomment-388132332

**Comment by dantoml** [comment]
0.9 beta is now available with support for custom external plugins for both drivers and devices!

You can find the documentation for external drivers here: https://www.nomadproject.io/docs/drivers/external/index.html
and an example plugin here: https://github.com/hashicorp/nomad-driver-lxc

Thank you for your interest - We're excited to see what you build!

**Comment by jboero** [comment]
If anybody is still looking for this, I love this feature request but I go about it a different way.

Rather than have Nomad support external systemd units why not convert a unit directly into a Nomad job spec?  I manage this with a few lines of Bash and a template.

![image](https://miro.medium.com/max/1400/1*iQfhlBWGaxyzvYLWC2PAfA.gif)

Versions for HCL and JSON can be found here: [HCL](https://github.com/jboero/nomadinit/blob/master/config/systemd2nomad.hcl.sh) [JSON](https://github.com/jboero/nomadinit/blob/master/config/systemd2nomad.json.sh)

**Comment by arianvp** [comment]
Because the interesting part of systemd is not the unit file format; it's the runtime and all the tooling around it. 
e.g. see all the features in `man systemd.exec`

I have a prototype here to make nomad talk directly to systemd over dbus https://github.com/arianvp/nomad-driver-systemd 

It has quite a few bugs at the moment though and I haven't work on it for a while.

**Comment by towe75** [comment]
@arianvp, @jboero : why not combine both ideas? Systemd has "transient units" both for root and user session scopes. The golang dbus api can easily create such units:


```
	properties := []dbus.Property{
		dbus.PropType("simple"),
		dbus.PropExecStart([]string{"/usr/bin/sleep","300"}, true),
	}
	res, err := conn.StartTransientUnit("sleeptest.service", "replace", properties, nil)
```


This takes away some drawbacks of your prototype, @arianvp : a unit is created automatically by nomad and systemd forgets it when it's completed. Nomad has also full control over the unit name, so you can run multiple copies of the same task. A transient unit also avoids conflicting systemd/nomad restart policies because the entire unit is controlled by the plugin.

I could imagine that this driver could become "the better rawexec" because systemd takes care about reaping childs etc. Also Nomad can run in a container and still control the hosts systemd (just volume-mount the socket), if desired. Polkit on the host can be used to configure the permissions for the nomad user etc.

IMHO the entire approach is a bit similar to deprecated coreos fleet: creating a distributed systemd.
