### ISSUE TITLE
[feature] add driver.docker.bridge_ip client attribute

### ISSUE THREAD

**Issue by a86c6f7964** [hashicorp/nomad#2785]
this way things that need to talk to something that is on the host machine and bound to the bridge ip (ie consul dns) can use it

https://www.nomadproject.io/docs/drivers/docker.html#client-attributes

**Comment by schmichael** [comment]
master (and soon 0.6) are able to advertise the Docker IP in Consul: https://github.com/hashicorp/nomad/blob/master/website/source/docs/drivers/docker.html.md#advertising-container-ips

Is this sufficient?

**Comment by a86c6f7964** [comment]
I don't understand what you mean by the "docker ip"? is that the bridge ip?

I don't think that will work because I need to set the https://www.nomadproject.io/docs/drivers/docker.html#dns_servers `dns_servers` param to be an IP that the container can talk to. So if consul is bound to the docker bridge (example 172.17.0.1) then it needs to be set to that, or it will have to be set to something like "${attr.unique.network.ip-address}" and make sure that consul is bound to the same ip as that attribute.

**Comment by schmichael** [comment]
> I don't understand what you mean by the "docker ip"? is that the bridge ip?

The IP Docker assigns to the container, so in the bridge's subnet but not the bridge's IP. The ports your container exposes are reachable on that IP from the host.

>  So if consul is bound to the docker bridge (example 172.17.0.1) then it needs to be set to that

Hm, I don't think if you run Consul in Docker with bridge networking it will be bound to the bridge's IP. It will be bound to the next free IP in the bridge's subnet. That's the IP the feature I linked would advertise. However if Consul is the service you wish to discover, advertising it in Consul isn't going to help!

I think for now running Consul with host networking is your best option as once services can reach Consul they can advertise/discover any other services as needed. Consul itself is just kind of a special case and needs to be in a known location. It's not possible to have the location be known with bridge networking because you don't know what IP the Consul container will be assigned even if the port is statically assigned.

**Comment by a86c6f7964** [comment]
I run consul on the host. That is why it binds to the bridge. You cannot
talk to the host except through bridge

**Comment by schmichael** [comment]
Ah! I understand now. Thanks for the extra details.

How is Nomad connecting to Consul? As a workaround for now you can always create your own meta key with the IP: https://www.nomadproject.io/docs/agent/configuration/client.html#meta

**Comment by a86c6f7964** [comment]
Nomad just connects to consul on localhost

**Comment by schmichael** [comment]
Makes sense! I'll try to get this in before we cut 0.6, but it's going to be close. :)

**Comment by shantanugadgil** [comment]
@schmichael ... just curios, how soon in 0.6 landing? 👍   😄

**Comment by schmichael** [comment]
@shantanugadgil :soon:
