### ISSUE TITLE
Github link points to Vagrant in mobile

### ISSUE THREAD

**Issue by carlpett** [hashicorp/nomad#2817]
The Github link points to mitchellh/vagrant instead of hashicorp/nomad in the mobile/responsive-less-wide version. I tried to figure out where this comes from, but didn't succeed, unfortunately, so no PR :(

**Comment by lfarnell** [comment]
So after some digging I may have an idea what's going on. The master branch does in fact point to the nomad github project and not the vagrant project when the mobile side nav is opened. It looks like that a fix has gone in #2603 but it just hasn't been deployed to nomadproject.io since the 0.6.0 release hasn't been shipped yet and the website is only updated per release. I believe this can be closed now! Good catch though :smile:

**Comment by carlpett** [comment]
Ah, that explains why I didn't find it then :) Great, looking forward to 0.6, and the new homepage links :wink:
