### ISSUE TITLE
Add support for "--device" option

### ISSUE THREAD

**Issue by jaychris** [hashicorp/nomad#2938]
We need an option that implements the "--device" Docker cli option, to mount usb devices and other serial control devices for hardware that container based applications are managing.

Per comment from @schmichael on #2671:

> Allowing mounting arbitrary devices makes sense. I think the distinction
between GPUs (#406) and other devices is we intend for the scheduler to
have first class knowledge of GPU resources. Other devices will just be
supported in driver configs.
>
> Jay or Pieter: Would one of you mind opening a Github issue for your
"--device" use cases? It shouldn't be blocked by #406.

**Comment by pieterbreed** [comment]
On my side, we need to support the `--device /dev/fuse` docker cli option to support mounting an AWS s3 bucket using [riofs](https://github.com/skoobe/riofs).

**Comment by kmalec** [comment]
I might post a small PR for this at some point, since we're currently PoCing stuff that runs GPU-enabled containers on CoreOS instances, and I need to use `--device /dev/nvidiactl --device /dev/nvidia0 --device /dev/nvidia-uvm`.
I've seen the GPU-specific issue, not sure it's needed - in our case, I took inspiration from The Internet(TM) and I've built the drivers and kernel module for CoreOS inside Ubuntu docker container, so to load them, I run privileged docker container first, then create the devices inside CoreOS with a script, and then expose those devices to the normal containers. Fingerprinting in that case would require making sure Nomad agent starts *after* the devices have been initialized.

In the long run, it's probably pretty cool, but for now, in my case we can make do by just tagging the instances' metadata and scheduling by a node class.
