### ISSUE TITLE
[improve] Do we has roadmap

### ISSUE THREAD

**Issue by linuxgood1230** [hashicorp/nomad#2985]
### nomad config options
1.nomad agent configs maybe store on consul-kv/bolt-db
    so we use cli config client configs,not edit file

### nomad manage agent on node
2. nomad agent list 
2. nomad agent restart xxxx-agent-node-name
3. nomad agent reload  xxxx-agent-node-name
4. nomad agent config  xxxx-agent-node-name client.metadata=value
All nomad manage operations do not impact on agent host's jobs/tasks

### Drive
5. drive allocations need can auto config on multi disk partitions,e,g /disk1,/disk2/disk3

### Custome schedule
7. nomad schedule list -- suport schedule type,eg database,system,core,batch,..[custome schedule]
8. nomad schedule define my-custom-schedule
9. nomad schedule config list -- 
  mayBe output
   constraint   operator   value
   kernel       =          linux
   host         regexp     .*.google.com
   host         regexp     .*.facebook.com
   my-value     =          my-define-value

10.nomad schedule define   my-value = 'new-my-value'
11.nomad schedule undefine kernel -- delete 
  All those operations on the fly

**Comment by dadgar** [comment]
1) You can generate your configs using consul-template
2) We split agents into their server and client counterparts. You have `nomad node-status` to list client nodes and `nomad server-members`  to list servers
3-5) SIGHUP is the preferred reload mechanism. The client configs should be more or less static and restarting over the network isn't something we have planned.
6) No current plans
7-11) Nomad has no intention of adding pluggable schedulers.

In general we do not share our roadmap too far out because it is liable to change. We don't want to promise and not deliver!

Thanks and I hope you enjoy using Nomad!
