### ISSUE TITLE
Advanced Strategies for Rolling deploys

### ISSUE THREAD

**Issue by diptanu** [hashicorp/nomad#317]
Rolling deploys in Nomad should support the following strategies -
- Nomad should restart the old version of the task if the update for that task failed and stop the rolling deploy.
- Nomad should support querying health of the updated task from Consul and only proceed with the rolling deploy when the current set of Tasks that it has updated becomes healthy.

**Comment by jsierles** [comment]
Is there any progress on this?

**Comment by doherty** [comment]
You might also consider allowing the job file to give a percentage of the job's capacity that you are willing to lose to updates, once health of the task is checked in Consul. This would mean that operators no longer need to know the size of their job, and guess at how long each replica will take to start up in order to reverse engineer suitable values for `stagger` and `max_parallel`; they can simply say "Updates should take down no more than 5% of the fleet" and have it Just Work.

**Comment by dadgar** [comment]
@doherty Yep that is a goal for us too.
@jsierles We are hopeful to bring this in 0.6.0

**Comment by danlsgiga** [comment]
This is the priority number 1 on our requirements to bring Nomad into production. Would be really nice to have it integrated with the health checks.

**Comment by greenboxal** [comment]
Is there any active development on this? We are interested in developing this feature.

**Comment by dadgar** [comment]
@greenboxal Yep. I am working on it now for 0.6.0

**Comment by dadgar** [comment]
Hey all closing this since 0.6.0 brought these features 🎉
