### ISSUE TITLE
[feature request] Allow dispatch_payload larger than 16KB

### ISSUE THREAD

**Issue by dukeland9** [hashicorp/nomad#3365]
Though artifact provides a convenient way to get the binary and/or data needed for a task, sometimes it's still useful to use some local binary or data to start a remote job. For example, one may want his/her java application tested on one machine before pushing the jar to the nexus repository where the jar can be used as an artifact for serious deployments later. The dispatch_payload stanza may be a way to solve this, however, a jar is very likely to be (if not always) larger than 16KB, it can't be used as a dispatch_payload (as stated in https://www.nomadproject.io/docs/job-specification/parameterized.html, "The maximum size of a payload is 16 KiB").

So shall we have dispatch_payloads larger than 16KB? Or it would be more convenient if the artifact stanza can handle this behind the scene: if the artifact address is a remote address, it works the same as now. If the artifact address is local, it automatically dispatches the local artifact to the clients.

**Comment by dadgar** [comment]
@dukeland9 Hey unfortunately we won't be increasing the allowed payload size since the payload is stored in memory and communicated using Raft across servers, we do not want to be committing jars over a consensus protocol :)

The solution is to provide the artifact source as metadata when dispatching and then interpolating it in the artifact block. That way you can pull in artifacts!
