### ISSUE TITLE
Move Start, Prestart and Cleanup logic of drivers to DriverHandle

### ISSUE THREAD

**Issue by sheerun** [hashicorp/nomad#3381]
Currently the driver-specific Prestart, Start, and Clenaup logic is handled within main process of nomad (Driver interface). It could cause instability of client. I think all the logic should be handled by DriverHandle interface that is executed remotely on spawned executor process. Am I right? Wrong?

**Comment by dadgar** [comment]
The drivers are launched externally so that they can be reconnected to in the case that the client is killed or for during an upgrade path. Moving the logic to the clients removes a clear abstraction that they have and introduces a lot of code duplication. Further in the case we bring driver plugins, all plugins would need to re-implement the logic.
