### ISSUE TITLE
Daylight-saving-time problem with nomad/periodic

### ISSUE THREAD

**Issue by port22** [hashicorp/nomad#3392]
Hi, I am looking for a solution to solve the cron/DST problem.

I have a need to run important jobs exactly at 2.30am every day, unfortunately.

You name it .. at summer/wintertime switch for example, using my timezone Europe/Berlin, 2am becomes 3am in a second which will skip the 2.30 job.
The other way round, 2.30 job will be executed; 3am becomes 2am, 2.30 job will be executed again.

Currently I am using UTC, but this requires that I change the cron statements every twice a year, and I almost always forget some ;-)

Now, maybe Nomad could be a good way to get around this with something like:
```
periodic {
    cron = "30 2 * * * *"
}
```

Am I missing from the documentation that there are maybe conditions to validate whether a job can be run, for example: Has it been running lately? Did it NOT run lately? any pre-run or post-run hooks?
At least, if I run nomad at UTC, would I only have one server to change, instead of a bunch with spread-across cronjobs?

How'd you do this with nomad?
Thanks a lot!

**Comment by nugend** [comment]
Sorry if this is a redundant question, but you did try setting the [timezone ](https://www.nomadproject.io/docs/job-specification/periodic.html#time_zone)in the periodic stanza to "Europe/Berlin", right?

If so, sounds like a bug in the way the cron scheduler is determining whether the job should be run or not.

**Comment by port22** [comment]
Hi, the timezone is irrelevant - in every timezone at a daylight-saving-switch an hour will be pushed forward at spring. And a job scheduled in that hour won't be processed because this hour simply does not exist. I was hoping I could implement pre/post-checks with nomad so that I could find out if $today is such a day and handle it accordingly.

**Comment by nugend** [comment]
Nomad doesn't interact with system cron. It uses the following vendor library: https://github.com/hashicorp/nomad/tree/master/vendor/github.com/gorhill/cronexpr. What I'm saying is that I believe your scheduled 2:30 job should execute immediately at 3:00, but I imagine that there is a bug preventing that.

**Comment by dadgar** [comment]
@port22 This would need some investigation. I am not sure how the cronexpr library handles this. You may want to write a little unit test and report back!

**Comment by dantoml** [comment]
@port22 Cron scheduling when DST is enabled on a machine is a fairly difficult problem, because the desired time does not exist, or may occur twice. It's possible to time smear these cases, and _some_ cron extensions have special handling around time shifts of <=3 hours, but we currently don't do this in Nomad.

Because of the nature of the Nomad periodic scheduler, supporting this would likely involve _predicting_ whether a DST event is going to occur, and responding to it as part of computing the next job dispatch time [here](https://github.com/hashicorp/nomad/blob/eecae582c20d0fb206a25910c5bffe9004ad6de0/nomad/leader.go#L419-L422), or somehow responding to periodic evaluations where the time has been missed, but both of these have a lot of 🐉's related to recovering from outage scenarios, and other time anomalies.

Your best bet would be to run without UTC and potentially template those job files for easier redeployment around DST, if you want 2:30-DST semantics in the near-medium term.
