### ISSUE TITLE
Feature request: run health-check script on the host instead of in the task environment

### ISSUE THREAD

**Issue by fho** [hashicorp/nomad#3455]
Nomad is currently only able to run health-check inside the tasks environment.
If the task is a docker container or the binary runs in a chroot, the health-check script has to be part of the container/chroot.

We are using the same tool to check the status of dozens of tasks. 
The same health-check tool has to be installed multiple times in all of the task environments.
In all of those environments the tool installation has to be maintained and it costs unnecessary disk space to store the same binary multiple times.

It would be great to have the option to run the health-check script on the host instead of inside the task's environment.

**Comment by schmichael** [comment]
This is a tricky problem to solve because it's difficult if not impossible to run scripts outside of a task's environment and ensure not just the proper security constraints but also ensure the execution environment (filesystem & network access) is appropriate for the check to execute.

Is downloading the check as an artifact per task prohibitively inefficient? If so, why? Disk space? Additional startup time downloading and extracting the tool artifact?

Perhaps it's easier to improve artifact handling than try to secure external scripts.

**Comment by dadgar** [comment]
I am also inclined to not support this. It adds additional complexity both for the health checking code and for the user to understand the behavior, especially as additional resource isolation mechanisms are enforced. It is much nicer to hold the invariant that the script has network/process/fs access to the task it is health checking.
