### ISSUE TITLE
Feature Request: Dynamically set 'priority' of parameterized job 

### ISSUE THREAD

**Issue by ckong1991** [hashicorp/nomad#3469]
It would be nice if we could set the priority of a parameterized job, e.g. through META when we dispatch a job. Current use case is to run the same task at different priorities, depending on the origin of the task (for our build system) - our work around is to register X jobs of the same template, with the priority/job name changed slightly.

**Comment by chelseakomlo** [comment]
Hey,

Thanks for the feature request! This will be possible in the future as Nomad's roadmap includes dynamic configuration. See https://github.com/hashicorp/nomad/issues/1185 for reference. 

Best,
Chelsea

**Comment by dadgar** [comment]
@ckong1991 To clarify how the link issue would resolve this, one could set the priority of the job to be a variable supplied as metadata provided when dispatching the parameterized job. Currently it isn't possible since interpolation is client side only and all fields that impact scheduling must be known at job submission time currently.
