### ISSUE TITLE
Add artifact_checksum to drivers

### ISSUE THREAD

**Issue by dadgar** [hashicorp/nomad#348]
Add an artifact_checksum that using the go-getter checksum feature: https://github.com/hashicorp/go-getter/pull/1/files

**Comment by armon** [comment]
This may not be necessary after talking to @mitchellh, since the checksum can be a query parameter in `artifact_source`

**Comment by catsby** [comment]
Maybe we could support both? An explicit `checksum` type config option feels better to me, but I'm fine either way. 

Regardless, I'll clean up the Qemu driver that does this on it's own, since it's now built into go-getter, and I'll make sure the other drivers behave as expected when a checksum is included

**Comment by dadgar** [comment]
I could go either way. As long as we have a section in the docs documenting that you can add the checksum it is fine.

**Comment by catsby** [comment]
Proposing  https://github.com/hashicorp/nomad/pull/381 as a fix

**Comment by dadgar** [comment]
#381 fixes
