### ISSUE TITLE
[question] Nomad clients running containers as root

### ISSUE THREAD

**Issue by Cryson** [hashicorp/nomad#3542]
### Nomad version
Nomad v0.7.0

### Operating system and Environment details
RHEL 7

### Issue
I've noticed that nomad clients execute the containerd runtime processes as root, see below:

```root      6153  1258  0 Nov03 ?        00:00:01 docker-containerd-shim 6834bdd19d0b846431e059446dc8c513d55663736cb90e41b74d43547285a303 /var/run/docker/libcontainerd/6834bdd19d0b846431e059446dc8c513d55663736cb90e41b74d43547285a303 docker-runc```

Is there a way to stop the containers from running as root for enhanced security? If not, do we have security concerns on the containerd processes being ran as root or have white papers on the security at this level?

**Comment by dadgar** [comment]
Hey @Cryson,

So that process is actually not being launched by Nomad but rather being managed by the Docker Engine. You will see the shim being launched regardless of if the container is launched using `nomad run` or `docker run`. 

It is likely that shim will have to be root as it is what will be making the syscall's to the OS to setup the isolated container environment! Hope that helps!
