### ISSUE TITLE
[Feature Request] Support StopTimeout for Docker tasks

### ISSUE THREAD

**Issue by angrycub** [hashicorp/nomad#3544]
Would it be possible to support the StopTimeout field on Docker container creation?

re: ZD-5428

**Comment by samart** [comment]
Thanks.

To all color to this ticket - 

Use case:

Operators may need to bounce docker engine, and engine will observe a stop-timeout if set on "docker run".  This helps to ensure there is consistent stopping behavior when either nomad does a container stop and also docker-engine doing the stop.  This helps protect applications that need a little more time to shutdown gracefully.  Otherwise, the default that docker provides is just 10 seconds.  When set, docker engine will wait the for the container that has the longest timeout.

Thank you!

**Comment by dadgar** [comment]
@samart Would you want this to be settable on its own or just be the same value as the kill_timeout. Have the two out of sync seems problematic.

**Comment by samart** [comment]
Hi Alex - it does make sense for it to be the same value and probably set automatically.  But who knows if you will encounter the oddball use use where someone might see this as a problem.

But i am pro setting it automatically and that's a good feature IMHO.

**Comment by dadgar** [comment]
Will need https://github.com/fsouza/go-dockerclient/pull/693 to merge first

**Comment by davidsylvester** [comment]
As part of which release this feature would be available ?

**Comment by dadgar** [comment]
It will be available shortly in 0.7.1
