### ISSUE TITLE
Docker --net container: Parameter

### ISSUE THREAD

**Issue by stevenpall** [hashicorp/nomad#371]
I noticed that in `docker.go`, the Docker network mode is checked to be one of `bridge`, `none`, or `host`. If it is none of these, `bridge` is defaulted to.
```
// Ignore the container mode for now
	switch mode {
	case "default", "bridge", "none", "host":
		d.logger.Printf("[DEBUG] driver.docker: using %s as network mode", mode)
	default:
		d.logger.Printf("[ERR] driver.docker: invalid setting for network mode: %s", mode)
		return c, fmt.Errorf("Invalid setting for network mode: %s", mode)
	}
	hostConfig.NetworkMode = mode
```
I have a use case where I'd like to run a primary container with `net=none` and then use pipework (https://github.com/jpetazzo/pipework) to assign a macvlan interface to it. In addition to this, sidecar containers would be run, ideally, using `net container:<primary_container>` so that they are in the same network namespace and only require one IP per "pod" (to use the Kubernetes term). What's the rationale for excluding `net container:` for the time being?

**Comment by cbednarski** [comment]
@stevenpall Thanks for the feedback. I think there are two significant considerations here.

First, our initial Docker implementation was naive with respect to various Docker network configurations, and a later community PR expanded the options beyond Nomad's intended design. Nomad's current design provides a single IP shared nonexclusively across all tasks in a task group. We still need to do some work on this to rope things back in (probably in 0.2) so Docker follows this model. 

Second, Nomad is not solely a Docker scheduler, and as such we are looking into ways we can provide capabilities (networking or otherwise) with a consistent interface across various providers (Java, exec, Docker, Qemu, etc.), and even on non-Linux operating hosts. This means we _sometimes_ preclude very specialized use-cases in favor of a more general approach, though I think in most cases we've simply not exposed all of the nobs you might want to turn.

Thus far, we've seen huge proliferation in networking implementations and networking uses-cases compared to other areas like OS or runtime, even amongst Docker-centric use-cases. For example, we have numerous SDNs, physical gear, and cloud platforms each with their own APIs and networking models. This is not surprising, but it creates a complex design and integration challenge for us.

Rather than have Nomad provide direct integration with specifics like GCE or SmartStack or Weave or Juniper or Cisco appliances, we'd like to expose lifecycle hooks (e.g. task created, started, stopped, or destroyed) and allow you to plug in your own networking solution. This allows you to turn the nobs you want to turn without us blocking your implementation, and also keeps Nomad's code leaner since we don't need to maintain support for the latest experimental SDNs or proprietary networking APIs in core.

In the short term our focus is to get the core networking design (shared IP across a task group) to work as expected in all our currently-supported use-cases (including Windows and non-Docker platforms). We're planning to add lifecycle hooks soon but not immediately -- currently we're targeting 0.3 or 0.4.

In the mean time, we appreciate feedback like yours to include in our design process. Overall we have likely considered a small fraction of the possible scenarios people are considering for their network topology so it is valuable for us to get information about which implementations are popular outside of the most common deployments and which nobs we need to expose to operators, whether though job configuration or nomad agent configuration.

**Comment by mfischer-zd** [comment]
I disagree that Nomad should support only the lowest common denominator with respect to configuration.  I'd much rather we support the full Docker option palette than burden the user with tuning it manually.  There's nothing wrong IMO with exposing Docker's configurability to the user any more than exposing the configurability of other implementations would be.

The ambassador pattern, where containers share network namespaces and dependent application containers can refer to sidecar proxies by name, is an extremely powerful paradigm for managing outgoing connections from applications. The ability to support this is something we desire immediately, and I don't think it's reasonable to delay our ability to use it simply because it wouldn't be possible to use it with some task engines.

**Comment by cbednarski** [comment]
Thanks for the feedback on this issue!

I've removed the restriction around container networking mode in #434. This should allow you to use nomad with custom drivers and technically it enables container networking also.

However, my understanding is that in container networking mode the configuration is passed as a tuple: `--net=container:name`. Currently there is no way to specify `net container:<primary_container>` so I think we will need some additional work to support this.

**Comment by mfischer-zd** [comment]
Thanks @cbednarski!  Your progress is much appreciated.

**Comment by stevenpall** [comment]
Thank you, @cbednarski!

**Comment by dadgar** [comment]
This has been fixed for a while. Going to close! If something changes we can reopen.
