### ISSUE TITLE
Nomad client `plan` is unclear about how a resource is exhausted.

### ISSUE THREAD

**Issue by egidijus** [hashicorp/nomad#3833]
We are running nomad in production. Our clusters scales in size between 1 and 6 machines.
The issue is that we should have enough capacity but nomad plan reports we do not have enough capacity.

### Nomad version
* Nomad v0.7.1

### Operating system and Environment details
* CentOS Linux release 7.4
* AWS EC2 
* Job/task driver = docker

### Issue
As a nomad user, I am unable to figure out this:
1. have I exhausted CPU across the entire cluster or just a single node?
2. If I exhausted CPU on a single node, which node was the "problem node"?
3. have I exhausted the CPU that is reserved by the job configuration (my job is asking for more than is available across entire cluster/node), OR are #4 the currently allocated job resources OK, but the currently running jobs are using so much CPU that the plan fails?
4. by how much have I exhausted the CPU?
5. how much available CPU do I currently have on my cluster?
6. how much available CPU do I currently have on my node?

I was expecting to be able to figure out where the CPU issue was, but I could not. So stated testing some of the tooling within nomad, and I was saddened.
So I opened this ticket: https://github.com/hashicorp/nomad/issues/3832

**Comment by dadgar** [comment]
Can you display your plan output and would be more than happy to explain its output.

For example:
```
- WARNING: Failed to place all allocations.
  Task Group "cache" (failed to place 1 allocation):
    * Resources exhausted on 2 nodes
    * Dimension "cpu" exhausted on 2 nodes
```

This plan is saying the scheduler looked at 2 nodes (all eligible in the selected DC) and found that neither node had sufficient CPU resources.

1. It is always looking at all eligible nodes given the datacenter list you provided.
2. This isn't really helpful information, as all nodes will have been evaluated.
3. That could be an interesting enhancement. You can open an issue for this
4-6 are capacity planning problems that the tool isn't designed for.

I am going to close this issue since the tool is working as planned and do not want to conflate the requirements of a job submitter and cluster operator trying to do capacity planning.

**Comment by egidijus** [comment]
Thank you.
@dadgar is there a tool or a thing I can use to do capacity planning on our nomad cluster?
I think if we want to maximize our hardware utilization, then knowing exact resource usage is important. Also knowing and understanding how nomad _sees_ resources would be useful (total MHz vs % across all cores).
