### ISSUE TITLE
rejoin_after_leave does not check if server belongs to cluster

### ISSUE THREAD

**Issue by arnecls** [hashicorp/nomad#3837]
### Nomad version

Nomad v0.7.1
Consul v1.0.2

### Operating system and Environment details

`Linux 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 GNU/Linux`

### Issue

rejoin_after_leave seems to merge state with other nomad server-members without any checks if the data is fitting (e.g. region or datacenter is matching).
This causes problems in dynamic, shared environments such as GCP with shared-vpcs where nodes move IPs all the time.

### Reproduction steps

1. Create two nomad server clusters A and B, 3 nodes each.
  Cluster A=[10.0.0.1,10.0.0.2,10.0.0.3] Cluster B=[10.0.0.4,10.0.0.5,10.0.0.6]
  `rejoin_after_leave=true` and `leave_on_terminate=true` must be set
2. Shutdown 10.0.0.1 (A1) and 10.0.0.4 (B1)
3. Create A1 again with the IP 10.0.0.4.

What happens:
As Node A1 is configured to peer with cluster A it connects to that cluster.
As A1 now has the IP of B1 the rest of cluster B thinks A1 is actually B1 and merges data.
Cluster B and A have now merged.

### Desired behavior

Upon re-joining there should be a (maybe optional) check refusing unwanted peers.

### Context

We are running a prod and stage cluster in the same subnet inside GCP.
Both environments are separate clusters with separate Datacenter settings so that we can e.g. test new nomad versions / infrastructure changes without the two clusters affecting each other.
As of this we do not want both clusters to merge although jobs are not really affected by this (because of the different datacenters).

Recreating instance in GCP tends to re-use old IPs, but not always.
Setting `leave_on_terminate=true` is required as it is not guaranteed that the old IP is being reused and we want old peers to properly leave the cluster.
Without setting `rejoin_after_leave=true` instances refuse to merge after re-creation if they get the same ip assigned as before. So we do need both.

Note: Consul is also affected by this problem.

### Temporary solution

We now use static IPs for our nomad/consul masters but this introduces other restrictions / problems with our setup.

### Config

Nomad (relevant parts)
```yaml
datacenter    = "${PROJECT}"
region        = "${REGION}"
leave_on_terminate = true

server {
  bootstrap_expect = 3
  rejoin_after_leave = true
}
```

Consul (relevant parts)
```json
  "datacenter": "${PROJECT}",
  "retry_join": ["provider=gce project_name=${PROJECT} tag_value=consul zone_pattern=(${REGION}.*)"],
  "leave_on_terminate": true,
  "rejoin_after_leave": true,
```

**Comment by schmichael** [comment]
Thanks for the thorough report @arnecls! This is something we should improve.

Out of curiosity is there some reason you're running two logical clusters in the same subnet? Preventing the clusters from communicating is the easiest way to prevent this sort of misconfiguration, but there's definitely more we could do here.

**Comment by arnecls** [comment]
We're connected to our on-premise datacenters in the same class-A net so IP ranges are somewhat constrainted. As we did not run into larger problems having multiple clusters in the same range we did not split our subnet further but we will probably do so in the near future.

**Comment by schmichael** [comment]
After thinking about this I *think* Nomad is doing the right thing.

When you refer to "clusters" does this mean different *regions*? I ask because Nomad has the following behavior if you explicitly join two servers or two servers implicitly join due to IP reuse:

1. The servers have *the same* `region` configured and join via the raft consensus protocol. If there's a quorum of servers they make scheduling decisions and operate as a logical cluster.
2. The servers have *different* `region` configurations and only join via the serf gossip protocol. This is [federation](https://www.nomadproject.io/guides/cluster/federation.html) and the two servers will be in distinct clusters. Commands intended for Region A sent to a node in Region B will get routed to Region A, but the two clusters will not share client nodes, resources, schedulers, etc.

For staging and prod clusters 1. is _really bad_ as you effectively are doing staging in prod. 2 isn't as bad and some people even choose to use Nomad that way, however it is riskier than fully partitioning the clusters.

The only way to disable federation right now is to partition the clusters in some way. The easiest is usually through multiple subnets/networks, but you can also use [TLS to effectively segment clusters.](https://www.nomadproject.io/guides/securing-nomad.html) Ideally you'd have both, but TLS would be sufficient if you don't want to reconfigure your network.

I think for now TLS would be our recommended way to ensure distinct Nomad clusters are segmented as it really provides strong guarantees and has additional security benefits.

Please feel free to reopen and/or let me know if I'm missing something! Thanks for the thorough report. It's a very tricky thing to balance easing federation but also easing cluster isolation.

**Comment by schmichael** [comment]
Unfortunately the nomenclature doesn't match between Nomad and Consul. You
would use Consul's datacenter parameter to mimic Nomad's region parameter.

I'm working on adding a section to our FAQ in your honor because this is an
unfortunate source of confusion we could really document better:
https://github.com/hashicorp/nomad/pull/3853
