### ISSUE TITLE
[thinking] Periodic batch job trigger immediately option

### ISSUE THREAD

**Issue by jrasell** [hashicorp/nomad#3858]
When deploying batch jobs, especially during initial release or when releasing updates to the program code, it would be nice to be able to enforce an immediate trigger upon registration so that operators can see the immediate results rather than wait until the next launch. After the initial trigger the job can stick to the initial planned launch cycle.

### Nomad version
`0.7.1`

**Comment by dadgar** [comment]
Hey this already exists and will be part of the UI as well in 0.8: https://www.nomadproject.io/api/jobs.html#force-new-periodic-instance

**Comment by shantanugadgil** [comment]
Will there be a commandline equivalent of the cURL command in v0.8?

Example: nomad run -force sample.nomad

**Comment by radcool** [comment]
Instead of `nomad run -force sample.nomad` perhaps its own subcommand (with something like `nomad job force sample`, also aliased to `nomad force sample`) would make it clearer that this only applies to an existing job ID (like the API does) and not to a job file. The subcommand would return an error if the job ID supplied does not point to a job of type "periodic".
