### ISSUE TITLE
[Feature] match Consul CLI UX 

### ISSUE THREAD

**Issue by c4milo** [hashicorp/nomad#3869]
Consul's CLI seems to pick up TLS configuration from the local Consul agent. It will be very nice to have the same behavior in Nomad. Right now, we have to set the following in order to use Nomad's CLI from a Nomad server agent: 

$ export NOMAD_ADDR=https://localhost:4646
$ export NOMAD_CACERT=nomad-ca.pem
$ export NOMAD_CLIENT_CERT=cli.pem
$ export NOMAD_CLIENT_KEY=cli-key.pem

**Comment by preetapan** [comment]
> Consul's CLI seems to pick up TLS configuration from the local Consul agent.

@c4milo is it possible that your consul agent has both http and https enabled? I was not able to reproduce this locally.  The[ API client](https://github.com/hashicorp/consul/blob/7de57ba4dea80b0fa02e517d673b0d727d2b5a3b/api/api.go#L323-L322) used by the CLI in Consul also needs similar environment variables and does not read TLS config params from the agent's config. It is not desirable for the client created by the CLI read from a directory owned by the agent, so this is expected behavior.

**Comment by c4milo** [comment]
:o I see, yes, that's probably what's happening! thanks @preetapan!
