### ISSUE TITLE
[question] Best practise for using vault with consul storage, with nomad and docker containers

### ISSUE THREAD

**Issue by durbz** [hashicorp/nomad#3884]
Hi,

I am currently researching the best practise for loading environment variables into docker containers in nomad jobs.

The current setup has vault servers in HA with consul storage, also in HA, along with a full nomad cluster. I currently write secrets to vault via ansible provisioning and want to rid the current way of doing things (using ansible variables directly in nomad jobs and instead use injected secrets which are stored in vault.

I am finding mixed answers during my research and would appreciate it if someone could enlighten me on a good setup. I've seen people mention the template stanza, however is it possible to do lookups within the environment specifications directly?

The bellow code shows an environment value set for a docker container in a nomad job, the "{{ aes_key }}" variable is actually set by ansible, is there a way to replace this to use vault directly instead?

```
env {
	AESKEY = "{{ aes_key }}"
        }
```

**Comment by Xopherus** [comment]
For static secrets you want to store them in the [KV Secret Backend](https://www.vaultproject.io/docs/secrets/kv/index.html). 

For short-lived secrets you would have to choose a secret backend which fits your needs. Have you looked at the [transit secret backend](https://www.vaultproject.io/docs/secrets/transit/index.html) to see if that would fit your needs? It's basically encryption-as-a-service with Vault. 

Also yes you will have to use the template stanza instead of env. The *template* stanza is for injecting secrets at runtime, whether they are from a file, consul-template, or vault. *env* is more for static environment variables. The good news is that you can add `env = true` to your template stanza so it basically does the same thing as the *env* stanza! 

Ref: https://www.nomadproject.io/docs/job-specification/template.html#environment-variables

Hope this helps!

**Comment by durbz** [comment]
@Xopherus Thank you for the response.

The the secrets would remain static until there's a configuration change in an Ansible variable file and later provisioned. How I update the secrets on Vault's side is to be determined yet, as I haven't elected an appropriate secret engine. Does having consul as a storage backend have any bearing on this?

**Comment by Xopherus** [comment]
Any reason why this variable has to be stored in Ansible at all? The purpose of Vault is to be your secret store so it kind of defeats the purpose if it's actually stored somewhere else (especially if it's in plaintext). A better practice would be to generate the key and store directly in Vault's KV Secret Backend. The best practice would have Vault generate the keys for you so they can be rotated based on a TTL.

As far as the storage backend, you can pick from a variety of different ones. Consul is a pretty good choice for HA but it has a couple of minor issues when managing large numbers of secrets.

**Comment by durbz** [comment]
You're right, the plan was to only use a var file for initial configurations - but I guess I can also do away with that, I just need to consider a new work-flow for bootstrapping. 

I've opted for consul storage and seems to be working pretty well thus far. 

Thanks for your input on this, there are so many "recommended" setups out there, that you can go in circles until you decide to ask the question!
