### ISSUE TITLE
Ability to disable raw_exec mounting under alloc/task directories?

### ISSUE THREAD

**Issue by hihellobolke** [hashicorp/nomad#3924]
I run nomad as root in a non-privileged container the raw_exec job fail because it attempts to mount directory (secrets directory I believe). I have also tried building nomad locally from master branch it has same behaviour. 

The jobs succeed *if* I run nomad as non-root user. 

Is it possible to:
- I guess check mount capabilities instead of root user when building Task directories? 
- or run only 1 group/task that share secrets at anytime?

### Nomad version
```
# /bin/nomad-0.7.1 version
Nomad v0.7.1 (0b295d399d00199cfab4621566babd25987ba06e)
```
```
# /bin/nomad-dev version
Nomad v0.8.0-dev
```

### Operating system and Environment details
Alpine container, unprivileged. But nomad run as root. Root user cannot mount.

### Issue
Tasks fail because nomad tries t mount

### Nomad Client logs (if appropriate)
```
02/28/18 22:21:56 PST  Setup Failure  failed to build task directory for "http-echo": mount: operation not permitted
02/28/18 22:21:56 PST  Task Setup     Building Task Directory
02/28/18 22:21:56 PST  Received       Task received by client
```

### Job file (if appropriate)

```
job "web1" {

constraint {
    attribute = "${attr.os.name}"
    value     = "alpine"
  }

  region = "global"
  datacenters = ["cr8dc"]
  type = "service"
  group "webserver" {
    count = 1
    task "http-echo" {
      driver = "raw_exec"
      config {
        command = "/usr/local/bin/http-echo"
        args = [
          "-listen", "0.0.0.0:8000",
          "-text", "hello world",
        ]
      }
      artifact {
        source = "https://github.com/hashicorp/http-echo/releases/download/v0.2.3/http-echo_0.2.3_linux_amd64.zip"
        destination = "/usr/local/bin"
      }

      resources {
        network {
          port "http" {
            static = "8000"
          }
        }
      }

      service {
        tags = ["http", "echo"]
        port     = "http"

        check {
          type     = "tcp"
          port     = "http"
          interval = "10s"
          timeout  = "2s"
        }
      }
    }
  }
}
```

**Comment by chelseakomlo** [comment]
Hi, thanks for reporting this issue. 

We don't recommend running Nomad in containerized environment- this isn't something that we officially support/test against. See https://github.com/hashicorp/nomad/issues/3676 for reference.

**Comment by shvar** [comment]
@hihellobolke, this not exactly an answer to your question, but we recently managed to find out a workaround for a similar issue. We tried to run nomad in circleCI container and when it got a task for dispatch, it failed with the same error.

Turned out, that this was happenning because of the fact, that Nomad drops permissions and tries to mount task directory to the client's folder, that was created with nomad's user.

So, the solution for us was to drop nomad's permissions from the very beginning and allow everything to happen with user nobody in /tmp:
Actual docker command: `su nobody -s /bin/sh -c 'nomad agent -dev'`

@chelseakomlo I understand, that you don't support containerized environment, but maybe this could be helpful.
