### ISSUE TITLE
Nomad should honor Docker's daemon configured logging driver

### ISSUE THREAD

**Issue by c4milo** [hashicorp/nomad#3976]
instead of configuring its own logging driver by default (syslog). Unless, it is explicitly overwritten from a task's driver config.

**Comment by dadgar** [comment]
Nomad has to configure its own logging to provide `nomad logs` functionality. If this issue was solved in docker we could allow multiple: https://github.com/moby/moby/issues/17910.

As it is, Nomad will keep configuring the logging driver and down the line we will likely have logging plugins of our own that will still require capturing Dockers log output.

**Comment by c4milo** [comment]
I understand the underlined need, I just think it breaks the principle of least astonishment since Nomad doesn't install or configure the Docker daemon, we do.
