### ISSUE TITLE
Allocation logs for listed allocation should be accessible regardless of the status.

### ISSUE THREAD

**Issue by emate** [hashicorp/nomad#3995]
**Situation**
Using raw_exec/exec driver, a user is running deployment for some job. Regardless of the deployment successfulness, we're ending up with the output of `nomad status <job_name>` like:
```
(root) ~ $ nomad status <job_name>
[...]
Allocations
ID        Node ID   Task Group            Version  Desired  Status    Created    Modified
1d87014d  e2531a4e  worker         165      run      running   6h48m ago  6h48m ago
8599c163  71030874  worker  164      stop     complete  6d20h ago  13s ago
```

Now, imagine your deployment is marked as failed (due to some logic) and you would want to check stderr logs for allocations still listed in `Allocations` section, but you're getting:
```(root) ~ $ nomad logs 8a9f02f7
Error reading file: Unexpected response code: 500 (failed to list entries: open /var/lib/nomad/alloc/8a9f02f7-1523-f683-f809-7903e7c9d940/alloc/logs: no such file or directory)
```

AFAIK happens, because of allocation logs getting removed upon allocation update while they are still referenced in job status output, creating a bit misleading experience.

**Proposition**
I think it would be feasible to allow accessing logs for allocations that are still listed in any of status commands (without the need to search for application logs in some central logging system) regardless of their status. Of course, any logs accessible from `nomad logs` command are meant to be ephemeral but keeping those accessible for the user would increase the integrity of the nomad user interface experience.
From my understanding, in order to achieve that, we can:
- perform Alloc GC during Deployment GC
- leave Alloc GC as is, but during the process, skip logs GC for all allocations still listed in any status command. 

Are there any other ways to achieve that? What do you think about that?

Thanks!

**Comment by schmichael** [comment]
> AFAIK happens, because of allocation logs getting removed upon allocation update

Indeed your assumption is probably accurate. Because Nomad binpacks the new placements it will often GC allocs being stopped and replaced. You can verify this is occurring by searching your Nomad client logs for "gc" and the alloc ID in question.

Depending on the reasons for the GCing listed you may be able to tune client configuration parameters to GC less often: https://www.nomadproject.io/docs/agent/configuration/client.html#gc_interval

Centralized logging is the best solution to ensure your logs are reachable regardless of the state of the allocation or node. While I wouldn't rule out supporting a two-phase clientside GC to allow logs to persist longer than the rest of an allocation's data, centralized logging just has so many benefits and is so widespread it's not a high priority.

Hope that helps!
