### ISSUE TITLE
Need IPv6 equivilent of ${attr.unique.network.ip-address}

### ISSUE THREAD

**Issue by xaque208** [hashicorp/nomad#4041]
I'm trying to get nomad working in an IPv6 only environment, and I'd like to ensure that even though the nomad server has a v4 address, that my services never bind to it.  As such, it would be great to specify the address of the server of the running job in an argument, but there doesn't seem to be a way to get this currently.  The `${attr.unique.network.ip-address}` looks to be the closest, but that results in an IPv4 address, even though my advertised addresses are only v6.

**Comment by dadgar** [comment]
Are you setting the clients config to use an interface with the IPv6 address? https://www.nomadproject.io/docs/agent/configuration/client.html#network_interface

That value is the result of the fingerprinted network interface. The address acquired from fingerprinting is then the value used by allocations to bind to.

**Comment by xaque208** [comment]
I believe I am.  Here is the client section of my config.  Note that lo1 is not lo0 below.  Its a loopback interface, but has v6 and v4 addresses on it.  In any case though, I'd like to be able to reference the v6 address in a job without knowing what the value is.

```
client {
  enabled = true
  servers = ["nom2.l.example.com"]

  options {
    "driver.raw_exec.enable" = "1"
  }

  network_interface = "lo1"
}
```

**Comment by jktr** [comment]
(nomad v0.8.3 on archlinux)

I have the same issue os OP. `attr.unique.network.ip-address` is always forced to ipv4 addr on my servers with globally routable dual-stack networking even though I have configured nomad/consul with only ipv6 binds/adverts.

The cause seems to be https://github.com/hashicorp/nomad/blob/7b9cf122446b02881250fc5e941fba3ff72e3365/client/fingerprint/network.go#L107 which always chooses the _first_ address found during fingerprinting, and fingerprinting always seems to find the ipv4 address first:
```
2018/04/28 11:05:28.688111 [DEBUG] fingerprint.network: Detected interface ens3 with IP: XXX.XXX.XXX.XXX
2018/04/28 11:05:28.688113 [DEBUG] fingerprint.network: Detected interface ens3 with IP: XXXX:XXXX:XXXX:XXX::1
```

It may make sense to expose an override for this value, possibly even with go-sockaddr templating.

**Comment by tsujp** [comment]
Any updates for this?
