### ISSUE TITLE
"nomad operator raft list-peers" fails on split-brain-like scenario

### ISSUE THREAD

**Issue by hryamzik** [hashicorp/nomad#4232]
### Nomad version
`Nomad v0.7.1+ent (83ac1d7316a79aacb09d349298e14e23a0aa9853)`

### Operating system and Environment details
`ME="Amazon Linux AMI 201`

### Issue

`nomad operator raft list-peers` command fails with `Failed to retrieve raft configuration: Unexpected response code: 500 (No cluster leader)`

### Reproduction steps

1. Set cluster of 6 servers (I'm aware it's a bad number but that was part of blue-green deployment, 3 + 3 servers)
2. Destroy any of 3 non-leader servers

That's it. You can even try to `force-leave` destroyed servers with `nomad server-members|grep 'failed'|awk {'print $1'}|xargs -I% bash -xc "nomad server-force-leave %"` but it won't make any sense.

**Comment by angrycub** [comment]
A 6 node cluster has quorum of 4 nodes.  If you do not [properly leave the nodes](https://www.nomadproject.io/docs/agent/index.html#stopping-an-agent) that you are decommissioning, you will lose quorum and be unable to elect a leader.  

In this case, you would need to do a [Manual Recovery Using peers.json](https://www.nomadproject.io/guides/outage.html#manual-recovery-using-peers-json)

This enables you to specify the member nodes and reestablish a proper voting quorum again.  The peers.info file has useful information about this process as well.

**Comment by schmichael** [comment]
To clarify what @angrycub said a bit: if you want servers to *leave* on shutdown you'll first have to configure them to `leave_on_interrupt` and `leave_on_termination`: https://www.nomadproject.io/docs/agent/configuration/index.html#leave_on_interrupt

I'm closing for now, but please feel free to reopen if we missed anything. Also don't hesitate to open a new issue if you have a specific suggestion on how to improve server management. Unfortunately since `force-leave` requires a leader, and a leader requires a quorum, there's no way to make it work for your use case.

**Comment by hryamzik** [comment]
My point was about recovery, not the initial failure. The only thing that worked was `peers.json` file. I'd expect `force-leave` to work in this case.
