### ISSUE TITLE
[question] constrain running allocations per task

### ISSUE THREAD

**Issue by henn1001** [hashicorp/nomad#4334]
Hi ,
is it possible to restrain/limit the number of running allocations per task? I want to do something like this: 

```
job "job1" {

  type = "batch"

  group "example" {

   # The batch should run 1000 times but only 2 active at the same time
   count = 1000

    task "server" {
 
      config {
        command = "DoSomethingt"
      }

      limit_parallel_tasks = 2
    }
  }
}
```

I already studied the docs but cant find a way to achieve this. Any help?

**Comment by henn1001** [comment]
Upon further reading, the parameterized job is more fitting for my use case.

So the workflow would be to create a job and then use dispatch to create N instances.  Still leaves me with the question if i have to limit the amount of "dispatch" calls at the user input side, or if i can handle the limit by nomad.

**Comment by dadgar** [comment]
@henn1001 I am going to close this since this wouldn't be a feature we would implement in Nomad but can instead be done by the user as you mentioned.

You have a few options. One would be to use parameterized jobs as you mentioned and dispatch 2 at a time. Another would be to simply run 2 workers and put work on a work queue and have them pull the work and exit when everything is done.

**Comment by henn1001** [comment]
thank you
