### ISSUE TITLE
Constraints work differently for groups and tasks ?

### ISSUE THREAD

**Issue by henrikjohansen** [hashicorp/nomad#4424]
The job file below fails to place allocations  ... 
 
```
  group "example" {
    task "task1" {
      constraint {
        attribute = "${attr.unique.hostname}"
        value     = "host1"
      }
    }

    task "task2" {
      constraint {
        attribute = "${attr.unique.hostname}"
        value     = "host2"
      }    
    }

    task "task3" {
      constraint {
        attribute = "${attr.unique.hostname}"
        value     = "host3"
      }
    }
````

However this *does* work as expected : 
```
group "example1" {
  constraint {
    attribute = "${attr.unique.hostname}"
    value     = "host1"
  }
  
  task "task" {
  }
}

group "example2" {
  constraint {
    attribute = "${attr.unique.hostname}"
    value     = "host2"
  }
  
  task "task" {
  }
}

group "example3" {
  constraint {
    attribute = "${attr.unique.hostname}"
    value     = "host3"
  }
  
  task "task" {
  }
}
```

### Nomad version
Nomad v0.8.4 (dbee1d7d051619e90a809c23cf7e55750900742a)

### Operating system and Environment details
Linux foo-foobar  4.4.0-128-generic #154-Ubuntu SMP Fri May 25 14:15:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by angrycub** [comment]
From the [Nomad docs](https://www.nomadproject.io/docs/job-specification/group.html):

> The group stanza defines a series of tasks that should be co-located on the same Nomad client. Any task within a group will be placed on the same client.

There would be no way to satisfy the first set of constraints since by definition all tasks in a group are scheduled on the same host.  I'm going to go ahead and close this issue since Nomad is working as inspected.

**Comment by shantanugadgil** [comment]
Hi @angrycub, would it be possible to flag this error during plan so it is obvious to user what the error is?

@henrikjohansen what is the plan output for the first job?

**Comment by angrycub** [comment]
I made a [cut-down version of the job described above](https://gist.github.com/angrycub/fe05a8142ffa5773156cb9570552366d).

The plan output would look similar to the following:

```
- WARNING: Failed to place all allocations.
  Task Group "cache" (failed to place 1 allocation):
    * Constraint "${attr.unique.hostname} = nomad-client-1.example.com" filtered 2 nodes
    * Constraint "${attr.unique.hostname} = nomad-client-2.example.com" filtered 1 nodes
```

The output indicates that the first instance of the hostname constraint filters out all of the nodes but the one node (it's a three client-node cluster) matching the given hostname.  The second constraint then filters out the remaining node since `nomad-client-1.example.com` doesn't match `nomad-client-2.example.com`.  This causes there to be no nodes eligible to schedule on. 

The run output looks similar:

```
[root@nomad-server-1 impossible_constratint]# nomad run example.nomad 
==> Monitoring evaluation "24b0414a"
    Evaluation triggered by job "example"
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "24b0414a" finished with status "complete" but failed to place all allocations:
    Task Group "cache" (failed to place 1 allocation):
      * Constraint "${attr.unique.hostname} = nomad-client-1.example.com" filtered 2 nodes
      * Constraint "${attr.unique.hostname} = nomad-client-2.example.com" filtered 1 nodes
    Evaluation "8a747025" waiting for additional capacity to place remainder
```

I made a documentation PR https://github.com/hashicorp/nomad/pull/4425 to highlight this possibility.
