### ISSUE TITLE
Usecase of nomad

### ISSUE THREAD

**Issue by suyash1983** [hashicorp/nomad#444]
We are looking for cloud cluster management service for following requirements:

- Discovery and monitoring of services (health check, resource utilization)
- Configuration management (installation, un-installation i.e. orchestration of services)
- Automatic failover/failback of services.
- User and log management and it's monitoring.

So my question is how Nomad help us to achieve above requirements.

**Comment by F21** [comment]
Nomad is a task scheduler that is comparable to Apache mesos.

To stand up an Apache mesos cluster, you need to install a Zookeeper quorum (so mesos can perform leader election), mesos itself and marathon to launch jobs.

In contrast, nomad ships all of that in 1 binary, so it is much simpler to deploy and manage.

In terms of discovery and monitoring, the plan is to lean on consul for service discovery. Consul also does health checks so that faulty services won't resolved. This is currently being implemented.

Configuration management is something you will have to manage yourself, however you can store global configuration in consul's key-value store. Nomad will launch your tasks by running an executable, docker container or a VM through QEMU. How those images are built and configured is up to you. 

In terms of failover, if a task fails, nomad will attempt to relaunch it in your cluster.

Nomad can log to statsd and syslog. It also provides an [http interface](https://www.nomadproject.io/docs/http/agent-self.html) for querying the state of each agent. How you monitor your services inside docker containers is up to you.

**Comment by suyash1983** [comment]
We are trying to understand the Hasicorp stack in our infrastructure, but we found there are so many products which raise confusion as below:
 
``Serf`` : Cluster Node configuration & management.
- So I assume, If I need to configure, manage and orchestrate cluster of nodes, then this package has to be used. Please confirm?

``Otto/Terraform/Vagrant`` : Infrastructure management
- Little confused as there are multiple solutions for doing same thing. Can you please help in understanding when to use each of these?

``Salt/Ansible`` : Service configuration, orchestration and management.
- Application deployment and configuration. These are third party solutions. So is there equivalent solution from Hashicorp? If not, then what would be the preferred solution to use with Consul.

``Consul`` : Discovery of services and health check.
- Does it only does service discovery, monitoring and health check. Then do I assume that I should use Salt/Ansible for application deployment and orchestration? Please confirm?

``Nomad`` : Cluster manager designed for log lived services and short lived batch processes.
- How does it is different from serf? How to decide when to use serf or nomad?

**Comment by suyash1983** [comment]
Thanks a lot for the quick reply.

Now with respect to Nomad I have certain queries:

1) We have set of physical/virtual machine where we want to execute particular binary/script (not in containers or docker) via Nomad . Those binary/script could be long running process like a daemon or it could be any command (short lived).

2) If any long running job like daemon executed by Nomad fails (because of node failure, network failure or process failure) then how Nomad helps to detect the failure.

3) In case of Job failure how Nomad helps to restart the job on the same physical/virtual machine.

4) If it unable to restart that job then how it schedules failover to other available machine(s) and intimate to user(s) of that service/job/process that now service has switch-over to other machine.

**Comment by veerals123** [comment]
i am also curious to know, whether Nomad handles service high availablity (auto failover) as mentioned in the Otto foundation description (although it shows us up as a future offering)

**Comment by dadgar** [comment]
@suyash1983: I can answer some of your questions:

1) Yes Nomad supports this workload. You can use the `exec` or `raw_exec` driver for this.
2) Nomad will detect the failure because Nomad Client's heartbeat to the server. If too many heartbeats are missed, the Client will be marked as dead and the tasks will be migrated. 
3) The Nomad Client will restart your failed jobs according to the restart policy (https://www.nomadproject.io/docs/jobspec/index.html#attempts)
4) This is a work in progress and will come as part of 0.3

**Comment by dadgar** [comment]
@veerals123: Nomad will do restarts at the client and will handle node failures as well by rescheduling on a different node.

**Comment by dadgar** [comment]
Going to close this ticket and recommend we have these types of discussions on the Google mailing list.
