### ISSUE TITLE
Feature - allow Nomad jobs to register with Consul connect

### ISSUE THREAD

**Issue by jrasell** [hashicorp/nomad#4451]
Consul 1.2 announced Consul connect as a feature and it would be awesome to allow Nomad jobs within their service stanza to configure connect such as registering dependant services as detailed - https://www.consul.io/intro/getting-started/connect.html

**Comment by jippi** [comment]
How is this not a thing already? its been multiple minutes since it was announced! </sarcasm>

**Comment by hvindin** [comment]
@jippi because hashicorp is a single company which owns all these tools and they have been working on this internally for a very very long time, a lot of the nomad team where directly involved etc. etc. or at least that's what I've been able to gather anyway `</assuming you already knew that but just incase someone else reads this>`

**Comment by chelseakomlo** [comment]
Thanks for the feature request, good to hear Consul Connect will be a useful feature to Nomad! Supporting Consul Connect integration is on the Nomad roadmap for later this year- we have a few major features planned for our next 0.9 release (Affinities, Driver Plugins, etc) and then we will be adding Consul Connect afterwards.

**Comment by jippi** [comment]
@hvindin yep, i know - I got carried away with @jrasell at hashidays when they announced it - so was all in good spirit :)

**Comment by lawliet89** [comment]
https://www.consul.io/docs/connect/platform/nomad.html

Documents how we can use Consul connect currently without built in support from Nomad.

**Comment by hvindin** [comment]
@lawliet89 Consul allowing nomad jobs to be addressed via consul connect is very different from native integration:

  > Using Connect with Nomad today requires manually specifying the Connect sidecar proxy and managing intentions directly via Consul (outside of Nomad).

I suspect that the ideal outcome would be the ability to declare a nomad job with all intentions and side car configurations ready to go so that there's no extra steps required once the nomad job is up and running.

So while you *could* do it manually, I know that my team and I aren't touching consul connect with any more than perhaps a passing curiosity until we see what an integrated workflow looks like that leverages the capabilities natively without requiring manual crafting of the cluster state to make it all happen.

Super excited for this feature to be rolled out by the way 😏

**Comment by lawliet89** [comment]
@hvindin of course. I was just pointing out the workaround for now.

**Comment by nanoz** [comment]
Now that Nomad 0.9 is in beta (congratulations !), I sincerely hope this issue will be prioritised on the roadmap 😀 

Maybe you can tell us where this matter stands in the Nomad roadmap @dadgar ?

**Comment by schmichael** [comment]
Unfortunately first class Consul Connect support did not make it into Nomad 0.9, but we've already begun work on network namespaces which will enable first class Connect support.

**Comment by hvindin** [comment]
While it's a shame that it didn't make it, I kind of get it comsidering how involved the process is to hook up consul connect without something like nomad. Lots of moving parts and the like.

Any idea where on the roadmap this is likely to fall? And what timelines that's likely to mean?

Lots of discussion happening in my current org about the desire for improving out ability to offer a better developer experience by handling both ingress and egress traffic so a lot of people are looking at istio, which gives my no warm fuzzy feelings based on how many issues people seem to be having with it...

**Comment by schmichael** [comment]
> Any idea where on the roadmap this is likely to fall? And what timelines that's likely to mean?

:soon: Work is already underway. I don't want to promise a specific release as our release dates and goals for 0.10 are still flexible and depend on a number of variables (such as how the 0.9.0 release goes!).

**Comment by chandy** [comment]
+1 to this work, I am in the same boat as @hvindin and would love to go with native integration vs something external.

**Comment by Eywek** [comment]
Any update on this? The 0.9 has been released

**Comment by nickethier** [comment]
Work is currently underway to support shared network namespaces between tasks. This is the foundation to support deeper Consul Connect integration coming in 0.10!

**Comment by hvindin** [comment]
🎉 this looks like it's well on its way given the updated docs here [consul connect](https://www.nomadproject.io/guides/integrations/consul-connect/index.html) and "releases" here [nomad 0.10.0-connect1](https://releases.hashicorp.com/nomad/0.10.0-connect1/)

Very keen for this to go GA 🙂

**Comment by schmichael** [comment]
:tada: Consul Connect support has landed in master. Docs are mostly there but are still being updated. Expect an official release :soon: 

For anyone at HashiConf US next week (I'm sadly missing): drop by the Nomad booth for a demo, to ask questions, or just to say hi! We love engaging with users!
