### ISSUE TITLE
Still uses "go-msgpack/codec" - unmaintained fork of "ugorji/go/codec"

### ISSUE THREAD

**Issue by onlyjob** [hashicorp/nomad#4454]
[nomad/structs/structs.go](https://github.com/hashicorp/nomad/blob/master/nomad/structs/structs.go#L40) uses [hashicorp/go-msgpack/codec](https://github.com/hashicorp/go-msgpack) which appears to be an obsolete (no commits since 2015) fork of actively maintained [github.com/ugorji/go](https://github.com/ugorji/go), [imported from the same file](https://github.com/hashicorp/nomad/blob/master/nomad/structs/structs.go#L36).

Needless forking is harmful. Please consider using the original project.

**Comment by onlyjob** [comment]
keepalive

**Comment by endocrimes** [comment]
@onlyjob Hey! - We're actually in the process of migrating to the upstream library in nomad right now. We originally switched to a fork due to the Consul usage of go/codec, which would frequently run into serialization issues between versions. See https://github.com/hashicorp/nomad/pull/5676 for more info
