### ISSUE TITLE
[question] can we global disable nomad alloc health check

### ISSUE THREAD

**Issue by linuxgood1230** [hashicorp/nomad#4459]
1. we have two datacenter.
2. when a datacenter 's nomad server network isolation.
3. all alloc check failed , all reschedule

**Comment by schmichael** [comment]
I am having a hard time understanding your question.

> 2. when a datacenter 's nomad server network isolation.

If Nomad clients are disconnected from servers, they are considered `lost` after a [grace period](https://www.nomadproject.io/docs/agent/configuration/server.html#heartbeat_grace) elapses.

Allocations on `lost` clients are rescheduled. If _all_ of your clients are unable to contact your servers, all work will be rescheduled as clients become available again.

> 3. all alloc check failed , all reschedule

What check are you referring to?

Are you referring to a [check_restart](https://www.nomadproject.io/docs/job-specification/check_restart.html) stanza restarting allocations? That is unrelated to Nomad servers, so I think you are referring to another check?

[Deployments also use health checks](https://www.nomadproject.io/docs/job-specification/update.html#health_check), but I doubt that is what you are referring to.

**Comment by linuxgood1230** [comment]
thanks 
> I have two dc like dc1, dc2, each has their own servers, three server
> I use consu job -wan and nomad server join to connect each datacenter
> I Test use iptables  IN dc2. one nomad server set iptables
  - -A INPUT -p tcp -m state --state NEW -m tcp  --dport 4647 -j DROP
> all nomad client  reschedule
> can we control how many nomad client node reschedule, like hard schudule limit .when down nomad client node big than the hard schudule limit , we stop reschudule, do nothing.
> another way, can we stop check/heatbeat alloces.

**Comment by preetapan** [comment]
@linuxgood1230 looks like you are asking for a configurable way to limit allocs rescheduled when a client node is marked "lost". Nomad reschedules those allocations because if the clients are lost, any updates to the state of those allocations can't reach the server. So, from a correctness perspective, Nomad reschedules them to a node that's still alive. Heartbeats between the client and server are a core feature of Nomad, so any test that you do that tries to drop all network traffic so that servers become isolated from clients, is only going to cause all allocs to get rescheduled. 

It would help us to understand your use case some more.  Can you explain why you need this feature? 

If you have *temporary* network issues in your environment, then you can try configuring the two hearbeat related parameters mentioned here - https://www.nomadproject.io/docs/agent/configuration/server.html#heartbeat_grace. Increasing the grace period allows for temporary network issues to not affect the allocations because the client node will not be marked lost till it is past its grace period.

**Comment by linuxgood1230** [comment]
thanks
I test two ways
1.  Network is a complex problem. 
2.  a nomad server failed of a datacenter
those will reschedule all my allocations.  
I want control the numbers of allocations/nodes can be failed at the same time.
May be -- this way, we known, what will happen, and the result of the isssue.
we do not let all  alloctions reschedule happen, nerver happen auto. may we can  mannul trigger.
limit_failed_allocations_ration=5%
limit_failed_nodes_number=2
limit_failed_nodes_raiton=1%

**Comment by linuxgood1230** [comment]
like database mysql
nomad health check is very simple. we want use  orchestator to make decision.
just want
nomad raw_exec, schedule(now it's very simple, can not custome)

**Comment by preetapan** [comment]
@linuxgood1230 We don't recommend running a mysql database on Nomad yet. We have future work supporting device plugins for that. Right now, Nomad is optimized for batch jobs, and long running services that don't store state on disk (because rescheduling such services is a hard problem). 

To your other request about controlling the number of allocations rescheduled when a node is lost, this isn't something we can support right now. It introduces more edge cases than it solves, and our system is designed to choose correctness over availability.

**Comment by linuxgood1230** [comment]
thanks very much
may increase a switch. global disable  allocation health check. 
just create, migrate, delete, schedule , others can custom their own .
