### ISSUE TITLE
[question] Getting the list of IPs of identical tasks in the same group as an environment variable before running the image

### ISSUE THREAD

**Issue by MrDeguito** [hashicorp/nomad#4460]
Hello nomad community, 

I was hoping to get some help with "Nomadizing" an in-house distributed application. The way this application has been written, at startup it needs to be passed down a list of IP:PORT pairs for all of the hosts that will be part of this cluster. It is expecting that value in an environment variable. We already run this application manually with docker today and pass the environment variable on the command line.

We also have been using Nomad for a while and like it but couldn't quite figure out how to get this list of IP:PORT pairs for all of the hosts that will be part of this cluster at the time of startup of all of the instantiations of the hosts.

We run a bunch of other clustered applications like Spark but they depend on a master to coordinate their state. If we have a group "clustered_app" where we specify "count = 5" and a task "server", how can I have each of these "server" tasks get the list of IPs of all of the other 4 identical tasks that are part of this group?

Thanks in advance for your help!

PS: We looked into interpolation of variables but that seems to be for sharing data between different tasks in the same group and I don't know if I can make those references circular

**Comment by shantanugadgil** [comment]
Hi, just curious, in the docker only scenario, is the port on all the machines fixed (same)?

**Comment by MrDeguito** [comment]
Yes, the port on all the machines is fixed (it doesn't have to be but it is)

**Comment by nickethier** [comment]
Hi @MrDeguito 

In your issue you say that in order to start up, your application needs to know the IP and PORT for each instance of the application. Nomad does not know this information before starting your application. You could define each instance as its own group and use constraints to force each allocation to a node with a static port, thus knowing upfront what all of the IP and PORTs will be. However, this really defeats the purpose of using a scheduler as you are essentially doing the scheduling yourself.

A better approach would be to utilize a service discovery solution such a [Consul](https://www.nomadproject.io/docs/service-discovery/index.html). Nomad can register each allocation's IP and port with Consul, then you can query Consul for the list of cluster members in your application.

**Comment by nickethier** [comment]
@MrDeguito closing this now, but please reopen if this doesn't answer your question.
