### ISSUE TITLE
[feature] notify systemd after agent has joined the cluster

### ISSUE THREAD

**Issue by jrasell** [hashicorp/nomad#4466]
In the same style that Consul integrated, it would be nice if Nomad could have the potential to notify systemd when the agent has successfully joined the cluster and is operational. This would allow dependant services to be correctly chained off Nomad rather than blindly starting assuming the service is OK.

Consul PR - https://github.com/hashicorp/consul/commit/31a310f551c36243d2aae9ed80054c200e079b81
Consul Issue - https://github.com/hashicorp/consul/issues/2121

I am happy to raise a PR for this if you believe its a worthwhile addition but have a few questions:
- preference on importing the Consul implementation systemd package or writing a custom Nomad one
- exactly where successful startup and join of an agent would be considered for notification

**Comment by nickethier** [comment]
Hey @jrasell 

Thanks for raising this issue. I'd advise holding off on any immediate work as there some work in progress that could affect this. I think this may benefit from some work we're doing to support external plugins. This is a valuable use case to identify and will help add perspective.

**Comment by jippi** [comment]
@nickethier any news on this?

**Comment by jrasell** [comment]
Please keep open.

**Comment by elcomtik** [comment]
@nickethier any news? 

I have an issue with dependency for vault-agent and experiencing exactly this issue https://github.com/hashicorp/nomad/issues/3885

I'm reloading nomad by vault-agent service, so I wanted to patch this by defining systemd service order. However, this is useless because the systemd unit for nomad is using Type simple, which doesn't wait for service startup. I tried to use types forking and notify, however, nomad doesn't support them also.

Support for proper systems notification is essential for proper integration with vault-agent which reloads nomad for ACL token renewal. This makes life with enabled ACL unnecessarily hard.

**Comment by tgross** [comment]
Shipped in Nomad 1.8.0: https://github.com/hashicorp/nomad/pull/20528
