### ISSUE TITLE
[feature] allow Nomad to manage its own ACL replication token

### ISSUE THREAD

**Issue by groggemans** [hashicorp/nomad#4487]
I manage Nomad ACL's trough vault, and Nomad is connected to the same vault cluster. When I had to deploy some new servers I accidentally used an ACL replication token created by Vault, thinking it would be renewed automatically. It was after a small hour of testing and looking at the logs I realized that it would never work, as Nomad currently doesn't support auto renewing the token.

Similar to the vault token itself, it would be nice if the ACL replication token could be rotated automatically. It might even be possible to request the token automatically trough vault.

**Comment by preetapan** [comment]
@groggemans thanks for the feature suggestion. However, our secret backend integration is designed this way so that ACL token management can be done externally and not be a Nomad concern. Having Nomad talk to vault to renew its ACL token would tightly couple the two so we will not be doing this at this time. 
Having more automation to manage internal ACLs in Nomad is something we will consider in the future with a more full fledged ACL management system that supports Vault and other ways.
