### ISSUE TITLE
cpu.frequency wrong for c5 amazon machines

### ISSUE THREAD

**Issue by camerondavison** [hashicorp/nomad#4550]
`/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq` does not exist for CoreOS `1800.5.0` running AWS `c5.9xlarge` or `c5.4xlarge`

This is causing `cpu.frequency` to use the `/proc/cpuinfo` value which is a point in time value not the max cpu freq.

**Comment by schmichael** [comment]
Hi @camerondavison!

Are you running Nomad in a container on CoreOS? Is sysfs mounted and readable inside the container? Can you use `rkt enter` to find out?

sysfs is the standard way to read CPU frequency. Please let me know if you're aware of another interface, and I'd be more than happy to try to get this fixed in our upstream library!

In the mean time you'll have to manually set the CPU frequency in each client's configuration file: https://www.nomadproject.io/docs/agent/configuration/client.html#cpu_total_compute

**Comment by Magical-Chicken** [comment]
Hi @schmichael, thanks for taking a look at this,

We are not running the nomad client in a container, it is run directly via a systemd unit file. The same nomad client configuration and invocation is used across multiple different instance as workers for an autoscaling group, but only the c5 series of aws instance types seem to have this issue.

In theory the dmi/smbios data should be correct in the vm as that is published by the hypervisor, so using dmidecode might work here. We found #4233, which was suggested for arm chips, but may work here too.

I don't know of any ways other than that to get cpu frequency, we were hoping yall might. I'll let you know if I can find anything else out about why cpufreq isn't giving us any useful data.

Thanks

**Comment by schmichael** [comment]
Thanks for looking into this!

`dmidecode` would be a good fallback option since Nomad is usually run as root. Strange that only that one instance type is missing the sysfs entry we look for. Are any cpu stats available via sysfs? Maybe there's another option? This almost smells like a kernel/hypervisor bug.

Can you grep for `CONFIG_CPU_FREQ` in your kernel's build config (eg `/boot/config-4.15.0-29-generic` on Ubuntu)?

**Comment by camerondavison** [comment]
not sure if this is what you are asking for or not, but 
```
core@ip-10-0-0-127 ~ $  cat /proc/config.gz  | zcat | grep CONFIG_CPU_FREQ
CONFIG_CPU_FREQ=y
CONFIG_CPU_FREQ_GOV_ATTR_SET=y
CONFIG_CPU_FREQ_GOV_COMMON=y
CONFIG_CPU_FREQ_STAT=y
CONFIG_CPU_FREQ_DEFAULT_GOV_PERFORMANCE=y
# CONFIG_CPU_FREQ_DEFAULT_GOV_POWERSAVE is not set
# CONFIG_CPU_FREQ_DEFAULT_GOV_USERSPACE is not set
# CONFIG_CPU_FREQ_DEFAULT_GOV_ONDEMAND is not set
# CONFIG_CPU_FREQ_DEFAULT_GOV_CONSERVATIVE is not set
# CONFIG_CPU_FREQ_DEFAULT_GOV_SCHEDUTIL is not set
CONFIG_CPU_FREQ_GOV_PERFORMANCE=y
CONFIG_CPU_FREQ_GOV_POWERSAVE=m
CONFIG_CPU_FREQ_GOV_USERSPACE=m
CONFIG_CPU_FREQ_GOV_ONDEMAND=m
CONFIG_CPU_FREQ_GOV_CONSERVATIVE=m
# CONFIG_CPU_FREQ_GOV_SCHEDUTIL is not set
```
looks mostly the same across all instance types for me

**Comment by schmichael** [comment]
Yup! Thanks! Just wanted to sanity check that CONFIG_CPU_FREQ was set. Really not sure what's going on on this instance, but it seems like a kernel/hypervisor bug.

Still hopefully we can land dmidecode support upstream to offer a workaround. In the mean time you'll have to set the [`cpu_total_compute`](https://www.nomadproject.io/docs/agent/configuration/client.html#cpu_total_compute) client config parameter.

**Comment by jippi** [comment]
On Ubuntu 14.04 i get the correct `54416` value for c5.4xl instance

**Comment by commarla** [comment]
We have the same issue here. On some c5 instances the file is here but sometimes not. We are using the `cpu_total_compute` option for now.

We're using debian stretch with kernel 4.16 or 4.18. but it's seems not related to the kernel version.

**Comment by tgross** [comment]
@shoenig I know we did some work to get these values from information we got from AWS. Was your impression that was going to be the semi-permanent solution or should we keep this issue open?

**Comment by shoenig** [comment]
Yeah this should just work now

```
$ rg 'c5\.'
client/fingerprint/env_aws_cpu.go
61:	"c5.12xlarge":   newCPU(48, 3.6),
62:	"c5.18xlarge":   newCPU(72, 3.4),
63:	"c5.24xlarge":   newCPU(96, 3.6),
64:	"c5.2xlarge":    newCPU(8, 3.4),
65:	"c5.4xlarge":    newCPU(16, 3.4),
66:	"c5.9xlarge":    newCPU(36, 3.4),
67:	"c5.large":      newCPU(2, 3.4),
68:	"c5.metal":      newCPU(96, 3.6),
69:	"c5.xlarge":     newCPU(4, 3.4),
```
