### ISSUE TITLE
Nomad failes to get token from standby Vault

### ISSUE THREAD

**Issue by kak-tus** [hashicorp/nomad#4641]
### Nomad version
v0.9.0-dev

### Operating system and Environment details
Ubuntu 16.04

### Issue
When Nomad tries to get token from standby Vault it fails with "error validating wrapping token: Vault is in standby mode".
Same issue is here https://github.com/hashicorp/vault/issues/3071.

There is 0.6.1 Vault api libraries vendored in Nomad. Is it possible to update them to at least 0.8.3? This version fixes issue above.

**Comment by kak-tus** [comment]
Unfortunately, https://github.com/hashicorp/nomad/pull/4658 was not fix the problem.

**Comment by tgross** [comment]
I'm reviewing open Vault issues following the new Vault workload identity work (ref https://github.com/hashicorp/nomad/issues/15617). Unfortunately this issue was left stale for so long that I doubt we're going to get more information from the user about it if we tried to pick it back up. It looks like there were some issues in the Vault API at some point but we're on a much much newer version from when this was originally reported. I'm going to close this out but if someone from the community encounters this problem again we'll be happy to revisit.
