### ISSUE TITLE
Allow to specify per node environment variables to tasks

### ISSUE THREAD

**Issue by mildred** [hashicorp/nomad#4715]
This is a feature request to allow nomad clients to forward specific environment variables to all the tasks they run. Those variables would be specified by key and value in the nomad client configuration.

Example client HCL config file:

```hcl
client {
  environment {
    CONSUL_ADDR = "http://192.168.x.y:8500"
  }
}
```

Use case (as shown above) is to be able to set consul address of the local node without having to specify it in the metadata and having each job file specify it again in their environment section. It can be thought as an extension of the existing [runtime environment](https://www.nomadproject.io/docs/runtime/environment.html).

Another configuration that could work:

```hcl
client {
  meta {
    CONSUL_ADDR = "http://192.168.x.y:8500"
  }
  export_meta = ["CONSUL_ADDR"]
}
```

**Comment by cricket007** [comment]
Can't this already be worked around by running Nomad via SystemD?

**Comment by mildred** [comment]
Nomad is running using systemd just fine, but docker containers started do not inherit any environment variables. So setting the variables in the systemd service will not have them inherited in the docker container.

**Comment by cricket007** [comment]
> docker containers started do not inherit any environment variables

I feel like that is somewhat intentional. AFAIK, no Docker orchestrator does this. 

However, I do think I've seen some feature like this in Rancher (1.x)

**Comment by tgross** [comment]
Hi @mildred and @cricket007!

First, Nomad does pass its environment variables to `exec`, `java`, and `raw_exec` tasks. These are subject to a [blocklist](https://nomadproject.io/docs/configuration/client/#env-blacklist) which can be configured on each client.

I believe the reason we don't currently pass environment variables to other task drivers because the runtimes for those drivers aren't child processes of Nomad. For example, the Docker task driver sends API calls to `dockerd`, which is the parent of the task processes. We could probably manage this with Docker because it has an environment variables field we can use. But task drivers like the QEMU task driver wouldn't even have a way to receive environment variables from Nomad in the VM's environment.

In the specific use case of Consul, if you're using Consul with Nomad you probably want to have a Consul client agent on each Nomad client host so that agent health checks work correctly. In which case you could set that meta variable either as localhost or by using a `go-sockaddr` expression like `{{ GetPrivateIP }}:8500`, depending on how you have Consul configured.

**Comment by mildred** [comment]
Yep, there are a number of tricks to do this inside the job file, but the idea was to allow to use unmodified nomad jobs to use consul to have something more flexible and decouple job implementation from the underlying infrastructure implementation.

**Comment by mikenomitch** [comment]
I'm going to close this out as there hasn't been a lot of interest on this one in several years, and it could lead users down a bad path - IE they have to know about their client env to know if their job will work. This would also be tricky to do for all of our different drivers. Plus the stuff tgross mentioned.

There are also (maybe not ideal) workaround like using a host volume on the client to get values into the tasks. (Might be a bad idea).

Appreciate the request/idea though!
