### ISSUE TITLE
Interpolation does not work with artifact checksums

### ISSUE THREAD

**Issue by matthoey-okta** [hashicorp/nomad#4814]
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Output from `nomad version`
Nomad v0.8.4 (dbee1d7d051619e90a809c23cf7e55750900742a)
### Operating system and Environment details
Amazon Linux 1 2018.03.1
### Issue
I looked at the release notes and didn't see this so I don't think it's my version.

When trying to use a meta variable and interpolation for a checksum of an artifact it fails out with an error message:
```
* Artifact 1 validation failed: 1 error(s) occurred:

* invalid checksum: encoding/hex: invalid byte: U+0024 '$'
* Artifact 2 validation failed: 1 error(s) occurred:

* invalid checksum: encoding/hex: invalid byte: U+0024 '$')
```
I originally had `md5:${NOMAD_META_ARTIFACT_MD5}` but also tried putting the `md5:` in the variable to no success.
### Reproduction steps
Attempt to use interpolation in the checksum of an artifact
Run nomad job plan on your job file.

**Comment by dadgar** [comment]
Good catch. Issue is that we are checking for the length pre-interpolation: https://github.com/hashicorp/nomad/blob/master/nomad/structs/structs.go#L6143-L6182

We will have to lower the level of validation we provide if there is an interpolation since on the server we may not have all possible values to interpolate with.

**Comment by matthoey-okta** [comment]
Thanks!
