### ISSUE TITLE
Consul Support for HTTPS Addresses and Token

### ISSUE THREAD

**Issue by bluk** [hashicorp/nomad#484]
I've set the `consul.address` for service discovery, but it seems that HTTPS scheme is not supported for Consul connections.

```
  "client": {
    "enabled": true,
    "servers": [ "192.168.1.100" ],
    "options": {
      "consul.address": "192.168.1.100:8501"
    }
  },
```

Startup logs have something like:

```
2015/11/22 16:16:30 [ERROR] consul: Error while registering service ServiceName with Consul: Put http://192.168.1.100:8501/v1/agent/service/register: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
```

I imagine that Consul token support is also necessary at some point.

**Comment by diptanu** [comment]
@bluk We are using the Consul api client, I think it uses http by default. Let me see how we can do https with it.

**Comment by diptanu** [comment]
@bluk Looks like the API client supports https via the Scheme parameter https://github.com/hashicorp/consul/blob/master/api/api.go#L157

We will add an option to support http very soon in the consul config, and until then if you set up the environment variables ```CONSUL_HTTP_SSL``` and ```CONSUL_HTTP_SSL_VERIFY``` via the Jobs DSL the current code should be able to do https since it appears that the client is reading those environment variables.

**Comment by bluk** [comment]
@diptanu Thanks!
