### ISSUE TITLE
Nomad UI: show timestamps next to evaluations

### ISSUE THREAD

**Issue by samart** [hashicorp/nomad#4920]
Nomad UI jobs page has a list of evaluations and a triggered by column. From an operational standpoint, we have discovered that It would be very valuable to have human readable timestamps to understand when an evaluation was triggered/run.

Thanks

**Comment by backspace** [comment]
Thanks for the suggestion. I have a PR for this [here](https://github.com/hashicorp/nomad/pull/6050), which requires the API support in #5881. You can try it out [here](https://deploy-preview-6050--nomad-ui.netlify.com/ui/jobs) with fake data.

I didn’t include modification time because it didn’t seem like it would be useful, do you agree?

**Comment by backspace** [comment]
This will be included as part of 0.10.
