### ISSUE TITLE
[question] embed nomad scheduler without network and server stuff

### ISSUE THREAD

**Issue by vtolstov** [hashicorp/nomad#4980]
i like nomad scheduler and want to use it inside my project, i'm need only small part like task with cpu, memory, disk constrains and scheduler that decide which node use to run.
As i understand, extract such parts are not trivial? Do you think about embedable variant of scheduler ?

**Comment by vtolstov** [comment]
Can you provide example how to fill nodes and take suitable nodes for specific task

**Comment by preetapan** [comment]
@vtolstov see  https://www.nomadproject.io/intro/getting-started/cluster.html for how to create a minimal cluster. Our documentation has more detailed examples on various features - https://www.nomadproject.io/docs/job-specification/
Rather than trying to embed Nomad into something else, I would recommend that you spin up a small cluster using the above example (one server/three clients) to play around with Nomad.
