### ISSUE TITLE
docs: execution ordering of job file stanzas

### ISSUE THREAD

**Issue by jrasell** [hashicorp/nomad#5047]
When working on Nomad job files, it would be very helpful to have reference documentation that describes the general order in which stanzas are executed. For example, it would be helpful to understand that all templates are executed and rendered before the artefact stanza is executed.

**Comment by tgross** [comment]
HI @jrasell! 😁 

Doing some documentation issue cleanup here. Some of this is intentionally undocumented because we don't want folks to rely on it, but the rest (including the items you're asking out here) can be found in [Templates, Artifacts, and Dispatch Payloads](https://www.nomadproject.io/docs/internals/filesystem#templates-artifacts-and-dispatch-payloads).

Closed by https://github.com/hashicorp/nomad/pull/9195
