### ISSUE TITLE
Question: What could go wrong if a nomad server and client ran on the same host?

### ISSUE THREAD

**Issue by ketzacoatl** [hashicorp/nomad#5053]
Hello,

The nomad config docs mention:

> Note that it is strongly recommended not to operate a node as both client and server, although this is supported to simplify development and testing.

What is behind this recommendation, what could go wrong with a production setup in this configuration?

Let's say you run _only_ 3 nodes in a DC, and then have 3 DCs. so 9 nodes, 3 different deployments, each node is a leader and a client in one agent. What could go wrong?

Thanks! :)

**Comment by xmaster484** [comment]
Hi, I too would like to know what the cons of running both on the same host would be.

**Comment by schmichael** [comment]
Nothing as long as long as _all_ nodes always have ample spare resources. If a job were to saturate one of the resources on a node (eg cpu, storage, disk IO, or bandwidth) and cause it to crash or be unable to do work in a timely manner, the 2 live nodes would eventually consider that job as "lost" and reschedule it. The job would then cause its new host to become unresponsive and you would no longer have a functioning Nomad cluster.

This might be manageable, but also consider that since Nomad isn't managing _itself_, growth in Nomad server memory isn't accounted for when making scheduling decisions. There are a variety of use cases where Nomad server agent memory grows over time which could cause an outage of either Nomad, your services, or both (depending on the whims of the oomkiller).

As with many suggestions I'm sure there are many users happily running clusters like the one you describe. Test your use case thoroughly (including how you intend to update agents and jobs) and it may fit your needs perfectly.

**Comment by kak-tus** [comment]
@ketzacoatl 
Also, you can read my article (problem #4 from it).
https://habr.com/post/435132/
(you can translate it from russian with google translate).

**Comment by ketzacoatl** [comment]
Thanks @schmichael !

**Comment by alshdavid** [comment]
Just to leave my thoughts to this;

For extremely simple use cases such as a small web server that I want to add competent container orchestration to, having one host as both the client and server is great as I don't (and haven't) needed more than one host since the inception of my project.

It also leaves the door open to adding another host in future
