### ISSUE TITLE
Nomad removes checks not managed by itself

### ISSUE THREAD

**Issue by poll0rz** [hashicorp/nomad#529]
Hi,
I have Consul already deployed, with some services and checks activated via config files in several hosts.
When I startup a Nomad client in a host, it removes those Consul checks.
I think this is a bad behaviour since they're not managed by Nomad:
    2015/12/02 09:52:00 [DEBUG] Removing check with ID: service:influx
    2015/12/02 09:52:00 [DEBUG] Removing check with ID: freespace
    2015/12/02 09:52:00 [DEBUG] Removing check with ID: service:grafana

Am I missing something? Thanks in advance!

**Comment by diptanu** [comment]
@poll0rz Yes currently we assume Nomad client is managing all the services running on a node, hence we remove all the services and checks that Nomad doesn't know about. This is done so that there are no zombie services and checks on a node.

Please see #525. Closint this one, let's continue the discussion on that ticket to better track all the threads in the discussion.
