### ISSUE TITLE
Periodic job sometimes doesnt Build Task Directory	

### ISSUE THREAD

**Issue by arnoldyahad** [hashicorp/nomad#5300]
### Nomad version
Nomad v0.8.7 (21a2d93eecf018ad2209a5eab6aae6c359267933+CHANGES)

(but also happened on 0.8.6) 

### Operating system and Environment details
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial
```

```
nomad agent-info
client
  heartbeat_ttl = 17.384301816s
  known_servers = <ip_list>
  last_heartbeat = 1.534232232s
  node_id = <id>
  num_allocations = 8
runtime
  arch = amd64
  cpu_count = 4
  goroutines = 96
  kernel.name = linux
  max_procs = 4
  version = go1.10.4
```

### Issue

using exec driver for a periodic job that should run every 5 mins . sometimes skips the "building task directory" step. which leaves the job without the environment and failing. 
 
![image](https://user-images.githubusercontent.com/18227724/52276184-32590100-295a-11e9-8309-27019b9a3b05.png)

(couldn't find an example without it now, because it happends rarely ( once a day )

**Comment by tgross** [comment]
Doing some issue cleanup. Since this issue was reported the entire task setup was rebuilt from the ground up to the "new" (as of 0.9) task driver model. That was in April 2019. My apologies for letting this issue linger for so long, but it's not going to apply to any currently supported version of Nomad.
