### ISSUE TITLE
[question] ephemeral_disk and docker volumes

### ISSUE THREAD

**Issue by vrenjith** [hashicorp/nomad#5343]
After reading the https://www.nomadproject.io/docs/job-specification/ephemeral_disk.html documentation so many times and after using `nomad` for last two years, I think I have a basic question :)

When we say a sticky `ephemeral` disk, what does that mean exactly? Which disk is this `ephemeral_disk`? Let's say in my `docker` definition,  I have a bunch of `VOLUME` directives which means that `docker` will auto create a set of volumes for each of those and mount them automatically.

Is this `ephemeral` stanza has any impact on those volumes?

**Comment by jippi** [comment]
ephemeral_disk would be everything inside your /alloc dir in the container / cgroup etc. So not data stored on the docker image itself. Also not related to docker volumes

**Comment by dantoml** [comment]
As @jippi said, `ephemeral_disk` is an allocation-local directory that is mounted into your container / cgroup. By default, it's short-lived because when an allocation terminates, we also remove the ephemeral directory. When you set the `sticky` and `migrate` options, we try to persist this for future allocations, but this is best-effort.

`ephemeral_disk` is completely independent from docker volumes.

**Comment by vrenjith** [comment]
@jippi and @dantoml , thank you so much for explaining this.

**Comment by israellot** [comment]
What's the "best effort" made as of today?
I've tried simply updating the memory resource for a task and couldn't get the ephemeral disk to persist accross the update.
