### ISSUE TITLE
Expose deployment version and canary status as variables

### ISSUE THREAD

**Issue by eigengrau** [hashicorp/nomad#5369]
### Issue

It would be convenient if the version number of the current deployment and the canary status of an allocation were exposed as variables for interpolation.

One use-case would be to interpolate the version number into any service names or tags in order to support blue/green deployments with proxies that route solely based on service names (in my instance, I am trying to work-around this issue in Traefik).

This issue is somewhat related to #4668.

As a work-around, a version number can be set manually in a `meta` stanza and interpolated as `NOMAD_META_…`. However, incrementing this can be easily missed when deploying a job, and keeping a version number tag or name in sync with Nomad’s own numbering would be useful.

**Comment by cgbaker** [comment]
We've been talking about adding the job information as a variable for interpolation; I've filed a new issue (#5379) to track this. That will provide the ability to query the job version.

With regard to the canary status, this is trickier. A canary job is not updated when it is promoted; therefore, if you used interpolation (or even a direct query against the allocation status using the Nomad API) to determine whether the task was a canary, this information would become stale as soon as the deployment was promoted (and the task was no longer a canary). One way to do that now is to perform blocking queries against the allocation API in order to notice these changes.

I'm going to close this issue in favor of #5379
