### ISSUE TITLE
[question] Executors runs a large number of threads. Is this expected?

### ISSUE THREAD

**Issue by nugend** [hashicorp/nomad#5393]
### Nomad version
Nomad v0.8.7 (21a2d93eecf018ad2209a5eab6aae6c359267933+CHANGES)

### Operating system and Environment details
Linux 3.10.0-327.36.3.el7.x86_64 Centos 7

### Issue
While using nomad with raw_exec enabled, executors create something like 60+ threads (seems to vary slightly). Is this expected? GOMAXPROCS should be 24 since the host has 24 cores. I can set the environment variable to something lower, but my understanding is that this really just a soft limit and since the number is generally much larger than that, I don't know if it would do much.

What I'd like to know is: How *many* threads should executors be running and if the numbers I'm seeing are considered within the normal range or not.

**Comment by preetapan** [comment]
@nugend could you share how you tracked these thread usages? If you can share a OS thread dump from what you observed, that will help investigation. Would also be curious to know if there was observable impact (like the client being unresponsive etc)

One thing to note is that we rely on a library that uses cgo for fingerprinting and stats, which may add additional threads.

**Comment by nugend** [comment]
Can I take that as confirmation that this seems to be an unexpectedly high number of threads for the executor to have spawned?

We just used basic command line tools to identify this. `ps`, `strace` and the like.

I have to admit my ignorance: What exactly is a threaddump? Does this differ in some way from a core dump?

The impact we had was that we could not longer spawn new processes because the host had hit the process id limit. We can, of course, increase this number, but it seemed quiet peculiar.

One thing I noticed while stracing was that it seemed like the executor was collecting stats on all of the pids associated with it (that is, reading one [or maybe a few] files in `/proc` for each of the threads which each have a unique pid). If my hazy understanding of the go hardware thread creation policy is correct, I could imagine that any latency in reading from `/proc` would cause additional system threads to be created, exacerbating the problem. Of course, I may be wildly off base on that point.

**Comment by preetapan** [comment]
@nugend re: "thread dump" I meant showing threads spawned by the Nomad process via `pstree` or `ps -T -p <pid>` so what you did above is good too. 

We discussed this internally, and currently GOMAXPROCS should be the only factor around number of threads used. Each task running on a client node spaws an executor and a logmon and those in turn have goroutines in them which could spawn threads. So its not totally unexpected to see 60 threads. On my 8 core laptop running five allocations I see it spawning 24 threads. Stats collection is one of the responsibilities of the executor but it also has goroutines for log collection and other. 

As long as you don't see any visible performance impact  this should be fine. We recommend reducing your GOMAXPROCS value if you want to limit this. 

I am going to close this issue based on the above, you can reopen if you observe visible performance issues such as the client being unresponsive due to CPU starvation.
