### ISSUE TITLE
[Documentation] Agent's behavior when servers are lost

### ISSUE THREAD

**Issue by mgrzybek** [hashicorp/nomad#5604]
The current documentation explains how consensus is computed between servers (https://www.nomadproject.io/docs/internals/consensus.html#raft-in-nomad) but nothing seems to be explained about the agents.

The documentation should explain agent's behavior when the quorum is lost:
* Is the current workload stopped ?
* Does the agent keeps things running ?

This makes me think of possible fencing / suicide mechanism.

**Comment by preetapan** [comment]
@mgrzybek The workloads are not stopped when a nomad client agent can't talk to servers because of lost quorum. Any _new_ workloads won't run, but existing workloads keep running. Updates to existing workloads (such as task events/failures) that travel from the agents to servers won't happen until quorum is regained and there's a reachable server. 

Thanks for the documentation suggestion, we will track that, potentially in a new page that explains all the failure modes and how Nomad responds to each.
