### ISSUE TITLE
Reboot Allocation

### ISSUE THREAD

**Issue by Smithx10** [hashicorp/nomad#5670]
Currently within the plugin architecture there is no way to reboot an instance in place.  I'd like a way to reboot an allocation in place with an exponential back off.  This would be similar to the container restartPolicy within Kubernetes Pod Lifecycle. https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy. 

The idea is that by restarting the allocation, or sending a signal, someone could restore the allocation health at a cheaper cost than a full killing and restarting of a task.    This would advantageous when paired with a service health check.

I'm new to Nomads ecosystem and perhaps have implemented Restart Incorrectly,  but I don't think so.

**Comment by endocrimes** [comment]
👋  @Smithx10,

Thanks for your issue, we're actually working to improve some of the control around this in 0.9.2. However, Nomad has a few pre-existing ways that will restart allocations:

- If configuration or secrets change [consul-template](https://www.nomadproject.io/docs/job-specification/template.html) can trigger a restart or signalling of your task
- if you register [service health checks](https://www.nomadproject.io/docs/job-specification/service.html) with Consul, we'll handle restarting tasks when the health checks fail
- If your application crashes, or otherwise terminates, we'll restart it according to your [restart stanza](https://www.nomadproject.io/docs/job-specification/restart.html)

And in Nomad 0.9.2, we'll be introducing support for manual restarts and signalling of tasks, as implemented in:

- `nomad alloc restart` #5502, #5565 
- `nomad alloc signal` #5515, #5612 
- `nomad alloc stop` #5512, #5597 

However, we don't currently support the [delay_function](https://www.nomadproject.io/docs/job-specification/reschedule.html#delay_function) from our rescheduling logic in local restarts. If that's a specific feature that you'd like to see added, I'd welcome another issue for it.

Thanks again!
