### ISSUE TITLE
exec driver failure (cgroup: memory limit)

### ISSUE THREAD

**Issue by pkrolikowski** [hashicorp/nomad#5679]
Hi Team,

After upgrading Nomad I can't run job with `driver="exec"` set (only this driver type is affected).
Job fails with error `memory.limit_in_bytes: device or resource busy`
See details below.

### Nomad version
`Nomad v0.9.1` (client & server)

### Operating system and Environment details
```Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```
```
uname -r
4.15.0-1030-gcp
```
### Issue
After upgrade to `0.9.1` (from `0.8.7`) I am not able to run job  using `exec` driver

### Reproduction steps
Run any job utilizing `exec` driver 

### Nomad Client logs (if appropriate)
```2019-05-10T11:43:29+02:00  Driver Failure         failed to launch command with executor: rpc error: code = Unknown desc = container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"process_linux.go:390: setting cgroup config for procHooks process caused \\\"failed to write 33554432 to memory.limit_in_bytes: write /sys/fs/cgroup/memory/nomad/ae62aa00-64f2-6d81-b965-cb2f5bb14b89/memory.limit_in_bytes: device or resource busy\\\"\""```

**Comment by schmichael** [comment]
Hi @pkrolikowski,

Posting your job file would let me confirm, but from the error it appears your job's memory limit is too low. Due to changes in 0.9 the Nomad executor process that runs alongside each task takes up more memory than in 0.8. It looks like you specified 32mb, but for `exec` jobs the executor requires about 35mb itself.

Setting the job limit to however much memory your process needs + 35mb for the executor should fix this. If not please feel free to reopen! We're hoping to improve the memory usage of the executor in a future release.
