### ISSUE TITLE
Migrate allocations if task driver is unhealthy

### ISSUE THREAD

**Issue by capone212** [hashicorp/nomad#5743]
### Nomad version
Output from `Nomad v0.9.0`

### Operating system and Environment details
LInux, 3 boxes with mixed client + server (for testing purposes)

### Issue
Dear maintainers, 
I have implemented driver plugin to schedule custom application logic with nomad.

The driver fingerprints environment periodically, and at some point, signals that driver is not healthy (drivers.HealthStateUnhealthy) using streaming response of Fingerprint() plugin rpc.

My assumptions that after  unhealthy event is sent, nomad should re-schedule tasks to migrate allocations to healthy nodes, much like what nomad do when node crashes. 
But this is not the case, currently nomad does not reschedule tasks from unhealthy task driver.

**Comment by cgbaker** [comment]
Hi @capone212 , this behavior is intentional on our part. It's partially informed by the use case around the docker driver. In the scenario where the Docker daemon is not responding, the driver plugin will mark it as unhealthy. However, the Docker task containers may very well be healthy; furthermore, since the daemon isn't responding, we don't even have the ability to restart them. As such, the scheduler acts in a very conservative manner here. It relies on other indicators to inform task rescheduling.

If a task has actually failed (or if you want to trigger a reschedule), a plugin should be able to accomplish this by short-circuiting the `WaitTask` and `InspectTask` methods.

**Comment by capone212** [comment]
Hi @cgbaker thanks for your response. I'll check `WaitTask` and `InspectTask`  and close the task if it works.

**Comment by capone212** [comment]
I am closing this task, because after signaling that task exited with WaitTask and InspectTask nomad moved allocations to another node.
