### ISSUE TITLE
[feature] consul & vault hyperlinks

### ISSUE THREAD

**Issue by TheRevenantStar** [hashicorp/nomad#5860]
Since the "HashiStack" is designed to be used all together, can a link be added (via config or consul auto-discover) to the other component of the stack?

I'd like to be able to click on the nomad logo and be presented a simple menu to jump to consul & vault (and maybe other services by config file)

**Comment by preetapan** [comment]
@TheRevenantStar Can you clarify if you mean in our UI or in the project website?

**Comment by TheRevenantStar** [comment]
In the UI

**Comment by DingoEatingFuzz** [comment]
This has been in the back of my mind for awhile now, so I'm glad others are thinking similarly :)

Doing this properly will require coordinating with other products and (ideally) deep-linking to things like services, intentions, and secrets.

There's chatter about all this internally, but the best I can say now is stay tuned, and I hope browser bookmarks aren't too troublesome in the meantime.

**Comment by cricket007** [comment]
Related to #6410 & #7056

**Comment by ChaiWithJai** [comment]
@mikenomitch I think this ticket needs to be broken up into 2 separate issues. One re:  changing the `ui config` block and then implementing the changes in the `ui` because right now we don't have access to the information we need.

cc:  @lgfa29 @tgross unsure who on the backend has bandwidth for this and when they'll have bandwidth.

**Comment by mikenomitch** [comment]
@ChaiWithJai If you don't mind, let's keep this as a single issue since I think just having the UI block without the UI isn't really delivering value.

That said, we'll need to figure out how to coordinate on our side, but hopefully shouldn't be too bad passing this off from backend to frontend.

**Comment by tgross** [comment]
@mikenomitch @ChaiWithJai I'm looking at this and I'm a little unclear as to what we're looking to implement.

I'd scoped out deep links for services in https://github.com/hashicorp/nomad/issues/10583 (much of which came from [(internal ref)](https://app.asana.com/0/758378679700210/1165474804795867/f)), but this issue looks like it's just about having the Nomad menu include a link out to a Consul and/or Vault server? That would make the server-side requirements of this issue:
* A `ui` config block on the server (does nothing within the next bit)
* A `ui.consul` and `ui.vault` config within that block, that gets exposed to the web UI via the API somehow...

Our [`ui` route](https://github.com/hashicorp/nomad/blob/v1.2.0/command/agent/http.go#L340) is a "file" server over the embedded static assets. We have a way to add headers in [`handleUI`](https://github.com/hashicorp/nomad/blob/v1.2.0/command/agent/http.go#L403-L409) but the content isn't otherwise dynamic outside of the API. But we already expose a [`/agent/self`](https://www.nomadproject.io/api-docs/agent#query-self) API that includes certain bits of the server's configuration. So I'll look at adding the fields there.

**Comment by juliezzhou** [comment]
FYI, this is the screenshot of what the UI should look like.
![hyperlink](https://user-images.githubusercontent.com/90711359/142697402-374a2320-80cf-4d73-be56-f9ab6f844da7.png)
