### ISSUE TITLE
Configuration: Add a delay before marking alloc as dead

### ISSUE THREAD

**Issue by legal90** [hashicorp/nomad#593]
When the node became unavailable, its tasks will be migrated to other nodes if possible. Regardless of the result, the desired state of old allocations will be set to "stop". If the node will be back on-line, it will kill these old tasks, even if they were not migrated.

**Feature Request:**
Please, make it possible to configure the delay between node's loss and marking its tasks (allocations) as dead.

**Use case:**
I'd like to use it in an edge case. 
Let's consider that the task is some stateful VM. It is constrained to be running on some concrete node, so we don't want this VM to be recreated from the scratch even if the node became offline by some reason. We just want to wait for some time until this node became available again and the driver re-open's the previous allocation.
However, this VM will be destroyed (by driver's method `Kill()`) as soon as node is back to online, because Nomad has marked this alloc's desired state as "stop". That's why we need a configurable delay between these steps in order to run stateful tasks. Moreover, it could be reasonable to use an infinity timeout here to avoid VM deletion.

Suggestions are welcome! :)
cc: @diptanu

**Comment by diptanu** [comment]
So this is slightly more complex than just adding a timeout. What we need here is introduce "Maintenance Primitives" to Nomad. 
We already have the "drain" primitive which allows operators to move allocations from that machine to somewhere else, in addition to that we should be able to mark a Nomad client under maintenance for a short duration of time which would allow operators to upgrade without moving allocations out of the machine.

When a client goes away, that might mean these things - a. the node is down b. the nomad client crashed c. Operator is upgrading the Nomad client. 

Operators would like the allocations to be removed and nodes to be marked as down when a node goes away especially on the public cloud, since that would mean that there services are going to be recovering very quickly. 

Whereas when operators are upgrading Nomad clients, we could potentially allow them to mark a node under maintenance which would mean that missing heartbeats from the client would not make the Nomad server think it's out of service. This would be useful for stateful services where draining a node to upgrade the client would mean that those services would take a really long time to serve traffic hence making the upgrade process of the Nomad clients across the whole fleet really long.

**Comment by legal90** [comment]
@diptanu Thank you for suggestion! I agree that "Maintenance Primitives" feature would be super useful. 
But will it help to solve an issue which I have described above? 

Being a stateful VM, my task should not be marked as dead regardless of the reason of node's outage. 
In such cases we assume that outage is unexapected, but Nomad could not recover the task state by re-allocation it to another node (for example, the VM could host some stateful database). The only way to do this is turning node back to online.
If it's not possible, the operator should make a decision to stop the job (`nomad stop ...`), which means the VM destroy and data loss. But such decision should always be made by operator only, and never by Nomad.
It's not the same as maintenance mode.

**Comment by diptanu** [comment]
@legal90 Yeah I think this is a slightly different use case and has to be handled differently. Let me think a little bit more about this one.

**Comment by mikenomitch** [comment]
I believe this is achieved by [max_client_disconnect](https://www.nomadproject.io/docs/job-specification/group#max_client_disconnect).

Closing this out!
