### ISSUE TITLE
[question] should encryption keys be unique per datacenter? per region? 

### ISSUE THREAD

**Issue by spuder** [hashicorp/nomad#5973]
The documentation does not clarify on the scope that encryption keys should be configured at. 

https://www.nomadproject.io/guides/security/encryption.html
https://www.nomadproject.io/docs/configuration/server.html#encrypt

If you have 'dc1' and 'dc2', should they share an encrypt key? or have unique keys?

**Comment by langmartin** [comment]
The encryption needs to be common to the entire cluster, because it's used to allow nomad servers to communicate. If you have entirely separate clusters in different data centers you may want to use different keys, but if a single job is going to be deployed to two datacenters, those servers need to share a key.
