### ISSUE TITLE
[question] can I specify envoy binary location for consul connect

### ISSUE THREAD

**Issue by yossisal** [hashicorp/nomad#5977]
### Nomad version
Nomad v0.10.0-connect1 (69bee35d435579073848593c313cfc3ee1842029)

### Operating system and Environment details
centos 7.4

### Issue
Can consul connect run without docker?

**Comment by schmichael** [comment]
Thanks for testing out the preview @yossisal!

Yes you can run the Envoy sidecar proxy without Docker. In the preview you may override the default Docker-based Envoy sidecar by specifying your own `nomad_envoy` task using the `exec` or `raw_exec` drivers:
```hcl
job "redis" {
  datacenters = ["dc1"]

  group "cache" {
    network {
      mode = "bridge"

      port "nomad_envoy" {
        to = -1
      }
    }

    service {
      name = "redis-cache"
      tags = ["global", "cache"]
      port = "6379"

      connect {
        sidecar_service { }
      }
    }

    task "redis" {
      driver = "docker"

      config {
        image = "redis:5-alpine"
      }

      resources {
        cpu    = 500
        memory = 256
      }
    }

    task "nomad_envoy" {
      driver = "exec"
      user   = "root"

      config {
        command = "envoy"
        args    = ["-c", "${NOMAD_TASK_DIR}/bootstrap.json", "-l", "debug"]
      }

      resources {
        cpu    = 100
        memory = 200
      }
    }
  }
}
```
[Full job file](https://gist.github.com/schmichael/9eb8e0ec67359dbb69ac441cd4cefc49)

Unfortunately due to a bug in the preview, Envoy must run as root which is disallowed by default in the `-dev` agent. You can fix this by adding a small configuration file named `allowroot.hcl`:

```hcl
client {
  options = {
    "user.blacklist" = ""
  }
}
```

Then run the dev agent with:

```
sudo nomad agent -dev -network-interface=<<Your public interface; eg eth0>> -config allowroot.hcl
```

Overriding will be easier and not require root for the Envoy task in the final release.

**Comment by yossisal** [comment]
thanks @schmichael  !
Unfortunately running as root as not an option... will wait for the final release. 
Any ETA on that? This feature is a real selling point!

**Comment by schmichael** [comment]
While I hate giving ETAs because things slip sometimes, before the end of August is our goal
