### ISSUE TITLE
Incorrect example in service check "bash-isms" documentation

### ISSUE THREAD

**Issue by phemmer** [hashicorp/nomad#5981]
[The documentation](https://github.com/hashicorp/nomad/blob/197114c017cda885750b1ae9756847edc7cdec4a/website/source/docs/job-specification/service.html.md#check-with-bash-isms) for the service check incorrectly states:
> test is not actually a command (binary) on the system

... and gives an example that it says will not work. 
These statements are incorrect. `test` is a binary on the system, and is even mandated to be so by POSIX: https://pubs.opengroup.org/onlinepubs/9699919799/
> all of the standard utilities, including the regular built-ins in the table, but not the special built-ins described in Special Built-In Utilities, shall be implemented in a manner so that they can be accessed via the exec family of functions

`test` is a standard utility, as defined here:
https://pubs.opengroup.org/onlinepubs/9699919799/

**Comment by notnoop** [comment]
Good catch, thank you!  We'll update the doc.

To clarify for future readers: The doc should indicate that `command` field should be a path to a binary rather than a shell expression.  `test -f /tmp/file.txt` is a bad `command` field, because it's not a path to a binary even if `test` itself is a binary.

```hcl
### THIS IS INCORRECT
service {
  check {
    type    = "script"
    command = "test -f /tmp/file.txt"
  }
}

### THIS IS CORRECT
service {
  check {
    type    = "script"
    command = "/bin/test"
    args = ["-f", "/tmp/file.txt"]
  }
}

### THIS IS ALSO CORRECT
service {
  check {
    type    = "script"
    command = "/bin/bash"
    args = ["-c", "test -f /tmp/file.txt"]
  }
}
```

The `command` needing to be a path is stated in the caveat in https://github.com/hashicorp/nomad/blob/v0.9.3/website/source/docs/job-specification/service.html.md#check-parameters .
