### ISSUE TITLE
Docs: strange phrasing for vault configuration

### ISSUE THREAD

**Issue by spuder** [hashicorp/nomad#6022]
The documentation for vault has a strange sentence in it. 

>The root token is the easiest way to get started, but we recommend a token role based token for production installations.

https://www.nomadproject.io/docs/vault-integration/index.html#vault-configuration

What is meant by the phrase `a token role based token`?  

Should this be `a role based token` ?

**Comment by notnoop** [comment]
They mean tokens based on token roles instead of being root token.  It seems Vault uses "token roles" instead of plain "roles", in the context of authentication to disambiguate it from other roles it supports (e.g. AppRole).

Token Roles is a named entity in Vault for bundling policies and associating with tokens, and can be managed by https://www.vaultproject.io/api/auth/token/index.html#create-update-token-role  .  Here, we suggest using tokens with this type of role instead of root tokens.

English-wise, the phrasing is odd for sure.  Please open a PR with a suggestions you have.
