### ISSUE TITLE
unable to read artifacts : permission denied for nobody user

### ISSUE THREAD

**Issue by harkamals** [hashicorp/nomad#6070]
### Nomad version
0.9.4

### Operating system and Environment details
RHEL 7.6

### Issue
Unable to read dir/files from /local, these are expanded from the artifacts. It used to work ok on 0.9.1 (issue persists on 0.9.3 and 0.9.4)
user: nobody
cat: /local/jobs/aws.nomad: Permission denied

### Job file (if appropriate)
job "test-exec" {

  datacenters = ["dc-1"]
  type = "batch"

  group "group" {

    task "tasks" {

      driver = "exec"

      artifact {
        source = "https://artifactory/artifacts.tar.gz"
      }

      config {
        command = "sh"
        args = [
          "-c",
          "whoami; cat /local/jobs/aws.nomad"
        ]

      }
    }

  }
}

**Comment by langmartin** [comment]
Hi! I've done a bit of version comparison, and I think that the archive file permission behavior is unchanged since 0.8.6. Is there any chance that permissions inside the artifact tarball have changed? The unpacked files are all owned by root, so in the archive you need global read permission. Permission bits are preserved when the tarball is unpacked.

Lang
