### ISSUE TITLE
question on moving jobs when they fail to start

### ISSUE THREAD

**Issue by ketzacoatl** [hashicorp/nomad#635]
question: if a node fails to start a job, and other nodes could accept that job, when will nomad move the job that is failing to start?

Thanks!

**Comment by diptanu** [comment]
@ketzacoatl You mean because of a driver failure?

**Comment by ketzacoatl** [comment]
I am not sure if there are other reasons a job would fail to start and end up with the same.. but yes, in my test, I had agent nodes with the `raw_exec` driver enabled, and nodes without, and the job was scheduled on the one without, continually retrying but failing. Nomad did not move the job to a node with the required driver enabled.

**Comment by ketzacoatl** [comment]
NOTE: I recognize I can use the driver constraint to prevent this specific situation from happening, but I'm still curious about this nuance of moving jobs when they are failing (and I've not yet seen constraints work properly in my setup).

**Comment by diptanu** [comment]
@ketzacoatl First of all, Nomad shouldn't schedule a job on a node where the driver which the job requires isn't present. If it is doing that, then it's possibly a bug. Can you please provide us the client and server logs and create a new issue if you are still seeing that?

Currently Nomad moves allocations only when a node fails. When an allocation fails because of driver failures Nomad currently doesn't move the allocations to another node. This is something we are going to address and possibly going to come with the next release.

**Comment by ketzacoatl** [comment]
Ok, I will setup a test to accurately confirm if what I saw is a bug.

**Comment by dadgar** [comment]
Closing as Nomad will move failed allocations and will not schedule to a node without the appropriate driver.
