### ISSUE TITLE
Migration stanza lacks scope for similar "jobs" or "tasks"

### ISSUE THREAD

**Issue by tsujp** [hashicorp/nomad#6408]
If I had a job which consists of a group of 2 tasks – say a webapp and it's accompanying database – and I needed 10 of these things but each with a slightly different configuration, say one has a database using Postgres, one using MySQL. Essentially all these jobs are 99% similar to their neighbours bar 1 or 2 things how would I do this? Would I have one single job with 10 groups of 2 tasks? Or 10 jobs each with 1 group of 2 tasks?

This is important because now assume I need to drain a client, or a client goes down, how do I then control how fast my tasks-groupings migrate to a new host. The only way it seems to do so is to have 1 single job file with 10 groups of these 2 tasks, but that seems hacky since they aren't _really_ related the only reason I'd have to do that is to get the Migration stanza to keep-scope.

Is there something I am missing here?

**Comment by schmichael** [comment]
Since the update and migrate stanzas affects the behavior of task groups, 10 jobs or 10 groups within a job will all behave the same when deploying updates or draining nodes. Allocations on nodes that crash are rescheduled as soon as the node is marked as `lost` (which depends on the heartbeat settings).

So unfortunately there's no way to control the rate at which distinct task groups are migrated off of a draining node.

I'm curious what you're use case is as it seems like it would be optimal to migrate/reschedule these down tasks as quickly as possible. When a task group has `count = 1` it cannot be highly available (there's only 1 instance so if it crashes you have downtime), the update and migrate stanzas are ineffective at preventing outages.

Closing for now but feel free to reopen with more details!

**Comment by tsujp** [comment]
@schmichael 

> Since the update and migrate stanzas affects the behavior of task groups, 10 jobs or 10 groups within a job will all behave the same when deploying updates or draining nodes.

I'm confused, this means that 10 separate jobs can be controlled via migrate to limit how many of these 10 separate jobs migrate at once? I thought this was only possible within a single job file stanza affecting groups, or within the group stanza affecting tasks.

> So unfortunately there's no way to control the rate at which distinct task groups are migrated off of a draining node.

Ah I see, well I'll leave my quote immediately above for context. 

My goal is to not have a traditional HA setup. Some jobs/tasks cannot be replicated like a webserver for instance, things that require globally unique addressing perhaps. It's enough that these workloads exist and it is straight up impossible to replicate them but what is required is that if they go down they are re-spawned in a defined manner as soon as possible.

Say I had 10 of these, and for this example it's just the http-echo service but we pretend each one is globally unique within the context of the world. I can configure this setup with each 10 separate job files, or 10 task groupings with 1 job file; first of all, which would you recommend for that?

Once that's done let's assume the host goes down or needs to be drained, these cannot be controlled as implicitly there is only `count = 1` for each so `migrate` or `update` won't affect them?

---

Unless, as I tend to overthink things, the solution is to use `count = 10` in this example and have the allocations fetch their special-setup at runtime? How would you suggest having a `count = 10` http echo service where each of the 10 counts fetches a currently not-in-use string to echo from at runtime? I'd imagine something with consul, and perhaps also vault.

Imagine the 10 strings were just "A" through to "J", each of the http-echos in the `count = 10` set needs to grab a letter that currently isn't being echoed by any of the others and then use that as it's `--text` argument for the config stanza to echo. Or, if it cannot be done in the config stanza some other way.

**Comment by schmichael** [comment]
> I'm confused, this means that 10 separate jobs can be controlled via migrate to limit how many of these 10 separate jobs migrate at once? I thought this was only possible within a single job file stanza affecting groups, or within the group stanza affecting tasks.

Sorry my wording was terrible: you are correct. The migrate/update distinctly from one another. I'm not sure what I meant by "all behave the same" but it should be something like "all migrate/update _independently_"

> I can configure this setup with each 10 separate job files, or 10 task groupings with 1 job file; first of all, which would you recommend for that?

If you want to operate on them as a unit, put them in a single job. By "operate as a unit" I'm referring to operations like:

* `nomad run web.hcl` can update them all in a single command/request.
* `nomad job status web` displays a summary for all groups and allocations in the job.
* `nomad stop web` stops all groups.

If you might want to operate on them independently, it will probably be easier to put them in separate jobs.

It's purely for your organizational convenience. Multiple jobs and multiple groups within a job are functionally equivalent.

> Unless, as I tend to overthink things, the solution is to use count = 10 in this example and have the allocations fetch their special-setup at runtime?

Using a single group with count > 0 will not have the behavior you desire. The `upgrade` and `migrate` stanzas will take affect, but those stanzas are only for _slowing down operations to prevent downtime for HA (highly available) services._ Since your services aren't HA, using `upgrade` or `migrate` will only _increase_ downtime.

> How would you suggest having a count = 10 http echo service where each of the 10 counts fetches a currently not-in-use string to echo from at runtime?

The `${NOMAD_ALLOC_INDEX}` environment variable is set and available for interpolation within the job for this purpose if you want to experiment with this approach.
