### ISSUE TITLE
Write a UI reverse proxy guide

### ISSUE THREAD

**Issue by DingoEatingFuzz** [hashicorp/nomad#6410]
It is common to put the Web UI behind some sort of proxy, but given the various ways that the Web UI interacts with the network, this is easier said than done.

We should write a guide that talks through all the subtleties of what the Web UI is doing, including:

1. Blocking queries leaving requests open for a long time
2. Log and file-streaming using [streaming requests](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream) but only in some browsers
3. Log and file-streaming optimistically dialing directly to client nodes but falling back on server nodes

Additionally, it would be nice to provide example configs for common tools such as nginx.

There are just a lot of details to figure out in the dark.

**Comment by jozef-slezak** [comment]
Related to #6413

**Comment by DingoEatingFuzz** [comment]
This guide was published today!

https://learn.hashicorp.com/nomad/operating-nomad/nginx-reverse-proxy

It also goes over WebSocket details required to proxy the new remote exec capability of the UI.

**Comment by pcbl** [comment]
Hi @DingoEatingFuzz , would it be possible to host it in a subdirectory within the proxy?
On the Tutorial it is hosted on location '/'. I tested and it worked like a charm. 

BUT, On my specific case I would host it under '/Nomad/'.... I tried but it did not worked... The UI ends up redirection(307) for a /ui/ instead of /Nomad/ui/
I assume I am missing something. Could you enlighten me? :-)

**Comment by DingoEatingFuzz** [comment]
Unfortunately you are not missing something 😞 For the time being the UI is hardcoded to expect the `/ui` path. There are plans to allow this to be customized.
