### ISSUE TITLE
Start Job button in UI breaks with Vault policies and allow_unauthenticated = false

### ISSUE THREAD

**Issue by fmarczew** [hashicorp/nomad#6414]
### Nomad version
v0.9.4

### Operating system and Environment details
Centos 7

### Issue
Hello,

not quite sure this is related to the ui or the integration of nomad with vault.
I get the following error after integrating vault  and trying to restart (stop and start) some job from the ui:

`Unexpected response code: 500 (Vault policies requested but missing Vault Token)`

For the nomad jobs vault is running fine as secrets getting accessed and the job templates can query secrets. The jobs are registered and deployed using the terraform nomad provider. I've looked up the sources of the provider and see that the vault_token should get injected in the job. As well i checked the sources of nomad and think this error is originated in the backend. If i use the nomad cli and set the environment variables accordingly everything is fine.

So my question therefore is: Am i missing something regarding the vault integration, or is the vault token simply missing in the client side of the ui ? Because in my secret folder of the job i see a vault token requested by the agent after deployment.

In my logs there is nothing else suspicious, simply the error, which i also see in the frontend. Otherwise i only see that vault tokens get requested, which seems fine.

Best Regards

Frank

### Reproduction steps
Set up Nomad and Vault, i am not running the nomad backend engine and gave nomad the root vault token.

**Comment by schmichael** [comment]
> I get the following error after integrating vault and trying to restart (stop and start) some job from the ui:

Unfortunately this is a bug:

Nomad does not return the Vault token submitted with a job through the [Job endpoint](https://www.nomadproject.io/api/jobs.html#read-job) for security purposes.

The UI's Start button reads-and-resubmits the job which now lacks a Vault token, so the API rejects the job.

To make matters worse it's difficult for the UI to even know it needs a Vault token. It can check for the presence of a `Vault` stanza in the job's JSON, but if [`allow_unauthenticated = true`](https://www.nomadproject.io/docs/configuration/vault.html#allow_unauthenticated) then no Vault token needs to be submitted.

The best it could do for now is detect this error and prompt for a Vault token.

I'm marking this a bug instead of a question. Thanks for submitting! Let me know if my explanation doesn't make sense.

**Comment by fmarczew** [comment]
Hello, 

yes, makes perfect sense.
It would be nice to start/stop jobs in the UI without setting `allow_unauthenticated = true`. 
But as a workaround i can live with that, as the access to the ui is restricted by the nomad acl token.

Thank you very much for the explanation.

Best

Frank

**Comment by tgross** [comment]
Starting in [Nomad 1.7.0-beta.1](https://github.com/hashicorp/nomad/releases/tag/v1.7.0-beta.1) we've deprecated the use of Vault tokens at the time of job submission. Nomad will use workload identities to sign into Vault for purposes of getting Vault tokens for those workloads. Using Vault tokens during job submission will be removed entirely in Nomad 1.9.
