### ISSUE TITLE
Checking logs in web UI sends the first request to local internal network IP, then hostname.

### ISSUE THREAD

**Issue by kaspergrubbe** [hashicorp/nomad#6454]
### Nomad version

```
$ nomad -v
Nomad v0.9.5 (1cbb2b9a81b5715be2f201a4650293c9ae517b87)
```

### Operating system and Environment details

Linux running on EC2, we run Haproxy in front of Nomad servers when we access the UI.

### Issue

When we visit the logs Nomad first sends a request to the local internal IP of the Nomad client instance, before routing the request through the hostname.

First log request (that times out after a long time) goes to `10.1.1.204:4646`:

![screenie_1570626474_006887](https://user-images.githubusercontent.com/334273/66484682-5ea3bf00-ea9f-11e9-84dd-0ff5850de13f.png)

Second (and subsequent) log requests goes to the right hostname:

![screenie_1570626499_112845](https://user-images.githubusercontent.com/334273/66484728-75e2ac80-ea9f-11e9-842c-6092c2303d00.png)

### Reproduction steps

Go to the logs for a task and observe the network tab.

**Comment by cgbaker** [comment]
This is the intended behavior. All of the Nomad HTTP API endpoints support relaying calls to the appropriate source (client node for some alloc endpoints, leader server for most everything else). However, because logs and filesystem access can result in streaming large amounts of data, the behavior of the UI and the CLI is to look up the IP of the client node and attempt to contact it directly, instead of relying on relaying. If that fails, then the relaying approach is used as a fallback.
