### ISSUE TITLE
Define Nomad Security Model

### ISSUE THREAD

**Issue by schmichael** [hashicorp/nomad#6493]
Nomad should publish a security model similar to Consul and Vault:

* Consul - https://www.consul.io/docs/internals/security.html
* Vault - https://www.vaultproject.io/docs/internals/security.html

Work with @chair6 and @picatz

**Comment by heipei** [comment]
Hello Team,

wanted to highlight that this would be very welcome because even as a semi-seasoned Nomad user I still struggle with some security concepts. My current issue is that I'm trying to determine what the threat model is in the following use-case:

- Nomad servers running in internal network
- Gossip encrypted
- RPC requires TLS and hostname verify (for client/server role distinction)
- HTTP with ACLs

Now I want to expose RPC to the Internet and then be able to spin up clients that connect to this RPC endpoint. From a comms point this should be fine due to required TLS for RPC. But what I'm trying to figure out is how or whether I can protect myself against a potentially compromised client. These questions come to mind:

- Can a client easily impersonate another existing client?
- Is it reasonable to use constraints to separate workloads between the different unrelated clients?
- What functions is a client able to perform using only the RPC interface? Can it read job definitions or perform cluster operations?
- Would using ACLs prevent any of these issues?
- What am I missing here?

**Comment by notnoop** [comment]
Closed by https://github.com/hashicorp/nomad/pull/8369 .

@heipei please review the doc and let us know if there any pending questions you have!  We'll be happy to follow up in a new ticket.

**Comment by heipei** [comment]
This is great, thanks everyone, answers a lot of the questions I had when I approached Nomad initially. I will make sure to review it properly and let you know if there's any open questions.
