### ISSUE TITLE
Improve upgrade documentation

### ISSUE THREAD

**Issue by schmichael** [hashicorp/nomad#6633]
Upgrade documentation should specify that only upgrading from 0.X to 0.X+1 is supported.

**Comment by preetapan** [comment]
Also need to add guidance around;
 - Upgrade order between clients and servers - Order shouldn't matter
 - What happens when you mix client and server versions 
 - Upgrade process for servers (how autopilot applies to upgrades for servers) and clients (swap binary / drain) 
 - Downgrade steps (wiping state).

**Comment by schmichael** [comment]
PR: https://github.com/hashicorp/nomad/pull/7078
