### ISSUE TITLE
Support adding tags to sidecar consul entry

### ISSUE THREAD

**Issue by dmwilcox** [hashicorp/nomad#6642]
### Issue
Without being able to assign tags to the sidecar consul entry I cannot collect metrics using the consul datasource in prometheus.

Normally I set a tag, such as "port=25000", which during re-labeling modifies the prometheus scrape target.  Without the ability to do that prometheus can only attempt to scrape the mTLS port.

The ideal way to do this would be to expose some options under the 'sidecar_service' stanza for configuring the sidecar.  Very few fields are not permitted when using consul connect directly and tags would be a welcome addition for modifying scrape targets for prometheus and tagging logs (by way of consu' "key=value" type labels) with nomad_follower.

Happy to do some work on this if it isn't already in the works.

**Comment by tgross** [comment]
Hi @dmwilcox! Thanks for opening this issue. Just to make sure I understand, you're referring to adding tags to the [`sidecar_service` stanza](https://www.nomadproject.io/docs/job-specification/sidecar_service.html)?

If so, I have good news! I dug around in the code and found that tags _are_ supported but appear to have been missed in the documentation. If you're interested in contributing a patch to the [Connect docs](https://github.com/hashicorp/nomad/blob/master/website/source/docs/job-specification/connect.html.md) I'd be happy to help get that merged in quickly.

**Comment by pashinin** [comment]
Adding tags to sidecar was planned for 10.1 but for reasons I don't know it was not included.
In fact it was already done in https://github.com/hashicorp/nomad/pull/6448
But according to CHANGELOG - now moved in 10.2. Why?

**Comment by tgross** [comment]
Thanks for catching that @pashinin! I was looking in `master` but not the current release. I'll have to make sure the doc fix lands in `master` as well.

As for why it was moved into a later release: the 0.10.0 release had some panic-causing bugs under some upgrade scenarios. Rather than waiting until all the feature work was ready, the Nomad team decided to publish 0.10.1 as a bugfix release and renamed the planned release as 0.10.2. See the [changelog](https://github.com/hashicorp/nomad/blob/master/CHANGELOG.md#0101-november-4-2019) for more details.

**Comment by tgross** [comment]
Looks like the docs landed in https://github.com/hashicorp/nomad/pull/6455. Once that's published, they'll show up in https://www.nomadproject.io/docs/job-specification/sidecar_service.html
