### ISSUE TITLE
Tests failing on master

### ISSUE THREAD

**Issue by ranjib** [hashicorp/nomad#666]
Hi, specs on master are failing [with following stacktrace](https://gist.github.com/cbednarski/b734dedbb7d5ffbcf764). Im using the stock vagrantfile from nomad master.

**Comment by cbednarski** [comment]
Thanks for the report! I moved the log to [a gist](https://gist.github.com/cbednarski/b734dedbb7d5ffbcf764) so it's easier to read.

**Comment by iverberk** [comment]
So, the panic is obviously due to the test timeout kicking in. This just needs more time to finish. I usually set it to 240s which is enough on my system.

The "Bind for 127.0.0.1:xxxxx failed: port is already allocated" error messages are (partly) due to the Docker tests being run in parallel. The tests all succeed if I disable the parallel option within the tests. Apparently the tests try to start containers on the same port in parallel and it is only due to timings if this succeeds or not, usually it doesn't.

I'm running the test tests locally on OSX with a Docker vm created by Docker machine. So maybe, because I'm not running Docker natively, this causes the problem? Would be good to hear from the official devs if they encounter similar issues with running the Docker tests locally.
