### ISSUE TITLE
[question] Batch jobs are metered an allocation on migration/draining

### ISSUE THREAD

**Issue by Brainfree** [hashicorp/nomad#6739]
Hello,

I have a cluster of nodes running Batch jobs.
These Batch jobs are configured to restart, and not reschedule (reschedule.attempts = 0).
This has worked perfectly fine, but one hitch I found is when performing rolling upgrades.
When performing rolling upgrades, the class of nodes are first drained, where all jobs are stopped, and migrated to another available node. 

Here is the hitch: Draining a node (and stopping the batch job due to it) counted as a allocation for that job (as if it failed due to restarting too many times), causing the job to complete, as rescheduling is disabled. BUT, if I made the job a Service type, migrations are NOT counted as a allocation, and it gets rescheduled on the new node just fine. The problem with Service jobs is that they are always restarted, even when they exit without error (complete).

So, my question is: 

- Is this the expected behavior, and if so, why are batch jobs treated as something optional?
- Could I simply tell nomad to stop the Service job before it non-error exits, to avoid having nomad reschedule it (as a hack)?

Thank you for your time, and your great product!

**Comment by tgross** [comment]
Hi @Brainfree! I just want to make sure I understand the two scenarios completely. You have jobs running, you want to perform a rolling upgrade of the Nomad agents. You `nomad node drain` each agent in turn. And then...

* Scenario 1 (batch jobs): the allocations running on the drained client are completed and then not rescheduled to other nodes.
* Scenario 2 (service jobs): the allocations running on the drained client are rescheduled to other nodes.

These behaviors are what we'd expect to see, and the difference comes from the goals of the two types.

For service jobs, the intent is that Nomad runs them until they've been replaced or stopped by the operator, so they get migrated. The details of that are an interaction between the [`migrate`](https://www.nomadproject.io/docs/job-specification/migrate.html) stanza and the node drain deadline.

For batch jobs, Nomad only migrates them once the drain deadline is reached. If there's no deadline, the drain will wait until the batch job has completed or failed so that you're not at risk of losing work in a batch process that hasn't checkpointed itself.

There's a more documentation on the batch behavior in the [node draining guide](https://www.nomadproject.io/guides/operations/node-draining.html#node-drains-and-non-service-jobs) if you'd like to dig into more.

**Comment by Brainfree** [comment]
Yes, that is how I understand it as documented.
But,
Batch jobs are not allowed to have a migrate stanza, and the batch jobs I am running, are designed to be stopped, and restarted (on another node) where they left of. These jobs can run for days (in theory for ever), and some simply work towards a response (like a remote method call). They are set to restart, and NOT reschedule (reschedule.attempts = 0).

When draining, I use --force flag, to trigger the graceful shutdown (kill_timeout set to 30m in the jobs), notifying them they should start stopping now. This all work fine. 

The problem is that during migration (stopping due to draining), Batch jobs are issued a new allocation (as if they failed due to restarting too many time), instead of being aware that is migrating, and not counting the migration allocation as its own. Since the jobs may not reschedule, the allocation issued due to migration cause them to complete. BUT, for Service jobs, nomad is aware of the migration, and does not count it as a allocation, which is what I desire for these Batch jobs, as they did not fail, but rather are being migrated. 

So my question is: 
Can migrations not cause a allocation to be counted for Batch jobs, just like Service jobs?

**Comment by tgross** [comment]
> Batch jobs are issued a new allocation (as if they failed due to restarting too many time), instead of being aware that is migrating, and not counting the migration allocation as its own. Since the jobs may not reschedule, the allocation issued due to migration cause them to complete (not be rescheduled).

Can you dig into this a bit more? What do you mean by "issued a new allocation" if it's not being rescheduled? I believe we should be seeing an evaluation (a decision by the scheduler) but not any more allocations.

That being said, it doesn't sound like the batch scheduler is what you want for this application, as the deployment behavior you're looking for sounds a lot more like the behavior of the `service` scheduler. Anything that could run "in theory forever" probably is a better fit for `service`.

**Comment by Brainfree** [comment]
Yeah, it would Service type jobs would work, but nomad always restarts services, even on a exit/0, which can't be configured (ex: a 'remote method call' type of behavior).

Here is a example of the situation:

Batch-Job:
```
job "batch_job" {
  datacenters = ["dc1"]
  type = "batch"
  group "flow" {
    reschedule {
      attempts = 0
      unlimited = false
    }
    restart {
      attempts = 3
      interval = "15m"
      delay    = "15s"
    }
    update {
      //Use FORCED updates
      //https://www.nomadproject.io/docs/job-specification/update.html#max_parallel-0
      max_parallel = 0
    }
    //NOT ALLOWED
    /*migrate {
      max_parallel = 1
      health_check = "task_states"
      min_healthy_time = "15s"
      healthy_deadline = "30m"
    }*/
    task "task" {
      driver = "..."
      kill_timeout = "30m"
    }
  }
}
```

Service-Job:
```
job "service_job" {
  datacenters = ["dc1"]
  type = "service"
  group "flow" {
    reschedule {
      attempts = 0
      unlimited = false
    }
    restart {
      attempts = 3
      interval = "15m"
      delay    = "15s"
    }
    update {
      //Use FORCED updates
      //https://www.nomadproject.io/docs/job-specification/update.html#max_parallel-0
      max_parallel = 0
    }
    migrate {
      max_parallel = 1
      health_check = "task_states"
      min_healthy_time = "15s"
      healthy_deadline = "30m"
    }
    task "task" {
      driver = "..."
      kill_timeout = "30m"
    }
  }
}
```

Given those jobs:
If I migrate the Batch one, it 'Complete' since rescheduling is disabled.
But, the Service one, will still be rescheduled, even though rescheduling is disabled, because (I assume) the scheduler is aware of the migration, and the new allocation is not counted, unlike the batch in the scheduler.

So, I am wondering if Batch jobs can be configured to have this same behavior. If not, and I am forced to use the Service scheduler, would I just have to tell nomad to stop the job when it successfully exits (0 exit code)?

Thank you!

**Comment by tgross** [comment]
So you're asking if there's a way to allow a batch job to be migrated (moved to another node on node drain) but not rescheduled? Keep in mind that the reason the batch job isn't being migrated is because Nomad is actually waiting for it to finish before considering the node drain complete.

I think you can demonstrate the behavior you're looking for if the `node drain -deadline` is less than the expected length of time it takes to complete the job. Let's try this using the jobspec below. This should work on any cluster with 2 or more client nodes.

```hcl
job "flow" {
  datacenters = ["dc1"]
  type        = "batch"

  group "flow" {
    reschedule {
      attempts  = 0
      unlimited = false
    }

    restart {
      attempts = 3
      interval = "15m"
      delay    = "15s"
    }

    task "task" {
      driver       = "docker"
      kill_timeout = "10s"

      config {
        image   = "busybox:1"
        command = "sleep"
        args    = ["180"]
      }
    }
  }
}
```


## Scenario 1

In the first scenario, we don't set a drain deadline, which means we default to a 1 hour deadline. In this case, we'd expect Nomad to wait until the task has completed (180s), which we can see in the output below it does. Because it's finished, it doesn't get migrated -- there's nothing left for the task to do!

```
▶ nomad job status flow
...
Allocations
ID        Node ID   Task Group  Version  Desired  Status   Created  Modified
7931e706  b9d92d04  flow        0        run      running  8s ago   7s ago

▶ nomad node drain -enable -yes b9d92d0
2019-11-20T15:23:56-05:00: Ctrl-C to stop monitoring: will not cancel the node drain
2019-11-20T15:23:56-05:00: Node "b9d92d04-d80f-dc6f-60bc-bd843eeba108" drain strategy set
2019-11-20T15:26:34-05:00: Alloc "7931e706-66d5-d5b1-0ac2-e362acce603e" status running -> complete
2019-11-20T15:26:34-05:00: All allocations on node "b9d92d04-d80f-dc6f-60bc-bd843eeba108" have stopped
2019-11-20T15:26:34-05:00: Drain complete for node b9d92d04-d80f-dc6f-60bc-bd843eeba108

▶ nomad job status flow
...
Allocations
ID        Node ID   Task Group  Version  Desired  Status    Created    Modified
7931e706  b9d92d04  flow        0        run      complete  3m53s ago  52s ago

# clean up after ourselves!
▶ nomad node drain -disable -yes b9d92d0
```


## Scenario 2

In the first scenario, we do set a drain deadline, and that deadline is less than the 180s that the job takes to complete. So in this case Nomad waits until the drain deadline (1m) and then migrates the task.

```
▶ nomad job status flow
...
Allocations
ID        Node ID   Task Group  Version  Desired  Status    Created    Modified
88673096  f1fa13ef  flow        1        run      running   38s ago    36s ago
7931e706  b9d92d04  flow        0        run      complete  5m57s ago  2m56s ago

▶ nomad node drain -deadline 1m -enable f1fa13ef
Are you sure you want to enable drain mode for node "f1fa13ef-f4a8-4944-7d56-82a63c9c372a"? [y/N] y
2019-11-20T15:29:16-05:00: Ctrl-C to stop monitoring: will not cancel the node drain
2019-11-20T15:29:16-05:00: Node "f1fa13ef-f4a8-4944-7d56-82a63c9c372a" drain strategy set
2019-11-20T15:30:17-05:00: Alloc "88673096-fda6-c217-b010-5d17cea0d11a" marked for migration
2019-11-20T15:30:17-05:00: Drain complete for node f1fa13ef-f4a8-4944-7d56-82a63c9c372a
2019-11-20T15:30:17-05:00: Alloc "88673096-fda6-c217-b010-5d17cea0d11a" draining
2019-11-20T15:30:28-05:00: Alloc "88673096-fda6-c217-b010-5d17cea0d11a" status running -> complete
2019-11-20T15:30:28-05:00: All allocations on node "f1fa13ef-f4a8-4944-7d56-82a63c9c372a" have stopped
```

If you take a look at the job status when the drain is at "marked for migration", you'll see:

```
▶ nomad job status flow
...
Allocations
ID        Node ID   Task Group  Version  Desired  Status    Created    Modified
f048fc55  b9d92d04  flow        1        run      pending   1s ago     1s ago
88673096  f1fa13ef  flow        1        stop     running   1m27s ago  1s ago
7931e706  b9d92d04  flow        0        run      complete  6m46s ago  3m45s ago
```

And then once the drain is done:
```
▶ nomad job status flow
...
Allocations
ID        Node ID   Task Group  Version  Desired  Status    Created    Modified
f048fc55  b9d92d04  flow        1        run      running   13s ago    2s ago
88673096  f1fa13ef  flow        1        stop     complete  1m39s ago  3s ago
7931e706  b9d92d04  flow        0        run      complete  6m58s ago  3m57s ago
```

**Comment by Brainfree** [comment]
I use force draining (--force) so nomad sends the STOP signal to them, where they given 30m to stop (kill_timeout = 30m). Otherwise, these jobs would never stop, as they will run forever, unless singled they should stop, where they are designed to stop, and be resumed later on.

What you are showing me, seems to be what I desire! 
For me, batch jobs were getting getting rescheduled due to migration, but when I made them a service, they did not. I'll look again, this could be explained if they were crashing when started on the new node, but it'll be quite strange why they would stop crashing due to being a service job.
