### ISSUE TITLE
Unable to load docker image from persistent volume

### ISSUE THREAD

**Issue by evheny0** [hashicorp/nomad#6846]
[question]

### Nomad version
Nomad v0.10.2 (0d2d6e3dc5a171c21f8f31fa117c8a765eb4fc02)

### Operating system and Environment details
Ubuntu 18.04.3 LTS

### Issue

I'm trying to load an image from host machine: I've put `image.tar` file into mounted persistent volume and trying to use it in `docker` driver, but it's still trying to load it from `/local`. Is there any way to load an image from host that I'm missing? Seem like currently there is no way to do this even with mounted volumes.

### Reproduction steps

See Job file

### Job file

```
job "job" {
  datacenters = ["dc1"]
  type = "service"

  group "group" {
    volume "builds" {
      type      = "host"
      read_only = false
      source    = "builds"
    }

    task "task" {
      driver = "docker"

      volume_mount {
        volume      = "builds"
        destination = "/builds"
        read_only   = false
      }

      config {
        load = "/builds/image.tar"
        image = "image"
      }
    }
  }
}
```

### Nomad Client logs
```
unable to open image archive: open /opt/nomad/data/alloc/c1c60208-6d92-07a9-04cf-83a8e51ed9be/task/local/builds/image.tar: no such file or directory
```

**Comment by tgross** [comment]
hi @evheny0! Thanks for opening this issue!

There's a bit of a chicken-and-the-egg going on here with this jobspec because of the way the filesystem for the container is created. Nomad creates the task directory first, so that it can download artifacts. But we can't mount the docker volume until after the container is created (but before it's started) because there's nothing to mount it to. But of course the container can't be created without the contents of the volume in your jobspec.

So creating a container from an image stored in a volume isn't going to work. You'll need to either run a Docker registry or use the `artifact` stanza to get the image and run an HTTP server to serve up the image file (or get it from object storage). If you have a well-known location of images on the node, you might even run a HTTP server for those images as a Nomad `system` job, using `host` networking.

**Comment by evheny0** [comment]
@tgross thank you for answer! Your options seems reasonable.
From documentation it seemed that `volume_mount` should work kinda like task's directory and described behavior seemed a bit not obvious, so I've created an issue in case there is some way to make it work.
Thanks!
