### ISSUE TITLE
Improve documentation for bridge stanza 

### ISSUE THREAD

**Issue by preetapan** [hashicorp/nomad#6873]
We need to make our docs around CNI clearer. It should describe specific use cases like when to use the Nomad bridge (CNI) vs docker's bridge network.

**Comment by jfcantu** [comment]
One thing I'd suggest for the documentation update: make it very clear that Docker's `bridge` mode and Nomad's `bridge` mode are completely different.

In my case, I just discovered that if a task is configured for Nomad `bridge` mode, and also configured for Docker `bridge` mode, Docker will take over from CNI and your task will end up attached to Docker's default `bridge` network rather than a namespace scoped to a Nomad group or task.

(Which, among other things, will prevent Consul Connect from working because `127.0.0.1` becomes container-specific and now your service can't use it to reach the sidecar proxy.)

**Comment by schmichael** [comment]
We should do this as part of #8575
