### ISSUE TITLE
Old bootstrap token not deleted when resetting the Bootstrap token

### ISSUE THREAD

**Issue by manish-panwar** [hashicorp/nomad#6937]
### Nomad version
Nomad v0.10.2

### Operating system and Environment details
PhotonOS

### Issue
When I `reset` the Bootstrap token, I could still see the old bootstrap tokens when I fetch them via REST API(`/v1/acl/tokens`). In fact I was still able to use the older bootstrap token. I am wondering if it's by design, and if yes, then why? `reset`  meaning I am throwing away existing Bootstrap token and replacing it with a new one.

### Reproduction steps

1 - Setup ACL and create Bootstrap token based on instructions [here](https://www.nomadproject.io/guides/security/acl.html)
2 - Validate that you are able to use the Bootstrap token to query various data from Nomad via REST API.
3 - Reset the Boostrap token by following the instructions from [here](https://www.nomadproject.io/guides/security/acl.html) (look under `Resetting ACL Bootstrap` section)
4 - I am successfully able to `reset` the Bootstrap token but I still see the older Bootstrap tokens when I query the [Token API](http://localhost:4646/v1/acl/tokens). I was also able to use the old Bootstrap token to make any API calls.

**Comment by notnoop** [comment]
Thanks for reporting @manish-panwar .  I agree that this is confusing indeed and we should address it.

It's by design.  Currently, we don't automatically invalidate previous tokens, including the earlier bootstrap token; the tokens remain active in case the bootstrap token is being used elsewhere in the system (just not immediately available to operator).

The `reset` terminology is confused here and refers to the bootstrap state of the nomad cluster, rather than to the bootstrap token specifically.

That being said, I agree that it is confusing and unexpected.  We'll follow up with documentation fixes to call this issue out, as well as consider revamping that function to have more intuitive as well as more flexible (e.g. a flag to invalidate earlier bootstrap token).
