### ISSUE TITLE
[question] how to 'drain' a container pre-termination

### ISSUE THREAD

**Issue by far-blue** [hashicorp/nomad#6955]
I have some services with multiple instances load-balanced by Fabio where requests can take a few seconds to complete and I'd like to be able to drain instances before terminating the container on upgrade or planned node migration (e.g. on draining a Nomad node).

My thinking is that if the service record for the instance is removed then Fabio will naturally stop sending new requests to an instance and so I just need to wait a few seconds before terminating the container.

does anyone know at what point a Consul service record for a container is deregistered during container shutdown? And is there any way I can get Nomad to delay terminating a container for a few seconds after the service is deregistered? Or is the recommended / only approach to catch the termination signal and wait a few seconds inside the container itself before terminating?

Thanks!

**Comment by tgross** [comment]
Hi @far-blue! There's a couple parts to this answer:

Nomad doesn't currently provide any sort of "drain this task before shutdown" because it's not aware of what workload an application is running (ex. is this HTTP or batch?). We do have some lifecycle hooks work underway that might help with this but as I understand it the first lifecycle hook to land will be "pre-start". That being said, when Nomad stops a task, it sends `SIGINT` to the task container, which you can handle in the task to wrap up work before shutting down gracefully (the Docker task driver will give you a short grace period before `SIGKILL`'ing... I think it's 10s by default?).

From the load balancer side, the problem should already be handled by Fabio. Take a look at the docs for [dynamic reloading](https://fabiolb.net/feature/dynamic-reloading/):

> Once the new routing table has been built it is atomically swapped with the active routing table without any service interruption. Existing connections remain open and running requests are served even if the new routing table no longer contains that route.

**Comment by far-blue** [comment]
Thanks for the info @tgross :)

So is the service deregistered in Consul by Nomad before the SIGINT is sent to the container or after the container is confirmed as terminated? I'm aware of how Fabio handles changes to services but, of course, there's no benefit in adding a wait in the container on receiving a SIGINT if the service hasn't been deregistered and Fabio is still actively routing new connections to it :)

**Comment by tgross** [comment]
The service is deregistered during the ["prekilling" step](https://github.com/hashicorp/nomad/blob/6c3a29a877b55572dd91a0adbf0a004784589e41/client/allocrunner/taskrunner/service_hook.go#L150-L168). So the signal is sent afterwards. In addition, the signal itself is async. You can see this demonstrated but running the job below and then shutting the job done while watching your Consul web UI and `docker ps`.

`example.sh` workload:
```bash
#!/bin/bash

trap graceful SIGTERM SIGINT

graceful() {
    echo "gracefully shutting down..."
    sleep 5
    echo "shutting down now!"
    exit 0
}

echo "starting!"
sleep 600
```

jobspec:
```hcl
job "example" {
  datacenters = ["dc1"]

  group "sleeper" {
    task "sleepy" {
      driver = "docker"

      config {
        image = "debian:buster"
        command = "/bin/bash"
        args = ["/example.sh"]
        volumes = [
          "/home/vagrant/example.sh:/example.sh",
        ]

        port_map {
          db = 6379
        }
      }

      service {
        name = "example"
        port = "db"
      }

      resources {
        cpu    = 500
        memory = 256

        network {
          mbits = 10
          port  "db"  {}
        }
      }
    }
  }
}
```

**Comment by far-blue** [comment]
Great, thanks :) And looking at the code you linked to I can see deregister happens before the task's shutdown_delay is respected so if I set a non-zero shutdown_delay on the task then I won't need to add a delay to handling the SIGINT in the container :)
