### ISSUE TITLE
Docker Driver Static Port Mapping fails to forward traffic

### ISSUE THREAD

**Issue by ghost** [hashicorp/nomad#6986]
Nomad fails to forward traffic into docker container when I use the following config block on task level:

```
			resources {
				network {
					mode = "bridge"
					port "http" {
						static = 3180
                                                to = 80
					}
                                       ...
				}
                                ...
                        }
```

However, everything works fine if I use `port_map`:

```
			config {
				port_map {
					http = 80
				}
			}
                        ...
			resources {
				network {
					mode = "bridge"
					port "http" {
						static = 3180
					}
                                       ...
				}
                                ...
                        }
```

**Comment by tgross** [comment]
Doing some issue cleanup around networking. Unfortunately the issue here is a straightforward bad jobspec and I wish we'd managed to look at it before the user's GitHub account was [ghosted](https://github.com/ghost). The `resources` block is not where the new networking configuration goes, so no routing would take place. This is all warned against in more recent versions of Nomad, so I'm going to close this out.
