### ISSUE TITLE
Change of inline template should be treated the same as change of rendered template

### ISSUE THREAD

**Issue by kshpytsya** [hashicorp/nomad#7189]
### Nomad version
Nomad v0.10.1 (0d4e5d949fe073c47a947ea36bfef31a3c49224f)

### Operating system and Environment details
Ubuntu 18.04.3 LTS

### Reproduction steps

- Register the attached job by doing `nomad job run - < jobfile`
- In Nomad UI, observe the following log for the task:
```
Signal USR1 received, data=one-default
Started, data=one-default
```
- Add `somekey` to consul, observe the following line appear in the task log:
```
Signal USR1 received, data=one-somekeyvalue
```
- Replace `data = "one` with `data = "two` in job file and re-register it by doing `nomad job run - < jobfile` again
- Observe a new allocation being made.

Result that I expect instead is seeing

```
Signal USR1 received, data=two-somekeyvalue
```
in existing allocation, just as in case of change of template rendition.

I understand that there may be technical reasons for current behavior but from the end-user POV the difference between these two cases doesn't seem to make sense.

### Job file

```
job "nomad-template-issue" {
  datacenters = ["dc1"]

  group "group1" {
    count = 1

    task "task1" {
      driver = "docker"
      config {
        image = "alpine:3.11.3"
        entrypoint = ["/bin/sh"]
        args = [ "${NOMAD_TASK_DIR}/script.sh" ]
      }

      resources {
        cpu    = 100
        memory = 16
      }

      template {
        destination = "local/script.sh"
        data = <<_END_
# trap 'echo "Signal USR1 received"' USR1
trap 'echo "Signal USR1 received, data=$(cat $NOMAD_TASK_DIR/data)"' USR1
kill -USR1 $$
echo Started, data=$(cat $NOMAD_TASK_DIR/data)
while true; do sleep 1; done
_END_
      }

      template {
        destination = "local/data"
        left_delimiter = "(("
        right_delimiter = "))"
        data = "one-((keyOrDefault \"somekey\" \"default\"))"
        change_mode = "signal"
        change_signal = "SIGUSR1"
      }
    }
  }
}
```

**Comment by shoenig** [comment]
Hey @kshpytsya thanks for taking the time to report this, especially with steps to reproduce!
The key observation is that in the first example, the nomad task definition itself is not being updated. Since the `change_mode` behavior is intended to apply to the template being rendered in a running allocation, the signal is passed along and things are fine. In the second case, the modified task configuration triggers a general rule that if a task definition is modified, that will cause a new allocation to be formed so the task can be re-launched using the new config.
Although in this particular example it would be conceivable to avoid re-launching the task, figuring out how to "partial-pre-render" the template at job submission time to detect this optimization is a layer of complexity I don't think we want to get ourselves into at this time.
Please feel free to re-open if I'm missing something, or if you've got more thoughts!
