### ISSUE TITLE
Firewall allow rule for Nomad on MacOS

### ISSUE THREAD

**Issue by alexboboc** [hashicorp/nomad#7228]
### Nomad version
Nomad v0.10.4 (f750636ca68e17dcd2445c1ab9c5a34f9ac69345)

### Operating system and Environment details
MacOS Catalina, with Nomad living at `/usr/local/bin/nomad`

### Issue
I am running an extremely basic Nomad server that literally uses all defaults. I want to enable MacOS's application firewall and only allow inbound traffic to my machine through SSH and Nomad's ports.

In MacOS, my configuration looks as follows:

![image](https://user-images.githubusercontent.com/1878922/75326927-5cfd4c80-5830-11ea-8bb2-825cd777e388.png)

However, I am not able to reach the UI on port 4646 from other machines in the network. If I disable the application firewall, it becomes accessible. Running `lsof -i tcp:4646` reveals that the `nomad` process does own port 4646 as expected. 

Is there something I'm not considering? Is the HTTP server run by a different process?

**Comment by shoenig** [comment]
Hey @alexboboc, sorry you're having trouble with this, but questions like this might be best asked on OS-specific help forums. To answer your Nomad questions, a nomad agent is a single process, and if port 4646 is open the UI should be accessible (as is the case when your firewall is disabled).
Just a thought - I know the homebrew folks went through months of effort in tweaking packages in preparation for Catalina, since newer versions of macOS do "interesting" things around the OS parts of the filesystem. It might be worth trying to run the nomad process from a user owned part of the filesystem and opening the firewall for that instead, on the chance that perhaps macOS is just blocking anything under `/usr`, for example.
