### ISSUE TITLE
[suggestion] docker exec flag -it for convencience 

### ISSUE THREAD

**Issue by rkno82** [hashicorp/nomad#7243]
### Nomad version
0.10.4

### Issue
I want to suggest that many users would like to have a flag -it to combine the option -i and -t. This is a very often used command to get into the container and it differs to docker and kubernetes.

### Reproduction steps
```
nomad exec -it <alloc> bash
flag provided but not defined: -it
Usage: nomad alloc exec [options] <allocation> <command>

  Run command inside the environment of the given allocation and task.

General Options:
...
Exec Specific Options:
..
  -i
    Pass stdin to the container, defaults to true.  Pass -i=false to disable.

  -t
    Allocate a pseudo-tty, defaults to true if stdin is detected to be a tty session.
    Pass -t=false to disable explicitly.
...
```

What do you think?

**Comment by cricket007** [comment]
Isn't this just a bash thing? For example `curl -f -s -L` is the same as `curl -fsL`

**Comment by tgross** [comment]
Fortunately for @rkno82's specific issue, there's no need to pass the `-i` or `-t` flag unless you want to disable them; these flags defaults are inverted from how Docker and Kubernetes define them. When you're doing a remote exec you almost always want the tty. So just leave the flags off! 😀 

```
▶ nomad alloc exec --help
Usage: nomad alloc exec [options] <allocation> <command>

...

Exec Specific Options:

...

  -i
    Pass stdin to the container, defaults to true.  Pass -i=false to disable.

  -t
    Allocate a pseudo-tty, defaults to true if stdin is detected to be a tty session.
    Pass -t=false to disable explicitly.

...
```

@cricket007 wrote:
> Isn't this just a bash thing? 

As it turns out, flag parsing is defined by the application (or more likely, the stdlib it's using). Most applications end up using GNU libc style flag parsing where you have single-dash for short (`-i`, `-t`) and double-dash for long (`--interactive`, `--tty`) options and can combine short options (`-it`). The ubiquitousness of this style is nice because it makes for a common syntax for CLI applications. So much so that'd be easy to think it was built into the shell! 😀 

The golang stdlib's `flag` package does plan9-style flag parsing where a single dash is the beginning of a flag of any length. We could work around this in Nomad by explicitly defining a `-it` and `-ti` flag, but you can see how that'd get cumbersome quickly. I think there are some third-party flag packages we could use to improve upon this, but it'd create some backwards compatibility issues with other people's existing scripts and create behavior differences between Nomad and Consul/Vault... so we'd need to spend some time examining the impact.

**Comment by rkno82** [comment]
Thanks @tgross . Sometimes it's easy.
