### ISSUE TITLE
reschedule job very low when Nomad Leader offline

### ISSUE THREAD

**Issue by Bingqiang-Jing** [hashicorp/nomad#7645]
### Nomad version
v0.10.3

### Operating system and Environment details
Windows

### Issue
I prepare three Windows PC, A is Nomad Server Leader, B and C is Nomad Server Follower, and A & B & C also is Nomad Client.

My job only include a simple task to run notepad.exe software, assume job running in Nomad Server Leader A, I test found reschedule job to Nomad Client B or C and start task very slow when A offline, about 5 minutes. but reschedule and start very quick (8 seconds) when job running in non-Leader node, for example from B reschedule to A or C.

Please everyone help, Thanks!

### nomad config file summary

```
server {
    enabled = true
    bootstrap_expect = 3
    min_heartbeat_ttl = "2s"
}

client {
    enabled = true
    meta {
        "priority"="1"
        "ability"="Stitch"
    }
}
```

**Comment by notnoop** [comment]
Hi @Bingqiang-Jing .  Thanks - this is somewhat expected behavior due to internal node tracking and management in Nomad.  Generally, we discourage colocating servers and clients on the same hosts.

As for technical details, leadership transitions are expensive and it can take awhile for the new leader to be established and new server configuration to make it the nomad clients.  As such, upon establishment, the new leader waits for 5m by default[1][2] before declaring any client dead and rescheduling their work.  So if a nomad node is both the leader server and a client running load, when it dies, other servers may take around 5minutes or more before rescheduling its work.

Hope that helps!

[1] https://github.com/hashicorp/nomad/blob/v0.10.5/nomad/config.go#L241-L244
[2] https://github.com/hashicorp/nomad/blob/v0.10.5/nomad/config.go#L386

**Comment by Bingqiang-Jing** [comment]
> Hi @Bingqiang-Jing . Thanks - this is somewhat expected behavior due to internal node tracking and management in Nomad. Generally, we discourage colocating servers and clients on the same hosts.
> 
> As for technical details, leadership transitions are expensive and it can take awhile for the new leader to be established and new server configuration to make it the nomad clients. As such, upon establishment, the new leader waits for 5m by default[1][2] before declaring any client dead and rescheduling their work. So if a nomad node is both the leader server and a client running load, when it dies, other servers may take around 5minutes or more before rescheduling its work.
> 
> Hope that helps!
> 
> [1] https://github.com/hashicorp/nomad/blob/v0.10.5/nomad/config.go#L241-L244
> [2] https://github.com/hashicorp/nomad/blob/v0.10.5/nomad/config.go#L386

Hi @notnoop, thanks for your reply, i got it
