### ISSUE TITLE
NVIDIA_VISIBLE_DEVICES has wrong content.

### ISSUE THREAD

**Issue by maaft** [hashicorp/nomad#7649]
When a job is started with a GPU device, NVIDIA_VISIBLE_DEVICES contains the fingerprint of the device, e.g. GPU-f894b4bf-479f-4d01-2adb-ef221aaf7a63.

This is pretty much useless, as nvidia related stuff will still see ALL GPUs inside the container.

AFAIK NVIDIA_VISIBLE_DEVICES must be set to the Device Index, e.g. {0,1,2,3, ... }

**Comment by tgross** [comment]
Hi @maaft! It suspect we were mirroring the what the Nvidia docker runtime was doing (but maybe @cgbaker can confirm that for me), where it looks like the value can be the index or the ID: https://github.com/nvidia/nvidia-container-runtime#nvidia_visible_devices

**Comment by maaft** [comment]
I did a little bit more research and in fact it works as expected when executing, e.g.:
```bash
docker run --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=GPU-4a2b334a-49bd-6fd9-fd9d-cf9d6bdfed11 nvidia/cuda:10.0-base nvidia-smi
```
nvidia-smi correctly prints only one GPU.

But somehow when started with nomad, the environment-variable seems to be ignored from docker.

How can I see the actual docker command that nomad executes?

**Comment by tgross** [comment]
Let's back up a little bit. We should be setting `NVIDIA_VISIBLE_DEVICES` based on the fingerprinted GPU(s). There may be multiple GPUs unless you've used [`ignored_gpu_ids`](https://nomadproject.io/docs/devices/nvidia/#ignored_gpu_ids) to restrict that.

So is the problem that you're seeing more GPUs in the container's `NVIDIA_VISIBLE_DEVICES` environment variable than you'd expect, or that you're seeing only one as expected but that the container's application is seeing all of them?

**Comment by maaft** [comment]
`NVIDIA_VISIBLE_DEVICES` is correctly set with one UUID.

When I execute e.g. `nvidia-smi` inside the container, I see all GPUs of my system, which I don't expect.

**Comment by maaft** [comment]
For debugging this I wrote this simple job spec:
```json
job "test" {
  datacenters = ["dc1"]
  group "asdasd" {
    task "fasfasfs" {
      driver = "docker"
      resources {
        device "nvidia/gpu" {
          count = 1
        }
      }
      config {
        image   = "nvidia/cuda:10.0-base"
        command = "top"
      } # config
    } # task run
  } # group
} # job
```

Unfortunately the Job just dies with `Exit Code: 1, Exit Message: "Docker container exited with non-zero exit code: 1"`. Could you help me with this? Where can I access more verbose logs of nomad? STDOUT and STDERR show nothing.

I added `command = "top"` such that the container keeps running. Maybe this is somehow wrong?

**Comment by tgross** [comment]
> I added command = "top" such that the container keeps running. Maybe this is somehow wrong?

That's because `top` is expecting a tty, which Nomad doesn't provide because it doesn't support interactive jobs. Try something like: 

```hcl
job "test" {
  datacenters = ["dc1"]
  group "asdasd" {
    task "fasfasfs" {
      driver = "docker"
      resources {
        device "nvidia/gpu" {
          count = 1
        }
      }
      config {
        image   = "nvidia/cuda:10.0-base"
        command = "sleep"
        args = ["10000"]
      } # config
    } # task run
  } # group
} # job
```

And then use `nomad alloc exec :alloc_id /bin/sh` to shell into the container to debug it in more detail. Or you could pass `command = "nvidia-smi"` directly and that'll show up in the alloc logs after it exits as in the example here: https://nomadproject.io/docs/devices/nvidia/#examples

**Comment by maaft** [comment]
Okay, thank you so far. I was able to find out that the unexpected behavior occurs when using the `privileged = true` flag.

```
job "test" {
  datacenters = ["dc1"]
  group "asdasd" {
    task "fasfasfs" {
      driver = "docker"
      resources {
        device "nvidia/gpu" {
          count = 1
        }
      }
      config {
        image   = "nvidia/cuda:10.0-base"
        command = "sleep"
        args = ["10000"]
        privileged = true
      } # config
    } # task run
  } # group
} # job
```

Or is this behavior expected?

**Comment by maaft** [comment]
From the Nomad Docs I see that `privileged = true` gives access to all devices on the host. Therefore, the container has also access to all GPUs.

I think I needed the flag to have access to `/dev/fuse`. But still I only want to see a single GPU when I have specified that the container only needs 1 GPU.

So from my point of view the expected behavior of `privileged` would be to give access to all devices *except* devices that are limited by the resource constraints.

Any thoughts?

**Comment by tgross** [comment]
> Okay, thank you so far. I was able to find out that the unexpected behavior occurs when using the `privileged = true` flag.

Ah! Yes, that totally makes sense. Running a Docker task with the `privileged` flag gives it wide-open privileges. If you really need a task to have more rights than default, I would recommend looking at using the [finer-grained permissions](https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities) described in the Docker docs, which you can toggle with Nomad jobspec flags like [`cap_add`](https://nomadproject.io/docs/drivers/docker/#cap_add), [`cap_drop`](https://nomadproject.io/docs/drivers/docker/#cap_drop), and [`security_opt`](https://nomadproject.io/docs/drivers/docker/#security_opt).

> I think I needed the flag to have access to `/dev/fuse`.

Interesting... I've been doing a lot of work on storage (like the new CSI feature), so I'd love to hear more about this use case. Is it something you could solve with [host volumes](https://nomadproject.io/docs/configuration/client/#host_volume-stanza)? Or maybe mounting it as a Docker volume?

The Docker docs I linked above say:
> To mount a FUSE based filesystem, you need to combine both `--cap-add` and `--device`

And have the example:
```
$ docker run --rm -it --cap-add SYS_ADMIN --device /dev/fuse sshfs
```

> So from my point of view the expected behavior of `privileged` would be to give access to all devices except devices that are limited by the resource constraints.

That makes sense to me.

But for task driver configuration, everything inside the `config` block is validated for structure but otherwise passed directly to the task driver's runtime. So `privileged` is implemented by Docker itself and not Nomad and not something we have control over. (This also means we don't currently have a way of implementing `privileged` for `exec` tasks, which is something I've been looking at separately.)
