### ISSUE TITLE
Question about consul heathcheck

### ISSUE THREAD

**Issue by mkabischev** [hashicorp/nomad#774]
I\`m testing nomad now and have a question about consul integration. I started 4 instances of same job. I see all of them in consul api/ui and it\`s very cool. But if i kill manually one of running containers this service removes from consul. And in this situation i can\`t detect that one of services is down. 
Of course i\`ve got restart policy and killed service starts again, but there is a time period then i have a problem but i can`t detect it. Is it ok? Or I missed something in configuration?

**Comment by mkabischev** [comment]
The same situation happens if i stop the whole node. All services are removed from consul.

**Comment by mkabischev** [comment]
I think nomad should really deregister service only when it reaches dead state. I`ll do some tests and create PR if everything will be ok.

**Comment by diptanu** [comment]
@mkabischev So the issue with not removing a service when the corresponding task is not present is that if you using Consul DNS, it might return you an IP Addr for the service which isn't running anymore and hence is problem for load balancing use cases for example.

If you are expecting a fixed number of services once you run a job, I would suggest using your monitoring system to alert you if the expected number of services are not present. Does this makes sense?

**Comment by mkabischev** [comment]
Hi @diptanu. Thx for your answer. About consul i`m a little bit disagree because in docs it`s written:
```For example, instead of making HTTP API requests to Consul, a host can use the DNS server directly via name lookups like "redis.service.east-aws.consul". This query automatically translates to a lookup of nodes that provide the redis service, are located in the "east-aws" datacenter, and have no failing health checks.```
So in my example DNS API wouldn`t return record about that killed copy of service. But it`s very important that i could find this failed copy by Consul Health API or just by UI.
I`m going to use Consul not only for services running by Nomad/Docker and I want it to be the entrypoint of healthchecking monitoring part. But now i have to implement special logic especially for Nomad services: checks how many allocations must exists, how many of them are running, on which nodes etc. 

So in my point of view if allocation is binded to some node and has desired status "running" Consul record for it must exists.

**Comment by skozin** [comment]
@mkabischev, @diptanu, so Nomad removes the service from Consul once a single instance of the task has failed, even if the task has more alive instances? For example, if I have this job:

zzzhcl
job "test" {
  datacenters = [ "dc1" ]
  group "test" {
    count = 2
    task "test" {
      driver = "docker"
      config {
        image = "nginx"
        port_map {
          http = 80
        }
      }
      service {
        name = "test"
        port = "http"
        check {
          type = "http"
          protocol = "http"
          path = "/"
          interval = "5s"
          timeout = "2s"
        }
      }
      resources {
        network {
          port "http" {}
          mbits = 10
        }
      }
    }
  }
}
```

and I kill one instance of this job, the `test` service will completely disappear from Consul? Is this correct?

**Comment by dadgar** [comment]
@skozin: that is not true. The service will still be registered.

**Comment by mkabischev** [comment]
@dadgar How to reproduce this situation.

I`ve started both consul & nomad.
```
consul agent -dev
```
```
nomad agent -dev
```

Then:
```
nomad init
nomad run example.nomad
```
Now everything is cool, service is running and registered in consul. But when I do `docker kill` then I see in nomad logs:
```
2016/02/10 08:02:13 [INFO] consul: deregistering service cache-redis with consul
    2016/02/10 08:02:13 [ERR] client: failed to complete task 'redis' for alloc '2ea29c27-c7a7-09e8-50a4-302ae7c151ad': Wait returned exit code 137, signal 0, and error Docker container exited with non-zero exit code: 137
    2016/02/10 08:02:13 [INFO] client: Restarting Task: redis
```

And in consul logs:
```
2016/02/10 08:02:13 [INFO] agent: Deregistered service 'nomad-registered-service-247060c4-86fc-f0fa-12a9-f4fa415812b8'
    2016/02/10 08:02:13 [INFO] agent: Deregistered check 'f91f658343f092920eb35db721abd80a41c4123b'
    2016/02/10 08:02:13 [DEBUG] http: Request PUT /v1/agent/service/deregister/nomad-registered-service-247060c4-86fc-f0fa-12a9-f4fa415812b8 (267.343µs) from=127.0.0.1:58776
    2016/02/10 08:02:13 [DEBUG] agent: Service 'consul' in sync
```
It`s not cool at all. Because I can`t see in consul that my service is down.

This happens because of this:
```go
OUTER:
		// Wait for updates
		for {
			select {
			case waitRes = <-r.handle.WaitCh():
				break OUTER
			case update := <-r.updateCh:
				if err := r.handleUpdate(update); err != nil {
					r.logger.Printf("[ERR] client: update to task %q failed: %v", r.task.Name, err)
				}
			case <-r.destroyCh:
				// Avoid destroying twice
				if destroyed {
					continue
				}

				// Send the kill signal, and use the WaitCh to block until complete
				if err := r.handle.Kill(); err != nil {
					r.logger.Printf("[ERR] client: failed to kill task '%s' for alloc '%s': %v", r.task.Name, r.alloc.ID, err)
					destroyErr = err
				}
				destroyed = true
			}
		}

		// De-Register the services belonging to the task from consul
		r.consulService.Deregister(r.task, r.alloc)

		// If the user destroyed the task, we do not attempt to do any restarts.
		if destroyed {
			r.setState(structs.TaskStateDead, structs.NewTaskEvent(structs.TaskKilled).SetKillError(destroyErr))
			return
		}```

For docker it waits for container state change and then de-registers service even if task can be restarted on the same node and while restarting it should be registered in consul, but fails healthchecks.

**Comment by skozin** [comment]
@dadgar, ah, so it would only deregister the failed instance of the service, right?

I partly agree with @mkabischev that this is a questionable approach, at least in the presence of registered Consul health check for that service. Health check would fail and remove the service from DNS replies even without deregistering the service, and the ability to see that certain service has failed is a good thing to have for e.g. alerting.

But question remains what to do when no Consul check is present. Another thing to consider is the latency of health checks. Nomad will probably notice that service has died before Consul.

One solution to these problems would be for Nomad to put the failed instance in [maintenance mode](https://www.consul.io/docs/agent/http/agent.html#agent_service_maintenance), so it would be immediately marked by Consul as unavailable, but will remain registered. Nomad could even provide the optional `?reason` parameter to note that maintenance mode is caused by service failure.

@dadgar @mkabischev what do you think about this approach?

**Comment by diptanu** [comment]
@mkabischev So the reason I am leaning towards de-registering the task which has been terminated and waiting to be re-started is because between restarts nomad sleeps for arbitrary amount of time that within a range that the user specifies. So users using the Consul Service API (and not DNS) would get Addresses of the Tasks which won't exist before that task has been restarted again.

One other reason why we want the Task to be removed from consul during the time we are waiting to restart is, say for some reason Nomad couldn't start the task because some other process(not under the control of Nomad) is hogging the port that the user's process wants to listen to and every time Nomad tries to restart the Task it crashes, users won't know that this is happening if the service is not de-registered and a tcp type check was registered with the Service which in this case would pass because there is a process listening on that port.

Does this makes sense?

**Comment by skozin** [comment]
@diptanu But this can also be solved by putting the service in maintenance mode, right?

**Comment by mkabischev** [comment]
@diptanu, yeah I understood reasons.
But really I don`t like idea that I have to implement complex monitoring logic in case of using nomad + consul. If I have 5 copies of some service running, I need to check nomad if all allocations have running state and additionally check consul for healthchecks. Of course it`s easy to do, but it requires time :) I think I`ll go this way.

@skozin but when we put service in maintenance mode all copies of this service will unavailable, it`s very bad.

**Comment by skozin** [comment]
@mkabischev the [`/v1/agent/service/maintenance/<serviceId>`](https://www.consul.io/docs/agent/http/agent.html#agent_service_maintenance) endpoint accepts service id, which is unique per service instance, so I suppose it would affect only particular instance. But let me check it.

**Comment by skozin** [comment]
@mkabischev, I've checked: like I guessed, it puts into maintenance mode only instance with the specific id, not all instances with matching name:

```sh
$ curl -w'\n' 10.0.42.1:8500/v1/agent/services?pretty
{
    "nginx-1": {
        "ID": "nginx-1",
        "Service": "nginx",
        # ...
    },
    "nginx-2": {
        "ID": "nginx-2",
        "Service": "nginx",
        # ...
    }
}

$ dig +short SRV @10.0.42.1 nginx.service.consul
1 1 8085 controller.node.dc1.consul.
1 1 8087 controller.node.dc1.consul.

$ curl -i -w'\n' -X PUT 10.0.42.1:8500/v1/agent/service/maintenance/nginx-1?enable=true
HTTP/1.1 200 OK
Date: Fri, 12 Feb 2016 20:26:45 GMT
Content-Length: 0
Content-Type: text/plain; charset=utf-8

$ dig +short SRV @10.0.42.1 nginx.service.consul
1 1 8087 controller.node.dc1.consul.
```

So maintenance mode can be used by Nomad instead of deregistering.

**Comment by diptanu** [comment]
@skozin For the reasons that I have stated above, I think we are going to leave the current implementation as is it is, unless there are more reasons to not de-register a service related to a Task when it is not running.

**Comment by skozin** [comment]
@diptanu, your explanation makes total sense, but I fail to understand what's the problem with using maintenance mode instead of deregistering. Maintenance mode has almost the same effect as deregistering:

* it removes the service from DNS responses;
* it makes Consul ignore all registered checks for that service.

So, in both examples you provided, maintenance mode would create no issues compared to deregistering of the service. Please correct me if I'm wrong.

Given this, and the fact that not deregistering the service is valuable for at least some users, I would seriously consider using maintenance mode, as far as there are no other issues with it.

**Comment by ElliotG** [comment]
Super late to this thread, but my team is hitting the same issue. Consul monitoring is not sufficient for real world nomad use cases, and adding additional checks is lame. I am not particular as to which use case, but it feels inadequate that you can't use consul checks for monitoring nomad jobs.
