### ISSUE TITLE
Add client header for UI to fix proxy buffering issues when viewing logs

### ISSUE THREAD

**Issue by pySilver** [hashicorp/nomad#7744]
There are issues with streaming logs when Nomad UI is placed behind proxy (such as fabio). Basically one gets error while trying to access logs:

```
Cannot fetch logs
The logs for this task are inaccessible. Check the condition of the node the allocation is on.
```

so logs **streaming** is not working.

Related issue:
https://github.com/hashicorp/nomad/issues/6409

How to fix:
Looks like its easy and requires JS client to set a proper header:

```
Accept=text/event-stream
```

Ref: https://fabiolb.net/ref/proxy.flushinterval/

**Comment by DingoEatingFuzz** [comment]
Hi @pySilver, the `text/event-stream` encoding would be incorrect for the request the UI makes since log streaming is not performed using SSE (server-sent events).

I would try playing with the [`proxy.globalflushinterval`](https://fabiolb.net/ref/proxy.globalflushinterval/) setting to get similar behavior for general HTTP streaming.

We also [recently published a guide on all the gotchas when reverse-proxying the UI](https://learn.hashicorp.com/nomad/operating-nomad/nginx-reverse-proxy). The example solutions are all for NGINX, but they should be transposable to Fabio.

**Comment by shantanugadgil** [comment]
Any tips for the Nomad servers being configured behind an AWS ALB?

We are seeing this for some users, and not able to isolate the specific combinations under which this manifests.

Wanted to ask here first, before digging for potential workarounds for AWS ALB.
