### ISSUE TITLE
Very high page fault count

### ISSUE THREAD

**Issue by Telavian** [hashicorp/nomad#7908]
### Nomad version
v0.10.0

### Operating system and Environment details
Windows Server 2016
12 core
98 GB

### Issue
After running my service for roughly 12 hours the computer becomes unresponsive and the nomad executable had roughly 1.1 billion page faults according to task manager. The page fault delta seems to get higher over time. At the end the delta itself was almost 500k.
I only thought to check hard faults after I killed nomad.

Killing my service or anything else seems to have no effect.
However after killing all nomad.exe then the server immediately becomes responsive.
taskkill /F /IM nomad.exe

Approximately 30 other minor services on same machine at the time.

This might correspond with #6759 because of page fault count.
However the service itself doesn't log that much.
Roughly 150K lines (30 MB) in that 12 hour window.

### Reproduction steps
With my service I can reliably reproduce this however not sure what the cause is so I can describe my service.

The service itself is roughly a data collector which spawns numerous MS Edge (Chromium) instances. These are constantly created and destroyed as needed.
If nomad doesn't care about spawned processes then this probably doesn't matter.

The service itself is a .Net core executable and is fairly standard in all other respects.

### Job file
(Variables are filled in by a deployer program I created)
```
      driver = "raw_exec"

      config {
        command = ""C:\Consul\_exec_service.cmd""
        args = ["{info.ProjectName}", "${NOMAD_TASK_DIR}\app\{info.ExecutableName}"]
      }
```
_exec_service.cmd

```
netsh advfirewall firewall add rule name="Allow %1" dir=in action=allow program="%2"
%2
netsh advfirewall firewall delete rule name="Allow %1" dir=in
```

### Nomad logs
The node itself is running in a cluster of 5 other nodes as a server and client. 
Is this bad?

These log lines are repeated numerous times:
```
2020-05-08T08:01:56.222-0700 [WARN ] client: error fetching host resource usage stats: error="Class does not exist."
2020-05-08T11:42:58.119-0700 [ERROR] client.gc: error garbage collecting allocations: error="context deadline exceeded"
2020-05-08T11:43:01.120-0700 [WARN ] client: error fetching host resource usage stats: error="context deadline exceeded"
```

**Comment by tgross** [comment]
Hi @Telavian and thanks for reporting this. Ordinarily in a situation where you're running into memory pressure on Nomad, I'd recommend that you use the [`reserved`](https://www.nomadproject.io/docs/configuration/client/#reserved) configuration on the clients to ensure that Nomad itself has enough resources to run itself. But the workload you're using is `raw_exec`, which means that although we can use the resource stanzas to figure out how much to schedule on a given host, the workloads can't actually be resource-constrained.

To verify this I would try to look into how much memory is being used up by the workloads and see if that's causing swapping. Particularly given that this is starting and stopping lots of Chrome instances! I would also recommend using a task driver that can constrain resource usage if at all possible.

> The node itself is running in a cluster of 5 other nodes as a server and client.
> Is this bad?

It's not really recommended to use a node as both server and client. If you're running a high volume of jobs through that could be impacting memory usage.

> client: error fetching host resource usage stats: error="Class does not exist."

I'm not sure where this text is bubbling up from, but we're using https://github.com/shirou/gopsutil as the metrics collector from the hosts. It doesn't appear in that code base either, so it may be something from lower down the stack. We'll need to look into that further.

> client.gc: error garbage collecting allocations: error="context deadline exceeded"

That error is happening because of the previous one. We're hanging trying to collect metrics which times-out the process that's looking at the client host to see if we need to GC an allocation.

**Comment by tgross** [comment]
Also [0.10.4](https://github.com/hashicorp/nomad/blob/master/CHANGELOG.md#0104-february-19-2020) shipped with a bug fix for telemetry that might reduce the amount of stats collection going on in your cluster, and IIRC we upgraded the `gopsutil` dependency for 0.11.0 which might help as well.
