### ISSUE TITLE
[question] ephemeral_disk on pause

### ISSUE THREAD

**Issue by evheny0** [hashicorp/nomad#7998]
Is there any way to "pause" job? I want to stop job's tasks, but but not delete `ephemeral_disk` content, so that after job "restart" `ephemeral_disk` will have it's content.
If not present, this behavior can be useful.

**Comment by tgross** [comment]
@evheny0 if you want the disk space to remain persistent, you might want to look into using either [`host_volume`](https://www.nomadproject.io/docs/configuration/client/#host_volume-stanza) or the [CSI integration](https://www.nomadproject.io/docs/internals/plugins/csi/#csi-plugins).

**Comment by evheny0** [comment]
@tgross it's kinda persistent disk space, but not really. Here is an example:

We have a DB in one of many staging jobs. At some point we want to "pause" the environment - stop the job for a while. And after a while, we want to start staging job again - with all the data that was there. But after real job "stop" we don't need any of DB's data.

`ephemeral_disk` with `migrate` option seems like the best fit for this, it only lacks that ability to migrate data not only on a new deployment, but also on "pause and start".

**Comment by tgross** [comment]
I'm trying unpack the feature request into details, because I think it's something we can do today with the right combination of features if I can understand the use case.

If you're looking to "pause" a job, it sounds like the reasoning there is to give the job's resources back to the cluster? So stopping the job (and therefore its tasks) does that. Then it's a matter of being able to restore the data when the job is recreated.

Where in your use case does the data "go" when it's not in use? Is this a cloud environment where there's an attached disk? Is the data stored on a particular host?

**Comment by evheny0** [comment]
Yes, that's right. And the data is supposed to be stored on some host, on which DB task was working.


In my current implementation (without `ephemeral_disk`) I use NFS for such data storage, so there is no need to migrate data. But NSF is rather slow, so I was looking for a solution that would allow me access data faster.

**Comment by tgross** [comment]
@evheny0 you're probably looking for either a host volume or CSI volume in this case. That'll give you a place to persist the data that doesn't disappear when the job is stopped.
