### ISSUE TITLE
Gossip encryption key started with a forward slash, causing Nomad to fail startup

### ISSUE THREAD

**Issue by robmonte** [hashicorp/nomad#8032]
### Nomad version
v0.10.2

### Operating system and Environment details
CentOS 7

### Issue
Nomad failed to start. The issue seems to be the encryption key that I set.

To generate the encryption key, I did **not** use `nomad operator keygen`. Instead, I used `openssl rand -base64 16`. By chance, this gave me a result with the first character of the sequence being a forward slash '/'.
Specifically, the key begins like so: "/+7VyM"...

### Reproduction steps
Use an encryption key starting with a forward slash '/'

### Nomad Service log
```
Started nomad.
Error loading configuration from /etc/nomad.d: Error loading /etc/nomad.d/nomad.hcl: At 6:11: expected '/' for comment
nomad.service: main process exited, code=exited, status=1/FAILURE
Unit nomad.service entered failed state.
nomad.service failed
```

**Comment by tgross** [comment]
Hi @robmonte! It looks like the config is seeing that slash and the HCL parser is expecting a comment. I wouldn't expect that to happen when quoted, but you might be able to workaround this by escaping the `/` in the config value.

Also, it looks like OpenSSL does its base64 encoding without using the [RFC4648 URL and filename safe alphabet](https://tools.ietf.org/html/rfc4648#section-5), which is somewhat atypical. If you need to use OpenSSL instead of `nomad operator keygen` for some reason, I would recommend piping the output to `base64` (which uses the URL and filename safe alphabet), rather than passing the `-base64` flag to OpenSSL.

**Comment by tgross** [comment]
Going to mark this as both a bug (because we could handle this more gracefully) and a docs fix.

**Comment by robmonte** [comment]
Thanks!
