### ISSUE TITLE
xterm.js: no source [Open Source compliance]

### ISSUE THREAD

**Issue by onlyjob** [hashicorp/nomad#8101]
[ui/vendor/xterm.js](https://github.com/hashicorp/nomad/blob/master/ui/vendor/xterm.js) is a source-less pre-built minified binary. That's not Open Source compliant.

Please provide original uncompressed human-readable sources.

See also https://wiki.debian.org/onlyjob/no-minification

**Comment by DingoEatingFuzz** [comment]
Hi!

A few things going on here.

1. xterm.js is not source-less, it's a very popular open source project: https://github.com/xtermjs/xterm.js/
2. xterm.js is not a binary, it's plain interpreted JavaScript.
3. xterm.js was temporarily vendored in its production state (concatenated and minified) to work around this documented issue: https://github.com/xtermjs/xterm.js/issues/2716
4. xterm.js is now conventionally linked and imported via the ui package.json file since the issue above has been addressed.
5. We will continue to minify our production build artifacts as is customary with the state of frontend web development. Minifying + gzipping is better than gzipping alone. 

All that said, the vendored version of xterm.js should have been removed with https://github.com/hashicorp/nomad/pull/7964 which put us back on the conventional path for requiring xterm.js as a dependency.

**Comment by onlyjob** [comment]
Denial again and a lot of it.  :(

1. You are re-distributing a binary without a source that means that the source tarball is not comprehensive. Downstream in Debian we have to throw away all pre-built binaries because you can't be sure what they are. That's build integrity and Open Source compliance to ship everything with sources (or in the source form).

2. It _is_ a binary (minified code), not human readable and not modifiable by human. Your rhetoric here is silly.

3. This is a problem that prevent upgrading of the official Nomad package in Debian.

4. Are you saying that the problem is fixed? When it is going to be released? Just uncompressing the file would be sufficient.

5. Just don't. What for?? To optimise about a second for a _first_ load??

**Comment by DingoEatingFuzz** [comment]
The vendored code is no longer on `master` and it will no longer be part of the built Nomad binary as of 0.11.3. This means `v0.11.3` will also be the first tag without these files.

As for why we minify production code, I already answered that. You have a history of unsuccessfully demanding projects no longer minify JavaScript and CSS so I feel no need to explain further.

My personal recommendation if you are serious about changing the state of the industry here is to get involved with standards working groups. Maybe start with [W3 Web Performance WG](https://www.w3.org/webperf/) or [W3 Web Apps WG](https://www.w3.org/2019/webapps/).

**Comment by onlyjob** [comment]
> The vendored code is no longer on master and it will no longer be part of the built Nomad binary as of 0.11.3. 

Very good. Thanks.

> As for why we minify production code, I already answered that.

No you did not. You merely said "as is customary with the state of frontend web development" which is hardly a rationale to sustain any practice regardless of whether it is really needed or even beneficial.

Please keep in mind that it may not be a problem for you but it is a practical problem for maintaining your product in Debian.

> You have a history of unsuccessfully demanding projects no longer minify JavaScript and CSS so I feel no need to explain further.

I'm merely calling for common sense and best practice. And if you think it was always unsuccessful then you are not aware of the track records. It is not the issue where "you need to explain further" or not. You just need to _listen_ and try to understand.

I don't see how web standards are related to bad practice of committing pre-built binaries without sources to repository and releasing them in source archives. You have something you can easily improve upon but instead you say "we don't care, we don't have to care as standards don't regulate that". There are many aspect of everyday life that are not regulated by standards.

Anyway, thanks for your comments.
