### ISSUE TITLE
[Meta] Nomad 0.12.0-beta1 Known Issues

### ISSUE THREAD

**Issue by galeep** [hashicorp/nomad#8213]
The purpose of this issue is to aggregate known bugs, alerts and late-breaking news for Nomad 0.12.0-beta1. As the team becomes aware of these items, they will be referenced here.

**Comment by DingoEatingFuzz** [comment]
### UI Known Issues for 0.12.0-beta1

**Scaling Controls #8207**

1. Invalid input should revert the value, not set to min (number input default)
2. Clicking the label of the stepper input should focus the input field
3. When the input field is focused, the value should be highlighted so you don't have to deleting the existing value before providing a new one
4. When the stepper input on the task group page is disabled, it's unclear why (usually due to a running deployment, but this could use an inline explanation via a tooltip)

**Comment by schmichael** [comment]
**Multi-interface networking not implemented for `system` jobs**

#8230

**Comment by tgross** [comment]
Looks like everything here was closed-out. Closing this issue.
