### ISSUE TITLE
CSI can't deregister volume

### ISSUE THREAD

**Issue by anthonymq** [hashicorp/nomad#8285]
I'm having troubles with an amazon efs volume that i deleted before stopping my nomad job who was using it. I can't stop allocations and can't deregister the volume.
![image](https://user-images.githubusercontent.com/1382637/85749124-de92b780-b708-11ea-8642-a36336e076bb.png)
Now I have two allocations that i can't deregister because the clients have been deleted and a volume that has been deleted on aws.

**Comment by anthonymq** [comment]
On another cluster, allocations can't be interrupted. This time the volume is still alive on aws.
<img width="1362" alt="Capture d’écran 2020-06-25 à 18 19 02" src="https://user-images.githubusercontent.com/1382637/85758323-81026900-b710-11ea-99e4-5756d0cac10d.png">
<img width="1362" alt="Capture d’écran 2020-06-25 à 18 20 37" src="https://user-images.githubusercontent.com/1382637/85758409-96779300-b710-11ea-91c9-5c5dab618898.png">
I should only have the first and the last allocations.

**Comment by tgross** [comment]
Hi @anthonymq sorry about this! This is the sort of problem I'm going to give you some tools to solve with https://github.com/hashicorp/nomad/issues/8251 and https://github.com/hashicorp/nomad/issues/8252. 

> On another cluster, allocations can't be interrupted
> The two allocation on version 15 have been stopped on their clients. But the nomad has not refreshed is state.

I can't think of a way that could be related to volumes, but stranger things have happened. I'll see if I can come up with a reproduction. Can you confirm that the command line shows this as well, and that it's not a web UI issue?

**Comment by anthonymq** [comment]
hi @tgross ,
Yes the cli responds the same thing. The volume is attached to multiple expired allocations.

**Comment by tgross** [comment]
Hey @anthonymq we shipped a `nomad volume deregister -force` in 0.12.0 which might help you out here. In the meantime, we're getting ramped up to wrap up these remaining CSI issues over the next couple weeks so hopefully we should have some progress for you.

**Comment by tgross** [comment]
Wanted to give a quick status update. I've landed a handful of PRs that will be released as part of the upcoming 0.12.2 release:

* #8561 retries controller RPCs so that we take advantage of controllers deployed in a HA configuration.
* #8572 #8579 are some improved plumbing that makes volume claim reaping synchronous in common cases, which reduces the number of places where things can go wrong (and makes it easier to reason about).
* #8580 uses that plumbing to drive the volume claim unpublish step from the client, so that in most cases (except when we lose touch with the client) we're running the volume unpublish synchronously as part of allocation shutdown.
* #8605 improves our error handling so that the checkpointing we do will work correctly by ignoring "you already did that" errors.
* #8607 fixes some missing ACLs and Region flags in the Nomad leader

I believe these fixes combined should get us into pretty good shape, and #8584 will give you an escape hatch to manually detach the volume via `nomad volume detach` once that's merged.

**Comment by tgross** [comment]
For sake of our planning, I'm going to close this issue. We'll continue to track progress of this set of problems in https://github.com/hashicorp/nomad/issues/8100.
