### ISSUE TITLE
Deploy services to a percentage of eligible nodes 

### ISSUE THREAD

**Issue by israellot** [hashicorp/nomad#8313]
Allowing to specify the node count as a percentage of eligible nodes instead of only a fixed number would allow a very simple and effective way to scale the deployment when adding or removing nodes from a cluster.

**Comment by notnoop** [comment]
Thank you for the enhancement request.  Mind if you elaborate on the use case more?

We currently aim to support the other direction: Nomad 0.11 introduced [Autoscaler](https://www.hashicorp.com/blog/hashicorp-nomad-autoscaling-tech-preview/) that autoscale services based on demand or user-defined metrics, and we plan to follow up to auto scale number of servers, so that we scale up servers if demand for any service goes up.  With this combination, we lessen the need of operators to manually manage the cluster.

I suspect you can also use the autoscaler to have the service be tracking a fraction of the number of total nodes.

Would that be sufficient in your use case?

**Comment by israellot** [comment]
I have a deployment with several services, each having a load that fluctuates a lot. I would rather look at scaling at a higher distance, looking at the whole cluster load and reduce scaling to add or remove nodes. For my use case, the resource cost of running additional services instances isn't high and I would like to be over provisioned rather than having to react to a spike.
My current solution is running jobs as system rather than services in order to have an allocation per node. I would like to be able to express that in terms of % of available nodes instead. 
I understand that it would probably be possible to achieve a similar outcome with Autoscaler if it moves to support scaling nodes as well. 
The fact though is that nodes can  already be auto scaled by cloud vendors solutions like Azure's Scale Sets, looking at global metrics, so if I'm able to make my handling capacity scale linearly with node count I wouldn't need to plug Autocaler to the infrastructure.

**Comment by mikenomitch** [comment]
After discussing this a bit internally, we don't think this is something we're going to do any time soon because there is a high engineering cost and computation cost when adding/removing nodes, and its probably not worth it.

With a system job and some constraints, you can get pretty close to this behavior in a few ways. One example - say you want something to run on 1/4 of the nodes, you could tag each node with some metadata value between 1 and 4, and then only run the system job on nodes with that value using a constraint. Unfortunately this might involve managing a lot of this by hand.

We'll be adding Dynamic Node Metadata in a future verison of Nomad, which could make tagging nodes easier for this as well.

Going to close this out as we won't solve this directly, but hopefully one of the workarounds is feasible.
