### ISSUE TITLE
Allow health checks to be used without Consul integration

### ISSUE THREAD

**Issue by swisspol** [hashicorp/nomad#8326]
Hi!

Unless I'm missing something obvious, health checks can only be used if you use Nomad with Consul. It would be useful to have this restriction lifted.

Example use cases:

- Use a lightweight Nomad setup with a few services where Consul would be overkilled as its features are just not needed
- Running long-running executables that are not "servers" but you want to make sure are not stuck or hanging

FWIW in k8s, liveness probes are unrelated to services or even exposing ports from the pods.

**Comment by tgross** [comment]
Hi @swisspol! Nomad's "liveness probe" is the task state: https://www.nomadproject.io/docs/job-specification/update#health_check. For anything more sophisticated than that, it's expected you'd use Consul.

**Comment by swisspol** [comment]
Thanks for getting back to me. The “check” stanza is inside the “service” stanza which is used to register with Consul. My observation/ question is that we don’t have Consul around, nor do we need it, so I’m assuming I can’t use just the health checks?

**Comment by tgross** [comment]
> My observation/ question is that we don’t have Consul around, nor do we need it, so I’m assuming I can’t use just the health checks?

Correct. Note that the tcp/http health checks are emitted by Consul and not Nomad (the script checks are not but only because Consul can't reach inside the tasks to execute them).

As a workaround, if you want liveness checks to be performing tcp/http/script checks, I'd recommend baking that into the application container and then having that fail the task state (i.e. exit 1) when it fails. You wouldn't be able to check external connectivity that way, but if that's what you want, then Consul is by far and away a better solution for you.
