### ISSUE TITLE
Can we inherit 'datacenter' attribute from Consul when using automatic clustering?

### ISSUE THREAD

**Issue by ccll** [hashicorp/nomad#8386]
Suppose I have bootstraped a Consul cluster, and intend to automatically bootstrap a Nomad cluster over Consul,
then it's natural to assume the Nomad agent should inherit 'datacenter' from Consul agent on the same node, rather than repeat the same information again in Nomad config file.

**Comment by tgross** [comment]
Hi @ccll! Unfortunately there's a bit of a nomenclature mismatch between Consul and Nomad on this subject.

A Consul datacenter is much more equivalent to a Nomad "region". Nomad can run groups of clients in multiple "datacenters" from the same set of Nomad servers (a single raft group). So for example, you might have:

* Nomad servers in `us-east-1` region.
  * Nomad clients in `us-east-1a` datacenter.
  * Nomad clients in `us-east-1b` datacenter.
* Consul servers in `us-east-1` datacenter.
  * Consul clients in `us-east-1` datacenter (both `us-east-1a` and `us-east-1b` Nomad datacenters!)

If you wanted a 1:1 match between Consul datacenters and Nomad datacenters, you'd need to run multiple Consul clusters, one for each Nomad datacenter within a region. We don't want to impose this topology on operators, so that's why we haven't implemented a feature like this.

**Comment by ccll** [comment]
@tgross Nice to know the differences, thanks!
Closing.

**Comment by martinmcnulty** [comment]
Hi @tgross, sorry to resurrect this old issue, but I wanted to check something before I decide on a production deployment of Nomad/Consul. I found this advice in [the Nomad docs](https://learn.hashicorp.com/tutorials/nomad/clustering#use-consul-to-automatically-cluster-nodes):

> Consul models infrastructures as datacenters and multiple Consul datacenters can be connected over the WAN so that clients can discover nodes in other datacenters. Since Nomad regions can encapsulate many datacenters, you should be running a Consul cluster in every Nomad datacenter and connecting them over the WAN.

That seems to suggest that we _should_ run multiple Consul clusters, one for each Nomad datacenter within a region, which seems to contradict your comment above?

**Comment by tgross** [comment]
> Since Nomad regions can encapsulate many datacenters, you should be running a Consul cluster in every Nomad datacenter and connecting them over the WAN.

No, that's an unfortunate documentation error. This should read: 

> Since Nomad regions can encapsulate many datacenters, you should be running a Consul cluster in every Nomad region and connecting them over the WAN.

**Comment by martinmcnulty** [comment]
Brilliant - thanks for the reply, and noted for next time! :)
