### ISSUE TITLE
allowlist for Docker volume source

### ISSUE THREAD

**Issue by danlsgiga** [hashicorp/nomad#8430]
### Nomad version
Nomad v0.12.0 (8f7fbc8e7b5a4ed0d0209968faf41b238e6d5817)

### Operating system and Environment details
`CentOS Linux release 7.7.1908 (Core)`

```
Client: Docker Engine - Community
 Version:           19.03.7
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        7141c199a2
 Built:             Wed Mar  4 01:24:10 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:45:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
### Issue
Using `mounts` of type `bind` or `volumes` in a docker task fails if pointing to a relative path that depends on `volume_mount` with:

```
failed to create container: API error (400): invalid mount config for type "bind": bind source path does not exist: /opt/nomad/client/data/alloc/fa3bf4e1-3e5e-9ebc-4a73-990b96a17bfe/jenkins/local/efs/jenkins
```

It seems to me that Nomad is trying to execute the bind mounts before the `volume_mount` block is executed.

While using the host path, it works as expected:

```
    ...
    task "jenkins" {
      driver = "docker"
      config {
        load = "jenkins.tar.gz"
        image = "jenkins/jenkins"

        volumes = [
          "/opt/efs/jenkins:/opt/jenkins",
        ]
      }
      ...
```

**Comment by tgross** [comment]
Hi @danlsgiga! Unfortunately I suspect this is a variant of the problem described here: https://github.com/hashicorp/nomad/issues/7796, but can you provide an example of the jobspec that fails so that I can confirm that?

**Comment by danlsgiga** [comment]
Sure, here it goes:

```hcl
job "jenkins" {
  region = "us-east-1"
  datacenters = ["us-east-1"]
  type = "service"

  update {
    max_parallel = 1
    min_healthy_time = "30s"
    healthy_deadline = "5m"
    auto_revert = true
  }

  group "jenkins" {
    count = "1"

    restart {
      attempts = 3
      interval = "2m"
      delay = "25s"
      mode = "delay"
    }

    volume "efs" {
      type      = "host"
      source    = "efs"
    }

    network {
      mode = "bridge"

      port "https" {
        to = 8443
      }
    }

    service {
      name = "jenkins"
      port = "https"
      
      check {
        name = "jenkins"
        type = "script"
        task = "jenkins"
        command = "/bin/curl"
        args = [
          "-I", "http://127.0.0.1:8080"
        ]
        interval = "15s"
        timeout = "5s"
        check_restart {
          limit = 3
          grace = "120s"
        }
      }
    }

    task "jenkins" {
      driver = "docker"
      config {
        load = "jenkins.tar.gz"
        image = "jenkins/jenkins"
        
        mounts = [{
          type = "bind"
          target = "/opt/jenkins"
          source = "local/jenkins"
          readonly = false
          bind_options {
            propagation = "rshared"
          }
        }]
      }

      volume_mount {
        volume      = "efs"
        destination = "/local/jenkins"
      }

      env {
        "CONTAINER_VERSION" = "1.0"
        "S3_BUCKET" = "<THES3BUCKET>"
        "ENVIRONMENT" = "test"
      }

      artifact {
        source = "${S3_BUCKET}.s3.amazonaws.com/files/containers/jenkins-v${CONTAINER_VERSION}.tar.gz"
        destination = "local/jenkins.tar.gz"
        mode = "file"
        options {
          archive = false
        }
      }     
      
      resources {
        cpu = 4000
        memory = 8096
      }
    }
  }
}

```

**Comment by tgross** [comment]
Thanks, that's super helpful! This isn't quite the problem in #7796 I think.

Walking through the code, I'm seeing that the `volume_mount` hook ensures the mount points exist but then is returning a configuration (ref [`client/allocrunner/taskrunner/volume_hook.go#L57`](https://github.com/hashicorp/nomad/blob/v0.12.0/client/allocrunner/taskrunner/volume_hook.go#L57)). That configuration gets passed down to the task driver to decide what to do with that.

In the Docker task driver, Nomad doesn't do any of the mounting itself, but validates the configuration to pass along to Docker. That happens in [`drivers/docker/driver.go#L956-L992`](https://github.com/hashicorp/nomad/blob/v0.12.0/drivers/docker/driver.go#L956-L992).

I suspect I can probably reproduce this behavior with Docker alone... let me take a crack at it and circle back. If so, it may be a case where we need to better-surface the relationship between `volume_mount` and Docker volumes.

(Also, your jobspec is interesting... in this case you're actually relying on the ordering described in #7796 because the artifact where the container image gets loaded from would otherwise get mounted-over by the EFS mount. Something we'll need to think about when we work on #7796)

**Comment by danlsgiga** [comment]
@tgross I don’t think the EFS mount would mount-over the artifact because jenkins.tar.gz is a file where jenkins is a folder with the mount_point... so, AFAIK, they won’t conflict

**Comment by tgross** [comment]
Oh yup, you're right... I missed `archive = false` there and was thinking of the `.tar.gz` getting unpacked. But even that would assume the `.tar.gz` contained the folder `jenkins/`.

Haven't had a chance to see if I can repro with Docker yet.

**Comment by danlsgiga** [comment]
Hey @tgross, any updates on this? My goal is to have `docker.volumes.enabled` set to `false` in my nomad client to avoid any job having access to my host filesystem and bind mounting it. Since `volumes` allow me to bind mount using relative paths from the allocation directory, I tried to use `volume_mount` to mount the host volume inside the task and then bind mount using `volumes` using the relative path.

**Comment by tgross** [comment]
Sorry, I hadn't gotten around to checking my theory on this. Thanks for reminding me to follow-up.

If I map the `mounts` and `volume_mount` configuration exactly to Docker inputs (by creating a job with each of the sections and then checking `docker inspect :id | jq .[0].Mounts` for each one), I can reproduce this without involving Nomad at all. The following script demonstrates the problem with what we're trying to do here:

```bash
#!/bin/bash

set -e

# give us a clean place to work
rm -r ./test-environment
mkdir -p ./test-environment
pushd test-environment

# create the source for the EFS host volume
mkdir -p ./efs

ALLOC_ROOT="$(pwd)/1234/alloc"

# create the allocation and task directories
mkdir -p "${ALLOC_ROOT}/taskname/local"
mkdir -p "${ALLOC_ROOT}/taskname/secrets"

# write our "artifact" to the task directory
touch "${ALLOC_ROOT}/taskname/local/jenkins.tar.gz"

# define the mount flags for the host volume 'volume_mount'
hvmount="type=bind,source=$(pwd)/efs,destination=/local/jenkins"

# define the usual Nomad binds
allocdir="type=bind,destination=/alloc,source=${ALLOC_ROOT}"
taskdir="type=bind,destination=/local,source=${ALLOC_ROOT}/taskname/local"
secretsdir="type=bind,destination=/secrets,source=${ALLOC_ROOT}/taskname/secrets"

# define the mount flags for the Docker 'mounts' config
bmount="type=bind,source=${ALLOC_ROOT}/taskname/local/jenkins,destination=/opt/jenkins"

# Note, this doesn't work
# bmount='type=bind,source=local/jenkins,destination=/opt/jenkins'
#
# The source for the Docker mount is made non-relative by Nomad.
# If we directly copy the config from the jobspec provided, we would get
# the following error:
#
# docker: Error response from daemon: invalid mount config for type
#   "bind": invalid mount path: 'local/jenkins' mount path must be absolute.

docker run --rm -it \
       --mount "$allocdir" \
       --mount "$taskdir" \
       --mount "$secretsdir" \
       --mount "$bmount" \
       --mount "$hvmount" \
       busybox:1 \
       /bin/sh
```

The error response returned is:
```
docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /home/tgross/test-environment/1234/alloc/taskname/local/jenkins.
```

I checked that this isn't an ordering problem -- if we change the order of `--mount` flags passed to Docker, it makes no difference.

All that being said, I'm sorry for not asking you what your original use case was, because now that you've explained that I realize that might have been a for fruitful discussion for you. It looks like what you're really trying to accomplish here is an allow-list of Docker volume locations? If you're using host volumes anyways, why involve Docker `mount` at all, instead of using the host volumes alone?

**Comment by danlsgiga** [comment]
So, the idea is to control volumes available to tasks via the `host_volume` client config only instead of allowing any task to bind mount a path from the host to the task and then disabling `docker.volumes.enabled`.

This way, tasks will only be allowed to mount volumes already exposed by the client and I can bind mount then using relative paths via the `volumes` stanza.

**Comment by tgross** [comment]
I understand that, but if you have host volumes, why not mount the host volume directly, rather than having the additional indirection of the `mount` stanza? Like this:

```hcl
      volume_mount {
        volume      = "efs"
        destination = "/opt/jenkins"
      }
```

**Comment by danlsgiga** [comment]
Ah, because the `host_volume` has 2 folders that need to be mounted in different locations inside the container.

```
volumes = [
          "/opt/efs/jenkins:/opt/jenkins",
          "/opt/efs/nginx:/opt/nginx",
]
```

Where `/opt/efs` is where the `host_volume` is set to. Perhaps I need to change the folder structure in my app to accommodate that. 🤔

**Comment by tgross** [comment]
Using a volume for two different volume_mount points is: https://github.com/hashicorp/nomad/issues/6536

It also seems like there's a feature request hidden here to have a flexible allowlist for Docker volume sources, rather than just a toggle constraining to the allocation's directory like we currently do. That's not supported directly by Docker (otherwise I'd suggest to set the config value there), so we'd have to figure out a way to do that in Nomad's Docker task driver.

In the meantime as a workaround, if you don't want to enable arbitrary Docker mount locations, I'd recommend creating a `host_volume` for each directory you want to mount to the container, rather than trying to split up the volume (which isn't supported).
