### ISSUE TITLE
[question] How does the count argument work in a group?

### ISSUE THREAD

**Issue by dean-n** [hashicorp/nomad#8484]
I was wondering if I could have some clarification on the count argument.

I would like to set up some replicas of some of my microservice apps. 

With the example on the documentation page (below), will 5 instances of a docker container be placed on the same node within a group?

I would like to deploy a docker container with replicas without any node affinity. Is this possible in nomad?

```
A group defines a series of tasks that should be co-located
  on the same client (host). All tasks within a group will be
  placed on the same host.
  group "webs" {
    Specify the number of these tasks we want.
    count = 5

    Create an individual task (unit of work). This particular
    task utilizes a Docker container to front a web application.
    task "frontend" {
      Specify the driver to be "docker". Nomad supports
      multiple drivers.
      driver = "docker"
}
```

### Nomad version
0.9.6

Thanks for reading :)
Dean

**Comment by notnoop** [comment]
Hi @dean-n !  I believe nomad does what you want!  `count` dectates how many replicas will be running in the cluster - In your example, Nomad will ensure that you have 5 services all the time, and will replace any failed ones (e.g. if a host dies).  Nomad will attempt to spread them to minimize disturbance if any host dies; but may run them on the same host because of capacity constraints (e.g. if cluster has < 5 hosts, some hosts will run multiple replicas).

To clarify the comment there, if you specify multiple tasks inside a group, Nomad will ensure that all of these tasks will be running together.  For example, if a task group with count=5 specifies two tasks: nginx and frontend; then Nomad will run 5 allocations (replica in nomad terminology), and each will have an nginx container and a frontend container.

Hope that helps!
