### ISSUE TITLE
Is there any sample for integrating hadoop?

### ISSUE THREAD

**Issue by luxuan** [hashicorp/nomad#853]

**Comment by jshaw86** [comment]
why would you want to put hadoop into another resource negotiator? There is precedent for such a thing in the mesos universe: http://myriad.incubator.apache.org/ but I find there use case arguments not that great, having a mesos manage your resource/node managers just seems dirty and redundant and doesn't ease management of yarn imo.

MRv1 and MRv2 do a fine job scheduling batch jobs. MRv2 can do forever running jobs but it's really trash at it so you should not use MRv2 for long running jobs and just use something like nomad or mesos directly

**Comment by luxuan** [comment]
@jshaw86  We want to deploy the batch jobs and long running jobs with sharing cluster resources.
 The long running jobs all run  in docker in our place, so we are searching for an solution for deploying docker containers and batch jobs, but we find yarn not well support and it may need other more work to to, such as http://tech.hulu.com/blog/2015/08/06/voidbox-docker-on-yarn/ .
Mesos is a good solution, but it seems not support _priority scheduling_ well. So we are considering nomad.
Sorry for my poor English, haha

**Comment by jshaw86** [comment]
@luxuan your english is fine! I don't see a reason why you couldn't run yarn in nomad since they're just java processes, you would need some significant tooling around the yarn configs as you scale up and down node managers etc... you would have to reference the resource managers directly to schedule the batch jobs and then just leverage nomad to run the long running jobs. You maybe able to write a bridge so when you specify batch in nomad it proxies to the resource managers and runs a your MR job, but why not just leverage nomad batch at that point?

**Comment by luxuan** [comment]
@jshaw86  Sorry, It seems that I'm not catch your point about the question. We are looking for a component to manager the all of the resource, which include both batch and long running jobs, for sharing all the resources in the cluster. If the nomad is OK, we need a sample project just like https://github.com/mesos/hadoop/ to integrate nomad, or some documents to explain the way to integrate nomad, because we developer team have little experience in hadoop/yarn and nomad.

**Comment by dadgar** [comment]
Closing this as we have not done any work to integrate the two. Feel free to email the mailing list to see if any community members have had success.
