### ISSUE TITLE
About Python in Docker with random error

### ISSUE THREAD

**Issue by jonatasfreitasv** [hashicorp/nomad#8539]
### Nomad version
Output from `0.12.1` and `0.11.x`

### Job type
Batch with Docker

### Operating system and Environment details
CentOS

### Issue
Is there any chance that nomad will send a command to the docker to finish and cause this error?
My use case is a lot of batch jobs (more then 8k with 11 clients) using Docker with Python code.
This error is random and if I run again, only fail jobs, complete with success.
I test a lot combination of cpu and memory.

### Stacktrace
`[<FrameSummary file main.py, line 56 in <module>>, <FrameSummary file /app/forecast.py, line 30 in make_prediction>, <FrameSummary file /app/tbatsmodel.py, line 97 in tbats_forecast>, <FrameSummary file /opt/conda/envs/env/lib/python3.7/site-packages/tbats/abstract/Estimator.py, line 98 in fit>, <FrameSummary file /opt/conda/envs/env/lib/python3.7/site-packages/tbats/tbats/TBATS.py, line 76 in _do_fit>, <FrameSummary file /opt/conda/envs/env/lib/python3.7/site-packages/tbats/abstract/Estimator.py, line 144 in _choose_model_from_possible_component_settings>, <FrameSummary file /opt/conda/envs/env/lib/python3.7/multiprocessing/pool.py, line 268 in map>, <FrameSummary file /opt/conda/envs/env/lib/python3.7/multiprocessing/pool.py, line 651 in get>, <FrameSummary file /opt/conda/envs/env/lib/python3.7/multiprocessing/pool.py, line 648 in wait>, <FrameSummary file /opt/conda/envs/env/lib/python3.7/threading.py, line 552 in wait>, <FrameSummary file /opt/conda/envs/env/lib/python3.7/threading.py, line 296 in wait>]`

### Allocation status
![image](https://user-images.githubusercontent.com/8763192/88465626-f5a8fe80-ce9a-11ea-98e5-b7c26c2727c9.png)

### Allocation status 2
![image](https://user-images.githubusercontent.com/8763192/88465768-d6f73780-ce9b-11ea-9fe9-55659948ebff.png)

### Evaluations
![image](https://user-images.githubusercontent.com/8763192/88465749-a4e5d580-ce9b-11ea-8dbd-e44e26eac511.png)

**Comment by tgross** [comment]
hi @jonatasfreitasv! Typically if you're seeing exit status 137, that means that the Docker daemon sent a SIGKILL after a SIGTERM failed to stop the allocation. If you look at that Recent Events table, you can see that Nomad tried to stop the application at 16:24:37 with the message `Sent interrupt. Waiting 5s before force killing." and then sometime later the container gets SIGKILL'ed.

I'd expect to see this if your application masks SIGTERM so that it can do a graceful shutdown, but doesn't shutdown quickly. You can give the application more time by adjusting the [`kill_timeout`](https://www.nomadproject.io/docs/job-specification/task#kill_timeout) value.

If this doesn't help, it would be helpful if you could provide the jobspec and logs from the client where the allocation is running.
