### ISSUE TITLE
Java - Detected No 

### ISSUE THREAD

**Issue by jakirpatel** [hashicorp/nomad#8722]
### Nomad version
Nomad v0.12.3 (2db8abd9620dd41cb7bfe399551ba0f7824b3f61)

### Operating system and Environment details
Linux test-server1 4.4.175-1.el7.elrepo.x86_64 #1 SMP Wed Feb 20 08:49:56 EST 2019 x86_64 x86_64 x86_64 GNU/Linux

### Issue
Jave not detected. 

# Java version output 
```
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)
```

# Process started as the root 
`root     13689     1  0 09:18 ?        00:00:04 /usr/local/bin/nomad agent -config /etc/nomad.d`

**Comment by shoenig** [comment]
Hi @jakirpatel sorry you're having trouble with this. Just to make sure, can you confirm Nomad being launched in such a way that the `java` command is on the `PATH` environment variable? For example you could launch a small task that dumps the output of `env`.

**Comment by jakirpatel** [comment]
Thank you @shoenig for your reply. 


This is from task which executes /bin/env.
```
LANG=en_US.UTF-8
NOMAD_ALLOC_DIR=/alloc
NOMAD_ALLOC_ID=e621fb4a-6e7f-a95a-ae29-44e7daa7b03a
NOMAD_ALLOC_INDEX=0
NOMAD_ALLOC_NAME=environment.mygroup[0]
NOMAD_CPU_LIMIT=100
NOMAD_DC=jpe2
NOMAD_GROUP_NAME=mygroup
NOMAD_JOB_NAME=environment
NOMAD_MEMORY_LIMIT=300
NOMAD_NAMESPACE=default
NOMAD_REGION=global
NOMAD_SECRETS_DIR=/secrets
NOMAD_TASK_DIR=/local
NOMAD_TASK_NAME=mytask
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
HOME=/
LANG=en_US.UTF-8
NOMAD_ALLOC_DIR=/alloc
NOMAD_ALLOC_ID=e621fb4a-6e7f-a95a-ae29-44e7daa7b03a
NOMAD_ALLOC_INDEX=0
NOMAD_ALLOC_NAME=environment.mygroup[0]
NOMAD_CPU_LIMIT=100
NOMAD_DC=jpe2
NOMAD_GROUP_NAME=mygroup
NOMAD_JOB_NAME=environment
NOMAD_MEMORY_LIMIT=300
NOMAD_NAMESPACE=default
NOMAD_REGION=global
NOMAD_SECRETS_DIR=/secrets
NOMAD_TASK_DIR=/local
NOMAD_TASK_NAME=mytask
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
HOME=/
```

I confirmed Java is in path : 

```
$which java
/u01/Oracle/Middleware/java/jdk1.8.0_251/bin/java
```

**Comment by shoenig** [comment]
Yup that looks like the problem then, @jakirpatel . Notice the `PATH` environment variable isn't being set for the Nomad agent in such a way that it contains the path to your `java` executable. 

If you're launching nomad on the command line you'd need something like, 
`sudo "PATH=/u01/Oracle/Middleware/java/jdk1.8.0_251/bin/java:$PATH" nomad agent -dev`

If you're using an init system like systemd, there will be some other way of configuring the environment variables for the process.
https://coreos.com/os/docs/latest/using-environment-variables-in-systemd-units.html

I'll go ahead and close this, since this isn't an issue with Nomad.
