### ISSUE TITLE
[question] Qemu example ssh 

### ISSUE THREAD

**Issue by shinji62** [hashicorp/nomad#8864]
Hi,

I try to run a Qemu VM , the nomad jobs seems to be running but I don't know how to ssh to the new VM.

My nomad job
```hcl
job "myvm" {
  datacenters = ["dc1"]
  type = "service"
  group "arene-ci" {
    count = 1

    restart {
      attempts = 2
      interval = "30m"
      delay = "15s"
      mode = "fail"
    }

    ephemeral_disk {
      size = 10000
    }

    network {
      port "ssh" { }
    }

    task "myvmtask" {

      driver = "qemu"

      config {
        image_path        = "local/ubuntu-18.04-server-cloudimg-amd64.img"
        graceful_shutdown = true
        args              = ["-nodefaults"]
        port_map = {
          ssh = 22
        }
      }


      artifact {
         source = "https://cloud-images.ubuntu.com/releases/bionic/release-20200908/ubuntu-18.04-server-cloudimg-amd64.img"
      }

    }
  }
}
```

So not sure what I should next, I can't find good tutorial on internet, so any help is welcome.

Thanks

**Comment by tgross** [comment]
Hi @shinji62! Your job configuration has a `port_map` config for the ssh port, so there's a port somewhere on the host that's being forwarded to port 22 in the VM. 

You'll need to get the port from the allocation. Look for the "Allocation Addresses" section of the `nomad alloc status :id` output:

```
$ nomad job status myvm
...
Allocations
ID        Node ID   Task Group  Version  Desired  Status   Created    Modified
36ad3699  5b2490fc  arene-ci    0        run      running  1m28s ago  52s ago

$ nomad alloc status 36ad
...
Allocation Addresses
Label  Dynamic  Address
*ssh   yes      10.0.2.15:24502
```

So for the example above, you'd then `ssh ubuntu@10.0.2.15 -p 24502` (but I don't know how your VM configures it's password or ssh key, that'll be in the docs for the VM image you're using).

Alternately, you can use a [`static`](https://www.nomadproject.io/docs/job-specification/network#static) port on your network configuration so that it's always available at the same port.

**Comment by shinji62** [comment]
Thanks @tgross ! Do you have a full working example with ubuntu?! That s could be nice.

**Comment by vcrazy** [comment]
Hi there. I have the same issue running qemu. Any port forwarding just hangs and timeouts and I can't make it work.
My config looks like this although I have tried different ways to make it work. This is the best I managed to do.

> job "test-qemu-vmdk" {
>     ...
> 
>     group "test" {
>     ...
> 
>         task "staging-machine" {
>             driver = "qemu"
> 
>             config {
>                 image_path  = "...vmdk"
>                 accelerator = "kvm"
>                 args        = ["-nodefaults"]
>                 port_map {
>                         ssh = 22
>                 }
>             }
> 
>             artifact {
>                 source = "...vmdk"
>             }
> 
>             resources {
>                 network {
>                        port "ssh" {}
>                 }
>             }
>         }
>     }
> }
> 

I see that the machine is running from the resource utilization tab.

![Screenshot from 2020-12-07 17-32-07](https://user-images.githubusercontent.com/545351/101371557-941a8700-38b3-11eb-8e4c-4bf885fa7200.png)

> root@host1:~# nomad alloc status 011760ed
> ...
> CPU          Memory           Disk    Addresses
> 91/4000 MHz  843 MiB/2.0 GiB  20 GiB  ssh: 172.16.0.21:26698

This way I see it is listening on the right port.

> root@host1:~# netstat -tulpn | grep qemu
> tcp        0      0 0.0.0.0:26698           0.0.0.0:*               LISTEN      45979/qemu-system-x
> udp        0      0 0.0.0.0:26698           0.0.0.0:*                           45979/qemu-system-x
> 

However, I can not connect via ssh. The same is true if I try HTTP or other. It just timeouts with `ssh_exchange_identification: read: Connection reset by peer`.

> root@host1:~# ssh 172.16.0.21 -p 26698
> ssh_exchange_identification: read: Connection reset by peer

How can I debug and find the problem?

Thanks!

**Comment by tgross** [comment]
Hi @vcrazy! You've got `-nodefaults` configured for your VM, but that prevents KVM from configuring the networking stack for the VM. So the problem here is not so much Nomad's port forwarding as the arguments you're passing to QEMU. See https://wiki.qemu.org/Documentation/Networking for more details on how you'll want to configure networking in the VM.

My colleague @angrycub has a simple (unofficial!) example [`tc_ssh.nomad#L50`](https://github.com/angrycub/nomad_example_jobs/blob/master/qemu/tc_ssh.nomad#L50) too if you want a place to start.

**Comment by vcrazy** [comment]
Thank you @tgross. I will fully read the qemu docs and contact your colleague if necessary I hope @angrycub won't mind. :) 
And I will write a complete example or post once I have this all figured out.

**Comment by tgross** [comment]
Looks like this was resolved. Going to close but please feel free to open a new issue if there are new problems that arise.
