### ISSUE TITLE
cli client doesn't respect env vars with nomad alloc signal command.

### ISSUE THREAD

**Issue by hongkongkiwi** [hashicorp/nomad#8894]
### Nomad version
Nomad v0.12.4

### Operating system and Environment details
Linux edge0 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Issue
When using the command `nomad alloc signal -s SIGHUP <alloc_id>` nomad does not respect the NOMAD_ADDR environment variable. Any other command works fine e.g. `nomad alloc status <alloc_id>`.

In my .bash_aliases file I have the following:
```
export NOMAD_ADDR=https://127.0.0.1:4646
export NOMAD_CACERT=/etc/nomad/certs/nomad-ca.pem
export NOMAD_CLIENT_CERT=/etc/nomad/certs/cli.pem
export NOMAD_CLIENT_KEY=/etc/nomad/certs/cli-key.pem
```

However, when connecting with the signal comment, it gives an error such as:
```
Error signalling allocation: Put "https://192.168.1.18:4646/v1/client/allocation/b16c3dfb-cfc3-e2ba-9c4c-241e889b7719/signal?region=global": x509: certificate is valid for 127.0.0.1, 172.17.0.1, not 192.168.1.18
```

So obviously (and strangely) for this one command it does not respect the environment variable for NOMAD_ADDR and somehow tries to connect to a lan ip instead of 127.0.0.1.

**Comment by tgross** [comment]
Hi @hongkongkiwi! Sorry to hear you're having trouble.

Just to help us narrow this down, are you experiencing the same issue with [`nomad alloc exec`](https://www.nomadproject.io/docs/commands/alloc/exec), [`nomad alloc fs`](https://www.nomadproject.io/docs/commands/alloc/fs), or [`nomad alloc logs`](https://www.nomadproject.io/docs/commands/alloc/logs)? Those commands use the same API to forward commands to the client nodes, whereas `nomad alloc status` just communicates with the server, so if those are also broken that would help identify where the problem is.
