### ISSUE TITLE
Run task remotely

### ISSUE THREAD

**Issue by trong** [hashicorp/nomad#898]
My case:
 - there is deploy server (jenkins)
 - there are 10 production servers under nomad

Now I do the following:
 - push builded docker image into own docker registry
 - copy nomad config (app.nomad) to production server through scp
 - run `nomad run app.nomad`  through ssh

Is some way to run this task from deploy server to production cluster directly?

**Comment by dadgar** [comment]
@trong the Nomad CLI is talking to Nomad via its HTTP API. So in order to run from the deploy server, the HTTP address that Nomad is listening on must be accessible. So this will involve setting up your networking rules properly.

When using the CLI you can give the address as follows (using the default IP:Port):

`nomad run -address=127.0.0.1:4646 app.nomad`
