### ISSUE TITLE
Documentation/Guidance needed: Blocked Evals

### ISSUE THREAD

**Issue by benbuzbee** [hashicorp/nomad#9134]
So very sorry for abusing the github issue system; happy to take this elsewhere if its not appropriate here

I am trying to understand how to handle eval.BlockedEval.  Consider
```
	// BlockedEval is the evaluation ID for a created blocked eval. A
	// blocked eval will be created if all allocations could not be placed due
	// to constraints or lacking resources.
	BlockedEval string

	// FailedTGAllocs are task groups which have allocations that could not be
	// made, but the metrics are persisted so that the user can use the feedback
	// to determine the cause.
	FailedTGAllocs map[string]*AllocMetric
```

This seems to imply I could queue a job demanding 1000 gigs of memory, and a sensible thing for Nomad to do is create a Blocked eval in case a node happens to appear having 1000 gigs of memory. However in practice, what actually happens is BlockedEval = "", and FailedTGAllocs contain the metric that memory dimension is exhausted.

I very rarely see BlockedEval set, for example even for ports it is set to "".

However, there is one case where I do consistently see it set, which is when then plan "fails to make progress" such as this code from generic_sched
```
	if err := retryMax(limit, s.process, progress); err != nil {
		if statusErr, ok := err.(*SetStatusError); ok {
			// Scheduling was tried but made no forward progress so create a
			// blocked eval to retry once resources become available.
			var mErr multierror.Error
			if err := s.createBlockedEval(true); err != nil {
				mErr.Errors = append(mErr.Errors, err)
			}
```

In this case a blocked eval is created, FailedTGAllocs is [] because no allocs were created, and the status of the eval becomes the string "maximum attempts reached (2/5)"

One example of when this happens is when all the nodes are updating at once and so Scheduler::SubmitPlan returns an updated state twice in a row.

This case makes me think the right thing to do with a blocked eval is to always ignore the eval that created it and instead track the new blocked eval because a blocked eval simply means "retrying again very soon"

However the comment in structs.go scares me - I don't want to wait on a blocked eval if it could take a very very long time go be evaluated, such as waiting on resources to become available.

Are there any guarantees on how many BlockedEvals will be created in a chain, or how long they will take to be evaluated? Will FailedTGAllocs always be filled out as long as the cluster is in a sane enough state to create allocations?

**Comment by benbuzbee** [comment]
And now I've seen one with a QueuedAllocation so I am very confused :(
```
{ID:6f249ce3-19ea-63fb-5ec8-8852919e3356 Priority:50 Type:batch TriggeredBy:job-register Namespace:default JobID:browser-nomad-client-1-c0695ed6-4ed7-41d3-984e-c4c20f8f6033 JobModifyIndex:50 NodeID: NodeModifyIndex:0 DeploymentID: Status:complete StatusDescription: Wait:0s WaitUntil:0001-01-01 00:00:00 +0000 UTC NextEval: PreviousEval: BlockedEval:46f88e32-dd09-a6db-0675-efc921d61ccd FailedTGAllocs:map[browsers:0xc000210510] ClassEligibility:map[] EscapedComputedClass:false QuotaLimitReached: AnnotatePlan:false QueuedAllocations:map[browsers:1] SnapshotIndex:50 CreateIndex:50 ModifyIndex:59 CreateTime:1603249899742154284 ModifyTime:1603249900145946717}
```

**Comment by tgross** [comment]
Hi @benbuzbee! An evaluation that's blocked will get requeued (unless it gets Nacked). We go and clean up any blocked evals for a job if the job gets an upsert that makes them invalid, or if the job is deregistered. Evals don't get GC'd unless they're terminal (complete or failed), so you probably don't want to poll on them forever.

But can we back up a bit and talk about what you're trying to do here? Maybe there's a better approach.

**Comment by benbuzbee** [comment]
Of course

What we want is to build an API that registers a batch job and waits until the allocation is placed or return an error if it cannot be placed

What we do now

1. -Register job
2.  Wait on the eval returned from the register job endpoint to enter a terminal state (not "pending")
3.  if the eval is "complete" and len(eval.FailedTGAllocs) != 0, it failed, log the reasons why it failed - e.g. "memory exahusted"
4.  if the eval is "complete" and len(eval.FailedTGAllocs == 0), it succeeded, query the v1/evaluation/N/allocations endpoint for our placed allocs
5.  If the eval is "failed" we fail and log the StatusDescription field

Now imagine that we try to schedule several jobs like this that needs 10 gigs of memory  but we only have 15, so only 1 can succeed

95% of the time the above algorithm works and we get an eval like this, with a useful error message: in FailedTGAllocs
````
 {NodesEvaluated:3 NodesFiltered:2 NodesAvailable:map[dc1:3] ClassFiltered:map[] ConstraintFiltered:map[${node.unique.id} = 1ca7323a-9896-98fc-d9cf-c2b089fb8a1f:2] NodesExhausted:1 ClassExhausted:map[] DimensionExhausted:map[memory:1] QuotaExhausted:[] Scores:map[] AllocationTime:102.984µs CoalescedFailures:0 ScoreMetaData:[]}
```
This is great and exactly what we want - we log that we are out of memory and know how to take action

However, 5% of the time the eval from the job registration api ends like this:
```
{ID:64f5faf2-e31d-1eaa-2e09-83ffa34884b1 Priority:50 Type:batch TriggeredBy:job-register Namespace:default JobID:browser-nomad-client-0-218deadd-c7a4-4f6f-b03b-b6a10a956948 JobModifyIndex:49 NodeID: NodeModifyIndex:0 DeploymentID: Status:failed StatusDescription:maximum attempts reached (2) Wait:0s WaitUntil:0001-01-01 00:00:00 +0000 UTC NextEval: PreviousEval: BlockedEval:ba5a915b-633e-d529-a8bb-7b50722ed984 FailedTGAllocs:map[] ClassEligibility:map[] EscapedComputedClass:false QuotaLimitReached: AnnotatePlan:false QueuedAllocations:map[browsers:1] SnapshotIndex:49 CreateIndex:49 ModifyIndex:56 CreateTime:1603325530935521972 ModifyTime:1603325531051356083}
```


Here I do not know what the right thing to do is
The error "maximum attempts reached (2)" is not very useful
The blocked eval "ba5a915b-633e-d529-a8bb-7b50722ed984" appears to stay in the Status = Blocked state forever

**Comment by tgross** [comment]
Ok, thanks for that context. This is helpful.

> However, 5% of the time the eval from the job registration api ends like this

I'm looking through the scheduler code and it looks like we should be seeing some kind of error coming out of [`process()`](https://github.com/hashicorp/nomad/blob/v0.12.6/scheduler/generic_sched.go#L216) if it returns `false` in almost but not quite all cases. It doesn't look like we should be seeing it when there are resource constraints not being met, which is probably why you're not seeing that in the response. But when we submit the plan to a worker, if the state store has stale data we retry with refreshed data (and no error). A couple questions that might help me debug what you're seeing:

* Is the cluster getting high volume of concurrent job registrations?
* Is it possible for you to capture logs at `debug`-level for one of these 5% cases? That'll have details we can use to figure out what the right thing to do here is.

**Comment by benbuzbee** [comment]
Attached the logs for this failure: [nomad.log](https://github.com/hashicorp/nomad/files/5425817/nomad.log)
```
eval 'd64d6c5f-c7b7-5617-5f92-f122e3ca5ad0' is in invalid state 'failed': maximum attempts reached (2), (Eval: &{ID:d64d6c5f-c7b7-5617-5f92-f122e3ca5ad0 Priority:50 Type:batch TriggeredBy:job-register Namespace:default JobID:browser-nomad-client-0-ef2d3282-d8ce-40ab-9a2b-7422d67d8d60 JobModifyIndex:53 NodeID: NodeModifyIndex:0 DeploymentID: Status:failed StatusDescription:maximum attempts reached (2) Wait:0s WaitUntil:0001-01-01 00:00:00 +0000 UTC NextEval: PreviousEval: BlockedEval:cda0d646-a979-a7e3-c7db-c1aa07ffe6c7 FailedTGAllocs:map[] ClassEligibility:map[] EscapedComputedClass:false QuotaLimitReached: AnnotatePlan:false QueuedAllocations:map[browsers:1] SnapshotIndex:53 CreateIndex:53 ModifyIndex:61 CreateTime:1603400213470922815 ModifyTime:1603400213634401929})
```

I know there are some certificates and keys in the logs, don't worry about it - its all local dev certs generated on the fly. Nothing non-public that I am worried about.

We definitely have concurrent job registrations going on, our service on starts registers a bunch of jobs.

In these logs, we run things locally. We
- Start nomad server
- start 3 nomad clients
- Schedule our jobs
- Crash because of the above eval failure
- stop the clients
- stop the server

**Comment by tgross** [comment]
Thanks @benbuzbee! I took a dive through those logs to make sure I understood what you were seeing. The short version is that you're seeing planner errors, which I'd expect to see in a cluster running near capacity.

Follow-ups:
* I want to look into whether we could improve the eval status description by getting planner errors into there and not just scheduler errors. 
* You should be looking for the change of the eval's `Status` to `"failed"` as shown in the error message you've shared.

---

If you want the long version...

Ok, so in all the logs below, only the `nomad-server-0` instance had anything relevant because this behavior is entirely inside the server and you only have one of them. So I've stripped that bit of prefix off for legibility. First let's look at the eval from your error message in a more readable format:

```
{
  ID:d64d6c5f-c7b7-5617-5f92-f122e3ca5ad0
  Priority:50
  Type:batch
  TriggeredBy:job-register
  Namespace:default
  JobID:browser-nomad-client-0-ef2d3282-d8ce-40ab-9a2b-7422d67d8d60
  JobModifyIndex:53
  NodeID:
  NodeModifyIndex:0
  DeploymentID:
  Status:failed
  StatusDescription:maximum attempts reached (2)
  Wait:0s
  WaitUntil:0001-01-01 00:00:00 +0000 UTC
  NextEval:
  PreviousEval:
  BlockedEval:cda0d646-a979-a7e3-c7db-c1aa07ffe6c7
  FailedTGAllocs:map[]
  ClassEligibility:map[]
  EscapedComputedClass:false
  QuotaLimitReached:
  AnnotatePlan:false
  QueuedAllocations:map[browsers:1]
  SnapshotIndex:53
  CreateIndex:53
  ModifyIndex:61
  CreateTime:1603400213470922815
  ModifyTime:1603400213634401929
}
```

We see the `Status: "failed"` and `StatusDescription: "maximum attempts reached (2)"`. The `CreateIndex: 53` and `JobModifyIndex: 53` will be relevant later. Ok, so following the lifetime of that evaluation, we see it gets dequeued by the batch scheduler:

```
     2020-10-22T20:56:53.543Z [DEBUG] worker.batch_sched: reconciled current state with desired state: eval_id=d64d6c5f-c7b7-5617-5f92-f122e3ca5ad0 job_id=browser-nomad-client-0-ef2d3282-d8ce-40ab-9a2b-7422d67d8d60 namespace=default results="Total changes: (place 1) (destructive 0) (inplace 0) (stop 0)
Desired Changes for "browsers": (place 1) (inplace 0) (destructive 0) (stop 0) (migrate 0) (ignore 0) (canary 0)"
```

Our batch scheduler determines how many allocations we need in [`computeJobAllocs`](https://github.com/hashicorp/nomad/blob/v0.12.7/scheduler/generic_sched.go#L332). The results [get logged](https://github.com/hashicorp/nomad/blob/v0.12.7/scheduler/generic_sched.go#L356) (across two lines, which is weird). This plan is submitted to the planner at [`SubmitPlan`](https://github.com/hashicorp/nomad/blob/v0.12.7/scheduler/generic_sched.go#L299)

The next line we see is:
```
    2020-10-22T20:56:53.543Z [DEBUG] nomad: plan for node rejected: node_id=d881542e-7fad-71de-c654-d5a6cdf9bcd6 reason=memory eval_id=d64d6c5f-c7b7-5617-5f92-f122e3ca5ad0
```

This is the expected [log message](https://github.com/hashicorp/nomad/blob/v0.12.6/nomad/plan_apply.go#L478) of a  [`evaluatePlanPlacements`](https://github.com/hashicorp/nomad/blob/v0.12.6/nomad/plan_apply.go#L437) call, called by [`evaluatePlan`](https://github.com/hashicorp/nomad/blob/v0.12.6/nomad/plan_apply.go#L400), called by the [`planApply`](https://github.com/hashicorp/nomad/blob/v0.12.6/nomad/plan_apply.go#L71) loop. This means the scheduler thinks there's enough room on the node, but by the time it gets to the planner it's either the node information has changed or it's conflicted with another concurrent placement. In a cluster running near to its memory capacity, a conflict is the most likely case. (See [scheduling internals](https://www.nomadproject.io/docs/internals/scheduling/scheduling) for more details.) So far nothing here is unexpected.

But then wait a sec, why do we see "submitted plan for evaluation" in the next log line:

```
    2020-10-22T20:56:53.544Z [DEBUG] worker: submitted plan for evaluation: eval_id=d64d6c5f-c7b7-5617-5f92-f122e3ca5ad0
```

On a production cluster with multiple servers, this submit is happening as an RPC to the leader. The leader is handling the apply in an sync loop, so the only error we get back from `Plan.Submit` RPC is if we couldn't _enqueue_ the plan.

```
    2020-10-22T20:56:53.544Z [DEBUG] worker: refreshing state: refresh_index=53 eval_id=d64d6c5f-c7b7-5617-5f92-f122e3ca5ad0
    2020-10-22T20:56:53.544Z [DEBUG] worker.batch_sched: refresh forced: eval_id=d64d6c5f-c7b7-5617-5f92-f122e3ca5ad0 job_id=browser-nomad-client-0-ef2d3282-d8ce-40ab-9a2b-7422d67d8d60 namespace=default
```

If we keep following [after that `Plan.Submit` RPC](https://github.com/hashicorp/nomad/blob/v0.12.7/nomad/worker.go#L319-L332) we see we've got a result back, but that the result is telling us the plan was submitted with stale data. It was a conflict, just as we thought! So now the worker waits until it has the fresh index (which on your 1-server cluster will be immediately), and then we return back to the scheduler, which returns [`false, nil`](https://github.com/hashicorp/nomad/blob/v0.12.7/scheduler/generic_sched.go#L313) for this attempt.

So we try again:

```
    2020-10-22T20:56:53.544Z [DEBUG] worker.batch_sched: reconciled current state with desired state: eval_id=d64d6c5f-c7b7-5617-5f92-f122e3ca5ad0 job_id=browser-nomad-client-0-ef2d3282-d8ce-40ab-9a2b-7422d67d8d60 namespace=default results="Total changes: (place 1) (destructive 0) (inplace 0) (stop 0)
Desired Changes for "browsers": (place 1) (inplace 0) (destructive 0) (stop 0) (migrate 0) (ignore 0) (canary 0)"
    2020-10-22T20:56:53.544Z [DEBUG] nomad: plan for node rejected: node_id=d881542e-7fad-71de-c654-d5a6cdf9bcd6 reason=memory eval_id=d64d6c5f-c7b7-5617-5f92-f122e3ca5ad0
    2020-10-22T20:56:53.544Z [DEBUG] worker: submitted plan for evaluation: eval_id=d64d6c5f-c7b7-5617-5f92-f122e3ca5ad0
    2020-10-22T20:56:53.544Z [DEBUG] worker: refreshing state: refresh_index=53 eval_id=d64d6c5f-c7b7-5617-5f92-f122e3ca5ad0
    2020-10-22T20:56:53.544Z [DEBUG] worker.batch_sched: refresh forced: eval_id=d64d6c5f-c7b7-5617-5f92-f122e3ca5ad0 job_id=browser-nomad-client-0-ef2d3282-d8ce-40ab-9a2b-7422d67d8d60 namespace=default
```

We go through the whole loop again, but it looks like we're getting the same error. The `refresh_index` hasn't changed and matches the job modify index from the eval, which tells us no new plans have landed in the meantime. Because the server will have multiple schedulers goroutines, you're hitting a race because one or more schedulers think there's enough room, but then the planner knows there isn't enough room. This is usually a matter of the cluster being very close to capacity and the planner getting a high volume of plans relative to the remaining capacity. You might be able to provide some context there -- are you very likely to get conflicts based on your current loading?

Next there's a few concurrent evaluations being processed and finally a few tenths of a second later we land here:

```
    2020-10-22T20:56:53.624Z [DEBUG] worker: created evaluation: eval="<Eval "cda0d646-a979-a7e3-c7db-c1aa07ffe6c7" JobID: "browser-nomad-client-0-ef2d3282-d8ce-40ab-9a2b-7422d67d8d60" Namespace: "default">"
    2020-10-22T20:56:53.634Z [DEBUG] worker.batch_sched: setting eval status: eval_id=d64d6c5f-c7b7-5617-5f92-f122e3ca5ad0 job_id=browser-nomad-client-0-ef2d3282-d8ce-40ab-9a2b-7422d67d8d60 namespace=default status=failed
```

So at this point we've failed because although the scheduler can propose a plan, the planner is not accepting it. That's why there's still a `QueuedAllocation` but no `FailedTGAllocs`, which aren't going to show up if we never placed. When the scheduler sets the status it calls into [`Plan.UpdateEval`](https://github.com/hashicorp/nomad/blob/v0.12.7/scheduler/util.go#L530), which is where we get this log entry:

```
    2020-10-22T20:56:53.736Z [DEBUG] worker: updated evaluation: eval="<Eval "d64d6c5f-c7b7-5617-5f92-f122e3ca5ad0" JobID: "browser-nomad-client-0-ef2d3282-d8ce-40ab-9a2b-7422d67d8d60" Namespace: "default">"
    2020-10-22T20:56:53.737Z [DEBUG] worker: ack evaluation: eval_id=d64d6c5f-c7b7-5617-5f92-f122e3ca5ad0
```

Circling back to one of your observations here:

> The blocked eval "ba5a915b-633e-d529-a8bb-7b50722ed984" appears to stay in the Status = Blocked state forever

But what you've shown in that example and these logs is that the blocked eval has `Status: "failed"` though, right? So if you don't want to block forever you need to check the status and not just that it was a blocked eval. It would probably be nice if we could get placement error info into the eval status description, but you can definitely use the `Status` field to check the overall status.

**Comment by benbuzbee** [comment]
Thanks for the good response, a better error is exactly what we're after

What i mean by blocked eval being blocked forever:

This eval
```
nomad status -verbose b12ab391-ffff-5557-6256-e0f8f3e6767b
ID                 = b12ab391-ffff-5557-6256-e0f8f3e6767b
Create Time        = 2020-10-21T03:20:43Z
Modify Time        = 2020-10-21T03:20:44Z
Status             = failed
Status Description = maximum attempts reached (2)
Type               = batch
TriggeredBy        = job-register
Job ID             = browser-nomad-client-0-6178bdb3-a3a6-44c5-bc7e-7ac1a3c11b80
Priority           = 50
Placement Failures = false
Previous Eval      = <none>
Next Eval          = <none>
Blocked Eval       = 131f8c33-a28c-ff5b-b27a-8d1794171e22
```

Points to `Blocked Eval       = 131f8c33-a28c-ff5b-b27a-8d1794171e22`

And that one seems to stay in `Status = blocked` forever (i waited a minute)
```
nomad status -verbose 131f8c33-a28c-ff5b-b27a-8d1794171e22
ID                 = 131f8c33-a28c-ff5b-b27a-8d1794171e22
Create Time        = 2020-10-21T03:20:44Z
Modify Time        = 2020-10-21T03:20:44Z
Status             = blocked
Status Description = created due to placement conflicts
Type               = batch
TriggeredBy        = max-plan-attempts
Previous Eval      = b12ab391-ffff-5557-6256-e0f8f3e6767b
Priority           = 50
Placement Failures = N/A - In Progress
Previous Eval      = b12ab391-ffff-5557-6256-e0f8f3e6767b
Next Eval          = <none>
Blocked Eval       = <none>
```

This left me unsure as to whether I should care about the "BlockedEval" field at all. Should I ignore the field or somehow track its status?

**Comment by tgross** [comment]
In the logs I was walking thru above for eval ID `d64d6c5f-c7b7-5617-5f92-f122e3ca5ad0`, you can see if you follow the job that a new eval `64d6c5f-c7b7-5617-5f92-f122e3ca5ad0` is the one that stays in blocked forever, and it gets re-evaluated every so often but now it's not hitting the "max attempts" error: that's because the scheduler knows there's no room for it and so it's going to stay there blocked until either the job is stopped or there is capacity available.

So to answer your last question, the `Blocked Eval` field is useful for knowing which eval the failed eval "handed off" the job to. That's where you'll want to watch if you're trying to follow the "final" eval status.

**Comment by tgross** [comment]
I'm doing some issue clean up and I think this one was answered. If you have more questions, let's open a new discussion.
