### ISSUE TITLE
CSI volume shows controller health as unhealthy even when no controller is needed

### ISSUE THREAD

**Issue by apollo13** [hashicorp/nomad#9252]
### Nomad version
0.12.5

### Issue
The `Storage -> Volume` tab says `unhealthy` for controller health for my CSI plugin:
![image](https://user-images.githubusercontent.com/81547/97912730-7e162580-1d4d-11eb-98ef-1527c931d5b5.png)

Since my plugin does not require a controller, it would be great if the UI could give one the benefit of the doubt if no controller is running. After all it lists it as  Schedulable which probably wouldn't work either if a healthy controller were a requirement :)

### Reproduction steps

Use any CSI plugin that does not need a controller.

**Comment by tgross** [comment]
Thanks for noticing this @apollo13. Definitely something that'd be nice to polish up.

**Comment by tgross** [comment]
@apollo13 I wasn't able to replicate this with a node-only plugin. The API includes a field `ControllerRequired` which the web UI uses to gray-out that field if one isn't required. The screenshot below is the AWS EFS plugin on Nomad 0.12.7:

<img width="909" alt="Screen Shot 2020-11-20 at 2 18 34 PM" src="https://user-images.githubusercontent.com/1409219/99840949-6dcabc80-2b3b-11eb-94af-47b1165e5194.png">

Have you set the [`csi_plugin.type`](https://www.nomadproject.io/docs/job-specification/csi_plugin#type) to `node`?

**Comment by tgross** [comment]
@apollo13 I was able to reproduce this with a node-only plugin. The screenshot below is the AWS EFS plugin on Nomad 0.12.7:

<img width="980" alt="Screen Shot 2020-11-20 at 2 29 42 PM" src="https://user-images.githubusercontent.com/1409219/99841865-d9615980-2b3c-11eb-82d0-b377cd7684a0.png">

Whereas the plugin tab shows it correctly:

<img width="909" alt="Screen Shot 2020-11-20 at 2 18 34 PM" src="https://user-images.githubusercontent.com/1409219/99840949-6dcabc80-2b3b-11eb-94af-47b1165e5194.png">

The API includes a field `ControllerRequired` which the web UI uses to gray-out that field if one isn't required. So that's not getting referenced in that volume tab for some reason. Should be a small fix.
