### ISSUE TITLE
The allocations endpoint with namespace=* does not interact with ACLs as expected

### ISSUE THREAD

**Issue by DingoEatingFuzz** [hashicorp/nomad#9268]
### Nomad version

1.0.0-beta2

### Issue

When ACLs are enabled and a token has permissions to namespaces individually but no permissions for `*`, requesting `/v1/allocations?namespace=*` results in a `403 Forbidden`.

I expected to get all allocations across all namespaces I have permissions for.
### Reproduction steps

1. Create some namespaces
2. Create policies that grant read access to namespaces individually
3. Create a token using those policies
4. Run `http localhost:4646/v1/allocations?namespace=* -- X-Nomad-Token:<token>` or similar

**Comment by DingoEatingFuzz** [comment]
Policy for reference.

```hcl
namespace "default" {
  policy = "read"
}

namespace "other-ns" {
  policy = "read"
  capabilities = ["list-jobs", "read-job"]
}

agent {
  policy = "read"
}

node {
  policy = "read"
}
```

**Comment by cgbaker** [comment]
i suspect it's a bad check early in the RPC call, which doesn't account for the sentinel: 
https://github.com/hashicorp/nomad/blame/v1.0.0-beta2/nomad/alloc_endpoint.go#L36

this code should probably be updated to reflect the pattern in job listing: 
https://github.com/hashicorp/nomad/blame/v1.0.0-beta2/nomad/job_endpoint.go#L1301

also, while we're fixing bugs... it looks like the filtering on this line is backwards: 
https://github.com/hashicorp/nomad/blob/master/nomad/state/state_store.go#L3356

and the allow check (in the latest version) is wrong as well (`list-jobs` instead of `read-job`): 
https://github.com/hashicorp/nomad/blame/ba17e2191ba3a0dbf479b51430b9d4815a0bc112/nomad/alloc_endpoint.go#L41

**Comment by yitbarek123** [comment]
@cgbaker , I'm also facing this issue with the latest nomad version 1.1.6 . 

Thanks.

**Comment by cgbaker** [comment]
Hi @yitbarek123 , please file a new issue with the pertinent details and someone from Nomad will triage it. Thank you!

**Comment by yitbarek123** [comment]
OK, @cgbaker . Thanks again.
