### ISSUE TITLE
Add policy rule `csi_volume` to complement `host_volume`

### ISSUE THREAD

**Issue by apollo13** [hashicorp/nomad#9273]
I couldn't find an existing issue, so here it goes… It would be great if ACLs would allow mounting of certain CSI volumes, ie add a `csi_volume` rule in addition to `host_volume` (https://learn.hashicorp.com/tutorials/nomad/access-control-policies#host-volume-rules)

**Comment by tgross** [comment]
Hi @apollo13! Can you explain in a bit more detail the use case here? Because volumes are namespaced, we already have the [`csi-mount-volume`](https://learn.hashicorp.com/tutorials/nomad/access-control-policies#csi-mount-volume) ACL available. The typical workflow we'd imagined is that you'd create a volume with a given namespace and allow jobs within that namespace to mount it. This becomes even more important once we implement the `CreateVolume` portions of the CSI spec (ref https://github.com/hashicorp/nomad/issues/8212)

**Comment by apollo13** [comment]
Oh, yeah I guess namespaces will cover that. I tend to always forget about namespaces since I am still on OSS 0.12. :) But 1.0 will indeed fix that. The only thing that is different to host volumes then is the missing distinction between read & write mounts. But I guess if namespaces are "cheap" building blocks then nothing stops one from creating multiple of them and registering the same volume once as "multi-node-reader-only" and once as "multi-node-multi-writer" in different namespaces?

**Comment by apollo13** [comment]
Closing because `csi-mount-volume` does what I want.
