### ISSUE TITLE
make release fails on s390x

### ISSUE THREAD

**Issue by bert2002** [hashicorp/nomad#9561]
Hi,
I am tryint to build nomad for s390x (Linux on IBM Z) and I can build it as a `dev` release, but not as a `release`. 

Works for dev (also dev-ui):
```
# make dev
==> Removing old development build...
==> Building pkg/linux_s390x/nomad with tags codegen_generated ...
```

Does not work for release:
```
# make release
==> Cleaning build artifacts...
==> Building pkg/linux_386/nomad with tags ui codegen_generated release...
# runtime/cgo
s390x-linux-gnu-gcc: error: unrecognized command line option '-m32'; did you mean '-m31'?
make: *** [GNUmakefile:78: pkg/linux_386/nomad] Error 2
```
Seems it does not detect the architecture correct.

bert

**Comment by tgross** [comment]
Hi @bert2002! Because we release from a pretty standard set of machines, we don't really do robust target detection for `make release`, just some simple `uname` checking:

```make
THIS_OS := $(shell uname | cut -d- -f1)
...

ALL_TARGETS += linux_386 \
	linux_amd64 \
	linux_arm \
	linux_arm64 \
	windows_386 \
	windows_amd64

endif

# On MacOS, we only build for MacOS
ifeq (Darwin,$(THIS_OS))
ALL_TARGETS += darwin_amd64
# Copy CGO files for darwin into place
endif

# On FreeBSD, we only build for FreeBSD
ifeq (FreeBSD,$(THIS_OS))
ALL_TARGETS += freebsd_amd64
endif
```

So your machine is building the `linux_386` target which is apparently can't do. If you can contribute a PR for a simple but more robust check so that we don't build targets that we can't cross-compile from s390x I'd be happy to review it.

**Comment by bert2002** [comment]
I am not a golang expert, so I extended the current solution to check for the architecture.

**Comment by roderickmarj** [comment]
yes
