### ISSUE TITLE
Unexpected behaviour of distinct_hosts between namespaces and same Job ID

### ISSUE THREAD

**Issue by Settler** [hashicorp/nomad#9792]
### Nomad version
Nomad v1.0.0 (cfca6405ad9b5f66dffc8843e3d16f92f3bedb43)

### Operating system and Environment details
Windows Server 2019 Core

### Issue
distinct_hosts constraint declared in Job files with same job id filters hosts between namespaces.

### Reproduction steps
1. Create job with distinct_hosts constraint
2. Run job in two different namespaces but on same node

### Job file (if appropriate)
--

### Description
In job stanza documentation (https://www.nomadproject.io/docs/job-specification/job):
`Job names are unique per region or namespace.`

So, we tried to separate one cluster between different environments (test, staging, etc.).
In our usecase we can run job files with SAME job id in different namespaces. For example run service in test environment and in staging environment and see same job name when query job list from different namespaces. And we expect that distinct_hosts work INSIDE namespace, but not between them. Because otherwise we cannot run services in different environments (namespaces) on same node using same job file with same Id.

As workaround we tried to use `name` property of Job which described as optional in documentation. We tried to place additional environment suffix to job Id to tell Nomad that those jobs are different and set `name` property to human readable name without environment prefix, because namespace already has environment meaning. But nomad has [strange logic](https://github.com/hashicorp/nomad/blob/1d2ac5bbb920509230ea06f7437f94617d1e5e1c/command/agent/job_endpoint.go#L146) which doesn't give opportunity to set name to different value than ID. Maybe this is also a bug? Because otherwise I can't understand meaning of name property for jobs.

**Comment by tgross** [comment]
Hi @Settler! Thanks for opening this issue!

> And we expect that distinct_hosts work INSIDE namespace, but not between them.

That's exactly what I'd expect as well so unfortunately this looks like a bug. And the `name` vs `ID` field is really only usable in the HTTP API; I'm not entirely sure why we document it as a jobspec field. I would recommend trying the `distinct_property` constraint but I suspect the problem will persist there as well. You might be able to use [HCL2 variables](https://www.nomadproject.io/docs/job-specification/hcl2/variables) to interpolate the job ID with the environment.

We'll look into the fix for this and see if we can come up with any additional workarounds in the meantime.

**Comment by Settler** [comment]
@tgross 
I've checked distinct_property. And it seems that it worked very well! I used this constraint:
```
    constraint {
      operator  = "distinct_property"
      attribute = "${attr.unique.hostname}"
      value     = 1
    }
```
I tried to start 2 instances of one job and set another constraint to run this job only on one node.
```
    constraint {
      operator  = "regexp"
      attribute = "${attr.unique.hostname}"
      value     = "TEST"
    }
```
Only one allocation started. For second allocation I received allocation failure event during evaluation.
After that, I removed regexp constraint and my job successfully run 2 allocations.
After that, I copied job HCL and run it in another namespace. And nomad successfully run allocations of that job on same nodes as first job.

So.. `distinct_property` works as expected, but `distinct_host` – no.

**Comment by angrycub** [comment]
@tgross and I had a discussion about this ticket earlier today and while the behavior is definitely not acting like we were expecting, by this time it's likely that someone has a dependency on the current behavior.  I proposed that we maintain the current behavior as a new constraint named `distinct_hosts_all_namespaces` and then correct the `distinct_hosts` behavior to honor namespaces as expected.  It would require folks that depend on the current behavior to make a jobspec change; however since the current behavior doesn't behave as advertised, this seemed to be the least _surprising_ move to make.

**Comment by mikenomitch** [comment]
@angrycub I think you might be right that people are relying on this behavior, but it doesn't seem worth it to add the extra configuration option, as namespaces should be distinct.

I also don't think that the risk mitigation of using `distinct_hosts` really makes sense in a cross namespace context - as they're likely truly distinct workloads.

My vote is to add this to the 1.5 milestone and then have us just add in a Namespace check to the code you linked to. And then we can call it out as a (minor) breaking change in the upgrade guide.

**Comment by mikenomitch** [comment]
I moved this to the 1.6 milestone as its a breaking change so we won't want to get it out in a point release.

**Comment by angrycub** [comment]
**Another thought/Parking this idea here**

I was talking with Tim and another way in which we might be able to retain the current behavior and make it more expected would be to add an interpolation that contains some elements of the job that we could use in a `distinct_property` constraint (like namespace in this case). The amount of effort involved is unknown, but it _seems_ like we should have the job at hand since we are in the process of evaluating other values into it.
