### ISSUE TITLE
[question] Topology dashboard overcounting allocations and reserved resources.

### ISSUE THREAD

**Issue by caiohcl** [hashicorp/nomad#9800]
Hi,

I recently updated Nomad to v1.0.1, and something caught my attention. I checked the topology dashboard, and under "Cluster Details" it shows that 151% of memory is currently in use. Another thing I noticed is that the Alloc number is different than what is shown in the graph. 

For example, here it shows that client 046 has 7 Allocs, but the graph shows only 2:

![image](https://user-images.githubusercontent.com/2295899/104478011-66e28800-5587-11eb-97ae-8117168087fd.png)

As far as I can tell, the Topology is also using "completed" allocations to get the Cluster Details. I wonder if I'm missing some configuration or if this is the correct behavior?

Thank you!

**Comment by idrennanvmware** [comment]
Curious - do you happen to have any prestart tasks?

**Comment by caiohcl** [comment]
Hi @idrennanvmware. No, I'm not using any prestart task.

**Comment by manveru** [comment]
The same is happening to me across multiple clusters since the 1.0 release candidates. We also have a high number of dead allocations taking up memory and space on the nomad server nodes until we manually GC them and restart the nodes.

**Comment by DingoEatingFuzz** [comment]
Hi @caiohcl, as @manveru is suggesting, this is due to terminal allocations. These allocations don't actually reserve resources in the mind of the scheduler which is how you're able to get to "151%" of reserved memory used.

This is definitely a bug and it's naturally where I didn't write tests 😂 😭 ☠️ 

https://github.com/hashicorp/nomad/blob/2867e262f1853731144efec74d2bbb01b1ca5aab/ui/tests/acceptance/topology-test.js#L8-L10
