### ISSUE TITLE
[feature request] Allocations top level group

### ISSUE THREAD

**Issue by jonatasfreitasv** [hashicorp/nomad#9844]
It will be possible to identify a group of allocations.

"Alocs Group" > Allocations > Jobs

**Example:**
Have to run a execution with simulation of 10k forecasts algo / allocations (with one batch job), this execution is part of a "execution group", a group of simulation and have to possible to run a lot of "executions groups", with a lot of allocations inside this group.

**Problems or other ways:**
I tried to run one allocation with a lot of jobs (more then 30k docker batch job), but, Nomad stuck.

**Comment by cgbaker** [comment]
Hi @jonatasfreitasv , so that we can understand what sort of changes might help, can you give more details on the use case? 

For example, if there are a smaller number of allocation groups, they can be put in different [Task Groups](https://www.nomadproject.io/docs/job-specification/group) in the Job. Then they are identified (and even scaled) by the Task Group name. HCL2 features like [dynamic blocks](https://www.nomadproject.io/docs/job-specification/hcl2/expressions#dynamic-blocks) may be useful for writing the job spec with repeated groups.

If you would like a simple partitioning of these (for example, to coordinate work), the environment variable `NOMAD_ALLOC_INDEX` will run from `0` to `count-1` for the allocations in a group, and can be used to partition.

**Comment by tgross** [comment]
This has been left waiting a reply for a while. Going to close it out.
