### ISSUE TITLE
Question can nomad task access env var to get public ip of node

### ISSUE THREAD

**Issue by fairbairn** [hashicorp/nomad#9856]
We're running a task as "exec".

The node that we spin up is cloud provisioned by terraform, and we stash away the node's external public ip address.

Presently, we do this by adding a value in the `/etc/environment` file on the vm.

The task's chroot area shows this reference, the /etc/environment in the chroot is the same.

Our problem is we cannot find a way to access that global environment variable in the job's HCL file so it can set a related environment variable that our binary needs to operate, in which it needs this public ip in its own protocol.

We've tried templates, we've tried env, we can't seem to find an example or documentation in which this is explained (outside of the standard NOMAD_ vars built in).

Let's say the global environment var is..
/etc/ environment
--
`cluster_node_public_ip=182.1.2.3`

We would think we could somehow reference that in the job hcl file, so when tasked by nomad, it would fill it in...
but nothing seems to work...

NOT..
```
MYVAR=$cluster_node_public_ip
MYVAR="$cluster_node_public_ip"
MYVAR="${cluster_node_public_ip}"
MYVAR=[[ (env "cluster_node_public_ip") ]]
```
We can't find a combination, under either `env` or `template`in which we can seem to reference.

We've tried setting `Environment=cluster_node_ip=$cluster_node_ip` in the nomad.service file under systemd.  Nomad might know about it, but we can't find a syntax to get it.

Open to how to do this..

**Comment by tgross** [comment]
Hi @fairbairn!

You can use [`${attr.unique.network.ip-address}`](https://www.nomadproject.io/docs/runtime/interpolation#interpreted_node_vars) if the advertised IP address matches that IP address. But in many cloud environments (for example, AWS), their software defined networking layer prevents us from using the standard tooling to get the nodes's public IP. For example, we can't run the equivalent of `ip addr` because the public IP won't be there.

But fortunately most cloud providers include the public IP in the host's metadata service, and we fingerprint that. The exact attribute you want will depend on the cloud provider and whether it's IPv4 or IPv6, but if you do a `nomad node status -verbose self` you'll see a list of available attributes. For example, I just checked here on an AWS node and I can see the `unique.platform.aws.public-ipv4` attribute is what I want.

**Comment by fairbairn** [comment]
This is actually cross-cloud.  We already know the public ip, we've put that in an environment variable on the machine.

The challenge is we can't get to it within the nomad task .hcl for job creation.

$cluster_node_public_ip will have the proper ip address, and it's defined under /etc/environment, but Nomad can't get to it for some reason.

I think our fallback option is that we'll have to modify our application itself, to go find that information somewhere else (like maybe some kind of .apprc file we shove into a file on the machine which replicates into chroot, and our app reads from).  We were hoping Nomad's job syntax would allow us to reference an environment variable pre-defined on the host at bootup and not deal with that.

**Comment by tgross** [comment]
> $cluster_node_public_ip will have the proper ip address, and it's defined under /etc/environment, but Nomad can't get to it for some reason

That's intentional: we don't want to expose Nomad's environment to tasks because Nomad is running as root and may have sensitive environment variables like the `VAULT_TOKEN`.

But given that you're writing host-specific files anyways, I think there's a good workaround. Instead of dropping the IP into `/etc/environment`, drop it as a Nomad configuration value for [`meta`](https://www.nomadproject.io/docs/configuration/client#meta) and then reference that using the job's [`meta`](https://www.nomadproject.io/docs/job-specification/meta). You can probably use Nomad's [configuration merging](https://www.nomadproject.io/docs/configuration#load-order-and-merging) behavior so that you only have to update that value and not template the whole config.

**Comment by fairbairn** [comment]
How would we "set" that NOMAD_META_public_ip value?

We run a provisioning task (user-data) on the Terraform apply that basically figures out the public ip and can stash it away, as well as craft the service files, and create the /etc/environment file if needed.

I think we've been missing this META concept.

Is that something we have to put in the Environment setting on the systemd service definition, or something we define by a specific name under /etc/environment on the host vm?

**Comment by fairbairn** [comment]
Looks like (not much on this btw), we could add another json file and reference that in the service file for systemd..

ie, -config=extra.json

if the json is..

```
{
   "public_ip": "1.2.3.4"
}
```

does that imply that nomad will then have an interval value available to us called ${NOMAD_META_public_ip} ?

**Comment by tgross** [comment]
Right! 

So for example, suppose I've got a minimal single-node Nomad cluster with a config file `/etc/nomad.d/nomad.hcl` like this:

```hcl
name         = "minimal"
log_level    = "WARN"
enable_debug = true
data_dir     = "/var/nomad"

server {
  enabled          = true
  bootstrap_expect = 1
}

client {
  enabled = true
  host_volume "shared_data" {
    path = "/srv"
  }
}
```

Then in my systemd prestart or configuration management or whatever, I'll create a file `/etc/nomad.d/meta.hcl` like this:

```hcl
client {
  meta {
    public_ip = "1.2.3.4"
  }
}
```

I can pass a config flag like `-config=/etc/nomad.d` to have it look for all the config files in that directory. Those configuration files will be merged, and when I run it I'll get a node that has the combined configuration like this:

```
$ nomad node status -self -verbose
...

Host Volumes
Name         ReadOnly  Source
shared_data  false     /srv
...

Meta
connect.gateway_image     = envoyproxy/envoy:v${NOMAD_envoy_version}
connect.log_level         = info
connect.proxy_concurrency = 1
connect.sidecar_image     = envoyproxy/envoy:v${NOMAD_envoy_version}
public_ip                 = 1.2.3.4
```

And now my jobs can use the environment variable `${NOMAD_META_public_ip}` just as you've said.

**Comment by fairbairn** [comment]
You are amazing.  Thank you!!!!

We'll start modifying our provisioning and logic to see if we can get this to work for us.  Extremely helpful.  Hope this thread helps others.
