### ISSUE TITLE
[question] number of task constraint for batch processing

### ISSUE THREAD

**Issue by orenmazor** [hashicorp/nomad#9954]
### Nomad version

Nomad v1.0.3 (08741d9f2003ec26e44c72a2c0e27cdf0eadb6ee)

### Operating system and Environment details

debian buster

### Issue

I'm using nomad to pipeline an ETL in my datawarehouse. the actual DAG is managed by luigi. docker is my executor.

I have a handful of tasks that can require potentially the maximum ram the worker has. my workers are not equivalent, so I can't _easily_ hardcode a `Resources{ MemoryMB}` setting in my job submission.

My question is:

is it possible for me to adjust my job definition to tell nomad "when you see jobs like this, only run one at a time"?

I played around with constraints but it feels like the wrong mechanism here. I can definitely solve this in code (e.g. get the host's available memory and adjust the nomad submission to have that hardcoded)

**Comment by tgross** [comment]
Hi @orenmazor! The challenge with this sort of thing is that the scheduler looks at the available memory on a set of nodes in order to make scheduling decisions, so setting the memory based on the node size is backwards from how Nomad tries to make decisions.

You can assign your client nodes a [`node_class`](https://www.nomadproject.io/docs/configuration/client#node_class) based on how much memory they have (ex. "small", "medium", "large") and use it as a scheduling constraint. But you'd still need to encode the memory resource limit based on those sizes.

You can also use a `distinct_hosts` constraint to prevent allocations from ending up on the same host. You could set the memory resource to the size of the smallest worker and use the Docker [`memory_hard_limit`](https://www.nomadproject.io/docs/drivers/docker#memory_hard_limit) as the real limit. But without knowing the node size at the time of job submission I think this just moves the problem around.
 
I suspect you're going to want to try the programmatic approach and set the values. Alternately, if you want the workload to take up all the resources on the host anyways, you might want to look at the `raw_exec` task driver.

**Comment by orenmazor** [comment]
hey @tgross thanks for following up. this fits with what I anticipated. 

you're right, the problem is moving around a bunch. I actually ended up solving my problem in a different part of the stack. the TLDR is my job submission comes from luigi (an etl tool). I noticed it supports semaphores, so I created a class of jobs that support reading from that semaphore. luigi just wont submit a job to nomad if the "big job" semaphore is taken.

its not a great solution but it's been working very well. until I come up with a better approach :)

**Comment by asquel** [comment]
@orenmazor sorry for popping up in the middle of the conversation. I am looking at nomad and luigi at the moment and was thinking of using it together. How did you do that ?

**Comment by orenmazor** [comment]
@asquel I ended up writing a contrib extension to luigi. it's similar to the docker extension, except instead of talking to the dockerd, I'm submitting jobs to nomad from python. then the luigi `complete()` method check just asks nomad if the tasks is done.

I will eventually find time to clean it up (there's a few issues at the moment, like if a long running nomad job gets garbage collected, and so forth) and open a PR to luigi :)
