### ISSUE TITLE
Nomad CLI connection configuration file

### ISSUE THREAD

**Issue by tgross** [hashicorp/nomad#9981]
The Nomad CLI accepts a number of environment variables. In https://github.com/hashicorp/nomad/pull/9959 a community member proposed adding `NOMAD_HEADERS`, which revealed a need to handle additional configuration values in a neater way. We could do this with a Nomad CLI connection configuration file (ex. `~/.nomadrc` or `$XDG_CONFIG_HOME/nomad.hcl`). Some concerns or open questions:

* The configuration file is security sensitive when ACLs are enabled.
* Can the configuration file have multiple "profiles" for pointing to different clusters?
* This should be a cross-product effort so that there's some consistency between Nomad and the features built into other products:
  * Consul has a [`consul_http_token_file`](https://www.consul.io/commands#consul_http_token_file) 
  * Vault has a [token helper](https://www.vaultproject.io/docs/commands#token-helper) concept
  * Waypoint has [workspaces](https://www.waypointproject.io/docs/workspaces)

**Comment by the-maldridge** [comment]
I absolutely am looking for this featureset.  I have an increasingly large and questionably maintainable set of shell scripts that set up boundary tunnels and configure various ports and access tokens.  Having Nomad be able to at least have an equivalent to consul's token_file would already be a huge win since I could export a static, non-sensitive environment variable and point at the token file.

**Comment by lgfa29** [comment]
Closing this one in favour of #11043. Feel free to 👍 and add more comments there 🙂
